### PR TITLE
fix: TransactionMessage.decompile() now counts the correct number of unsigned, writable accounts

### LINKED ISSUE #28900: [web3.js] Discrepancy between legacy Transaction API and new VersionedTransaction API
#### Problem

Version: `@solana/web3.js@1.66.2`

Combination of `VersionedTransaction.deserialize` and `TransactionMessage.decompile` produces different result from the legacy `Transaction.from` API when deserializing the same exact transaction.

Reproduction below (note the difference in the `isWritable` flag of the last `key`)
Screenshot 2022-11-20 at 23 31 41

https://codesandbox.io/p/sandbox/funny-ride-1zmikd

While not 100% sure, I believe the legacy API produces the correct result and the new API is being wrong.

<details><summary>Serialized transaction</summary>

```
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAUHLl06XmBMUgEaGqFEDWXlrfuG9BxuqyiqilWnn+lBhO3ljbFniLvsim6dTEc5cyoTN2b5SA3mE/vy52heCKtBsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACK/25BBZJGavm0hr5XZ58vaLQc3cMeAgkndKj2Ni7RPDGxjMPhSKClKTgYkg7frtqzkeSTNsC3TbZp0QRwNCSwUhn4magdT/hPtZPS7fipCsGzqzQlj33yM+pQMCsb0uBX82VZkozhurrbZbi12eMbon+FOb7GAsyxrcKvufRnDqK6IjeTZQF0WwCoTTZmOO6HR7bBk26zWjZL9jPKBtpQEFBgAGAQMEAhHyI8aJUuHytv5AQg8AAAAAAA==
```
</details>

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

Message headers give you the following:

* number of required signatures (`numRequiredSignatures`)
* number of read-only signed accounts (`numReadonlySignedAccounts`)
* number of read-only unsigned accounts (`numReadonlyUnsignedAccounts`)

If we want to know how many writable unsigned accounts there are, we have to:

* start with the total number of accounts
* subtract the number of those that are signers (`numRequiredSignatures`)
* subtract the number of read-only unsigned accounts (`numReadonlyUnsignedAccounts`)

That spells:

```ts
const numWritableUnsignedAccounts =
  message.staticAccountKeys.length -
  numRequiredSignatures -
  numReadonlyUnsignedAccounts;
```

Unfortunately, we forgot to subtract out the number of signers, making it possible to overcount `numWritableUnsignedAccounts`. This played havoc when deserializing messages like the one in #28900's repro.

All of this could result in accounts being needlessly marked as writeable, which could only serve to make the network slower (ie. causing the validator to run transactions in serial that could otherwise have been safely run in parallel).

#### Summary of Changes

* Fix the calculation of `numWritableUnsignedAccounts`
* Write a test that asserts you can decompile a legacy message with `TransactionMessage`
* Copy the repro from #28900 into a test to validate this fix and to serve as a regression going forward.

Fixes #28900.

### CODE REVIEW

File: web3.js/src/transaction/message.ts [hunk 1]
```diff
@@ -49,7 +49,9 @@ export class TransactionMessage {
     assert(numWritableSignedAccounts > 0, 'Message header is invalid');
 
     const numWritableUnsignedAccounts =
-      message.staticAccountKeys.length - numReadonlyUnsignedAccounts;
+      message.staticAccountKeys.length -
+      numRequiredSignatures -
```
Comment (steveluscher) [inline web3.js/src/transaction/message.ts:53]: Without this change, the test in this commit incorrectly marks the last account as writable.

**Review by jstarry — APPROVED** [review]

**Comment by steveluscher** [comment]
Got the idea to double check the Rust code, and found it to already be correct.

https://github.com/solana-labs/solana/blob/98525ddea99c6ebdcfe0dcbda9de49c93035050f/sdk/program/src/message/versions/v0/mod.rs#L284-L286
