### PR TITLE
More conservative purge_zero_lamport_accounts purge logic

### LINKED ISSUE #7117: thread 'main' panicked at 'Snapshot bank failed to verify'
#6890 appears to still reproduce on the TdS testnet with the tip of master (d5beb8a9e4efcbee6fbd666b34938e8efffb6a43).

STR:
1. `solana-validator -l l -n tds.solana.com:8001 -o - `

Output:
```
[2019-11-25T16:34:12.115958676Z INFO  solana_core::validator] local retransmit address: 0.0.0.0:9757
[2019-11-25T16:34:12.115967876Z INFO  solana_core::validator] Initializing sigverify, this could take a while...
[2019-11-25T16:34:12.115977276Z INFO  solana_core::validator] Done.
[2019-11-25T16:34:12.115985377Z INFO  solana_core::validator] creating bank...
[2019-11-25T16:34:12.118331915Z INFO  solana_core::validator] genesis hash: H7zfo6f7NEYMCXfZnjvVbt565oZiw6hxFAguSCppvfFx
[2019-11-25T16:34:12.118488017Z INFO  solana_ledger::blocktree] Maximum open file descriptors: 65000
[2019-11-25T16:34:13.537219725Z INFO  solana_ledger::blocktree] "l/rocksdb" open running
[2019-11-25T16:34:13.538683149Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "l/snapshot"
[2019-11-25T16:34:13.538775250Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "l/snapshot.tar.bz2"
[2019-11-25T16:34:14.137411559Z INFO  solana_ledger::snapshot_utils] snapshot untar took 598ms
[2019-11-25T16:34:14.137592862Z INFO  solana_ledger::snapshot_utils] Loading from "/home/mvines/l/snapshot/.tmpfHPe5D/snapshots/425913/425913"
[2019-11-25T16:34:14.568162144Z INFO  solana_runtime::accounts_db] accounts_db: total_stores: 65 newest_slot: 425913 oldest_slot: 0 max_slot: 0 (num=7) min_slot: 356 (num=1)
[2019-11-25T16:34:14.568315247Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=65i
thread 'main' panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:228:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2019-11-25T16:34:14.570606184Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:228:9" location="ledger/src/snapshot_utils.rs:228:9"
```

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Purging zero lamport accounts where the parent account's appendvec is not removed is not compatible with snapshots. Since the index is not serialized in the snapshot, the old view of the account could be revived.

#### Summary of Changes

Don't purge zero lamport accounts unless all AppendVecs containing parent accounts can be also removed.

Fixes #7117

### CODE REVIEW

File: runtime/src/accounts_index.rs [hunk 1]
```diff
@@ -29,13 +29,21 @@ impl<T: Clone> AccountsIndex<T> {
...
-            .iter()
+    fn get_rooted_entries(&self, list: &[(Slot, T)]) -> Vec<(Slot, T)> {
+        list.iter()
             .filter(|(slot, _)| self.is_root(*slot))
             .cloned()
-            .collect();
+            .collect()
+    }
+
+    pub fn would_purge(&mut self, pubkey: &Pubkey) -> Vec<(Slot, T)> {
```
Comment (ryoqun) [inline runtime/src/accounts_index.rs]: nits: no need to be `mut` here.

File: runtime/src/accounts_db.rs [hunk 2]
```diff
@@ -1735,6 +1792,97 @@ pub mod tests {
...
+        let accounts = AccountsDB::new_single();
+
+        let mut current_slot = 1;
+        accounts.store(current_slot, &[(&pubkey, &account)]);
+        accounts.add_root(current_slot);
+
+        current_slot += 1;
+        accounts.store(current_slot, &[(&pubkey, &zero_lamport_account)]);
+        accounts.store(current_slot, &[(&pubkey2, &account2)]);
+        for _ in 0..33000 {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: Thanks for adapting my test!

Here is my bad magic number. How about like this?
```patch
diff --git a/runtime/src/accounts_db.rs b/runtime/src/accounts_db.rs
index 03b8450d7..36b350b3d 100644
--- a/runtime/src/accounts_db.rs
+++ b/runtime/src/accounts_db.rs
@@ -1861,7 +1861,8 @@ pub mod tests {
         current_slot += 1;
         accounts.store(current_slot, &[(&pubkey, &zero_lamport_account)]);
         accounts.store(current_slot, &[(&pubkey2, &account2)]);
-        for _ in 0..33000 {
+
+        while accounts.storage.read().unwrap().0.get(&current_slot).unwrap().len() < 2 {
             accounts.store(current_slot, &[(&filler_account_pubkey, &filler_account)]);
         }
         accounts.add_root(current_slot);

```

File: runtime/src/accounts_db.rs [hunk 3]
```diff
@@ -1735,6 +1792,97 @@ pub mod tests {
...
+        slot: Slot,
+        pubkey: Pubkey,
+        expected_lamports: u64,
+    ) {
+        let ancestors = vec![(slot, 0)].into_iter().collect();
+        let (account, slot) = accounts.load_slow(&ancestors, &pubkey).unwrap();
+        assert_eq!((account.lamports, slot), (expected_lamports, slot));
+    }
+
+    fn reconstruct_accounts_db_via_serialization(accounts: AccountsDB, slot: Slot) -> AccountsDB {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: This is copy-n-paste thing I did in hurry. I owe you; however could you make `test_accounts_db_serialize` use this also? That change should really straight-forward.

File: runtime/src/accounts_db.rs [hunk 4]
```diff
@@ -1623,12 +1659,33 @@ pub mod tests {
         assert_eq!(accounts.load_slow(&ancestors, &pubkey), Some((account, 1)));
     }
 
+    fn print_index(label: &'static str, accounts: &AccountsDB) {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: These are pretty neat!

File: runtime/src/accounts_db.rs [hunk 5]
```diff
@@ -1036,21 +1086,7 @@ impl AccountsDB {
         update_index.stop();
         trace!("reclaim: {}", reclaims.len());
 
-        let mut remove_dead_accounts = Measure::start("store::remove_dead");
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: just to be sure; these `Measure`s are no longer needed? The code move to `handle_reclaims` didn't carry with them.

File: runtime/src/accounts_db.rs [hunk 6]
```diff
@@ -573,12 +576,59 @@ impl AccountsDB {
...
+
+        // Calculate store counts as if everything was purged
+        // Then purge if we can
+        let mut store_counts: HashMap<AppendVecId, usize> = HashMap::new();
+        let storage = self.storage.read().unwrap();
+        for (slot_id, account_info) in &reclaims {
+            if let Some(slot_storage) = storage.0.get(&slot_id) {
+                if let Some(store) = slot_storage.get(&account_info.id) {
+                    if let Some(store_count) = store_counts.get_mut(&account_info.id) {
+                        *store_count -= 1;
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: nits: it might be pedantic to avoid overflows? Or it never happens? Hmm, hard situation, but I might could write a test case for it.

File: runtime/src/accounts_db.rs [hunk 7]
```diff
@@ -573,12 +576,59 @@ impl AccountsDB {
...
+                    } else {
+                        store_counts
+                            .insert(account_info.id, store.count_and_status.read().unwrap().0);
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: Should this start with `.insert(...count... **- 1**);`, shouldn't?

Locally, both version passes the relevant test, indicating still not adequate test coverage. ;)

File: runtime/src/accounts_db.rs [hunk 8]
```diff
@@ -573,12 +576,59 @@ impl AccountsDB {
...
+            reclaims.extend(accounts_index.would_purge(purge));
         }
         let last_root = accounts_index.last_root;
+
+        // Calculate store counts as if everything was purged
+        // Then purge if we can
+        let mut store_counts: HashMap<AppendVecId, usize> = HashMap::new();
+        let storage = self.storage.read().unwrap();
+        for (slot_id, account_info) in &reclaims {
+            if let Some(slot_storage) = storage.0.get(&slot_id) {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: Make this just a `wrap`s because something is very broken if we get `None` for `slot_storage` or `store_count`. Or at least add `warn!`s by adding `else` clauses.

File: runtime/src/accounts_db.rs (hunk 7 above)
Comment (ryoqun) [reply runtime/src/accounts_db.rs]: nits: use `store.id` to make reasoning a bit lighter? (first of all, `id` is too generic...)

File: runtime/src/accounts_db.rs [hunk 9]
```diff
@@ -573,12 +576,59 @@ impl AccountsDB {
...
+                if let Some(store) = slot_storage.get(&account_info.id) {
+                    if let Some(store_count) = store_counts.get_mut(&account_info.id) {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: nits: use `store.id` to make reasoning a bit lighter? (first of all, `id` is too generic...)

File: runtime/src/bank.rs [hunk 10]
```diff
@@ -1446,20 +1446,6 @@ impl Bank {
         self.rc
             .accounts
             .verify_hash_internal_state(self.slot(), &self.ancestors)
-            && !self.has_accounts_with_zero_lamports()
```
Comment (ryoqun) [inline runtime/src/bank.rs]: (note to myself: lifting this restriction is needed because we're purging 0-lamport accounts conservatively, however is this really OK so as not to cause shielding attacks? Maybe I'm still not sure about it completely or missing something.)

File: runtime/src/accounts_db.rs [hunk 11]
```diff
@@ -560,6 +560,9 @@ impl AccountsDB {
         false
     }
 
+    // Purge zero lamport accounts for garbage collection purposes
+    // Only remove those accounts where the entire rooted history of the account
+    // can be purged because there are no live append vecs in the ancestors
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: Such a descriptive great comment!

File: runtime/src/accounts_db.rs (hunk 5 above)
Comment (sakridge) [reply runtime/src/accounts_db.rs]: They are not strictly necessary. They are just adding some timing information when you run with the profiler on.

File: runtime/src/accounts_db.rs (hunk 3 above)
Comment (sakridge) [reply runtime/src/accounts_db.rs]: Yea. I can try to clean that up.

File: runtime/src/bank.rs (hunk 10 above)
Comment (sakridge) [reply runtime/src/bank.rs]: Yea, the requirement is not necessarily that there are no 0-lamport accounts, just that they do not alter the accounts view such that it would give incorrect results when the accounts db has operations performed on it. Removing all 0-lamport accounts was just an easy way to verify that there are no incorrect shielding accounts, but it wasn't correct.

We do some checks when we do verify_hash_internal_state that looks at all account paths from the root, I think we have to convince ourselves that this is enough or that we maybe need to make extra checks.

I have an idea to add another path which is like an aggressive purge_zero_lamport_accounts path which removes them from the index and then rewrites the AppendVec stores to not contain those accounts at all so that the accounts store is consistent, but I think that can be in a follow-up PR if required.

File: runtime/src/accounts_db.rs (hunk 7 above)
Comment (sakridge) [reply runtime/src/accounts_db.rs]: Thanks for the catch. I added a test and changed AccountIndex::id to AccountIndex::store_id.

File: runtime/src/accounts_db.rs (hunk 8 above)
Comment (sakridge) [reply runtime/src/accounts_db.rs]: Added `unwrap()` since these should always be present.

File: runtime/src/accounts_db.rs (hunk 6 above)
Comment (sakridge) [reply runtime/src/accounts_db.rs]: I don't think it should be able to happen, but if you can think of any more tests that would be great.

File: runtime/src/bank.rs (hunk 10 above)
Comment (ryoqun) [reply runtime/src/bank.rs]: Oh I see! Then, purging zero lamports account isn't set in stone as a hard requirement. That makes sense!

File: runtime/src/accounts_db.rs [hunk 12]
```diff
@@ -560,25 +560,77 @@ impl AccountsDB {
...
     pub fn purge_zero_lamport_accounts(&self, ancestors: &HashMap<u64, usize>) {
         self.report_store_stats();
+        let mut purges = HashMap::new();
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: Yeah, this is exactly what I thought would have liked to see! But not bothered to write a comment. :p This way, we can reduce redundant call of `would_purge` around [here](https://github.com/solana-labs/solana/pull/7157/files#diff-2099c5256db4eb5975c8834af38f6456R598). :)

**Comment by ryoqun** [comment]
@sakridge Thanks for addressing all review comments! This looks almost complete! Only remaining is at my part: Come up with a creative testcase (https://github.com/solana-labs/solana/pull/7157#discussion_r352319669) and run this locally.

Also, I think the quality of this PR is well beyond being mere a _draft_ PR. :)
