### PR TITLE
bench-tps: Send/confirm a loopback payment after each batch of transactions

### LINKED ISSUE #764: bench-tps fails periodically on testnet with "Error: Couldn't get new last id!"
Doesn't seem to reproduce as often when I run `bench-tps` locally against the same net.  GCP throttling the testnet client instance might have something to do with it

### PR DESCRIPTION
**Pull request by mvines**
Fixes #764

Rather than just waiting for `last_id` to advance, `bench-tps` now sends/confirms a single transaction and is quite patent waiting for it to complete (necessary when using CPU verification)

### CODE REVIEW

**Comment by mvines** [comment]
Depends-on: #867

**Comment by aeyakovenko** [comment]
Won’t this take forever?

**Comment by mvines** [comment]
It shouldn't, unless I'm missing something (certainly possible!).  `client.poll_get_balance()` and `client.poll_for_signature()` both timeout after a second, so on a packet drop the loop will just run a second or third time until the `client.transfer()` makes it through and is confirmed.

**Comment by mvines** [comment]
I mitigated #867 here by using a separate client for the barrier transaction that only transfers 1 token to itself, so the account balance never hits zero

File: src/bin/bench-tps.rs [hunk 1]
```diff
@@ -105,35 +105,97 @@ fn sample_tx_count(
...
+                Transaction::new(keypair, id.pubkey(), 1, *last_id)
+            }
+        })
+        .collect();
 
     let duration = signing_start.elapsed();
     let ns = duration.as_secs() * 1_000_000_000 + u64::from(duration.subsec_nanos());
-    let bsps = txs as f64 / ns as f64;
-    let nsps = ns as f64 / txs as f64;
+    let bsps = (tx_count / 2) as f64 / ns as f64;
```
Comment (mvines) [inline src/bin/bench-tps.rs]: Looks like we need a ` >> 1` here (and on the next line too) to generate the right stats number

Comment (sakridge) [reply src/bin/bench-tps.rs]: Should we just switch to `keypairs.len()` for this function? or `let tx_count = keypairs.len();`

Comment (mvines) [reply src/bin/bench-tps.rs]: Yeah, I'll do that.   All the `/2` is pretty gnarly.

**Comment by mvines** [comment]
done

**Comment by aeyakovenko** [comment]
@mvines graphana perf hud seems busted after this pr. I think waiting for confirmation will slow down everything
