### PR TITLE
Fix bad ancestor check

### LINKED ISSUE #17377: thread 'solana-replay-stage' panicked at 'candidate_latest_frozen_vote is a frozen bank, so must exist in ancestors map'
The `bvb` node running:
```
solana-validator 1.7.0 (src:e320af99; feat:3533521759)
```
just panicked with:
```
thread 'solana-replay-stage' panicked at 'candidate_latest_frozen_vote is a frozen bank, so must exist in ancestors map', core/src/consensus.rs:781:26
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1321:5
   3: solana_core::consensus::Tower::check_switch_threshold
   4: solana_core::replay_stage::ReplayStage::select_vote_and_reset_forks
   5: solana_core::replay_stage::ReplayStage::new::{{closure}}
```

This may be a new regression on master.  I just updated it to a new master build a couple hours prior.  Previously it was running b5302e76198b951e7d4f96fbf5f17e273f209dcd for I didn't observe this panic

### PR DESCRIPTION
**Pull request by carllin**
#### Problem
Slot voted for in gossip may have been purged by a root by the time the switch threshold check is made

#### Summary of Changes
If the gossip vote is not in BankForks, don't it in the switch threshold check
Fixes #17377

### CODE REVIEW

**Review by jstarry — APPROVED** [review]

**Comment by mvines** [comment]
Thanks!

File: core/src/consensus.rs [hunk 1]
```diff
@@ -776,9 +778,30 @@ impl Tower {
...
+                    // if `candidate_latest_frozen_vote` is not found in the ancestors/descendants map (recall these
+                    // directly reflect the state of BankForks), this implies that `B` was pruned from BankForks
+                    // because it was on a different fork than `last_voted_slot`, and thus this vote for `candidate_latest_frozen_vote`
+                    // should be safe to count towards the switching proof:
+                    //
+                    // However, there is also the possibility that `last_voted_slot` is a stray, in which
+                    // case we cannot make this conclusion as we do not know the ancestors/descendants
+                    // of strays. Hence we err on the side of caution here and ignore this vote. This
+                    // is ok because validators voting on different unrooted forks should eventually vote
+                    // on some descendant of the root, at which time they can be included in switching proofs.
```
Comment (ryoqun) [inline core/src/consensus.rs:801]: @carllin :+1: thanks for defending/maintaining the persistent tower. :)
