### PR TITLE
ff cleanup: vote_state_update_credit_per_deque

### LINKED ISSUE #27091: Feature Gate: Match vote credit awards for new voting schema with old schema
### Description

The new VoteStateUpdate is crediting vote awards incorrectly compared to the old Vote instruction. 

### Feature ID

CveezY6FDLVBToHDcvJRmtMouqzsmj4UXYh5ths5G5Uv

### Activation Method

Single Core Contributor

### Minimum Beta Version

1.11.0

### Minimum Stable Version

1.11.0

### Testnet Activation Epoch

414
### Devnet Activation Epoch

443
### Mainnet-Beta Activation Epoch

491

### PR DESCRIPTION
**Pull request by AshwinSekar**
Activated mainnet 491.

Fixes #27091

### CODE REVIEW

File: programs/vote/src/vote_state/mod.rs [hunk 1]
```diff
@@ -549,7 +549,7 @@ pub fn process_new_vote_state(
     new_root: Option<Slot>,
     timestamp: Option<i64>,
     epoch: Epoch,
-    feature_set: Option<&FeatureSet>,
+    _feature_set: Option<&FeatureSet>,
```
Comment (AshwinSekar) [inline programs/vote/src/vote_state/mod.rs:552]: intentionally leaving this here because the upcoming timely vote credits change will need it

**Review by carllin — APPROVED** [review]
