### PR TITLE
fix: mark the socket as closed when receiving a close/error message

### LINKED ISSUE #25133: web3.js: _updateSubscriptions running in infinite recursion, crashing developed app
#### Problem
When using latest release of @solana/web.js (1.41.4) and getting errors like this one:
obraz
developed app is crashing.
I suspect this happens because of recursion there, which seems to run indefinitely: 
obraz
When using version not containing this change in code (1.41.1), crashing doesn't happen.

#### Proposed Solution
Use one of solutions mentioned in TODO comment ("Maybe add an 'errored' state or a retry limit?")

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

In #25133 @awojciak noticed that the subscriptions manager would keep trying to slam a closed socket with requests. I believe this is because we were not properly marking the socket as closed when receiving a `'close'` event.

#### Summary of Changes

Toggle the connectedness flag when we get a close/error event.

Fixes #25133.

### CODE REVIEW

File: web3.js/src/connection.ts [hunk 1]
```diff
@@ -4174,13 +4174,15 @@ export class Connection {
    * @internal
    */
   _wsOnError(err: Error) {
+    this._rpcWebSocketConnected = false;
```
Comment (steveluscher) [inline web3.js/src/connection.ts:4177]: MDN says:

> The error event is fired when a connection with a WebSocket has been closed due to an error (some data couldn't be sent for example).

**Review by jstarry — APPROVED** [review]

**Comment by jstarry** [comment]
I think you're right about this being the root problem, nice!
