### PR TITLE
Change Blockstore TryPrimaryThenSecondary to Secondary only

### LINKED ISSUE #19952: `solana-ledger-tool` can unexpectedly modify the operative ledger
#### Problem

`solana-ledger-tool` attempts to open the ledger in primary/RW mode regardless of what operations it is performing.  This can lead to unexpected modifications being made and potentially corruption if incompatible versions are used.

#### Proposed Solution

Open the ledger with the least permissions necessary for the specified operation

### PR DESCRIPTION
**Pull request by steviez**
#### Problem
The `AccessType` enum specifies different modes of opening RocksDB. As of right now, there are three values that function as follows
- `PrimaryOnly` ==> Gives read+write access, this is what a running validator process has/needs
- `PrimaryOnlyForMaintenance` ==> Gives read+write access, used by `ledger-tool purge` only
- `TryPrimaryThenSecondary` ==> Tries to open with primary access, but opens secondary if primary fails. Primary will fail if the ledger is already open (ie by the validator process), so this mode allows `ledger-tool` operations while the validator is still running.
   - If Primary succeeds, read+write access is obtained
   - If Primary fails and Secondary succeeds, only read access is obtained (Secondary is inherently read-only)

If a use case is fine with secondary, we shouldn't give that use case primary access ever. Furthermore, restricting primary access will prevent unintended changes to the blockstore. For example, running `solana-ledger-tool verify` could result in slots being marked dead; this could be confusing to a user, especially if it could only happen some of the time (when the validator is running such that `verify` would get secondary access).

#### Summary of Changes
- Replace `TryPrimaryThenSecondary` with `Secondary` and use `Primary` in ledger-tool only when absolutely necessary
- Disable automatic compactions in `Secondary` (accomplished by passing cf_descriptors to open function)
- Guard more blockstore operations in blockstore_processor with `is_primary()`
   - Also demote some assertions to warnings such that `verify` can run in read-only mode without asserting

~~This PR is based upon https://github.com/solana-labs/solana/pull/23390 right now.~~

Fixes #19952

### CODE REVIEW

File: ledger/src/blockstore_processor.rs [hunk 1]
```diff
@@ -661,9 +661,9 @@ pub fn process_blockstore_from_root(
             .set_roots(std::iter::once(&start_slot))
             .expect("Couldn't set root slot on startup");
     } else {
-        assert!(
-            blockstore.is_root(start_slot),
-            "starting slot isn't root and can't update due to being secondary blockstore access: {}", start_slot
+        warn!(
+            "Starting slot {} isn't root and can't update due to being secondary blockstore access",
+            start_slot
```
Comment (steviez) [inline ledger/src/blockstore_processor.rs:666]: This function, `process_blockstore_from_root()`, later calls `load_frozen_forks()` which queries the blockstore for a root:
https://github.com/solana-labs/solana/blob/359e2de090607ded83c1d329ffcf65d2e797ffde/ledger/src/blockstore_processor.rs#L1127

However, the function also checks `bank_forks` and takes the max:
https://github.com/solana-labs/solana/blob/359e2de090607ded83c1d329ffcf65d2e797ffde/ledger/src/blockstore_processor.rs#L1128-L1129

So, I don't think it is actually a problem not to set `start_slot` as a root in the blockstore. As a quick test, I tried replaying a blockstore that has no roots:
```
Ledger has data for 103 slots 121519298 to 121519400
  with 0 rooted slots from 0 to 0
  and 103 slots past the last root
```
I got the same hashes as I did when running with current tip of master; and note this line of output which corresponds to the lines I called out above:
```
[2022-03-22T20:24:37.754080813Z INFO  solana_ledger::blockstore_processor]
load_frozen_forks() latest root from blockstore: 0, max_root: 121519300
```

**Review by steviez — COMMENTED** [review]
Most of this review is fairly straight forward; just the one bit I called out that I think needs more attentiveness than the rest.

File: local-cluster/tests/common.rs [hunk 2]
```diff
@@ -73,14 +73,27 @@ pub fn open_blockstore(ledger_path: &Path) -> Blockstore {
...
     )
-    .unwrap_or_else(|e| {
-        panic!("Failed to open ledger at {:?}, err: {}", ledger_path, e);
+    // Fall back on Secondary if Primary fails; Primary will fail if
+    // a handle to Blockstore is being held somewhere else
+    .unwrap_or_else(|_| {
+        Blockstore::open_with_options(
+            ledger_path,
+            BlockstoreOptions {
+                access_type: AccessType::Secondary,
```
Comment (steviez) [inline local-cluster/tests/common.rs:88]: The tests in `local-cluster` open lots of `Blockstore` sessions, sometimes multiple open at once. Instead of updating each instance to either explicitly be `Primary` or `Secondary`, I recreated the `TryPrimaryThenSecondary` behavior in this wrapper. This seems acceptable to me to keep the test logic simpler (not having to know Primary vs. Secondary in every spot).

File: ledger/src/blockstore_processor.rs (hunk 1 above)
Comment (steviez) [reply ledger/src/blockstore_processor.rs:666]: @carllin - I think Yueh-Hsuan and I should be able to handle rest of review between us, but from `git blame`, I'd appreciate any thoughts on this modification

File: ledger/src/blockstore_db.rs [hunk 3]
```diff
@@ -520,7 +518,7 @@ impl Rocks {
     }
 
     fn is_primary_access(&self) -> bool {
-        self.1 == ActualAccessType::Primary
+        self.1 != AccessType::Secondary
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_db.rs:521]: Probably safer with `self.1 == AccessType::Primary || self.1 == AccessType::PrimaryForMaintenance`.  If we introduce a new AccessType in the future, then this function might be something easily forgotten.

File: ledger/src/blockstore_db.rs [hunk 4]
```diff
@@ -1613,8 +1611,9 @@ fn get_db_options(access_type: &AccessType) -> Options {
 
 // Returns whether automatic compactions should be disabled based upon access type
 fn should_disable_auto_compactions(access_type: &AccessType) -> bool {
-    // Disable automatic compactions in maintenance mode to prevent accidental cleaning
-    matches!(access_type, AccessType::PrimaryOnlyForMaintenance)
+    // Leave automatic compactions enabled (do not disable) in Primary mode;
+    // disable in all other modes to prevent accidental cleaning
+    !matches!(access_type, AccessType::Primary)
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_db.rs:1616]: I like this change!

We might also consider moving the inline comment to the function comment block.

File: ledger/src/blockstore_processor.rs [hunk 5]
```diff
@@ -1049,7 +1049,9 @@ fn process_bank_0(
     )
     .expect("processing for bank 0 must succeed");
     bank0.freeze();
-    blockstore.insert_bank_hash(bank0.slot(), bank0.hash(), false);
+    if blockstore.is_primary_access() {
+        blockstore.insert_bank_hash(bank0.slot(), bank0.hash(), false);
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_processor.rs:1053]: If the change looks good to @carllin, we may also consider adding an assert inside insert_bank_hash().

File: ledger/src/blockstore_processor.rs [hunk 6]
```diff
@@ -1224,8 +1226,12 @@ fn load_frozen_forks(
                                 new_root_bank = new_root_bank.parent().unwrap();
                             }
                             inc_new_counter_info!("load_frozen_forks-cluster-confirmed-root", rooted_slots.len());
-                            blockstore.set_roots(rooted_slots.iter().map(|(slot, _hash)| slot)).expect("Blockstore::set_roots should succeed");
-                            blockstore.set_duplicate_confirmed_slots_and_hashes(rooted_slots.into_iter()).expect("Blockstore::set_duplicate_confirmed should succeed");
+                            if blockstore.is_primary_access() {
+                                blockstore.set_roots(rooted_slots.iter().map(|(slot, _hash)| slot))
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_processor.rs:1230]: Same for this function.

File: ledger/src/blockstore_processor.rs [hunk 7]
```diff
@@ -1406,7 +1412,9 @@ fn process_single_slot(
     })?;
 
     bank.freeze(); // all banks handled by this routine are created from complete slots
-    blockstore.insert_bank_hash(bank.slot(), bank.hash(), false);
+    if blockstore.is_primary_access() {
+        blockstore.insert_bank_hash(bank.slot(), bank.hash(), false);
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_processor.rs:1416]: We may also move the is_primary_access check inside the insert_bank_hash to prevent the case where we forgot to check before inserting.

**Review by yhchiang-sol — COMMENTED** [review]
I like the change!  Let's wait for @carllin's comment.

File: ledger/src/blockstore_db.rs [hunk 8]
```diff
@@ -293,62 +293,60 @@ impl OldestSlot {
 }
 
 #[derive(Debug)]
-struct Rocks(rocksdb::DB, ActualAccessType, OldestSlot);
+struct Rocks(rocksdb::DB, AccessType, OldestSlot);
 
 impl Rocks {
     fn open(path: &Path, options: BlockstoreOptions) -> Result<Rocks> {
-        let access_type = &options.access_type;
+        let access_type = options.access_type.clone();
```
[the remark this answers is not in the document]
Comment (steviez) [reply ledger/src/blockstore_db.rs:300]: Yep, this clone is necessary so as it to keep `options` whole such that it can be borrowed by `cf_descriptors()` (partial moves are a thing but partial borrows are not).

File: ledger/src/blockstore_db.rs (hunk 3 above)
Comment (steviez) [reply ledger/src/blockstore_db.rs:521]: 100% agree

File: ledger/src/blockstore_processor.rs (hunk 5 above)
Comment (steviez) [reply ledger/src/blockstore_processor.rs:1053]: This thought did cross my mind, but I opted to leave the check outside of the blockstore functions since the secondary use case is so limited. My thought process was that if we added a check to any of the modifying functions, we should arguably add a check to all modifying blockstore functions

Comment (carllin) [reply ledger/src/blockstore_processor.rs:1053]: @steviez I see your point, although enforcing this new check on every new change in the future might be hard to maintain.

One alternative is to pass that access mode down to the `LedgerColumn`: https://github.com/solana-labs/solana/blob/7ba66eed0e93a5420acc0d509f8e460163835a31/ledger/src/blockstore_db.rs#L964 and have it no-op when those modes are enabled

File: ledger/src/blockstore_processor.rs (hunk 1 above)
Comment (carllin) [reply ledger/src/blockstore_processor.rs:666]: This functional change here is switching from an assert to a warning?

> So, I don't think it is actually a problem not to set start_slot as a root in the blockstore. As a quick test, I tried replaying a blockstore that has no roots:

`Blockstore::is_root` doesn't actually modify the database right?

Comment (steviez) [reply ledger/src/blockstore_processor.rs:666]: > This functional change here is switching from an assert to a warning?

Yes

> `Blockstore::is_root` doesn't actually modify the database right?

Also yes, `is_root()` only checks if the given slot is a root

File: ledger/src/blockstore_processor.rs (hunk 5 above)
Comment (carllin) [reply ledger/src/blockstore_processor.rs:1053]: Another thing of note, right now when we open as a secondary we run this code: https://github.com/solana-labs/solana/blob/7ba66eed0e93a5420acc0d509f8e460163835a31/ledger/src/blockstore_db.rs#L336-L341, which internally in the wrapper calls here: https://docs.rs/rocksdb/latest/src/rocksdb/db.rs.html#448-451, passing `AccessType::Secondary`

What if instead we opened with the readonly option here: https://docs.rs/rocksdb/latest/rocksdb/struct.DBWithThreadMode.html#method.open_cf_for_read_only

Comment (steviez) [reply ledger/src/blockstore_processor.rs:1053]: `AccessType::Secondary` in RocksDB implicitly means that it is read-only.

> Perhaps then it will cause all writes to fail at runtime in which case we know which functions to go and write handlers for the failures for,

Given my earlier note, this already happens with `Secondary`. The new places that I added `is_primary_access()` guards around were found through CI and running several `solana-ledger-tool` commands locally, and noting which spots spit a RocksDB error back at me.

Comment (steviez) [reply ledger/src/blockstore_processor.rs:1053]: > and have it return a failure when those modes are enabled. Annoying bit there is all existing code will have to handle that failure.

I don't think this would provide any extra value - RocksDB seems to already do a similar check under the hood and will spit an error out about the operation not being supported in Secondary mode. The operations on `LedgerColumn` return a Result, so all of our functions either bubble that Result up with `?` operator or do an `unwrap()` in the function

Comment (carllin) [reply ledger/src/blockstore_processor.rs:1053]: Got it, that makes sense. I think we should rework some of the existing `blockstore_processor` (tests with sufficient code coverage of the entire restart logic starting at `process_blockstore_from_root()` to take a db with a `AccessType::Secondary` so that we can catch these types of failures in the future.

Comment (steviez) [reply ledger/src/blockstore_processor.rs:1053]: > Got it, that makes sense. I think we should rework some of the existing `blockstore_processor` (tests with sufficient code coverage of the entire restart logic starting at `process_blockstore_from_root()` to take a db with a `AccessType::Secondary` so that we can catch these types of failures in the future.

That seems reasonable to me

File: ledger/src/blockstore_processor.rs [hunk 9]
```diff
@@ -1585,8 +1601,45 @@ pub mod tests {
         trees::tr,
     };
 
+    // Convenience wrapper to optionally process blockstore with Secondary access.
+    //
+    // Setting up the ledger for a test requires Primary access as items will need to be inserted.
+    // However, once a Secondary access has been opened, it won't automaticaly see updates made by
+    // the Primary access. So, open (and close) the Secondary access within this function to ensure
+    // that "stale" Secondary accesses don't propagate.
+    fn test_process_blockstore_with_access(
```
Comment (carllin) [inline ledger/src/blockstore_processor.rs:1610]: nit: test_process_blockstore_with_access -> test_process_blockstore_with_custom_options

File: ledger/src/blockstore_processor.rs [hunk 10]
```diff
@@ -1585,8 +1601,45 @@ pub mod tests {
...
+        genesis_config: &GenesisConfig,
+        blockstore: &Blockstore,
+        opts: ProcessOptions,
+        process_with_secondary: bool,
```
Comment (carllin) [inline ledger/src/blockstore_processor.rs:1614]: I think we can just directly pass the `AccessType` here and that will remove the `if/else` block

Comment (carllin) [reply ledger/src/blockstore_processor.rs:1614]: Might need to plumb that through in the rest of the spots where the bool is currently used though, but I think `enums` are more readable anyways

**Review by carllin — APPROVED** [review]

**Comment by yhchiang-sol** [comment]
@steviez: Looks like @carllin and I have previously approved.  If you want to merge this PR, let's rebase it and I will give it a final pass.

**Comment by steviez** [comment]
Yeah, there is a minor issue with one of the unit tests. Figured it out but never pushed the change up

File: ledger/src/blockstore_processor.rs [hunk 11]
```diff
@@ -1601,15 +1667,26 @@ pub mod tests {
...
                 ..ProcessOptions::default()
             },
+            blockstore_access_type.clone(),
         );
         assert_eq!(frozen_bank_slots(&bank_forks.read().unwrap()), vec![0]);
+
+        let dead_slots: Vec<Slot> = blockstore.dead_slots_iterator(0).unwrap().collect();
+        match blockstore_access_type {
+            AccessType::Secondary => {
+                assert_eq!(dead_slots.len(), 0);
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_processor.rs:1684]: This is good!

Maybe consider adding a comment here describing if a DB is open as secondary then it will be immutable and thus we don't expect dead_slots to be updated.

File: ledger/src/blockstore_processor.rs [hunk 12]
```diff
@@ -1569,8 +1593,50 @@ pub mod tests {
...
+    // Convenience wrapper to optionally process blockstore with Secondary access.
+    //
+    // Setting up the ledger for a test requires Primary access as items will need to be inserted.
+    // However, once a Secondary access has been opened, it won't automaticaly see updates made by
+    // the Primary access. So, open (and close) the Secondary access within this function to ensure
+    // that "stale" Secondary accesses don't propagate.
+    fn test_process_blockstore_with_custom_options(
+        genesis_config: &GenesisConfig,
+        blockstore: &Blockstore,
+        opts: ProcessOptions,
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_processor.rs:1605]: Looks like we can simply pass the reference here to avoid cloning on the call-site as `test_process_blockstore` also uses the reference of `opts` internally.

https://github.com/solana-labs/solana/blob/master/ledger/src/blockstore_processor.rs#L575-L583

**Review by yhchiang-sol — DISMISSED** [review]
Looks good!  Left some comments but please feel free to do them in a separate PR as they are only test-related functions.

File: ledger/src/blockstore_processor.rs (hunk 12 above)
Comment (steviez) [reply ledger/src/blockstore_processor.rs:1605]: Definitely going to resolve this one separately, so as not to muddy up this diff.

**Review by yhchiang-sol — APPROVED** [review]
LG!
