### PR TITLE
Ensure blobs are deserializable without unwrapping

### LINKED ISSUE #2607: Fullnode can't tolerate bad blobs
#### Problem
while blobs are signed, they are not validated as deserialize-able to Entry outside db_ledger

however, db_ledger assumes all blobs stored with the ledger are deserializeable in some cases, and panics

Example case:
https://github.com/solana-labs/solana/blob/master/src/db_ledger.rs#L484

#### Proposed Solution
db_ledger should probably just drop the blob when deserialize() fails

### PR DESCRIPTION
**Pull request by carllin**
#### Problem
Blocktree + replay stage could not tolerate blobs that were not deserializable to an entry

#### Summary of Changes
1) Blocktree checks blob is deserializable before handing them to replay_stage, returns error otherwise
2) replay_stage marks a fork as dead if it gets a Deserialize error from blocktree
3) Add tests in blocktree and replay_stage to ensure above works

Fixes #
Fixes #2607

### CODE REVIEW

File: core/src/replay_stage.rs [hunk 1]
```diff
@@ -292,10 +293,23 @@ impl ReplayStage {
...
         progress: &mut HashMap<u64, ForkProgress>,
     ) -> Result<()> {
-        let (entries, num) = Self::load_blocktree_entries(bank, blocktree, progress)?;
-        let result = Self::replay_entries_into_bank(bank, entries, progress, num);
+        let result = {
+            let load_result = Self::load_blocktree_entries(bank, blocktree, progress);
+            if let Ok((entries, num)) = load_result {
+                Self::replay_entries_into_bank(bank, entries, progress, num)
+            } else {
+                // Just to appease the compiler so that the Result types match in both branches.
```
Comment (rob-solana) [inline core/src/replay_stage.rs]: you can't do a load_blocktree_entries.map() to get to the type you want?

Comment (carllin) [reply core/src/replay_stage.rs]: Yup, switched to using `and_then`, much cleaner :D
