### PR TITLE
Revert "change test validator from non upgradable bpf loader to upgra…

### LINKED ISSUE #30402: v1.15.2 solana-test-validator --bpf-program flag seems to be broken
#### Problem
Programs deployed with the following command:

```solana-test-validator --bpf-program <program_id> <path>```

throw the following error at invocation:

```Error: failed to send transaction: Transaction simulation failed: This program may not be used for executing instructions```

Programs work fine when deployed manually with solana program deploy.
The program accounts look different in local explorer when deployed with --bpf-program and solana program deploy.

[See this repo for screenshots and to replicate the issue.](https://github.com/ananas-block/exec_test)

### PR DESCRIPTION
**Pull request by CriesofCarrots**
…dable bpf loader (#29051)"

This reverts commit b43eabaa47430529195f708f6722afb7af15ad0c.

#### Problem
#29051 broke `solana-test-validator --bpf-program`. To use the upgradeable bpf loader, a program must have a separate programdata account; simply changing the owning program is not enough.

#### Summary of Changes
Revert

Will follow with proper TestValidator support for the upgradeable loader.

Fixes #30402

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Argument for v1.15 backport is the flag is currently broken in all v1.15 releases

**Review by joncinque — APPROVED** [review]
Thanks for fixing this. That was short-sighted of me, apologies

**Comment by CriesofCarrots** [comment]
Merging on red `assert_instruction_count`: https://github.com/solana-labs/solana/pull/30411#issuecomment-1437658733

File: validator/src/bin/solana-test-validator.rs [hunk 1]
```diff
@@ -204,7 +204,7 @@ fn main() {
 
                     programs_to_load.push(ProgramInfo {
                         program_id: address,
-                        loader: solana_sdk::bpf_loader_upgradeable::id(),
+                        loader: solana_sdk::bpf_loader::id(),
```
Comment (godmodegalactus) [inline validator/src/bin/solana-test-validator.rs:207]: Hey,

I had the same idea, But in genesis we pass the bootloader program id to specify which loader to use for the program.
Is old loader deprecated and we now use this loader for all the programs?

Comment (CriesofCarrots) [reply validator/src/bin/solana-test-validator.rs:207]: I don't understand your question. This change is a revert *to* the old immutable loader.
We are, however, considering proper support for the upgradeable loader in solana-test-validator, as well as defaulting to the upgradeable loader: https://github.com/solana-labs/solana/pull/30412
