### PR TITLE
make a copy of the ledger for sanity check

### LINKED ISSUE #985: LastIdNotFound: ledger verify panic seen on testnet-sanity
This error seen when validating the leader's ledger on testnet deploy:

`verify failed at entry[256], err: LastIdNotFound(3BzTic3PP7urawGXa4n8ATmc5y3ks4SnStJ7FYmz3zep)`

See buildkite build #1115 in testnet-deploy builds.

### PR DESCRIPTION
**Pull request by rob-solana**
we can't verify a live ledger, unfortunately, fixes #985

### CODE REVIEW

File: ci/testnet-sanity.sh [hunk 1]
```diff
@@ -20,7 +20,10 @@ echo "--- $NET_URL: verify ledger"
 if [[ -z $NO_LEDGER_VERIFY ]]; then
   if [[ -d /var/snap/solana/current/config/ledger ]]; then
     # Note: here we assume this script is actually running on the leader node...
-    sudo solana.ledger-tool --ledger /var/snap/solana/current/config/ledger verify
+    LEDGER=/tmp/ledger-${BUILDKITE_BUILD_ID:-$$}
+    cp -r /var/snap/solana/current/config/ledger "$LEDGER"
+    solana.ledger-tool --ledger "$LEDGER" verify
+    rm -rf ${LEDGER}
```
Comment (mvines) [inline ci/testnet-sanity.sh]: nit: remove curlies?

File: ci/testnet-sanity.sh [hunk 2]
```diff
@@ -20,7 +20,10 @@ echo "--- $NET_URL: verify ledger"
 if [[ -z $NO_LEDGER_VERIFY ]]; then
   if [[ -d /var/snap/solana/current/config/ledger ]]; then
     # Note: here we assume this script is actually running on the leader node...
-    sudo solana.ledger-tool --ledger /var/snap/solana/current/config/ledger verify
+    LEDGER=/tmp/ledger-${BUILDKITE_BUILD_ID:-$$}
+    cp -r /var/snap/solana/current/config/ledger "$LEDGER"
+    solana.ledger-tool --ledger "$LEDGER" verify
```
Comment (mvines) [inline ci/testnet-sanity.sh]: Plop the ledger copy into cwd so we don't need to worry about cleaning up /tmp when `solana.ledger-tool` returns non-zero?
