### PR TITLE
tower: when syncing from vote state, update last_vote

### LINKED ISSUE #32880: Panic in core/src/heaviest_subtree_fork_choice.rs, thread solReplayStage
#### Problem

One of our Solana mainnet nodes panicked. It was not validating at the time.

```
thread 'solReplayStage' panicked at 'a bank at last_voted_slot((212118116, ugZWxPNYKgnkE1h71oek7Xvr9vDvcwRS1PZ8HcgcRGv)) is a frozen bank so must have been added to heaviest_subtree_fork_choice at time of freezing', core/src/heaviest_subtree_fork_choice.rs:874:29
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: <solana_core::heaviest_subtree_fork_choice::HeaviestSubtreeForkChoice as solana_core::fork_choice::ForkChoice>::select_forks
   3: solana_core::replay_stage::ReplayStage::new::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-08-18T07:20:50.607088657Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i message="panicked at 'a bank at last_voted_slot((212118116, ugZWxPNYKgnkE1h71oek7Xvr9vDvcwRS1PZ8HcgcRGv)) is a frozen bank so must have been added to heaviest_subtree_fork_choice at time of freezing', core/src/heaviest_subtree_fork_choice.rs:874:29" location="core/src/heaviest_subtree_fork_choice.rs:874:29" version="\"1.14.23 (src:devbuild; feat:1879391783)\""
```

This is running Solana 1.14.23.

[Full validator logs since the earliest occurrence of `ugZWxPNYKgnkE1h71oek7Xvr9vDvcwRS1PZ8HcgcRGv`.](https://github.com/solana-labs/solana/files/12377051/2023-08-18-solana.txt)

The code is this: https://github.com/solana-labs/solana/blob/68c6fd139fb7b2650be5852270cee703cae6acbc/core/src/heaviest_subtree_fork_choice.rs#L866-L878

It was originally introduced in https://github.com/solana-labs/solana/commit/cb8661bd49bb3591360589cba73d3593249b9fcc#diff-f1f89ae82910cdfebacc27d6ef29a9a55dc89eea426a8e4fcb1586f4ca8da55cR501-R513 by @ryoqun, although the conditions around it have changed since then. @ryoqun, do you have any clue what might be going on here?

#### Proposed Solution

I am not familiar enough with the replay stage to investigate what went wrong here. Let me know if there is anything I can do to help diagnose this further.

### PR DESCRIPTION
**Pull request by AshwinSekar**
#### Problem
On replay, if validators observe a newer vote state from a frozen bank, they will adopt that vote state in favor of their local tower. This is to avoid an outdated local tower from sending out slashable votes, or in case of large divergences, having to wait forever for lockout to expire. 

However when we adopt vote state, we do not update the tower's `last_vote` field. This causes problems in situations where our fork choice does not agree with the on chain vote state. 
Consider the following:

```
[...] - 115 - 124 - 125 - 126 - 127
         \
          - 120 - 121 - 122 - 123
```
Previously our validator had voted on slots `124` and `126` which landed in block `127`. Currently, our validator has replayed only up to `115` and has most recently voted on `115`.

Next it receives the remaining blocks up to `127` to replay. Upon replay of `127` it realizes it has voted on slots `124` and `126` in the past, and updates the tower vote state to reflect that.
https://github.com/solana-labs/solana/blob/14d0759af0663c7739ffd0c6e94c3c57f1ebcff1/core/src/replay_stage.rs#L3029-L3031

Suppose that previously, our validator did not get a chance to observe the `120` fork which is why it voted on `124`. However in our current run, fork choice rates `123` as the best slot. When it comes time to select forks, we select `123` as the heaviest slot *and* `123` as the heaviest slot descended from our last vote:
https://github.com/solana-labs/solana/blob/14d0759af0663c7739ffd0c6e94c3c57f1ebcff1/core/src/consensus/heaviest_subtree_fork_choice.rs#L1015-L1017
Because we have not updated our last vote, we think that the heaviest slot descends from our last vote, and incorrectly `SwitchForkDecision::SameFork` 
https://github.com/solana-labs/solana/blob/14d0759af0663c7739ffd0c6e94c3c57f1ebcff1/core/src/consensus.rs#L872-L875

At this point we vote on `123`, however because we adopted the vote state from `127` which contains votes for `124` and `126`, this vote will fail. Unfortunately we use `process_vote_unchecked` which silently ignores this error. We think that the vote has succeeded, and construct our new `last_vote` from the tower. This `last_vote` is garbage, it contains slot `126`, but has a `vote_hash` for slot `123`.
https://github.com/solana-labs/solana/blob/14d0759af0663c7739ffd0c6e94c3c57f1ebcff1/core/src/consensus.rs#L569-L578
Any further operations involving the tower + fork choice will now panic, as the last vote in the tower does not exist in fork choice (invalid `SlotHashKey`). 

#### Summary of Changes
- When adopting on chain vote state, update `tower.last_vote` as well.
- `tower.record_bank_vote...` variants should use `process_vote_unfiltered`. Although it is unlikely we can recover in case this vote fails, we can log the error to make debugging such situations possible. 

Fixes #32880 
This is the proper fix for #32894

### CODE REVIEW

File: core/src/consensus.rs [hunk 1]
```diff
@@ -564,29 +581,35 @@ impl Tower {
...
-            ))
+            let epoch = self.vote_state.current_epoch();
+            let result = process_vote_unfiltered(
+                &mut self.vote_state,
+                &vote.slots,
+                &vote,
+                &[(vote_slot, vote_hash)],
+                epoch,
+            );
+            if result.is_err() {
```
Comment (carllin) [inline core/src/consensus.rs:594]: maybe just bubble up the error from `process_vote_unchecked` and error log here?

File: core/src/consensus.rs [hunk 2]
```diff
@@ -564,29 +581,35 @@ impl Tower {
...
+                warn!(
```
Comment (carllin) [inline core/src/consensus.rs:595]: could be as strong as error!

File: core/src/consensus.rs [hunk 3]
```diff
@@ -564,29 +581,35 @@ impl Tower {
...
+                    "Error while recording vote {} {} in local tower {:?}",
+                    vote_slot, vote_hash, result
+                );
+            }
+            self.update_last_vote_from_vote_state(vote_hash);
```
Comment (carllin) [inline core/src/consensus.rs:600]: If we set this properly when we ingest a new on chain tower in `ReplayStage::compute_bank_stats()`, is this still necessary here?

Comment (AshwinSekar) [reply core/src/consensus.rs:600]: We still need it because we are recording a new vote here. this takes care of this block we were doing previously:
```
new_vote.set_timestamp(self.maybe_timestamp(self.last_voted_slot().unwrap_or_default()));
self.last_vote = new_vote;
```

File: core/src/replay_stage.rs [hunk 4]
```diff
@@ -3074,6 +3074,37 @@ impl ReplayStage {
 
                                 tower.vote_state.root_slot = bank_vote_state.root_slot;
                                 tower.vote_state.votes = bank_vote_state.votes;
+
+                                let last_voted_slot = tower.vote_state.last_voted_slot().unwrap_or(
+                                    // If our local root is higher than the highest slot in `bank_vote_state` due to
+                                    // supermajority roots, then it's expected that the vote state will be empty.
```
Comment (carllin) [inline core/src/replay_stage.rs:3080]: not exactly clear to me how supermajority roots cause tower to be empty

File: core/src/replay_stage.rs [hunk 5]
```diff
@@ -3074,6 +3074,37 @@ impl ReplayStage {
...
+                                    // In this case we use the root as our last vote. This root cannot be None, because
+                                    // `tower.vote_state.last_voted_slot()` is None only if `tower.vote_state.root_slot`
+                                    // is Some.
```
Comment (carllin) [inline core/src/replay_stage.rs:3083]: where is this logic guaranteed?

File: core/src/replay_stage.rs [hunk 6]
```diff
@@ -3074,6 +3074,37 @@ impl ReplayStage {
 
                                 tower.vote_state.root_slot = bank_vote_state.root_slot;
                                 tower.vote_state.votes = bank_vote_state.votes;
+
+                                let last_voted_slot = tower.vote_state.last_voted_slot().unwrap_or(
```
Comment (carllin) [inline core/src/replay_stage.rs:3078]: doesn't this have to be `Some` because we checked 

`if bank_vote_state.last_voted_slot()
                                > tower.vote_state.last_voted_slot()` 

above, so there must be at least some vote in `bank_vote_state.last_voted_slot()`

Comment (AshwinSekar) [reply core/src/replay_stage.rs:3078]: not necessarily, see here:
```
bank_vote_state
    .votes
    .retain(|lockout| lockout.slot() > local_root);
```

File: core/src/replay_stage.rs (hunk 5 above)
Comment (AshwinSekar) [reply core/src/replay_stage.rs:3083]: `None <= None`. If `tower.vote_state.last_voted_slot()` is `None`, this means `bank_vote_state.last_voted_slot()` must have originally been `Some` in order to pass this check:
```
if bank_vote_state.last_voted_slot()
                                > tower.vote_state.last_voted_slot()
```
That means it must have been adjusted here:
```
bank_vote_state .votes .retain(|lockout| lockout.slot() > local_root);
```
For it to have been adjusted, it must have passed this check:
```
if let Some(local_root) = tower.vote_state.root_slot {
```
So it follows that iff `tower.vote_state.root_slot` is `Some` then `tower.vote_state.last_voted_slot()` is `None`

File: core/src/replay_stage.rs (hunk 4 above)
Comment (AshwinSekar) [reply core/src/replay_stage.rs:3080]: you're right I don't think wait for super majority triggers this. it would be cases where root is artificially increased, which i believe could only happen when restarting from a snapshot. I'll update the comment.

File: core/src/replay_stage.rs (hunk 5 above)
Comment (carllin) [reply core/src/replay_stage.rs:3083]: ah yeah, i missed the logic where we adjust the root and filter out slots less than the root

File: core/src/replay_stage.rs (hunk 4 above)
Comment (AshwinSekar) [reply core/src/replay_stage.rs:3080]: Anything that artificially increases the root could trigger this. I think snapshot is the best example, but I think supermajority roots could also cause this:
https://github.com/solana-labs/solana/blob/d90e1582869d8ef8d386a1c156eda987404c43be/ledger/src/blockstore_processor.rs#L1576-L1580

File: core/src/replay_stage.rs [hunk 7]
```diff
@@ -3074,6 +3074,37 @@ impl ReplayStage {
...
+                                // progress map.
+                                //
+                                // Finally if both `bank` and `bank_vote_state.last_voted_slot()` are duplicate,
+                                // we must have the compatible versions of both duplicates in order to replay `bank`
+                                // successfully, so we are once again guaranteed that `bank_vote_state.last_voted_slot()`
+                                // is present in progress map.
+                                tower.update_last_vote_from_vote_state(
+                                    progress
+                                        .get_hash(last_voted_slot)
+                                        .expect("Must exist for us to have frozen descendant"),
```
Comment (carllin) [inline core/src/replay_stage.rs:3106]: just wanted to make sure root bank exists in bank forks even if we load from a snapshot, I think it does because of `bank_from_snapshot_archives()`

**Review by carllin — APPROVED** [review]
