### PR TITLE
Ensure accounts are unlocked

### LINKED ISSUE #3425: Bank's call to account::squash() causes assert on testnet
#### Problem
The fullnode is crashing with the following assert

```
thread 'solana-replay-stage' panicked at 'assertion failed: !self.account_locks.lock().unwrap().contains_key(&fork)', runtime/src/accounts.rs:995:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:482
   6: std::panicking::begin_panic
   7: solana_runtime::accounts::Accounts::squash
   8: solana_runtime::bank::Bank::squash
   9: solana::bank_forks::BankForks::set_root
```

This has been observed on V0.12 but should apply to master branch as well.
This PR comments out the offending call in V0.12 for beacons release.
https://github.com/solana-labs/solana/pull/3424

#### Proposed Solution
Reassess the crash on master branch. If it's a contained fix, pick it up to v0.12 and revert the change that's commenting out the call to squash.

### PR DESCRIPTION
**Pull request by sambley**
#### Problem
While performing the squash operation on accounts, the testnet asserts due to the condition that there are still accounts that are in locked state. There shouldn't be any accounts in locked state when the bank is frozen and squashed.

#### Summary of Changes
The accounts are left locked in case of error conditions that subsequently causes the assert when the bank accounts are squashed. Make sure the accounts are unlocked when the transaction processing fails.

Fixes #3425

### CODE REVIEW

File: core/src/banking_stage.rs [hunk 1]
```diff
@@ -269,17 +269,15 @@ impl BankingStage {
             bank.load_and_execute_transactions(txs, lock_results, MAX_RECENT_BLOCKHASHES / 2);
         let load_execute_time = now.elapsed();
 
-        let record_time = {
-            let now = Instant::now();
-            Self::record_transactions(bank.slot(), txs, &results, poh)?;
```
Comment (carllin) [inline core/src/banking_stage.rs]: Ouch haha

Comment (carllin) [reply core/src/banking_stage.rs]: It might be good to move the logic before the unlock into a separate function with a result which we can handle here, so nobody ever makes a similar mistake again?

**Comment by sakridge** [comment]
Nice.. good catch.

File: core/src/banking_stage.rs (hunk 1 above)
Comment (sambley) [reply core/src/banking_stage.rs]: Moved the logic to separate function.

**Comment by aeyakovenko** [comment]
@pgarg66, we should probably cherry-pick this change for the release.

**Comment by aeyakovenko** [comment]
@sambley feel free to merge this if it's ready

File: core/src/banking_stage.rs (hunk 1 above)
Comment (sakridge) [reply core/src/banking_stage.rs]: Well. Would be best to make an object that wraps the locks, on drop it unlocks the accounts and also add a test. We can file an issue for those things though.

Comment (sambley) [reply core/src/banking_stage.rs]: Opened a separate issue to track wrapping this in an object
https://github.com/solana-labs/solana/issues/3463
