### PR TITLE
Prevent cargo from running a non-BPF compiler for BPF target

### LINKED ISSUE #26583: cargo build-bpf stopped working after upgrade, uses wrong rustc
#### Problem
Processes spawned by `cargo-build-bpf` use the wrong rustc:
```
$ cargo build-bpf
BPF SDK: /home/kamm/dev/mango/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/kamm/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -Zremap-cwd-prefix= --target bpfel-unknown-unknown --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

where 
- `cargo --version` is `cargo 1.62.0 (a748cf5a3 2022-06-08)`. 
- `solana --version` is `solana-cli 1.10.29 (src:7f1fb145; feat:1425680972)`

Note how it tries to run against `.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc` instead of `.rustup/toolchains/bpf/bin/rustc`

For older versions of `cargo-build-bpf` that don't pass `-Zremap-cwd-prefix=` yet, the error will be
```
error: Error loading target specification: Could not find specification for target "bpfel-unknown-unknown". 
Run `rustc --print target-list` for a list of built-in targets
```

Going back to an older toolchain version with rustup does (surprisingly) not help. The error persists after a `rustup default 1.59.0-x86_64-unknown-linux-gnu`.

#### Analysis

The issue seems to be a RUSTC environment variable that cargo sets before calling `cargo-build-bpf`. This can be seen by passing `--generate-child-script-on-failure` and inspecting the resulting script.

In fact I can reproduce the error with `RUSTC=~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc cargo +bpf build --target bpfel-unknown-unknown --release`

#### Proposed Solution

Workaround 1: `cargo +bpf build-bpf`.

Workaround 2: Use an old cargo version explicitly: `~/.rustup/toolchains/1.59.0-x86_64-unknown-linux-gnu/bin/cargo build-bpf`

Possibly unset `RUSTC` in `cargo-build-bpf`? But it's possible that whatever changed also had other effects.

### PR DESCRIPTION
**Pull request by dmakarov**
#### Problem

cargo-build-bpf if started from cargo may run a wrong (non-BPF capable) rust compiler.

#### Summary of Changes

Remove RUSTC var from cargo-build-bpf environment.

Fixes #26583

### CODE REVIEW

File: sdk/cargo-build-sbf/src/main.rs [hunk 1]
```diff
@@ -524,8 +525,19 @@ fn build_sbf_package(config: &Config, target_directory: &Path, package: &cargo_m
...
+            env::var("RUSTFLAGS").ok().unwrap_or_default()
+        );
+    }
+
+    // RUSTC variable overrides cargo +<toolchain> mechanism of
+    // selecting the rust compiler and makes cargo run a rust compiler
+    // other than the one linked in BPF toolchain. We have to prevent
+    // this by removing RUSTC from the child process environment.
+    if env::var("RUSTC").is_ok() {
+        env::remove_var("RUSTC")
```
Comment (t-nelson) [inline sdk/cargo-build-sbf/src/main.rs:539]: should probably log a warning about ignoring the caller's environment?

Comment (dmakarov) [reply sdk/cargo-build-sbf/src/main.rs:539]: good poinr, i’ll add a warning message.
