### PR TITLE
fix: transactions populated from RPC requests retain original account key order

### LINKED ISSUE #21722: Web3.js transaction serialize => deserialize => serialize can produce "Signature verification failed" due to bug in Message serialization
#### Problem

The logic here https://github.com/solana-labs/solana-web3.js/blob/74007a55afa29b36e0535bb9bcff3b64dda9b19e/src/transaction.ts#L261-L281

Can lead to different orderings to accountMetas after serializing and deserializing.  The "content" of the transaction is the same, however the accountKeys flipped around. So long as the indices still hold true for writable accounts, the transaction will function the same.

The issue is that this is then serialized and used to create a transaction signature. So this non-determinism can mean that a previously correct signature is now incorrect. 

Code to reproduce:

```js
    const signer = Keypair.generate();
    const acc0Writable = Keypair.generate();
    const acc1Writable = Keypair.generate();
    const acc2Writable = Keypair.generate();
    const t0 = new Transaction({
      recentBlockhash: "HZaTsZuhN1aaz9WuuimCFMyH7wJ5xiyMUHFCnZSMyguH",
      feePayer: signer.publicKey
    });
    t0.add(new TransactionInstruction({
      keys: [{
        pubkey: signer.publicKey,
        isWritable: true,
        isSigner: true
      }, {
        pubkey: acc0Writable.publicKey,
        isWritable: true,
        isSigner: false
      }],
      programId: Keypair.generate().publicKey
    }))
    t0.add(new TransactionInstruction({
      keys: [{
        pubkey: acc1Writable.publicKey,
        isWritable: false,
        isSigner: false
      }],
      programId: Keypair.generate().publicKey
    }))
    t0.add(new TransactionInstruction({
      keys: [{
        pubkey: acc2Writable.publicKey,
        isWritable: true,
        isSigner: false
      }],
      programId: Keypair.generate().publicKey
    }))
    t0.add(new TransactionInstruction({
      keys: [{
        pubkey: signer.publicKey,
        isWritable: true,
        isSigner: true
      },{
        pubkey: acc0Writable.publicKey,
        isWritable: false,
        isSigner: false
      },  {
        pubkey: acc2Writable.publicKey,
        isWritable: false,
        isSigner: false
      }, {
        pubkey: acc1Writable.publicKey,
        isWritable: true,
        isSigner: false
      }],
      programId: Keypair.generate().publicKey
    }))
    t0.partialSign(signer);
    const t1 = Transaction.from(t0.serialize());
    t1.serialize()
```

A workaround is to, before pre-signing the transaction, run Transaction.from(tx.serialize({ requireAllSignatures: false })). Then sign the transaction and serialize. This ensures the ordering doesn't get jumbled. 

#### Proposed Solution

Add a default sorting here based on the alphabetical (or just numerical) sorting of the public keys so that this function is deterministic.

https://github.com/solana-labs/solana-web3.js/blob/74007a55afa29b36e0535bb9bcff3b64dda9b19e/src/transaction.ts#L261

### PR DESCRIPTION
**Pull request by jordansexton**
#### Problem

`Transaction.populate` is kind of broken (see https://github.com/solana-labs/solana/issues/21722). It's not so much that the implementation of `populate` itself is broken, but rather that attempting to reserialize a transaction that was deserialized from a message is conceptually invalid.

#### Summary of Changes

This PR attempts to fix the issue in a surgical and slightly hacky fashion, without adding to or changing the public API, or breaking _correctly behaving_ applications.

This is accomplished by setting an internal `Message` property if the `Transaction` was created with `populate`. If this `Message` exists, it will be used instead of recompiling the message from the transaction, which is what causes the account key order to change.

Instructions cannot be added to a populated transaction. This will throw an error at runtime. Since _correctly behaving_ applications should not add instructions to a compiled message, I regard this as non-breaking. YMMV. If there are concerns about this, it could be limited to populated transactions with non-null signature values.

I haven't added getters/setters for `feePayer`, `recentBlockhash`, `nonceInfo`, or `instructions`. If added, these could throw errors if these are set on a populated transaction. I wanted to first propose these changes and gather feedback.

Fixes #21722
Closes #23684 (duplicate, but also adds to the public API which I don't think we should do for this)

### CODE REVIEW

**Comment by t-nelson** [comment]
I think this gets the job done.  Kinda sucks carrying the duplicate data around, but given the rest of the inefficiencies in the lib, probably a small price to pay for compatibility

**Comment by jstarry** [comment]
Current fix looks great!

> I haven't added getters/setters for feePayer, recentBlockhash, nonceInfo, or instructions. If added, these could throw errors if these are set on a populated transaction. I wanted to first propose these changes and gather feedback.

What if we cache the fields which affect message compilation (`feePayer`, `recentBlockhash`, `nonceInfo`, and `instructions`) as `_populatedMessageFields` and then check in `compileMessage` if any of them have been modified. If modifications are detected, throw an error. Otherwise return the cached `_message` that you added.

**Comment by jordansexton** [comment]
> What if we cache the fields which affect message compilation (`feePayer`, `recentBlockhash`, `nonceInfo`, and `instructions`) as `_populatedMessageFields` and then check in `compileMessage` if any of them have been modified. If modifications are detected, throw an error. Otherwise return the cached `_message` that you added.

Hmm, we could do that. My instinctual preference is to fail fast if someone tries to modify a Transaction that shouldn't be modified rather than wait until it's serialized. But throwing errors inside of setters is kind of gross on multiple levels.

@steveluscher thoughts?

**Comment by t-nelson** [comment]
> But throwing errors inside of setters is kind of gross on multiple levels.

That was what motivated me to suggest not being able to deser into `Transaction` at all, but some new type that doesn't allow modifications other than addSignature

**Comment by steveluscher** [comment]
> That was what motivated me to suggest not being able to deser into Transaction at all, but some new type that doesn't allow modifications other than addSignature

I've only thought about this for three seconds, but this strikes me as a worthwhile project. You'd have to upgrade all consumers of `Transaction` to understand and handle this new `ImmutableTransaction` or `CompiledTransaction` type (as @t-nelson said… compatibility vs…).

If you did it this way, TypeScript will prevent you from trying to modify such a transaction, saving you from having to find out at runtime, which is nice.

More work though.

**Comment by jstarry** [comment]
Cool, I think we all agree that overhauling the transaction class is the way to go but this PR is still a good incremental fix. I'm fine with it as is.

**Comment by jordansexton** [comment]
> What if we cache the fields which affect message compilation (feePayer, recentBlockhash, nonceInfo, and instructions)

@steveluscher @jstarry this has been done. Implementation is pretty ugly, but I'm not sure how to make it cleaner and still check everything.

File: web3.js/src/transaction.ts [hunk 1]
```diff
@@ -204,6 +214,141 @@ export class Transaction {
    * Compile transaction data
    */
   compileMessage(): Message {
+    if (this._message) {
+      const originalTransaction = this._originalTransaction;
+      if (!originalTransaction) {
+        throw new Error(
+          'Transaction mutated after being populated from Message',
+        );
+      }
```
Comment (steveluscher) [inline web3.js/src/transaction.ts:223]: This is just here to narrow the TypeScript type, right? If `_message` is non-null, then `_originalTransaction` is for sure non-null, isn't it?

File: web3.js/test/transaction.test.ts [hunk 2]
```diff
@@ -365,14 +365,14 @@ describe('Transaction', () => {
...
-    const tx = Transaction.from(wireTransaction);
+    const deserializedTransaction = Transaction.from(serializedTransaction);
 
-    expect(tx).to.eql(expectedTransaction);
-    expect(wireTransaction).to.eql(expectedTransaction.serialize());
+    expect(expectedTransaction.serialize()).to.eql(serializedTransaction);
+    expect(deserializedTransaction.serialize()).to.eql(serializedTransaction);
   });
 
   it('populate transaction', () => {
```
Comment (steveluscher) [inline web3.js/test/transaction.test.ts:378]: It's probably too much work, but adding a few of these might prevent someone from breaking this code in the future.

```
// Do some illegal modification...
expect(transaction.compileMessage).to.throw();
```

**Review by steveluscher — APPROVED** [review]
LGTM! Since there are so many `throws` you might consider doing something like…

```
function fail(): never {
  throw new Error(...);
}

if (transaction.foo !== originalTransaction.foo) {
  fail();
}
```

File: web3.js/test/transaction.test.ts (hunk 2 above)
Comment (jstarry) [reply web3.js/test/transaction.test.ts:378]: I agree that we should have test coverage that a post-populate modification actually throws an error

**Comment by steveluscher** [comment]
> I think I came up with something that would be cleaner here…

Nice; yeah, at one point I had thought about hashing properties of the transaction to be able to detect modifications, but then I forgot.

You could even use one of these ‘stable stringify’ implementations and just throw a giant bundle of properties at it. https://www.npmjs.com/search?q=stable%20stringify

Pluses: easy way to get a unique identifier
Minuses: have to carry around giant strings in memory, `JSON.stringify` is no picnic performance-wise

Either way, if any material property ever gets added to `Transaction` and we forget to add it to this check, we're back to square one. That's probably an argument to go for the solution based on two different types of transaction.

**Comment by jordansexton** [comment]
Haha that approach is so much cleaner. I merged your stringify change, though I'm not sure offhand how the objects, especially `TransactionInstruction`, are going to get stringified. I'll do some testing.

File: web3.js/src/transaction.ts (hunk 1 above)
Comment (jordansexton) [reply web3.js/src/transaction.ts]: Removed in stringified version.

File: web3.js/.eslintrc.js [hunk 3]
```diff
@@ -31,14 +31,6 @@ module.exports = {
...
       },
     ],
-    indent: [
-      'error',
-      2,
-      {
-        MemberExpression: 1,
-        SwitchCase: 1,
-      },
-    ],
```
Comment (jordansexton) [inline web3.js/.eslintrc.js:41]: I removed this eslint rule because indentation is already handled by prettier, and the rule conflicts with prettier's formatting.

File: web3.js/src/transaction.ts [hunk 4]
```diff
@@ -169,13 +202,41 @@ export class Transaction {
...
+      feePayer: this.feePayer ? this.feePayer.toJSON() : null,
+      nonceInfo: this.nonceInfo
+        ? {
+            nonce: this.nonceInfo.nonce,
+            nonceInstruction: this.nonceInfo.nonceInstruction.toJSON(),
+          }
+        : null,
+      instructions: this.instructions.map(instruction => instruction.toJSON()),
+      signatures: this.signatures.map(({publicKey, signature}) => ({
+        publicKey: publicKey.toJSON(),
```
Comment (jordansexton) [inline web3.js/src/transaction.ts:234]: I don't love that it's `publicKey` here and `pubkey` in the instructions. Not sure if we should preserve consistency with the type or make for a predictable interface.

**Review by steveluscher — COMMENTED** [review]
I'm about to hop on a plane, but real quick: comparing a hash of a transaction to see if it was modified: love it. The hash being implemented with `JSON.stringify` is sort of a bummer though. Like… these will hash to a different string.

```
signatures: [{
  signature: ...,
  publicKey: ...,
}]
```

…will mismatch with…

```
signatures: [{
  publicKey: ...,
  signature: ...,
}]
```

I actually think that's happening here. `compileTransaction` and `toJSON` have them in different orders.

It would be nice to use an actual, stable, order independent object hashing function that just gives a SHA or something. But that would mean extra bytes in the JS package.

Ugh!

File: web3.js/src/transaction.ts (hunk 4 above)
Comment (jstarry) [reply web3.js/src/transaction.ts:234]: I think the name discrepancy is ok, but can we make `toJSON` an internal method?

Comment (jordansexton) [reply web3.js/src/transaction.ts:234]: Yeah, I can do that. Always nice to kick the can on changes to the public API.

File: web3.js/src/transaction.ts [hunk 5]
```diff
@@ -169,13 +211,44 @@ export class Transaction {
...
+        signature: signature ? [...signature] : null,
+      })),
```
Comment (steveluscher) [inline web3.js/src/transaction.ts:248]: Oh nice. I was worried that there existed the possibility of false positives because in `populate` these keys are ordered ``signature`, `publicKey` instead of `publicKey`, `signature`, but since you're destructuring and restructuring them here, there's no risk of that.

**Review by steveluscher — APPROVED** [review]

**Comment by steveluscher** [comment]
If this need to stringify objects in a way that's stable – regardless of whether keys are in different orders – ever comes up again, this is one of my favs.

https://github.com/facebook/relay/blob/ec03bf455d28b7eb30e5251731bf768eac2c2abd/packages/relay-runtime/store/OperationExecutor.js#L1668-L1670

**Review by jstarry — APPROVED** [review]

**Comment by jstarry** [comment]
@mergifyio rebase

**Comment by jstarry** [comment]
@jordansexton do you mind rebasing and merging this when you get the chance?

**Comment by jordansexton** [comment]
@jstarry unfortunately there's a failing test which surfaced this issue:

https://github.com/solana-labs/solana/blob/6c5a3ca4a0bf016f6c4401f3a7b1c789a1140add/web3.js/src/connection.ts#L3897-L3905

Transaction simulation from a Message relies on modifying the transaction after populating it. If I merge this change as is, it will break transaction simulation.

I did something _very hacky_ and unset the internal properties in this instance to keep the current behavior of `simulateTransaction`:

https://github.com/jordansexton/solana/blob/c81f047f7dcb73de89661782dd0d478b987b1c17/web3.js/src/connection.ts#L3898

If tests pass now, I'll merge away.
