### PR TITLE
Don't panic on packet data

### LINKED ISSUE #1274: Malformed transactions crash the leader
Need to at least audit all calls to `deserialize()` and ensure its error is being handled and not `unwrap()`ed.

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Malformed or malicious packets could cause panics

#### Summary of Changes

Handle bad packets gracefully.

In general packet handling was analyzed looking for cases where a bad packet would cause a panic.  The changes in this PR are more nits that were found during that analysis.

One question is core/src/archiver.rs - download_from_archiver().  This function returns a result but is full of calls to `unwrap()` or functions that can panic.  Should this function be allowed to panic?

Fixes #1274

### CODE REVIEW

**Comment by sagar-solana** [comment]
Yeah I think `download_from_archiver` panicking is okay for now. It's only used by tests.

File: sdk/src/short_vec.rs [hunk 1]
```diff
@@ -179,8 +179,8 @@ impl<'de, T: Deserialize<'de>> Deserialize<'de> for ShortVec<T> {
 /// Return the decoded value and how many bytes it consumed.
 pub fn decode_len(bytes: &[u8]) -> Result<(usize, usize), Box<bincode::ErrorKind>> {
     let short_len: ShortU16 = bincode::deserialize(bytes)?;
-    let num_bytes = bincode::serialized_size(&short_len).unwrap() as usize;
```
Comment (garious) [inline sdk/src/short_vec.rs]: A test here would be nice. That error looks unreachable.

Comment (jackcmay) [reply sdk/src/short_vec.rs]: Same as before but return the error instead of panicking even if it is unreachable today
