### PR TITLE
Fix slow/stuck unstaking due to toggling in epoch

### LINKED ISSUE #10982: Stake accounts stuck deactivating
#### Problem
A collection of stake accounts on mainnet-beta are "stuck" in the deactivating state. All 14 of them happen to have been delegated and deactivated in epoch 16. The immediate cause of this issue is that the StakeHistory sysvar reports 0 lamports as deactivating for epoch 16, so that the share of deactivating stake allotted to each of these accounts is also 0.

Here is the output of `solana stake-history` for nearby epochs:
```
    19      5071038.34127776          400.39543424           15.31303968 SOL
     18      5020338.33040928        50700.01086848           15.31303968 SOL
     17       5020338.3381264            0.09771712           15.41847392 SOL
     16      4970322.82421824        50000.20086848                     0 SOL
     15        5020319.828784            2.99315136        49999.99771712 SOL
```
`15.31303968 SOL` corresponds to the amount of stake "stuck" in these 14 accounts.

Addresses:
```
[
    ZKbZsMhUJMp7MfcFmkYqtipcgcJxi33GiCyNMTQKUV9,
    2371aoQkSwkqoceYzA7ycSaLaW2takvLv52u8FDYmFJU,
    3Sxhqd87eGHzRCHW1wK8EbkVVpAqLeEoYSYQHpuKh9EZ,
    3fu3BEhLWP1Zm6PyjrSQWDkwMEmiUgnQy6xXDrRxeQg9,
    6uMvSMbEux6VLE2D4JY471hmG74PUDTvAqc2ggTi6Zg3,
    7SGCyBSwNCbhC1FxPW5FFTuyyoNqo1kWBN3P2ua881zJ,
    7cg9whPgWFZbCTn52AEjUaUAJk44n2jgpZWjzYPPtSVR,
    9S1gnNB1yQy3j1uTqrLVX6UqzQYKpHbdBtwHb4vjUfYd,
    9dUAdJcdKQ5ZDsJg4sWYTtCuYgtQbQwnXKFqJQGjTnEH,
    Bo1PzDvwSMorNW7dMsbT69aRuJox6aXKWeGLyu6FYikU,
    CVUysRJyjdRey56q92bTuzgNVot99uhdo5aSRH6qMBav,
    D59zLU646AvzXyhxMSZvFT67JiggCMYzUzWKB47qNhcn,
    DzHX8tfrE7uhSDpo9m1pcGHbH2sStmDuipRbdQYBRsKw,
    F6Ni2rYtY74h8ju7neMbUMC1afccDoELFEHhHiwY38ui,
]
```

@t-nelson reported seeing this issue locally when delegating and deactivating stake in the same epoch, but it does not always reproduce.

#### Proposed Solution

???

CC: @garious

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

if activation_epoch == deactivation_epoch, there should be no need for cooldown. But we incorrectly require it not at the epoch, but at the following epochs. And if stake history says no other deactivating stakes, the cooldown could be stuck. Otherwise (most of time), we incorrectly cool-downs the quickly-deactivated stake account very slowly.

For details, please see the attached test.

#### Summary of Changes

We need to ensure to return `(0, 0)` (= no effective stake, no activating stake) for stake account activated-then-deactivated in a single epoch.

Special gating required because of duality of codepath when calculating stakes: instruction processor and normal runtime:
- old instruction processor (legacy_stake_program): call `stake_and_activating(..., false);`
- new instruction processor (stake_program): call `stake_and_activating(..., true);`
- runtime/bank: call `stake_and_activating(..., flag)` where `flag` is conditioned by runtime feature.

Fixes #10982

Context: #13460 #13471.

### CODE REVIEW

File: cli/src/stake.rs [hunk 1]
```diff
@@ -1514,7 +1514,7 @@ pub fn build_stake_state(
             let current_epoch = clock.epoch;
             let (active_stake, activating_stake, deactivating_stake) = stake
                 .delegation
-                .stake_activating_and_deactivating(current_epoch, Some(stake_history));
+                .stake_activating_and_deactivating(current_epoch, Some(stake_history), true);
```
Comment (ryoqun) [inline cli/src/stake.rs:1517]: to be rebased on #13497

File: runtime/src/bank.rs [hunk 2]
```diff
@@ -871,7 +869,15 @@ impl Bank {
         if parent.epoch() < new.epoch() {
             new.apply_feature_activations(false);
         }
+        let cloned = new
+            .stakes
+            .read()
+            .unwrap()
+            .clone_with_epoch(epoch, new.stake_program_v2_enabled());
```
Comment (ryoqun) [inline runtime/src/bank.rs:876]: Actual `clone()`-ing moved here because I wanted to touch runtime feature (via `.stake_program_v2_enabled()`).

File: runtime/src/bank.rs [hunk 3]
```diff
@@ -871,7 +869,15 @@ impl Bank {
...
+        *new.stakes.write().unwrap() = cloned;
 
+        let leader_schedule_epoch = epoch_schedule.get_leader_schedule_epoch(slot);
```
Comment (ryoqun) [inline runtime/src/bank.rs:879]: moved here because we should update anything related stakes after we update the `Bank::stakes` conditionally on the runtime feature activation.

File: programs/stake/src/stake_state.rs [hunk 4]
```diff
@@ -302,12 +310,16 @@ impl Delegation {
...
+        fix_stake_deactivate: bool,
     ) -> (u64, u64) {
         let delegated_stake = self.stake;
 
         if self.is_bootstrap() {
             // fully effective immediately
             (delegated_stake, 0)
+        } else if fix_stake_deactivate && self.activation_epoch == self.deactivation_epoch {
+            // order important; and this correctly consider boostrap stakes first
+            (0, 0)
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:322]: For this three lines, we need a 400+ lines pr. What a wonderful world.

File: programs/stake/src/stake_state.rs [hunk 5]
```diff
@@ -1593,12 +1650,158 @@ mod tests {
...
+            );
+        }
+
+        #[test]
+        fn test_old_behavior_slow() {
+            do_test(
+                OldDeactivationBehavior::Slow,
+                false,
+                &[
+                    (0, 0, 0),
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:1736]: notice, previously we're doing right for the calculation of stake when it's the epoch we modified the stake account.

File: programs/stake/src/stake_state.rs [hunk 6]
```diff
@@ -1593,12 +1650,158 @@ mod tests {
...
+                    (13, 0, 13),
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:1737]: but, at the next epoch, we're incorrectly activating it by iterating the loop exactly once.

File: programs/stake/src/stake_state.rs [hunk 7]
```diff
@@ -1593,12 +1650,158 @@ mod tests {
...
+                    (10, 0, 10),
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:1738]: And cooldown must be wrongly required.

**Comment by ryoqun** [comment]
todo:

- [ ] careful local testing.

File: runtime/src/bank.rs (hunk 2 above)
Comment (ryoqun) [reply runtime/src/bank.rs:876]: There is same change in #13461

**Review by CriesofCarrots — DISMISSED** [review]
One nit. Otherwise this looks good to me.
The existing cli code is actually nice for testing; I ran `solana stake-account` and `solana stakes` against mainnet-beta to see the issue resolved :)

It'd be nice to get a preview of what will happen to MNB stake-history after this goes into effect (with no other activations/deactivations), since we've had that stuck-deactivating 15.31303968 SOL following us since epoch 17. Would that be easy to simulate in your local tests?

**Comment by ryoqun** [comment]
(for the record): local testing result

Upon immediate onset of next epoch following feature activation, stuck deactivating stake disappears and stuck accounts suddenly chaged to deactivated

```
$ ./target/release/solana --url http://localhost:8899 feature status
Feature                                      Description                              Status
...
AgFqbhaAiommMnEuiWCX2uqD9xDRkGSvBfKkSQScHPUT solana_stake_program v2                  active since slot 1152
...

$ ./target/release/solana --url http://localhost:8899 epoch-info

Block height: 1175
Slot: 1176
Epoch: 9
Epoch Slot Range: [1152..1280)
Epoch Completed Percent: 18.750%
Epoch Completed Slots: 24/128 (104 remaining)
Epoch Completed Time: 9s/51s (41s remaining)


$ ./target/release/solana --url http://localhost:8899 stake-history

  Epoch       Effective Stake      Activating Stake    Deactivating Stake
      8           2.723530923           0.771903317                     0 SOL
      7           2.278368163           1.341495357            0.12442928 SOL
      6           1.822694531           1.797168989            0.12442928 SOL
      5           1.458155625           2.161707895            0.12442928 SOL
      4             1.1665245            2.45333902            0.12442928 SOL
      3             0.9332196            2.68664392            0.12442928 SOL
      2            0.74657568            2.87328784            0.12442928 SOL
      1            0.49771712            2.99771712                     0 SOL
      0            0.49771712                     0                     0 SOL

# BEFORE:

$ ./target/release/solana --url http://localhost:8899 stake-account my-identity2.json
Balance: 3 SOL
Rent Exempt Reserve: 0.00228288 SOL
epochs Some(1) Some(1)
self CliStakeState {
    stake_type: Stake,
    account_balance: 3000000000,
    delegated_stake: Some(
        2997717120,
    ),  
    delegated_vote_account_address: Some(
        "9SuFhTi4dywYKaavMR7M5N7TRZLs8dm7tsHLaP8cLgaS",
    ),  
    activation_epoch: Some(
        1,
    ),  
    deactivation_epoch: Some(
        1,
    ),  
    authorized: Some(
        CliAuthorized {
            staker: "7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j",
            withdrawer: "7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j",
        },  
    ),  
    lockup: None,
    use_lamports_unit: false,
    current_epoch: 6,
    rent_exempt_reserve: Some(
        2282880,
    ),  
    active_stake: Some(
        124429280,
    ),  
    activating_stake: None,
    deactivating_stake: Some(
        2873287840,
    ),  
    epoch_rewards: Some(
        [],
    ),  
}   
Delegated Stake: 2.99771712 SOL
Inactive Stake: 0.12442928 SOL
Deactivating Stake: 2.87328784 SOL  
Stake deactivates starting from epoch: 1
Delegated Vote Account Address: 9SuFhTi4dywYKaavMR7M5N7TRZLs8dm7tsHLaP8cLgaS
Stake Authority: 7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j
Withdraw Authority: 7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j


# AFTER:

 $ ./target/release/solana --url http://localhost:8899 stake-account my-identity2.json
Balance: 3 SOL
Rent Exempt Reserve: 0.00228288 SOL
epochs Some(1) Some(1)
self CliStakeState {
    stake_type: Stake,
    account_balance: 3000000000,
    delegated_stake: Some(
        2997717120,
    ),
    delegated_vote_account_address: Some(
        "9SuFhTi4dywYKaavMR7M5N7TRZLs8dm7tsHLaP8cLgaS",
    ),
    activation_epoch: Some(
        1,
    ),
    deactivation_epoch: Some(
        1,
    ),
    authorized: Some(
        CliAuthorized {
            staker: "7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j",
            withdrawer: "7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j",
        },
    ),
    lockup: None,
    use_lamports_unit: false,
    current_epoch: 10,
    rent_exempt_reserve: Some(
        2282880,
    ),
    active_stake: None,
    activating_stake: None,
    deactivating_stake: None,
    epoch_rewards: Some(
        [],
    ),
}
Stake account is undelegated
Stake Authority: 7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j
Withdraw Authority: 7DEkZ3z7cWA7DpfBZjR6iCEdc5zkfr8wZi2TNBTkbt6j






```

File: sdk/src/feature_set.rs [hunk 8]
```diff
@@ -155,6 +155,10 @@ impl FeatureSet {
         self.is_active(&cumulative_rent_related_fixes::id())
     }
 
+    pub fn stake_program_v2_enabled(&self) -> bool {
+        self.is_active(&stake_program_v2::id())
+    }
```
[the remark this answers is not in the document]
Comment (ryoqun) [reply sdk/src/feature_set.rs]: yeah. that's too much, just removed :)

**Comment by ryoqun** [comment]
> It'd be nice to get a preview of what will happen to MNB stake-history after this goes into effect (with no other activations/deactivations), wince we've had that stuck-deactivating 15.31303968 SOL following us since epoch 17. Would that be easy to simulate in your local tests?

In short, as [this local testing shows](https://github.com/solana-labs/solana/pull/13501#issuecomment-725392716), it only corrects future stake history entries newer than or equal to the epoch `stake_program_vs` is activated. So, entries for epoch 17 and onwards 
 won't be updated.

On top of stake history sysvar, this fix will also suddenly changes stake distribution and consequencial leader schedule of N+1.

The inconsistent stake history indeed slightly continue to skew the current cluster-wide stake distribution if there are still activating stakes (should be verry small) since epoch 17. Also this slightly affects all of deactivating stakes, because deactivating stake is suddenly will be reduced. Anyway, I think we can't do about this. Reconstructing stake history on-chain is now impossible and doing that off-chain and replacing with it will be very questionable practice.


We can't retrospectively update older epoch entries because we can't re-construct older stake history entries only with current live account view. That's because some stakes account has been removed. I think that's why stake history exists in the first place.

> Would that be easy to simulate in your local tests

Also, I can simulate locally and I'll post the result

**Comment by ryoqun** [comment]
base

```
$ ./target/release/solana stake-history

  Epoch       Effective Stake      Activating Stake    Deactivating Stake
    110   167401122.360376567        1558239.481008      5500563.01978176 SOL
    109   169346111.643292427       1661779.5395936      3606784.13554912 SOL
    108   169237091.558366656       160538.31356384        51533.54167776 SOL
    107   165667340.091970176       5224280.6991696       1654544.5458128 SOL
    106   165667255.045828164         1686.88142464         1617.14832232 SOL
    105   164010737.121094346      1689662.44849672        33159.83680256 SOL
...
```

warped without fix

```
$ ./target/release/solana --url http://localhost:8899 stake-history

  Epoch       Effective Stake      Activating Stake    Deactivating Stake
    111   163458814.134642482      5501268.70896064       516292.52201376 SOL
    110   167401122.360376567        1558239.481008      5500563.01978176 SOL
    109   169346111.643292427       1661779.5395936      3606784.13554912 SOL
    108   169237091.558366656       160538.31356384        51533.54167776 SOL
    107   165667340.091970176       5224280.6991696       1654544.5458128 SOL
    106   165667255.045828164         1686.88142464         1617.14832232 SOL
    105   164010737.121094346      1689662.44849672        33159.83680256 SOL
...
```


warped with fix

```
$ ./target/release/solana --url http://localhost:8899 stake-history

  Epoch       Effective Stake      Activating Stake    Deactivating Stake
    111   163458798.821602821      5501268.70896064       516277.20897408 SOL
    110   167401122.360376567        1558239.481008      5500563.01978176 SOL
    109   169346111.643292427       1661779.5395936      3606784.13554912 SOL
    108   169237091.558366656       160538.31356384        51533.54167776 SOL
    107   165667340.091970176       5224280.6991696       1654544.5458128 SOL
    106   165667255.045828164         1686.88142464         1617.14832232 SOL
    105   164010737.121094346      1689662.44849672        33159.83680256 SOL
...
```

diff:

```diff
diff --git a/bbb b/aaa
index d23742fdb6..afd0edf741 100644
--- a/bbb
+++ b/aaa
@@ -1,5 +1,5 @@
   Epoch       Effective Stake      Activating Stake    Deactivating Stake
-    111   163458814.134642482      5501268.70896064       516292.52201376 SOL
+    111   163458798.821602821      5501268.70896064       516277.20897408 SOL
     110   167401122.360376567        1558239.481008      5500563.01978176 SOL
     109   169346111.643292427       1661779.5395936      3606784.13554912 SOL
     108   169237091.558366656       160538.31356384        51533.54167776 SOL

```


for the record, anyone can easily test like (with https://github.com/ryoqun/solana/tree/slow-stuck-stake-deactivation-manual-testing):

```
$ ls -l target/mainnet-beta51
total 339624
-rw-rw-r-- 1 ryoqun ryoqun     34256 Nov 11 22:03 genesis.tar.bz2
-rw-rw-r-- 1 ryoqun ryoqun 347735912 Nov 11 22:03 snapshot-48245556-5g8cBQtEJVAWzDULQGyzVfJyWgqkeKSqscoUHqQxSQAa.tar.zst

$ ./target/release/solana-ledger-tool --ledger target/mainnet-beta51/ create-snapshot --warp-slot 48384000 48245556 target/mainnet-beta51-warped-without-fix
...

$ cp target/mainnet-beta51/genesis.tar.bz2 target/mainnet-beta51-warped-without-fix/

$ ./target/release/solana-validator --ledger target/mainnet-beta51-warped-without-fix/ --no-port-check -o - --rpc-port 8899
...

$ ./target/release/solana --url http://localhost:8899 epoch-info

Block height: 45870201
Slot: 48384000
Epoch: 112
Epoch Slot Range: [48384000..48816000)
Epoch Completed Percent: 0.000%
Epoch Completed Slots: 0/432000 (432000 remaining)
Epoch Completed Time: 0s/2days (2days remaining)


$ ./target/release/solana --url http://localhost:8899 stake-history
...

```

**Comment by ryoqun** [comment]
Also, it looks like all of affected stake accounts are delegating now inactive leader validators. I see no difference of stake distribution at present.

```
Active Stake: 168443805.634629071 SOL
Current Stake: 0 SOL (0.00%)
Delinquent Stake: 168443805.634629071 SOL (100.00%)

Stake By Version:
unknown  -   0 current validators ( 0.00%), 237 delinquent validators (100.00%)

  Identity                                      Vote Account                            Commission  Last Vote  Root Block     Credits  Version   Active Stake
! DWvDTSh3qfn88UoQTEKRV2JnLt5jtJAVoiCo3ivtMwXP  FKsC411dik9ktS6xPADxs4Fk2SCENvAiuccQHLAPndvk    7%   48245555    48245524           0   unknown  13857657.412171241 SOL (8.23%)
! Awes4Tr6TX8JDzEhCZY2QVNimT6iD1zWHzf1vNyGvpLM  DumiCKHVqoCQKD8roLApzR5Fit8qGV5fVQsJV9sTZk4a    8%   48245555    48245524           0   unknown  12291353.93916928 SOL (7.30%)
! XkCriyrNwS3G4rzAXtG5B1nnvb5Ka1JtCku93VqeKAr   beefKGBWeSpHzYBHZXwp5So7wdQGX6mu4ZHCsH3uTar     8%   48245555    48245524           0   unknown  11315843.00231168 SOL (6.72%)
! ChorusmmK7i1AxXeiTtQgQZhQNiXYU84ULeaYF1EH15n  Chorus6Kis8tFHA7AowrPMcRJk3LbApHTYpgSNXzY5KE    8%   48245555    48245524           0   unknown  8105656.27984856 SOL (4.81%)
! Certusm1sa411sMpV9FPqU5dXAYhmmhygvxJ23S6hJ24  CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu   10%   48245555    48245524           0   unknown  5147610.75114992 SOL (3.06%)
! ateamuvZX4iy2xYrNrMyGgwtTpWFiurNzHpmJMZwjar   ateamaZDqNWDztxnVKZhRsp4ac53KvT1rVKyU5LnL6o    10%   48245555    48245524           0   unknown  3626944.26152144 SOL (2.15%)
! 6TkKqq15wXjqEjNg9zqTKADwuVATR9dW3rkNnsYme1ea  GvZEwtCHZ7YtCkQCaLRVEXsyVvQkRDhJhQgB6akPme1e    0%   48245555    48245524           0   unknown  3246630.77724225 SOL (1.93%)
! SFundNVpuWk89g211WKUZGkuu4BsKSp7PbnmRsPZLos   SFund7s2YPS7iCu7W2TobbuQEpVEAv9ZU7zHKiN1Gow     7%   48245555    48245524           0   unknown  2610891.36361184 SOL (1.55%)
! fishfishrD9BwrQQiAcG6YeYZVUYVJf3tb9QGQPMJqF   7VGU4ZwR1e1AFekqbqv2gvjeg47e1PwMPm4BfLt6rxNk    8%   48245555    48245524           0   unknown  2606389.0838864 SOL (1.55%)
! LunaowJnt875WWoqDkhHhE93SNYHa6tfFNVn1rqc57c   LunaFpQkZsZVJL2P2BUqNDJqyVYqrw9buQnjQtMLXdK     8%   48245555    48245524           0   unknown  2590874.89988444 SOL (1.54%)
! 4YGgmwyqztpJeAi3pzHQ4Gf9cWrMHCjZaWeWoCK6zz6X  8jxSHbS4qAnh5yueFp4D9ABXubKqMwXqF3HtdzQGuphp   10%   48245555    48245524           0   unknown  2496450.80823856 SOL (1.48%)
! Dokia75SVtetShgapUBoVFfYjL99fQyr1twxKKyTZKa3  H3GhqPMwvGLdxWg3QJGjXDSkFSJCsFk3Wx9XBTdYZykc   10%   48245555    48245524           0   unknown  2475672.06182592 SOL (1.47%)
! 5XKJwdKB2Hs7pkEXzifAysjSk6q7Rt6k5KfHwmAMPtoQ  GMpKrAwQ9oa4sJqEYQezLr8Z2TUAU72tXD4iMyfoJjbh   10%   48245555    48245524           0   unknown  2085944.88251632 SOL (1.24%)
! Fd7btgySsrjuo25CJCj7oE7VPMyezDhnx7pZkj2v69Nk  CcaHc2L43ZWjwCHART3oZoJvHLAe9hzT2DJNUpBzoTN1  100%   48245555    48245524           0   unknown  1969836.330288 SOL (1.17%)
! 6yf57R7U1J1VXszE7CobdYEWQNJMPRfWEgGfaRsVNk32  CRzMxdyS56N2vkb55X5q155sSdVkjZhiFedWcbscCf7K   10%   48245555    48245524           0   unknown  1577430.86171328 SOL (0.94%)
! forb5u56XgvzxiKfRt4FVNFQKJrd2LWAfNCsCqL6P7q   76nwV8zz8tLz97SBRXH6uwHvgHXtqJDLQfF66jZhQ857    9%   48245552    48245521           0   unknown  1494854.81591168 SOL (0.89%)
! 7cVfgArCheMR6Cs4t6vz5rfnqd56vZq4ndaBrY5xkxXy  FQwewNXahV7MiZcLpY6p1xhUs2acVGQ3U5Xxc7FzV571   10%   48245555    48245524           0   unknown  1416668.36364032 SOL (0.84%)
! AoUwfPuiEek2thVRDhMP7HbQb9rguyab4rDiz2NAfwwA  8HR5rCobbFMDe5EbgKdJLNDWVCeGG79w837BUxtsCngs    0%   48245555    48245524           0   unknown  1000112.99537968 SOL (0.59%)
! F3LudCbGqu4DMqjduLq5WE2g3USYcjmVK3WR8KeNBhWz  FSj7gzzNHhALp1qVP7BLqbakcLSMNosEtykLn69vHXyk    4%   48245555    48245524           0   unknown  951226.79843952 SOL (0.56%)
! MCFmmmXdzTKjBEoMggi8JGFJmd856uYSowuH2sCU5kx   2het6nBRLq9LLZER8fqUEk7j5pbLxq2mVGqSse2nS3tf   10%   48245555    48245524           0   unknown  817627.38624816 SOL (0.49%)
! BZBKHmW1DhBaAPojxWBQ26vGz42Y7MtNviFZWpc6nGLb  AGXZemZbyZjz5NBhufcob2pf8AXnr9HaGFUGNCfooWrB  100%   48245555    48245524           0   unknown  772272.95907456 SOL (0.46%)
! DDnAqxJVFo2GVTujibHt5cjevHMSE9bo8HJaydHoshdp  9GJmEHGom9eWo4np4L5vC6b6ri1Df2xN8KFoWixvD1Bs   10%   48245555    48245524           0   unknown  750145.78707968 SOL (0.45%)
! 3KNGMiXwhy2CAWVNpLoUt25sNngFnX1mZpaiEeVccBA6  BH7asDZbKkTmT3UWiNfmMVRgQEEpXoVThGPmQfgWwDhg   10%   48245555    48245524           0   unknown  705802.84236992 SOL (0.42%)
! 3RXKQBRv7xKTQeNdLSPhCiD4QcUfxEQ12rtgUkMf5LnS  BxFf75Vtzro2Hy3coFHKxFMZo5au8W7J8BmLC3gCMotU    8%   48245555    48245524           0   unknown  695076.94375808 SOL (0.41%)
! CjmXSapt1ouz3CZzgkRJckBEwMSo5fVdVrizLeRscwYD  B6nDYYLc2iwYqY3zdmavMmU9GjUL2hf79MkufviM2bXv    8%   48245555    48245524           0   unknown  679498.08173936 SOL (0.40%)
! a1phaKk6UbG1P2ZCpfMVFUeRM5E2EZhGvUjqWHRsrip   5CgQubGD1uwodwCe5UXDADbC69SiqXR8qq6pDMSm7ut5    5%   48245555    48245524           0   unknown  672768.77342784 SOL (0.40%)
! ABC1U4cf9DZMwqy8ktEr4WJj8VHmVBQibbC57gEJthwY  abc1zP7ihWsgQW8z5YmfQNqMckJE5Dfx8fwUNMNVNkY   100%   48245555    48245524           0   unknown  671787.93101248 SOL (0.40%)
! 4XspXDcJy3DWZsVdaXrt8pE1xhcLpXDKkhj9XyjmWWNy  9sWYTuuR4s12Q4SuSfo5CfWaFggQwA6Z8pf8dWowN5rk    8%   48245555    48245524           0   unknown  659623.97033344 SOL (0.39%)
! HzrEstnLfzsijhaD6z5frkSE2vWZEH5EUfn3bU9swo1f  DQ7D6ZRtKbBSxCcAunEkoTzQhCBKLPdzTjPRRnM6wo1f    0%   48245555    48245524           0   unknown  624943.37795056 SOL (0.37%)
! 6cgsK8ph5tNUCiKG5WXLMZFX1CoL4jzuVouTPBwPC8fk  9iEFfC6qCU6DBTWxL84YQdpNmpZ9yBBu4sW62yeiEVKe   10%   48245555    48245524           0   unknown  616465.10824304 SOL (0.37%)
! 3m4ov8U9Gccm8Wmkmuk4xJJajF6dSUQWZFDp36y7zHdW  CrdE3LLgvBDU7wkiPJHRH6mtspSWwZmUd9ybhrtG9adv    7%   48245555    48245524           0   unknown  606350.09173936 SOL (0.36%)
! 4h5muqwz35tyPQdAXkZMyVM5cnGN5oXouTZL2AFA1Fjh  9v5gci7uDiaGKRmQ2dn6WJMB94YqFaVFBTiFzBzNhyaw    3%   48245555    48245524           0   unknown  600026.0529528 SOL (0.36%)
! 2jS8AX38m8F9C5juToW1FmTufEbb1DfDzZJj9HSJcWwo  D3DfFvmLBKkX9JJNEpJRXpM1pYTVPQ5dpPQRc9F49xk4   10%   48245555    48245524           0   unknown  600024.05533568 SOL (0.36%)
! 8gcMmaEAXfRZKcXHeHV2x8R1ebb78inTr9xhhEuNNoTt  LneJvrSDJGqfpbsKHPfyaxSPecBtqRHTJnwyBzG4vPC    10%   48245555    48245524           0   unknown  599924.17048192 SOL (0.36%)
! FGiEdzde7Fco2WLpNQMat299hUVoykJdaA5hxdmCzHiS  3r5ZXC1yFqMmk8VwDdUJbEdPmZ8KZvEkzd5ThEYRetTk   10%   48245555    48245524           0   unknown  599920.96208192 SOL (0.36%)
! 3fA6TU7fQCkNDDKYJeCY4Ag2gCatEsYnYL4SpkSDYfCw  7Hs9z4qsGCbQE9cy2aqgsvWupeZZGiKJgeb1eG4ZKYUH   15%   48245555    48245524           0   unknown  599895.99086848 SOL (0.36%)
! 3B2mGaZoFwzAnWCoZ4EAKdps4FbYbDKQ48jo8u1XWynU  edu1fZt5i82cFm6ujUoyXLMdujWxZyWYC8fkydWHRNT     0%   48245555    48245524           0   unknown  599586.99776256 SOL (0.36%)
! 3nRhescC7HMYC8gKti3ENiBe8LnKZUs2gzYPAjYniQCP  4ScTBfR4v2Lw9hWuzayJjfZdBKQVUeg7Rm92Rsq7HZkV    8%   48245555    48245524           0   unknown  599424.17038192 SOL (0.36%)
! 2NJZ1Ajcwtc7hZdVXTXrh2SAiAXnFkVm6MWcGjBZfPkS  H1wiu8FvJZ3UqUCGMNfVeAbtB7YJMcL9aHGPJdvPNKTm    9%   48245555    48245524           0   unknown  599424.17038192 SOL (0.36%)
! HahmUFR44BXFP7fVLsnd4pyaE7GoN1KKV1hdL2eVUpok  F5XcsWb5YCA39hLGP1tpUZDScTTgn1k2UeHXyaFpGXMj  100%   48245555    48245524           0   unknown  599420.96208192 SOL (0.36%)
! 7nYNfGS6VVxzCZmfbLGpsXYFm2LS9XRrva9hZahFmpqh  4nQTSgKURZexbRj4oXKwMiqwVCPobTcaTyMph728J3XR   10%   48245555    48245524           0   unknown  599395.99086848 SOL (0.36%)
! 4tS3UZfuRHzXuPenvErtRPtnZfY1KHhT96JBCQsLzKqW  D9iBN61a4MAt49gvaovohF77zqzoyQ5ERVZUoAfub3o2  100%   48245555    48245524           0   unknown  599395.99086848 SOL (0.36%)
! Ev8D9dwYdfebkdLgAjwiJtCkqS882Uvrit5qN6NTeHMy  BNTmegvdXzNVyc3UMTWSMSfJUryjr3fXEVErtdqrfs6y   10%   48245555    48245524           0   unknown  599395.99086848 SOL (0.36%)
! 23SUe5fzmLws1M58AnGnvnUBRUKJmzCpnFQwv4M4b9Er  4PsiLMyoUQ7QRn1FFiFCvej4hsUTFzfvJnyN4bj1tmSN    0%   48245555    48245524           0   unknown  598490.86140288 SOL (0.36%)
! 9CqDvvGvSNVZDo5RskCAv4fTubpFCs9RLTrjUxEYrvNA  DzCirYWNsCECVHgSaMVg1mqMzKwtGuN2Pqm2a4HqVpTE    8%   48245555    48245524           0   unknown  597945.17038192 SOL (0.35%)
! spcti6GQVvinbtHU9UAkbXhjTcBJaba1NVx4tmK4M5F   49DJjUX3cwFvaZD5rCAwubiz7qdRWDez9xmB381XdHru    3%   48245555    48245524           0   unknown  595627.93812 SOL (0.35%)
! CAo1dCGYrB6NhHh5xb1cGjUiu86iyCfMTENxgHumSve4  51JBzSTU5rAM8gLAVQKgp4WoZerQcSqWC7BitBzgUNAm  100%   48245555    48245524           0   unknown  595509.96208192 SOL (0.35%)
! A79u1awz7CqnxmNYEVtzWwSzup3eKPNW6w2Jrd56oZ3y  6UDU4Z9TTbYy8gcRKBd7RX3Lm2qMsSR4PMuzoyYPzLma  100%   48245555    48245524           0   unknown  594895.99086848 SOL (0.35%)
! 8ebFZA8NPLBZD91CwsG1HWQsa2B5Ludgdyf5Hi3sYhhs  9tedbEYypEKXAMkHcg42rn3fXY1B8hB6cdE3ZTFouXLL   10%   48245552    48245521           0   unknown  589974.1129088 SOL (0.35%)
! 8pyp3vfVPRziYdAYEyqkwytdBbdVbQmHqfQAVDcRV3w   GB44NXtM7zGm6QnzQjzHZcRKSswkJbox8aJsKiXGbFJr   10%   48245555    48245524           0   unknown  589937.9885856 SOL (0.35%)
! 6BDNnr38moGRQyvx1Ehs9cM6tJDFK7LF6mUvLziyNrzW  7NwjYBhHVqEbqmMHqMqUnQ4thomaX9qXytMEULQFkAny    8%   48245555    48245524           0   unknown  589296.16353328 SOL (0.35%)
! 2mMGsb5uy1Q4Dvezr8HK2E8SJoChcb2X7b61tJPaVHHd  CAf8jfgqhia5VNrEF4A7Y9VLD3numMq9DVSceq7cPhNY  100%   48245555    48245524           0   unknown  584526.99315136 SOL (0.35%)
! 6hpMTcU76pCkSZHG1qdfw8ZrM9rFwFCpmKZWqBc5VXr3  J9Go27V87fCdJtjMxmFJu48ctrHzFoe6xQpA6Ecq4Wkw    1%   48245555    48245524           0   unknown  582476.99086848 SOL (0.35%)
! ArmanP3SBD1DVSoKCqK7d6S2kLpyncYey2Ybf3o5XkTn  3byuwfBCZ4JLdbsuirv6yV3opAfgv2kw3BHjqjGUSDCd  100%   48245555    48245524           0   unknown  582416.99086848 SOL (0.35%)
! 2Ue9zGmDnvYRrJNEjuAdNkbbickw6fKWtbeNM7T2rakg  6559KMdiUseNSAkRcK9WcFcNTppoj6jWtKVedpMkBYCn  100%   48245555    48245524           0   unknown  582276.99086848 SOL (0.35%)
! 452L4U6HbzT59EP9vLyPxddF99FBBZ7foCrcn5A9HLMK  3TC4dtYuka6fhC54ZM7yicFLmSJq38GPs1KCSwap6CuT  100%   48245555    48245524           0   unknown  581990.99086848 SOL (0.35%)
! 5ya8UPujuXN8cys1EaaqMMH3auby3HTHZki73Q4Yfkff  3ZhXyB3T1uTnUPmehLnBUF5Go4Zyh1NQdCPseayr6BPq  100%   48245555    48245524           0   unknown  581976.99086848 SOL (0.35%)
! DNWsTLvsMixgUcbM93437U8DWmJ9bZikQeBxQLHbeH5L  7X5QAMP54upioBdu75QZkz8hpYcwz7UmzAHGB2STq9da  100%   48245555    48245524           0   unknown  581976.99086848 SOL (0.35%)
! 2us4ysyNvYJHkYi7CtRuW413Mwi34kjjFQGhZDch4DEN  5dwMHTsS52QGYVGWyui1P555XkBPzGa8uoQc7aZunLGy  100%   48245555    48245524           0   unknown  581976.99086848 SOL (0.35%)
! 8GLRbAstsabZuZUx73AoyfGi1FRCWSUhRgMugFyofEz7  7PmWxxiTneGteGxEYvzj5pGDVMQ4nuN9DfUypEXmaA8o   10%   48245555    48245524           0   unknown  578950.14397824 SOL (0.34%)
! Fudp7uPDYNYQRxoq1Q4JiwJnzyxhVz37bGqRki3PBzS   4QhNoG3PN1FXXFhAEA2QWdor6xjXvM9pjq6MXAUV8Zg2   10%   48245555    48245524           0   unknown  578896.99315136 SOL (0.34%)
! 9JJQN1WpJ8QvH6XK1xAMbSpgHSiwqBgWaeCh3ViEFmtN  6GJ23VmcWCVnm6iATqdmTjX6JeFDCCaG7PuRh5ehn9af   12%   48245555    48245524           0   unknown  578022.96208192 SOL (0.34%)
! uEhHSnCXvWgtgvVaYscPHjG13G3peMmngQQ2ghC54i3   5K8qgC9nHzKHSSyo9fKLsMfYmavYdMgEaYx86cMmVKVv    5%   48245555    48245524           0   unknown  575026.17809904 SOL (0.34%)
! H3WEH47bHUy9i9rmzdaxmoLagoUhbcJ2shPXcsp8QdJC  5swjaAU8NapTsmgHGAPe8wUjrK1HYPL2G64AwyH4djhz  100%   48245555    48245524           0   unknown  574497.99086848 SOL (0.34%)
! E6cyDdEH8fiyCTusmWcZVhapAvvp2LK24zMLg4KrrAkt  BohPTSY4vvjGd9ARFqDJjRaHZKP4bde7ewBq65WgRGmA   10%   48245555    48245524           0   unknown  571027.1726648 SOL (0.34%)
! 6wsSvrZPbjWeNNZ92KWtj94pdHj8v8sRbKsu1ZSpztpP  2naPB8XC4FWp4er8M2nxDsphXHEyQH2CSQMFaSHxWWd8  100%   48245555    48245524           0   unknown  570998.99315136 SOL (0.34%)
! EvnRmnMrd69kFdbLMxWkTn1icZ7DCceRhvmb2SJXqDo4  9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF    0%   48245555    48245524           0   unknown  570798.74601264 SOL (0.34%)
! Dq3piY2ZcBvNN84j2EhDLtTzRAw95za7Eau89pNcmSd5  2PEyBgsPYBQ8pMdXQtEaPGNqWQHE9GCnmV2tTVN4GMru   10%   48245555    48245524           0   unknown  569051.14931248 SOL (0.34%)
! 3RbsAuNknCTXuLyqmasnvYRpQg3MfWZ5N7WTi7ZGqdms  4aFj9VyXDrqU4TnKWnMVuPaAVTaF4GZLLKZN2iZivW29  100%   48245555    48245524           0   unknown  567299.9885856 SOL (0.34%)
! CwhdMezLucz7bcuWzStpLXgrzKGC2tBBiaVmJZjfprRN  VNbW721iu6uVkrx246N2BiQth8u4b4SCPJwH3JvUovD     7%   48245555    48245524           0   unknown  566077.1228088 SOL (0.34%)
! JD6R8sK3cu7tphNMyhzxSGnSf9DcFUacXBgqycvGAjai  GzhZDPBjhZpeteBULgSuwpPRd76yTCH8P37PCMmtN1yh    5%   48245555    48245524           0   unknown  566052.15159536 SOL (0.34%)
! 46yVA2WVP6ah5wLREZGHbGvvPaM55rcwDKDDikzn3BVV  2dCciM6aFdDXeiirHNTmkxh9Sda1DwfPfF1HVNZSrPcE    7%   48245555    48245524           0   unknown  566052.15159536 SOL (0.34%)
! DAHJgPKdmncYW8DmY6meaU953a7SktQ7eDGtWduC8W8m  C6uqzABsRPmFd14iL9Ej36AbddVxXPJWV6jwbLZYdYJM    7%   48245555    48245524           0   unknown  566027.18038192 SOL (0.34%)
! 9q16BB7WGmBxf1nJTdxH5zPnBUhtHqdqXqRFjSjuM4k7  GK9MfwWEK7BvMS8eQDaiEPnKcqMJoS7SKUiEBQY2pfxC    8%   48245555    48245524           0   unknown  566027.1726648 SOL (0.34%)
! 7X1kgrfYRwFd94yyE8tvsQF5aTFHdmoLXnG4q79onDAg  5TkFPZf79rezPXzCTP6DjH4NLb7Hw3jRsAme1fv431oz   10%   48245555    48245524           0   unknown  566023.97208192 SOL (0.34%)
! 245B9WFHUGuWycSXHagHXwsXGcxDkNYfxWBaeh7vAHDU  BfF3vg8UFcwTkFJNgQ7KQTAZBUWegF3spPm79d71WNwo  100%   48245551    48245520           0   unknown  566000.9643648 SOL (0.34%)
! 8o59jbS8MEqSd1J72ryL7dghg9djh2BAUtpkZvTTYh4H  7kge23FTbCXc6dZxMPQfAWLnVFTgGzio5wpXUo9si2mV   10%   48245555    48245524           0   unknown  565999.00086848 SOL (0.34%)
! 7Gjec4iDbTxLvVYNsRbZrrHdtyLByzdDJ1C5BmcMMBks  CKBuZBQBsHwxSpgVsQC8p7p3fRgCxqGnwpAR7H54Mjom   10%   48245555    48245524           0   unknown  565999.00086848 SOL (0.34%)
! 4JryygoiM1j324fYkeBzcQDcwRfd2WpgkEzUePFj1rJY  8ge8UzG9FyW4NDZ6zzZiUypnbcNQ3nUfTBKndxsmWqSB    9%   48245555    48245524           0   unknown  565999.00086848 SOL (0.34%)
! Ge8M91yymAsZmjCyeAVCpxGA9k62CR8cxf4AhP1c38UP  GjYzNftUGedbXZXMVm8P9HsvJDosFgPEwJSzjswuDZv6  100%   48245555    48245524           0   unknown  565998.99315136 SOL (0.34%)
! Fw3khiQmpKLSdNyoVR52WxbTWT9gjFSXFsZewknwLGb5  J6hFEnGhsGxTyss6DNW9aNQskPZ98gD8P6Wo1F5MBsCK  100%   48245555    48245524           0   unknown  565998.99315136 SOL (0.34%)
! 69QvoqgDazuAqD4ygG6YsA31HBV31L497XqmQohF5ajH  8rKN2jdSDUeDX4niaKhvcsuSbN31b9JsMJCDwuFVmqtv  100%   48245555    48245524           0   unknown  565998.99315136 SOL (0.34%)
! 5p8qKVyKthA9DUb1rwQDzjcmTkaZdwN97J3LiaEywUjd  EsEtxoyhFTgfvudcy2VwwQJ1qA6BScLUW39PKpYczuxF  100%   48245555    48245524           0   unknown  565997.99086848 SOL (0.34%)
! AyYqAhyCCxRrNGbm3dY4aGY9SyaQC9UvPTSHvMQK4YW2  GJPXfCUjDy9PjqQ2Cvh7pSEvPu8vRjMXz2kSULBBaSLt  100%   48245555    48245524           0   unknown  564998.99315136 SOL (0.34%)
! 7CyNBLaoav9fZhX4D2WGrL5XCuMroSgDut68vtL8NB9p  DEU9FLyWEMihJzWat5RzgftPRy9nrQhspSQHGh12wCxC  100%   48245555    48245524           0   unknown  563977.99315136 SOL (0.33%)
! DTF5DM36Jc4vkVPJXbSm7wRLe6eeX1UWo72WQhxKJpR2  FqUfeiVYd1LMNSDw1t9WE6fAXAKzjUVHf8YzZXWQjSMd   10%   48245555    48245524           0   unknown  561999.99086848 SOL (0.33%)
! GfCNi6GaCfEKyvpS8fs1D6VUdQcPJg4VrULvFFEBLFW6  BUY3swp2NSTMsQmLDnYgoEoLNJyCX1MQZQjnAVL7SnSx  100%   48245555    48245524           0   unknown  561999.00086848 SOL (0.33%)
! Azg1hC9mg7pkSq6Q5sAESsBsrxHoUuyRnUYSCJMJMdup  HQ6ywTaLZxjEVLJsR4rLeLjGw7ZDJKd2c5fSF8FHxaG7  100%   48245555    48245524           0   unknown  561999.00086848 SOL (0.33%)
! HVWzcQZ12pvZN726XXgA2jBfDuj6wDFwSFVdzxooi7qx  7DJunpQm9vgLXnspokwjivkdX6UkugT3HZs4prjsPkG4  100%   48245555    48245524           0   unknown  561999.00086848 SOL (0.33%)
! 81zNHWkYaQRL3TWHSNwzX6T64yUyVQ7qXzLLxvaaB6b3  2mQNruSKNnn6fWqJjKNGsQtpsMnuxxMzHsrKT6iVR7tW  100%   48245555    48245524           0   unknown  561999.00086848 SOL (0.33%)
! 3T2nqHFbmexvkhEo25SKnJsbaAjuyUGBjvdttczxDKgs  2hjoQMqRAG5ftTPCSkUavMEaVX35qbj3LK3Q3HDmv4mZ  100%   48245555    48245524           0   unknown  561999.00086848 SOL (0.33%)
! 7DBhzr38xGJeALbZB9bpA5bnzVL8N9oGCjFfWuN6t8cG  2cFGQhgkuibqREEXvz7wEb5CwUqGHfBSTB2oa1hmhkcw  100%   48245555    48245524           0   unknown  561999.00086848 SOL (0.33%)
! C5oTsyGA1gBvgWpvS6EaWGAgEKDBkMpQaPeLTiaLuYKi  EXEGg4fRhq7YqK62oKejKeErBHLJqM9tb6iqWpVaHWDD  100%   48245555    48245524           0   unknown  561999.00086848 SOL (0.33%)
! GZNnph4EvmyjjL5uzF9xNNTHyV46RzbkW4w4HYU8BQCW  6anBvYWGwkkZPAaPF6BmzF6LUPfP2HFVhQUAWckKH9LZ   10%   48245555    48245524           0   unknown  558022.45751616 SOL (0.33%)
! 9e7XGRqQqEvppx4Lkj6P1S7k65yWQpf3vcNzWecKSzDd  6hkfqeNAbURk7CmAQsP4Qm6WwHVF4LxHupEvQf7Tkrf1   10%   48245555    48245524           0   unknown  557498.99315136 SOL (0.33%)
! DohaxzeUj6ma9shCykxGxi7FbWnMyW9hzNjwQjZHEDV7  AdtBv6jyEjY74XhkxZkowMuGfV1r58j44WCRyeToic99   10%   48245555    48245524           0   unknown  557498.99315136 SOL (0.33%)
! HW7ntfUHapD5o7McDuPfGvkfzrPcmuPSbZMMoe2gksKQ  5TFdzjKE6LnkhQArxWjt26yVCXskPo3fUXE8F351Cfn7  100%   48245555    48245524           0   unknown  556998.99315136 SOL (0.33%)
! CsqwHrSUAWsWpN5kUcjcv4Nsq5JtgFiDJTckaY1zuXPf  8Dfm249TXe9Wd3wYEnpBdSme659gecoEMH8zx1YWN79v  100%   48245555    48245524           0   unknown  555999.9643648 SOL (0.33%)
! AWHfhBSMN7rX7NEDrKNfjnUyR7W1xpfistTy6w9GqT6U  5PKBzZEbwGEXhQj47eiwH6RHAPSCxcVhdYcFttW5gLWQ  100%   48245555    48245524           0   unknown  555998.99315136 SOL (0.33%)
! HwdfNWCqP2vXRvaHqQhoVUM2uPndaY8DDJzzBxCoPNHU  EzZEi48kvDWPJJBM1z9nmjpgRyMwWJwaa4xVW2U6psPr    8%   48245555    48245524           0   unknown  554052.14387824 SOL (0.33%)
! FVsjR8faKFZSisBatLNVo5bSH1jvHz3JvneVbyVTiV9K  EY2zW89vZnPe2ts1FMzPK59cuEq69rRzEAhyLNge8gUj  100%   48245555    48245524           0   unknown  554033.43329536 SOL (0.33%)
! AXXrLQ7bVy92pPxW7heQkAHfg8LuJ4uufUWCQgH12rmR  C4MqmofwTAQKYjRawSSN9NhKXd7J78tPnZGLyNSXV2To    7%   48245555    48245524           0   unknown  554027.1726648 SOL (0.33%)
! D2RV1q6FgePVVjrMa7AMzVbvvAeg5oS7TAV7qdNKSDsX  CCxSNvJogH6LWyoiEbG7JfcWybw2FqqCExs5GuemChGr  100%   48245555    48245524           0   unknown  554019.36208192 SOL (0.33%)
! 6h9jyRgfpmgXNyaWpbDpbxbCoF56WEbzsruhMwDn2om4  3Pb8KDmneuKuS38aDSFnK1WGz18aZN5Tuyu5ZaNUnySc   10%   48245555    48245524           0   unknown  553999.99086848 SOL (0.33%)
! 4daH8Aotxpk68HsMvws3P5AQL3F1gVTA44jqLaB2GuGx  4sFsBDei4m7UXwuMeAGVmnJxZe9peJ5tvq581HoT9aH9  100%   48245555    48245524           0   unknown  553999.49086848 SOL (0.33%)
! DViARWAWKkxAzp4UCgbw5B9pLSrBY3PaztFErcwgVUKX  HeTyhZdUKswQoonJJTXqAnDN48ceyVAeFaKfYKayGPNS  100%   48245555    48245524           0   unknown  553999.00086848 SOL (0.33%)
! cZCvgqgrdX2LCScVku8CprMnAUZtSicBDJ8eiowfonn   8BbpzqTUCUa4oR71AMgcBiTQvd6Gta3xJHCG4xK9mKBp  100%   48245555    48245524           0   unknown  553999.00086848 SOL (0.33%)
! 68EWE8SmV58oRG9JJELNDt8Y6MuWBbfraoT67KFw5Ath  63FR3fGznHYCUrsNtHcdMhMgcWBc9KTY5Mc4z5k9rQ2K  100%   48245555    48245524           0   unknown  553999.00086848 SOL (0.33%)
! FEpYb3oJbdPf77DPdQagkcmcJ4SqcfRDeCydKVkks4HK  7gds7PbCzmHbJStjxA5L5K8cu2LVUakmd3MDXFHSfcic  100%   48245555    48245524           0   unknown  553999.00086848 SOL (0.33%)
! Arvv3uwEyDPKckw3wEFiCq9hgxMw8kawFU6doxFAWGYR  27MtjMSAQ2BGkXNuJEJkxFyCJT8dugGAaHJ9T7Gc6x4x  100%   48245555    48245524           0   unknown  553998.99315136 SOL (0.33%)
! 7aR6AjK87ehUxwEJrPpnoizUKtxJKxqZCQCEGD3h1Xgf  B1UaJwhZ9rmB6rUwCikMCkYEPVgpGYgmmrKqfAHCZanw  100%   48245555    48245524           0   unknown  553998.99315136 SOL (0.33%)
! 94HgFvsD8zm7UXJ5KJxN4zW5nsdhZWY2LFREjfaFEHwR  J6XZBDuUpuBzgcVGmY8NgHQYKbGZegoYmbpadAKo1qRw  100%   48245555    48245524           0   unknown  553998.99315136 SOL (0.33%)
! zeroT6PTAEjipvZuACTh1mbGCqTHgA6i1ped9DcuidX   5BAi9YGCipHq4ZcXuen5vagRQqRTVTRszXNqBZC6uBPZ    6%   48245555    48245524           0   unknown  553998.99315136 SOL (0.33%)
! DAS6zKbzVe5DFSwyEgo1TisuWt31HjBdZxzgBF2ASiju  7LtXiFCXqxwntUkTfzMAmS8TTehK8m3cbzx7BgvYFTiP  100%   48245555    48245524           0   unknown  553998.99315136 SOL (0.33%)
! pZ2nxiW1M78Ez9Tk5DcQyw1nWpmPFVZk8KDGKWbvvUV   36z2quTJD9JPAbvTgecCXnhgjJkreA2F7SHH32vXFExo  100%   48245555    48245524           0   unknown  553997.99086848 SOL (0.33%)
! 6kDyGMHbuWekkcquroYNp8VRL5pQiUzEJ11gJ75qJsRy  7yXM5mUSAtBuh2TcCABvSJa3LouZ8wcLps5zTEMiwxvj  100%   48245555    48245524           0   unknown  553498.99315136 SOL (0.33%)
! BT9ZFvsDfX6WpLFqmWEYuLuE5i3SxzdSJ1Vzm9arbRub  F7MeskoJC8pFwUsw3tNPA5ct8H1FRpuyi4JhFSLBsH4Y  100%   48245555    48245524           0   unknown  551999.99086848 SOL (0.33%)
! GRmtMtAeSL8HgX1p815ATQjaYU4Sk7XCP21i4yoFd3KS  GF9q1CPvyjZhAHex6wkGqeCioEkLGzaGJUF1QgZwGFwa  100%   48245555    48245524           0   unknown  551998.99315136 SOL (0.33%)
! FaGBP8LJrXE5h3cFRtPxz8x8695LQAYnvYn3NGtVtvrw  H8ByRrxt3hxFY6wWEsRSAUvD9iT5wJWdVYQzCnhuPXsU  100%   48245555    48245524           0   unknown  551998.99315136 SOL (0.33%)
! 7XSCAfoJ11zrQxonjbGZHLUL8tqpF7yhkxiieLds9mdH  EujFnyMz71DXdN93GeSCDU7pFiy1vrFG7cAbtfAhFeSe  100%   48245555    48245524           0   unknown  551998.99315136 SOL (0.33%)
! FAAvB4WnbSPNT35oUXDvkYj932KFRPi24dNBtrSpPvCY  6HNFsRJCHnfsT88sxsgtnq1MVsrUPba8fDiPJ1udPfF2    7%   48245552    48245521           0   unknown  551757.1726648 SOL (0.33%)
! DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ  8XgHUtBRY6qePVYERxosyX3MUq8NQkjtmFDSzQ2WpHTJ  100%   48245555    48245524           0   unknown  550666.96664768 SOL (0.33%)
! CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S  9bRDrYShoQ77MZKYTMoAsoCkU7dAR24mxYCBjXLpfEJx  100%   48245555    48245524           0   unknown  550378.96664768 SOL (0.33%)
! GYZdxwPwV3wTFVC8DdZuJQZDDRCg45AtqUai8cpSyAga  FxXCvhMZGUCSi8ZwYFLVSZBFyBNyFGLEmLQxc8BLctDt   10%   48245555    48245524           0   unknown  550028.17494768 SOL (0.33%)
! 2D2v7sMqDuq2ekZnFhaQm4k2ErWHemZQuYf5qaVTPFmg  FQtMWMc1yo8NGpvPEFck2eCaTexa1434i87X5T9qDwqX   10%   48245555    48245524           0   unknown  550028.17494768 SOL (0.33%)
! AmhQFcGvH2hjkucP78rn6GMKSbstYwyFpCDVKZUwBGrG  BdM7KCd6ZYWcaCMmHVi8YeL4jFzDVM9cRLJUeRAGSvMS   10%   48245555    48245524           0   unknown  550028.17494768 SOL (0.33%)
! Hmube7PkFmvattfygQgEyWe4GfZ9Dskj4Zc9YFfRj9JU  HoFU1hVTYvh4ryBfbYCzTu9dBta73jX3Ag3rzzoqYJG6  100%   48245555    48245524           0   unknown  550004.99315136 SOL (0.33%)
! 9Mo3ap3jpuqQpLi75EsiXLWfTr1cbBhrJNumoq1wnVp6  9K67smfw8hDXmtnR7uvP62WrKUcB7oZ8cvpsB1hmrCzf  100%   48245555    48245524           0   unknown  550004.19315136 SOL (0.33%)
! EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru  438C7o4cJrbchdmxEPvFgaE5g9DocWKeSc1k4E1aY7qw  100%   48245550    48245519           0   unknown  550000.99315136 SOL (0.33%)
! BGBxrNWZ9HDBQoXA9Zq6t4auRXa59qrLQkiTGtZK6FU9  462gkiydfX1ks7bzS71j4k5uLZaonTzcz5mfJpgLGe9k  100%   48245555    48245524           0   unknown  550000.99315136 SOL (0.33%)
! 12oRmi8YDbqpkn326MdjwFeZ1bh3t7zVw8Nra2QK2SnR  7vJeGJzbaa3bghTsPsFi83T6VCy5uLaQ12r32JA6s8xc  100%   48245555    48245524           0   unknown  550000.99315136 SOL (0.33%)
! D1KH1UwfTLaBW3NubpvNv4ze9S7SKW6jd5TLdrwZgLP1  1gqv7KGm888nQXsJoNFwGaDkNERUBztuekjzK3J3T7a   100%   48245555    48245524           0   unknown  550000.99315136 SOL (0.33%)
! 2zAbHUpE4MRgEwq1MWh3i9aJyzazSjUUPrmhNViqQn5W  ESjX2jRuvdr2a47JfEKjP24gNsgreE9PvSpkw4t5Xn2M  100%   48245555    48245524           0   unknown  550000.99315136 SOL (0.33%)
! 2mKEUVkcttHeMeaZK8jjwkuwGSdCBm23xDgzXgbhTdPe  EoMcV8x78aGZYN3RSW8xk311Q8xKNHMXF94UJaEzsMoW  100%   48245555    48245524           0   unknown  550000.49315136 SOL (0.33%)
! HzvGtvXFzMeJwNYcUu5pw8yyRxF2tLEvDSSFsAEBcBK2  9diFDvrfJD8RvBBF36cMLyQAnvafbeu3KFKAwv4od5nX  100%   48245555    48245524           0   unknown  550000.24315136 SOL (0.33%)
! 9gJT69qJUibNmfnAPBgsqSmLqVxc3kxXpw1Vk7APDrso  C6DEs3i448uhrsWMMnWYq7WsxkujcgADrCJQ4AMJ8ipj  100%   48245555    48245524           0   unknown  550000.10415136 SOL (0.33%)
! 2dxz129YxB1xtf7Mx6HUT5JspexArNNtQt84FYueWZV7  5RCD4pZcKH3NHN4XHxvsnVAawSaConLgsZbreSN5dXpZ  100%   48245555    48245524           0   unknown  550000.09315136 SOL (0.33%)
! A31PGH4i5xGn7SHWpsQRhpBYUwanRuqNrHBp8bSeCSEr  EkLA4nA5jtM2t2FkNWo6XWAyvQyaJJUZoX5p7LMawoaz  100%   48245548    48245517           0   unknown  550000.00315136 SOL (0.33%)
! HoXANZnWTGeePertqWkMEnnhgXjTjzpfWaT2kja2ZgVU  4dmBLJcchyfucSxkVmrymmsnVpZm3rBkp7kbF7qHTTYW  100%   48245555    48245524           0   unknown  550000.00315136 SOL (0.33%)
! Hj2jzpAp57KyM3SmnYwJbDVrQ8tTWizMon2hhzYzwxet  686JcEJ98r8fMtUiVuKiz4WRoBpJ2Sm9zMhdc2b6H4bu  100%   48245555    48245524           0   unknown  550000.00315136 SOL (0.33%)
! G2TBEh2ahNGS9tGnuBNyDduNjyfUtGhMcssgRb8b6KfH  F5b1wSUtpaYDnpjLQonCZC7iyFvizLcNqTactZbwSEXK  100%   48245555    48245524           0   unknown  549999.99815136 SOL (0.33%)
! 2VA3q6DbiLjbrLgnkiZ2fdyuRyVBkYRgqBDwA6qYiSDD  g4MMQmzT7182jBvyUebMvsgvNM3RVrVFFJd9tRjWXhf   100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 9nEBir5mYz5yAnAtuZsuBxwfC7SayWZTMnyCmmTsUknf  6HNqJpARCvuabtvJFWXbTedMrRpZHZYd7MgYmuFhcbXM  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 3rqEEEGjHRyndHuduBcjkf17rX3hgmGACpYTQYeZ5Ltk  8xV77wuFP5BkMDdb1845hRRWZNbDNAbcV75BjMuViWpf  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 6uHvWHjBYiMowwKUZ5waAc83x5bnLbmGfxDnXPVQYorh  2jvDEtiywY9sjx29gCAQjvxD5gJLcw89NVhkJ6ybajZC   10%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 2mDrrmhSzpSyaF12izGk8hnFjtKCGeCFPwQHpRiJDby2  9wQQnnnkk5b5GkQWTW9L4kEA3CjFv6CqsQd5gt6tRsHK  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 6GRLDLiAtx8ZjYgQgPo7UsYeJ9g1pLX5j3HK97tFmtXb  7gfSX88DYoScBCaFqNxbsgFeZom8Qotnf747iJLhhJC6  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 3vYPCtncFxQ1RVtSpB2HRg1udHfeVPWPpWALuJaMcLx3  6ywtN5KvEmTqdsynVraiUWGD4pxr3WQEKrWQZ4f9c5Xo  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 9xg5FUCSJvvFkUF2dLoSHAR72DnA3qQqzTzWhHibZ33c  7UKUPLwLrV7iLqL5ndTzYDav73mpoMxKjyM7EjMExTaw  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 6iSLGrFY1zCktMVkALyGqcQVqp4rUmKkozHG23EXwPwt  9bwet11HasEXpoRedsk6yMt37u2p5ikUoYFjGVRrkpNp  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! AaDBW2BYPC1cpCM6bYf5hN9MCNFz79fMHbK7VLXwrW5x  DTWh2VQuUJmskHuZWy1KLNvzKqk7PeMkCoaNvZy415U7  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 768DzddM8MGfosYS5JxjzpY2FcnqeNHUxMerFQHWmwKy  4Dh6frby55aY5NXdCGYe6yU61xusgzNHBa3GeXWMLPJ4  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! FCWkGAHDWK41ANjiaoPudkCZRkvTecaEkoZQugezUnpr  GptPXjYUBUjxpRmueH6F5JcqizvjPTRDShTJQ8Vp6uN1  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 9ppJrpsbbuGNjiMhhD52Ueco4KXUzVfrtNQ6tAcDab4f  EcjtYtuxBuupjeyXNdttATwoQoNL5Ck7bmrqDCj3ALT4   10%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 2LhJjdjNic2BcsRLN8opwd9KZSsabebQMnxj2PkU8ADQ  6mCs4Gi8L5RQ4ewnabmwCcVDQLBuvyqnaRcm5LGTciyz   10%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2  4785anyR2rYSas6cQGHtykgzwYEtChvFYhcEgdDw3gGL  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 2B5wMmBQkMHu9V5JbUyJuf2mJJUU286qKPsZzvQQjTNQ  3LAzTH2Fbsza2wbnKgrDcQKdaQRshQkb4w4vk12E5KH2   10%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 34t5CmGFfVkdpxQgKbAJKje1NLXa1AdWUerSjnomPgxH  Ae8UD1RQBAR7PcyTJjmEsypojpuKmMGDBJxwiZorZA2M  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! HJFFKSJxhoeRCoe3xJPyCaS6sGCnknXcLfH3Vg7fBh2M  52DDH9Z6tdkuDAmAPJDeuXmdn5iNMZ1xHCv9zWYyWxp8  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! GwnQsVbbVsMhGqWV3gcVCF1364LRmftggyc5SmsYMLrY  4n4KiUuRwgAqdTh6ag8WRy3ibL2gbWTVJPfEGw3SAsHx  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 2KnfYVJiAtxiSPfHYRzTsGGhUAhDTNrJXWn7n6K6giJU  BUTBf3nPUdD8zEKSqZgpHzYqpzPc74ueXaGMBkVAe19U  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! D6pUrfgc5ZyXSfgtCBYozydRSz92pse1S7AZP58muEYk  6yg4Usyr8VkvY8m7wrbLHegKVnKaAQmEwS6cuGnwB6wT  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! CVRr5oHCAAooVbYze7CvXtRp4FUtkMCSqBZU7MVu8v8e  cover89z945JotsCRGdbjakJm4rnL5XspFSPgN1mVZj    10%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! EZUyrtZoBWMMoXTLzDo4RVTXi5XKYCs1kq7oESFLDvCP  2PC2DCk8C7n4jhXA427a1qL9CFRu7PtrzKHixU6LXocN  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ  sCtiJieP8B3SwYnXemiLpRFRR8KJLMtsMVN25fAFWjW   100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 34viN9UrGJaVabrrSZDs8MnKwVt34nw2wv4Xkwk64shV  GhKEDkvGkf2kceG45ppzqnPD6BPXi1PyW1xGNWJdh5QW  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 5SpUnGmQBUYVWJgagPjgyvXW4ivYPi6v3n453Qi81Lox  Fpd3kqPgWrC7J2NroJLfSeswn4oSFgySW1KhggTBjHKh  100%   48245554    48245523           0   unknown  549999.99543424 SOL (0.33%)
! nCN1wrDwLYg3zBZ8DbDt6dDHJAtWk6Ms1VK5neZ1fQt   9m54h2iW3nk1TeRqtW415zrTry8MfafzQgwRGxhcvjSR   10%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 5rNErxSxMj3WysMx8bC8vHkbrt9QmwMeG9H6aTp71485  7ZJHBz4SzQw1GDQZRaCMLvo7uoUo7cY1BUioA7mdfD65  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! 4asJHLR6DbifuQK2MRGNx9iHujYDYkQ9pqQXsmbc7fyD  DgStbviwdrLoVnRLrg9LSoUYQ1XEcwWyXUEHMfhQiZem  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! DSV16KKYW34qjxTBcTzURTyJYgw7qLq4VLKq3UavQKCk  61dX6srk1WmiGtd9UM4SHttUDzfWrY8zXg4h8gSmhYMq  100%   48245555    48245524           0   unknown  549999.99543424 SOL (0.33%)
! FoigPJ6kL6Gth5Er6t9d1Nkh96Skadqw63Ciyjxc1f8H  irKsY8c3sQur1XaYuQ811hzsEQJ5Hq3Yu3AAoXYnp8W     8%   48245555    48245524           0   unknown  129074.03558064 SOL (0.08%)
! ExnG6VdMubFJfrB7qereo3YxUMyeZvTuZUVKfv7R1YZD  EHhxJpoAZXSSmUBhUXUMNd29verm4WdmaHQ2eZtU7fWR  100%   48245555    48245524           0   unknown  55998.99543424 SOL (0.03%)
! E1SFkvPjU31xWMcvgnX6vhGvfRvb1zXvHFkqmQNEGZKK  HgovzvawYMRPY6Go2kaQF1vLR4rNixooHKrUWSH6aW4C  100%   48245555    48245524           0   unknown  53998.99543424 SOL (0.03%)
! Bb4BP3EvsPyBuqSAABx7KmYAp3mRqAZUYN1vChWsbjDc  13HNYUVBVHgJSfNKvgXgKia3bywzXabGzQjFyMQxLMjS  100%   48245555    48245524           0   unknown  51998.99543424 SOL (0.03%)
! 4ULWSuaNnhQntP3DVxg1xa4yeNLNpDnAw3gTtrhPHzEA  G7akZgkcuqr7Vw1bHXqerKeawQ2Uc1WK9VaYq9APWNLE  100%   48245555    48245524           0   unknown  50000.09543424 SOL (0.03%)
! JCZNdppKyur55JqY5VBctkVjxEcgoQq3RmBuVbQxSCEq  39ueFBsyhKixjBqNJ74L7DackgeZyBALqjiP8CsBhgEc  100%   48245551    48245520           0   unknown  49999.99771712 SOL (0.03%)
! J5MroSHMzcPUTXcnpXygeCFnXJ39NBG5RRQRYD29ZwNy  CYqN2y4bGWXbJUUxVNGMxq8bQVZCQYE8T2Ryfvra17RL  100%   47174336    47174305           0   unknown  399.99771712 SOL (0.00%)
! Ew9iVxc78r9f9w6EEtX5No6wTzXuEsPCbaCsBBhUrfE7  FE9WXaL9cvXPBYzwGv2bgthnsDH8GiaK7nHamiib4CXy    7%   42019755    42019724           0   unknown  198.97121344 SOL (0.00%)
! 67joanjyAoVmb9nZLyX8p3Gx9tAxzXaUgHDe3kaUH4wf  9vNLTLdwAdHw8EdiZrLzDtUpm3hp7E2MGaNi6SmdfBGz   10%   48245555    48245524           0   unknown  115.97121344 SOL (0.00%)
! 2xte5CBkCBEBLNviyAfvSaTkMy6tvg99Cy3XJj9EJJs2  EFEKcHrUBsRoQkuTSJAQNZnj1u8h9oE4LoCYerednc3F    7%   48245555    48245524           0   unknown  41.99771712 SOL (0.00%)
! DE37cgN2bGR26a1yQPPY42CozC1wXwXnTXDyyURHRsm7  5enTTfG63W4JUzCpwioeLte7827NrYXUgGr6z7Rm7xf5  100%   46453583    46453552           0   unknown  25.96893056 SOL (0.00%)
! 8dXuaz4CSz2pizYfspXrmUGJHZKnfaQwAHMgkt3CZNDd  6Hr77bmtmxbs3eo5NTiXDqevUTVhumNHuiTYHEAyYyvJ  100%    7393633     7393602           0   unknown  15.5007568 SOL (0.00%)
! 8sv24V7cy7tyFPwn8nqAKXiigeNmgYACoFmG2z2XBTZw  83b3MHxfxGLYkhfjT3nFtPRmYL3eKk5EMALsVAHAmgqK  100%   48245555    48245524           0   unknown  9.99771712 SOL (0.00%)
! GLmkRrNqTSVi9ykTBQVX9M8cV9EwiCABknXVweS4QVxj  6syLbA7pHFWGJetPdB5Hyzf33r7B6zZK7qurwCv4Afqk  100%   48245555    48245524           0   unknown  9.99771712 SOL (0.00%)
! 9gFxqsXbFyrKXUkqpAatonn47uYZ7sEZSnMxhzQoXrUJ  48oxpSHQkM4sdXUY9NQ8KnEtebzZbyk8uUT7JRdVQNuf    8%   48245555    48245524           0   unknown  2.99771712 SOL (0.00%)
! 5qsT9h2TuTMPLtX6gcD2DG6mcZwechxmWhKRFHbCt6Pu  21ryEourynXqhpLe1DsFz8yoeFKSXE14T8bKBFmzcYzt  100%    7393690     7393659           0   unknown  2.99315136 SOL (0.00%)
! FCQTtjeFK7Fj64aVDwdahfyxiG94uLnUjkmmXUq2esuf  BCnjkkKPBT8cegVkFQ15B6TtonqD9d27gM5UUD6imEe9  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! BJevND8rrW5f9AHSysSGTtDWKcARxSpzTyDAvCm26Qms  32PqUswoHFz1mEYqm4bsxyZmtXFQUc4x6a4JjLNwhHVo  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! 2UuVd6BMW97MRnj7mCpq8PhYmqmUYuojvDkqWstwASCm  EVoQv6TSBZfTiLFoc42B12iShLNUYiB9PCc2uxFxHMoV  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! nVmiYamBpwzEqxykaGBWvY9W4R7rmK1JudonPRhmkAw   7k2ysYjSheYCamBximJsfCHSivXNyGobD3gBrVMK423G  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! CBUGET5PnvLc3HvEeFYj64iTvdKhYV6pujTPDdDh785K  GuxBSrv5jnSwwPepkqnmkM7YCBSakKanbnw4BKMdda4j   10%   48245551    48245520           0   unknown  0.99771712 SOL (0.00%)
! Dgwcrprgu1WeCNEVG2stkiABqWjfSFfBuXeMrR7qwJHp  HhzsBi7Y6DPfcZtYAUcbhNzStpicPar8Psy84yS8ZeVg    5%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! Dfc73Czi5K3xa6yKMq98LHJx69PDsSzUvSdCSSqr8NDQ  2xT5m25m9mDkdpLV1mT5fWkvH15jGy1dm7anNQLzzYGA  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! BxN7s13iMFRCZEumBRzUpH9E25V77dL7VgSig18MYKbm  3Ueg3qrAVv95tJzTiKM2dd33NswZT77yRf9wXcBDCn2c  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! DJHsoHQvqYjb8G2Ni6XSbBSHxmycMAsZksRDytQ2bntK  GwjRJdT9nKmegq6a8nyvEPfoQZUSPp6N4KmWAUMo76aU  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! 8Ey5FDayWYgJdVoquScT2hJDKWk7nQQfqzfGBt1emJpx  2YnL16L174Tj8awY9FfRfR5odpGNEbLnx3dM6CRt9L81  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! 3BKnjJPKQrC7zw7X3KtTKVtZtjLoLgzeJ9xZoAtZyVci  AkSj1eriN7dwVYfvdBmWp9txDjBv8kmgXe9xwhH6dABU  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! Diman2GphWLwECE3swjrAEAJniezpYLxK1edUydiDZau  voteRnv6PBzmiGP8NicWtQiqEJTwKKq2SxtqtdLUJjd    10%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! 3LKjD9Cb8RKKbmwM3LphHEvfZdjEU4rAFGDDUiVnuXhJ  4rxFGSzXiTXuF9GveXbMr4fJAPPnQVjHmpEZbWV8jz9m    7%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! FMcxJrnU61J7s74PhmNdbyJjDJ4b6npACF6Zs2bKeFWX  ED52ZoxYTVz2PEV687evqwDg4ozPVzyPtEb298o1Ya5b  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! 4QNekaDqrLmUENqkVhGCJrgHziPxkX9kridbKwunx9su  GNZ1PAAS33davY4Q1BMEpZEpVBtRtGvSpcTH5wYVkkVt   10%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! BFMufPp4wW276nFzB7FVHgtY8FTahzn53kxxJaNpPGu6  7K8DVxtNJGnMtUY1CQJT5jcs8sFGSZTDiG7kowvFpECh   10%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! 2Ce1dmtdnvgDwD1MiZjP9wwGup6j8H7uXGuGMa9uZo5v  GTeoHau1SpLhoiDGJdQpGd7AS3gyaFLgGVG2EHQRHoWp  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! Gyxhb2GGcB3s5h1HcHekRJYyAHRXEDP1FfX5fncE9edA  2xjAQsHLsV36NLFkxdApzLg4SNqm15mNqYaBQ4xp5joh  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! 6pTM5pLcQFEzCnd2GxLqLm4jL97ZL8L1ThSpR5aVRfc2  7rhm6RffTmi6WLrMjviwEYebm3D9ugUNBvj9t4iUzZTW  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! EjcGVYigv2PA6MeZxRmgFot1P7eGQThFMS2Yh3cj5r2n  Dn2cRSWAfQpb3NyUJ2q33t1scBLxzo8TZBAyKsWhX7zh   10%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! wpd8e4dzFVnCQY3jPuB9J7pKYQd6Mstz5tjWzF97Kxb   Hp1Eieo4bm5u94AG26mybZJB6NsKaB1KYR8DCPriupDA  100%   48245555    48245524           0   unknown  0.99771712 SOL (0.00%)
! Bx6R7GBNsFCt7KJUZw5yrbvdhL1EYcXPhkUBnS2t3c7E  GMnqnaM2QsBLn6nCTxJ15DzZKuyc3UZAogCva5DC7w5M    6%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! HS8DF8wP3A8qSHPnzbE6pSvXub4FeZQ6xMNSJuqArAHS  8HKHFcDGkmeedbTcnK8ntXdqRhYJYWEGbk8325tgv47i  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! GosJ8GHbSUunTQPY5xEyjhY2Eg5a9qSuPhNC4Ctztr7y  DHXbmu3KUhHYn2Trned5ZUaGC6GRgHYhJoRbCr75XQxj  100%   48230042    48229989           0   unknown  0.49771712 SOL (0.00%)
! Hp9NMFfFhDQJCkgUHLajoWqTjm1xxdvQEyUnoYn1GWFX  FM9TSfBK3Xcdj2KY91hUZveSbiTDCBbaYkDbL1ksdwvn    5%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 9vpYXvRdqNJD2YKRZ9q6Xm7fh4FdPGuc5PBZSusv8vbi  8dk8UAi3d6K49fCPiwXyPynhYjQX6wxVA8mdSNzTGVts  100%   48230433    48230402           0   unknown  0.49771712 SOL (0.00%)
! BLPBUAuWmjTKT8rF6nXnHJCcuK4ZonH4xdYSD1gZiET9  7iEP8fEN2be9CZdeiXirtVZTzLKQCEsfMA4E4eeik8T2  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 4PRFPF7f9ERz9azkDFSFfgpye6yixPENCka994j8mQbj  Csp2hDVRX4cRitFEswJJcoH9ju4rcPUSsqU9pkh5JBQU  100%   48230513    48230482           0   unknown  0.49771712 SOL (0.00%)
! 42xkjBQvPyicSdCET8eTWwJayTBofFLGWyCiuodd1SoT  B4H6ZdnJ8YisoYJdbkRjzt9uE5uRSpVqiFGBK9fHNugk  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 8waGfnuaHHUgZT19xQo8LWsAY2CSrXiUMeMDUUrvkeu3  7vmQeg3tFytF8BSYbC5uEwzgCMs9vxs1s3MhSSi4VJC9  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! HU8uKcH8b2GRD5T2LYKDzV82H7CiRLTQLwYTNxAD7b62  4PTVcstjs4s89uETGapnjTNPDa4XfHF9kLUu8WCeYNQb  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! EEN4pf92jyVoASZ6pQQMHcKXTF4d5T3cY1a942QhRasc  DCkFCCEQCuRTcJ3y4rTnWyXnQsi5abfCFXPZZ7pjPJqG  100%   47710275    47710244           0   unknown  0.49771712 SOL (0.00%)
! 4i9CE2ewTTWwJkdMvNcia3D4yR5v4AKryae4nxeSULwL  2TmFPDTyCkuEAMQgf4HdEeSqim11oAJfVKzarEEyFUiU  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 9of5uVqC4EYZ4LLJzPecynNM4GsQWiT1WtHfA39VqcCR  GS9YcwyoG3Y3guieVbDEVyneaa9RnwddwmR98L83McKi  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 6RmSMaZbyb7SGKLp34MXY2qkFePZh41Frs79xJgEg5R6  DGu5PHMFTRhrRcqXw3EfmMxHk3eYLVL6iWbieQ63GYoN  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 914RFshndUeZaNPjf8UWDCyo49ahQ1XQ2w9BnEMwpHKF  4cCd4SGrMswhqboYBJ5AcCVvCjh5NtaeZNwWFJzsnUWY  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! Fa17nmHFt62kmerRQNGtgVWDxnuf7UD3PY2eeFfhpz2t  E3yhPs5PPN4RZh8FbJo2eqtdrAYKCK9H7pcSD1vCNCP4  100%   47845489    47845458           0   unknown  0.49771712 SOL (0.00%)
! FAwRZwJgi7h81ZphYhLauZKvBHvkr3Dbhh6R8DsaD4Xv  7uwo6mYWMRvPhCG1p1Rsc7iuZsv9cN8Gas6n3cLJ1w7b  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 2VAofLE2bYNM3ZPGfn6dJh2zqtnmNdD1bGqFet8mVYFN  4nCK62aZ126pC1krepWXXxgBJGgPUGEWni2iCABZop81   13%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 5Q1tTkjCtYFAtyZ4fxYYND8Ru65LLPuZSo8or9Keyq1h  TxDx1cjjxb15qEUSZWDpHyRnPb1vkYB8djt1scaFfhm   100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 9YDu59tKDysB9zT9P8cgvaogmuy64R1Nxbr57QHztNrW  2oxQJ1qpgUZU9JU84BHaoM1GzHkYfRDgDQY9dpH5mgGn    6%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! EXCMwETx5Txcvxt6YYqxFmhSpQKH5BVjdat3NE5eJJ6a  3yafqDTZxjRCaF8TgPYUvGhnCeuK3sGyoXVRwWnS8ADy  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 77xRWv8Z3kaQpD9K3Den7YWJ7sxsf1KTnw5MdcM7Gtnw  HSV5EHECVyJhDFV1uApzXbU7uK17Z1FXcvtJvHyi2jXC  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! Hqc2qT3vXvBSKozmz7Rd7gLF6jUJHuQEGBTnCHzEBnqk  AJUWPjhNKgo37ta9ycv9bS3DYAT1DY4NP1DDi8DwLeXG  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! 12CUDzb3oe8RBQ4tYGqsuPsCbsVE4KWfktXRihXf8Ggq  AruoPzGrtfAaqUFPUDVmzUHDBjxFJLD8nodzArr346yR  100%   48245555    48245524           0   unknown  0.49771712 SOL (0.00%)
! Gdo6FaCtTQqGYsmDQrX2icSZeqDCdVizGzBDNbiqCGbJ  6k6Yo8kmwssvayHTzp8K4jtVwmyRyjvQx6T96DNJAdYH    5%   48245555    48245524           0   unknown  0.09771712 SOL (0.00%)
! 5GattKwm5oBpDJGgdL7ZZfCMthoETwrZFmQMDK5eq86a  3WrKhSfqEn2nrnsXaSi4ohUUdjE8btXkJ1BycnHizrYx    5%   48245555    48245524           0   unknown  0.04771712 SOL (0.00%)
! GXYeb8vmmvvPxPvUPX6RQ139W3kv7AX9vqr39PzpVTus  6PnJSGnDvxemLEqmqWMqzfgNw1wbp37vNKextbdb59e9  100%    8072826     8072795           0   unknown  0.01543424 SOL (0.00%)
! JCmdhNCyzypryaQUGLGxbCM366dScTD4tVy5ooSWyaBZ  83c5NZebvsUQsL3e9xb37nHiYchLCudDYtQ5Z3gLnLxv  100%   48245555    48245524           0   unknown  0.00771712 SOL (0.00%)
! GXYeb8vmmvvPxPvUPX6RQ139W3kv7AX9vqr39PzpVTus  98gEkDwAgaJd5SzYgDeDCiS4fQuthwXMLPBBwWzpr8aD  100%    7680911     7680880           0   unknown  0.00771712 SOL (0.00%)


```

**Comment by CriesofCarrots** [comment]
> We can't retrospectively update older epoch entries because we can't re-construct older stake history entries only with current live account view. That's because some stakes account has been removed. I think that's why stake history exists in the first place.
> 
> Anyway, the effect should be very small overall. So I don't think this is a real concern.

Oh yes, I knew this would only affect future epochs. I was asking because having a non-zero `deactivating` value, or a greater/lesser value, could make a difference in how much of one particular stake account can deactivate at future epochs. But as you demonstrate, the delta is too small to make a difference. Thank you very much for running that warp to be sure!

File: cli/src/stake.rs (hunk 1 above)
Comment (CriesofCarrots) [reply cli/src/stake.rs]: Added feature check in cli

File: cli/src/stake.rs [hunk 9]
```diff
@@ -1881,6 +1887,15 @@ pub fn process_delegate_stake(
     }
 }
 
+pub fn is_stake_program_v2_enabled(rpc_client: &RpcClient) -> bool {
+    rpc_client
+        .get_account(&feature_set::stake_program_v2::id())
+        .ok()
+        .and_then(|account| feature::from_account(&account))
+        .and_then(|feature| feature.activated_at)
+        .is_some()
```
Comment (CriesofCarrots) [inline cli/src/stake.rs:1896]: `RpcClient::is_feature_enabled(feature_id)` might be a useful method someday, but just have this specific use for now.

**Review by CriesofCarrots — APPROVED** [review]
This seems good to me

File: cli/src/stake.rs (hunk 9 above)
Comment (ryoqun) [reply cli/src/stake.rs:1896]: @CriesofCarrots Oh, sorry for post merge comment, but, I think this might be better off checking the current slot of cluster. Otherwise, there is small time window where this returns too newer stake calculation behavior when the feature is pending to be activated for the next epoch.

**Comment by ryoqun** [comment]
Thanks for merging this and fixing the cli part!

left some comment here: https://github.com/solana-labs/solana/pull/13501/commits/2631caaeaa97f60ab92980017f8b78a721564981#r522000316

File: cli/src/stake.rs (hunk 9 above)
Comment (CriesofCarrots) [reply cli/src/stake.rs:1896]: I believe this is correct as-is. The activation_at field in the account is changed from `None` to `Some(slot)` on the epoch boundary when the feature activates: https://github.com/solana-labs/solana/blob/master/runtime/src/bank.rs#L4119-L4122
When the feature activation has been requested, but is still pending, L1895 returns `None`, so the old stake calculation is used.

This is the same logic used here: https://github.com/solana-labs/solana/blob/master/cli/src/feature.rs#L298

Comment (ryoqun) [reply cli/src/stake.rs:1896]: oh yeah. you're right! Sorry for misguiding you... I misunderstood the code. It seems that my in-brain runtime feature activation code got corrupted somehow... ;)
