### PR TITLE
Don't hardcode username in sys-tuner

### LINKED ISSUE #7206: sys-tuner should not assume the "solana" user
The hard coded user name, "solana", doesn't work generally.  For example in the soft launch infra, the daemons run under the user "solanad".  

https://github.com/solana-labs/solana/blob/a35087a5ed78a93de11cdd4f402784b9f5ca4e53/sys-tuner/src/main.rs#L74

Instead we should accept a username as a clap.rs command-line argument.

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
sys-tuner is assuming the "solana" username for peer. This will break if validator is booted with a different user account.

#### Summary of Changes
Pass username as command line argument.

Fixes #7206

### CODE REVIEW

File: net/remote/remote-node.sh [hunk 1]
```diff
@@ -129,7 +129,7 @@ cat >> ~/solana/on-reboot <<EOF
   # shellcheck source=/dev/null
   SUDO_OK=1 source scripts/tune-system.sh
 
-  sudo RUST_LOG=info ~solana/.cargo/bin/solana-sys-tuner > sys-tuner.log 2>&1 &
+  sudo RUST_LOG=info ~solana/.cargo/bin/solana-sys-tuner -u solana > sys-tuner.log 2>&1 &
```
Comment (mvines) [inline net/remote/remote-node.sh]:
```suggestion
  sudo RUST_LOG=info ~solana/.cargo/bin/solana-sys-tuner -u $(whoami) > sys-tuner.log 2>&1 &
```

File: sys-tuner/src/main.rs [hunk 2]
```diff
@@ -66,6 +67,24 @@ fn tune_system(uid: u32) {
 #[cfg(unix)]
 fn main() {
     solana_logger::setup();
+    let matches = App::new(crate_name!())
+        .about(crate_description!())
+        .version(crate_version!())
```
Comment (mvines) [inline sys-tuner/src/main.rs]: use our version macro please: https://github.com/solana-labs/solana/blob/e2f07a5220191ee6fe3b196651cc45a3dfa1483d/validator/src/main.rs#L321

File: sys-tuner/src/main.rs [hunk 3]
```diff
@@ -66,6 +67,24 @@ fn tune_system(uid: u32) {
...
+        .arg(
+            Arg::with_name("user")
+                .short("u")
```
Comment (mvines) [inline sys-tuner/src/main.rs]: I'd be happy with just the long option
