### PR TITLE
gce.sh: Unwind allocation upon failure

### LINKED ISSUE #6334: colo.sh create does not clean up after itself if bs leader is not created
#### Problem

Looks like `colo.sh create` still creates the client nodes if the bootstrap leader fails to be allocated, then doesn't deallocate client nodes after the bs leader failure.

To reproduce: Allocate all available colo nodes except a non-GPU node, then do a creation of a different testnet name and only the client will get allocated.

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

`net/gce.sh` and `net/colo.sh` leave around partially allocated testnets upon failure

#### Summary of Changes

Install a `trap` a the top of `create` if `--allow-boot-failures` was not passed.  In the trap function, call `delete` if we are exiting with error.

Fixes #6334

### CODE REVIEW

File: net/gce.sh [hunk 1]
```diff
@@ -575,6 +575,14 @@ delete() {
   $metricsWriteDatapoint "testnet-deploy net-delete-complete=1"
 }
 
+create_error_cleanup() {
+  RC=$?
```
Comment (mvines) [inline net/gce.sh]: `declare RC=$?`
