### PR TITLE
Dont process entries in case of failed CPU verification

### LINKED ISSUE #7168: Un-necessary processing of entries in case of failed CPU verification
#### Problem
In case of CPU entry verification, we are processing entries even though the verification is already failed.

#### Proposed Solution
Refactor `EntryVerificationState` to include a `EntryVerificationStatus` enum and `status` method, which can be used to bail out earlier in case verification is failed

### PR DESCRIPTION
**Pull request by ParthDesai**
#### Problem
In case of CPU entry verification, we are processing entries even though the verification is already failed.

#### Summary of Changes
Refactor `EntryVerificationState` to include a `EntryVerificationStatus` enum and `status` method, which can be used to bail out earlier in case verification is failed

Fixes #7168

### CODE REVIEW

**Comment by ParthDesai** [comment]
@mvines Any updates on this?

**Comment by mvines** [comment]
@pgarg66 is a better reviewer for this part of the code

**Comment by ParthDesai** [comment]
@pgarg66 Let me know if you have any feedback on this.

File: core/src/replay_stage.rs [hunk 1]
```diff
@@ -1049,13 +1050,17 @@ impl ReplayStage {
...
+        }
+
         let mut replay_elapsed = Measure::start("replay_elapsed");
         let res =
             blocktree_processor::process_entries(bank, entries, true, transaction_status_sender);
         replay_elapsed.stop();
         bank_progress.stats.replay_elapsed += replay_elapsed.as_us();
 
-        if !entry_state.finish_verify(entries) {
+        if let EntryVerificationStatus::Failure = entry_state.finish_verify(entries) {
```
Comment (sakridge) [inline core/src/replay_stage.rs]: `if EntryVerificationStatus::Failure == entry_state.finish_verify(entries) {`

would be clearer for these, imo.

File: ledger/src/entry.rs [hunk 2]
```diff
@@ -148,53 +148,71 @@ pub fn next_hash(start_hash: &Hash, num_hashes: u64, transactions: &[Transaction
...
-                            } else {
-                                let mut poh = Poh::new(hash, None);
-                                if let Some(mixin) = tx_hash {
-                                    poh.record(*mixin).unwrap().hash == answer.hash
+    pub fn status(&self) -> EntryVerificationStatus {
+        self.verification_status
+    }
+
+    pub fn finish_verify(&mut self, entries: &[Entry]) -> EntryVerificationStatus {
+        match self.verification_status {
```
Comment (pgarg66) [inline ledger/src/entry.rs]: @ParthDesai can we just use `if verified` here, instead of defining a new `enum`?

Comment (ParthDesai) [reply ledger/src/entry.rs]: @pgarg66  Simply using boolean and mark `verified=false`, there will be ambiguity among these two:
1) Pending verification
2) Failed verification

Advantage of using enum is we can represent all three state without ambiguity:
Pending/InProgress (In case of gpu)
Success
Failure

Comment (pgarg66) [reply ledger/src/entry.rs]: `verified` would be false only if `verify_cpu` (or GPU) failed in verification. On that note, https://github.com/solana-labs/solana/pull/7169/files#diff-376f67abc475fe7f487984f195d0fca7L327 could set verified to `res` (similar to `verify_cpu`), instead of `false`.
 
@sakridge , do you know why `verified: false` at  https://github.com/solana-labs/solana/pull/7169/files#diff-376f67abc475fe7f487984f195d0fca7L327. `finish_verify` would return false if `self.hashes` is `None`. Is that the intended behavior?

Comment (sakridge) [reply ledger/src/entry.rs]: @pgarg66 How can `self.hashes` be `None` in that case, it sets it to `Some(hashes)`. What it sets it to should actually never matter since it should go through the GPU path there and using this:
https://github.com/solana-labs/solana/blob/323673c3c0b8e33b14d27f1e408a4624c3eb5160/ledger/src/entry.rs#L179

Comment (sakridge) [reply ledger/src/entry.rs]: @ParthDesai we could keep the return here as bool, no? We should never be pending after `finish_verify`

Comment (pgarg66) [reply ledger/src/entry.rs]: > @pgarg66 How can `self.hashes` be `None` in that case, it sets it to `Some(hashes)`. What it sets it to should actually never matter since it should go through the GPU path there and using this:
> https://github.com/solana-labs/solana/blob/323673c3c0b8e33b14d27f1e408a4624c3eb5160/ledger/src/entry.rs#L179

Maybe a better question would've been: would setting `verified: res` in  https://github.com/solana-labs/solana/pull/7169/files#diff-376f67abc475fe7f487984f195d0fca7L327 have any adverse effect? I guess not, based on your reply above.

File: ledger/src/entry.rs [hunk 3]
```diff
@@ -204,7 +222,7 @@ pub trait EntrySlice {
     /// Verifies the hashes and counts of a slice of transactions are all consistent.
     fn verify_cpu(&self, start_hash: &Hash) -> EntryVerifyState;
     fn start_verify(&self, start_hash: &Hash) -> EntryVerifyState;
-    fn verify(&self, start_hash: &Hash) -> bool;
+    fn verify(&self, start_hash: &Hash) -> EntryVerificationStatus;
```
Comment (sakridge) [inline ledger/src/entry.rs]: Similar to my other comment, leave this as bool. It makes it seem like you could return Pending from these interfaces but that's not actually the case because this is meant to be a blocking call.

File: ledger/src/entry.rs (hunk 2 above)
Comment (ParthDesai) [reply ledger/src/entry.rs]: @sakridge @pgarg66  I did it for consistency's sake. 

My reasoning comes because of different handling of object states:

In case of CPU verification:
Verification happens in `start_verify` itself, and verified is set to `true` or `false`

In case of GPU verification:
Verification happens when `finish_verify` is called and then verified is changed to `true` in case verification succeeds, and set to `false` in case of verification fails. 

So, the semantics of `verified: false` after `start_verify` is called depends upon whether it is CPU or GPU verification.

Maybe, instead of checking if `Hashes` is `None` or `Some(hashes)` to determine the behaviour we could just have a flag indicating CPU or GPU verification.

Comment (sakridge) [reply ledger/src/entry.rs]: @pgarg66 there is no `res` there. At that point we have just kicked off the GPU path and we don't know if it will be verified until finish_verify is called.

Comment (pgarg66) [reply ledger/src/entry.rs]: Got it.. makes sense. Thanks

Comment (ParthDesai) [reply ledger/src/entry.rs]: @sakridge So, if I use `bool`, how would I be able to distinguish between verification completed or pending? after my call to `start_verify` returns?

Comment (sakridge) [reply ledger/src/entry.rs]: @ParthDesai For `start_verify` you can use the enum since the state can be in pending state there. But for when you know you are done, I think it makes it cleaner from the API to only expose two options passed or not.

Comment (sakridge) [reply ledger/src/entry.rs]: I think it might be also cleaner to use an enum, and then have a CPU struct and a GPU struct contained in them so it's clear which path is using what fields.

Comment (ParthDesai) [reply ledger/src/entry.rs]: @pgarg66 @sakridge How does it look like now? Main interface is left as it is, while also allowing different enum for CPU and GPU verification.
