### PR TITLE
fix: optional stake lockup field parameters

### LINKED ISSUE #15326: web3: Accept `null` lockup in interfaces for create/initialize stake account
#### Problem

Lockups on stake accounts are a niche use-case. The web3 interface for creating and initializing them requires this field be provided, causing confusion as to what the value should be

#### Proposed Solution

Allow `null` lockups in interfaces and fill in default, no-lockup values

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

I used the "chore" semantic commit prefix on a commit I meant to release.  Now I need to "fix" something, so...

--

`Lockups` are a fringe feature of the stake program.  It's annoying to have to specify them when creating/initializing stake accounts

#### Summary of Changes

Make them optional

Fixes #15326

### CODE REVIEW

File: web3.js/src/stake-program.ts [hunk 1]
```diff
@@ -502,7 +507,8 @@ export class StakeProgram {
    * Generate an Initialize instruction to add to a Stake Create transaction
    */
   static initialize(params: InitializeStakeParams): TransactionInstruction {
-    const {stakePubkey, authorized, lockup} = params;
+    const {stakePubkey, authorized, lockup: maybe_lockup} = params;
+    const lockup: Lockup = (typeof maybe_lockup !== 'undefined') ? maybe_lockup : Lockup.default;
```
Comment (jstarry) [inline web3.js/src/stake-program.ts:511]:
```suggestion
    const {stakePubkey, authorized, lockup: maybeLockup} = params;
    const lockup: Lockup = maybeLockup || Lockup.default;
```

**Review by jstarry — DISMISSED** [review]
Looks good!
