### PR TITLE
Fix race condition between shrinking and cleaning (for 1.1)

### LINKED ISSUE #11232: Replay stage panicked on mainnet-beta API node
#### Problem

```
thread 'solana-replay-stage' panicked at 'called `Option::unwrap()` on a `None` value', runtime/src/accounts_db.rs:857:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86

  ...

  15: solana_runtime::accounts_db::AccountsDB::clean_accounts
  16: solana_ledger::snapshot_utils::add_snapshot
  17: solana_ledger::bank_forks::BankForks::generate_snapshot
  18: solana_ledger::bank_forks::BankForks::set_root
  19: solana_core::replay_stage::ReplayStage::new::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

log: https://drive.google.com/file/d/1zkxKc6QDoKm_myODIC03BS-Y6q20_cM6/view?usp=sharing

This node was running the v1.1.22 release

#### Proposed Solution

Triage and resolve

tag: @ryoqun @sakridge

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

Slot shrinking violates an assumption of account cleaning: stores of slots should generally be immutable once rooted, especially when doing the cleaning process.

So, `panic!` can be triggered intermittently if the background slot shrinking touches to-be-cleaned slots while the cleaning process is running and vice versa.

Note: this is a possible DOS attack vector.

#### Summary of Changes

Ensure not to run slot shrinking if account cleaning is in progress by holding shared lock (`shrink_candidate_slots`) from each processing with appropriate lifetime.

Also, as a really last-minute bonus for the v1.1, just back-port some measure thing from #10099 .

(Also, this is manually back-ported version of #11235 because v1.1 branch doesn't contain #10099).

Fixes #11232

### CODE REVIEW

File: runtime/src/accounts_db.rs [hunk 1]
```diff
@@ -795,6 +795,11 @@ impl AccountsDB {
     // Only remove those accounts where the entire rooted history of the account
     // can be purged because there are no live append vecs in the ancestors
     pub fn clean_accounts(&self) {
+        // hold a lock to prevent slot shrinking from running because it might modify some rooted
+        // slot storages which can not happen as long as we're cleaning accounts because we're also
+        // modifying the rooted slot storages!
+        let _candidates = self.shrink_candidate_slots.lock().unwrap();
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:801]: Removing this line easily causes `test_shrink_and_clean` failures

**Comment by ryoqun** [comment]
I've finished local testing!
