### PR TITLE
Fix BPF program static linking for tests

### LINKED ISSUE #5991: Fix BPF program testing when statically linking BPF loader
#### Problem
Native programs can be statically linked in tests by calling `bank.add_instruction_processor(..)` but this approach is not working for testing BPF programs. Even after adding the BPF loader as an instruction processor, BPF program instructions pass through the message processor to the native loader. This is because `MessageProcessor` tries to match the BPF program id instead of the BPF loader id in its `instruction_processors`.

#### Proposed Solution
When the native loader is invoked, it pulls the native library name from the native program account data. We can match that library name against a new "named instruction processor" in order to intercept BPF program instructions before they try to load a native library.

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Native programs can be statically linked in tests by calling bank.add_instruction_processor(..) but this approach is not working for testing BPF programs. This is important because native programs currently cannot be deterministically loaded when the solana runtime is not a path dependency. [Details here](https://github.com/solana-labs/solana/issues/5966)

Additionally, there was a bug with loading executable accounts that didn't affect the network. The issue was that the public key in the executable account tuple of (PublicKey, Account) is supposed to represent the executable account, not the owner of the account.

#### Summary of Changes
* Intercept BPF program instructions by checking the loader id instead of program id against instruction processors
* Fix executable account loading

Fixes #5991

### CODE REVIEW

File: runtime/src/accounts.rs [hunk 1]
```diff
@@ -180,8 +180,9 @@ impl Accounts {
             }
 
             // add loader to chain
-            program_id = program.owner;
+            let program_owner = program.owner;
```
Comment (CriesofCarrots) [inline runtime/src/accounts.rs]: 🎉 this makes so much more sense to my brain
