### PR TITLE
An async test is flaky on ci

### LINKED ISSUE #21392: Sporadic test issue with test_async_report_metrics
#### Problem

Seeing the following failure quite a few times:

thread 'qos_service::tests::test_async_report_metrics' panicked at 'assertion failed: `(left == right)`
  left: `4096`,
 right: `2048`', core/src/qos_service.rs:341:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panicking.rs:107:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panicking.rs:145:5
   4: solana_core::qos_service::tests::test_async_report_metrics
             at ./src/qos_service.rs:341:9
   5: solana_core::qos_service::tests::test_async_report_metrics::{{closure}}
             at ./src/qos_service.rs:309:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

https://buildkite.com/solana-labs/solana/builds/59851#5786531d-4ec5-4ef3-a931-e24a6603a676

### PR DESCRIPTION
**Pull request by taozhu-chicago**
#### Problem
The test that spawns two threads are flaky on ci, it fails from time to time as if one or both spawned threads didn't run.

#### Summary of Changes

Fixes #21392

### CODE REVIEW

**Comment by taozhu-chicago** [comment]
not really sure why this test fails, looking at the one failed on you and myself, feels the spawned test thread(s) didn't run. Can't reproduce the failure locally. Added some logs and trying more CI builds, it has been consistent success so far.

**Comment by taozhu-chicago** [comment]
the changes in this PR didn't really change code logic nor test setup. But it passes the `coverage` tests many times I tried. I am going to merge it to master for now, but still would like to have you guys take a look to see if there are something I overlooked. @behzadnouri  @lijunwangs thanks.

File: core/src/qos_service.rs [hunk 1]
```diff
@@ -327,16 +328,50 @@ mod tests {
...
+                        .compute_cost_count
+                        .load(Ordering::Relaxed)
+                );
+            })
+            .unwrap();
 
-        let th_2 = thread::spawn(move || {
-            qos_service_2.compute_transaction_costs(txs_2.iter(), false);
-        });
+        th_1.join().expect("qos service 1 panicked");
```
Comment (lijunwangs) [inline core/src/qos_service.rs:365]: Since we are joining on the threads -- so I do not think the reason is the thread was failed to launched. I think something else is causing the sporadic issue.  The compute_cost_count is changed in two places:

1.                 (
                    "compute_cost_count",
                    self.compute_cost_count.swap(0, Ordering::Relaxed) as i64,
                    i64
                ),

2.         self.metrics
            .compute_cost_count
            .fetch_add(txs_costs.len() as u64, Ordering::Relaxed);

I am guessing it could happen this way:

1. One thread is done with compute_transaction_costs and update the count to 2048.
2. The report thread kicks in and reset the value to 0
3. The other thread run compute_transaction_costs again and set it to 2048.
4. The test loads the 2048.

Changing to shorter txn list only changes the timing part I think.

Maybe we can turn off report in the tests?

    fn reporting_loop(running_flag: Arc<AtomicBool>, metrics: Arc<QosServiceMetrics>) {
        while running_flag.load(Ordering::Relaxed) {
            // hardcode to report every 1000ms
            metrics.report(1000u64);
            thread::sleep(Duration::from_millis(100));
        }
    }

Comment (taozhu-chicago) [reply core/src/qos_service.rs:365]: Sharp eyes! Thanks @lijunwangs , this is very likely cause, I totally overlooked reporting part. Putting in a fix soon
