### PR TITLE
Apple M1 compatibility

### LINKED ISSUE #16072: Failed to build on Mac m1
#### Problem

I am building on my new Mac m1 and it failed.

The author of `ring` says it can be fixed by upgrading dependency (https://github.com/briansmith/ring/issues/1163).

I tried add ring = "0.16.19" to cargo.toml but failed because this virtual manifest specifies a [dependencies] section, which is not allowed

I tried to search ring in the project directory and I only find them in cargo.lock.

It seems ring is a dependency of dependency of Solana. I am new to Rust and I do not know how to fix this.

```
 Compiling tokio-threadpool v0.1.18
   Compiling tokio-codec v0.1.2
error: failed to run custom build command for `ring v0.16.12`

Caused by:
  process didn't exit successfully: `/Users/xxx/code/solana/target/debug/build/ring-e5b7d4867a02bd0a/build-scrixxx-build` (exit code: 101)
  --- stdout
  CARGO: /Users/xxx/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo
  CARGO_CFG_TARGET_ARCH: aarch64
  CARGO_CFG_TARGET_ENDIAN: little
  CARGO_CFG_TARGET_ENV: 
  CARGO_CFG_TARGET_FAMILY: unix
  CARGO_CFG_TARGET_OS: macos
  CARGO_CFG_TARGET_POINTER_WIDTH: 64
  CARGO_CFG_TARGET_VENDOR: apple
  CARGO_CFG_UNIX: 
  CARGO_FEATURE_ALLOC: 1
  CARGO_FEATURE_DEFAULT: 1
  CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
  CARGO_FEATURE_LAZY_STATIC: 1
  CARGO_HOME: /Users/xxx/.cargo
  CARGO_MAKEFLAGS: --jobserver-fds=3,4 -j --jobserver-auth=3,4 -j
  CARGO_MANIFEST_DIR: /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12
  CARGO_MANIFEST_LINKS: ring-asm
  CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
  CARGO_PKG_DESCRIxxxION: Safe, fast, small cryxxxo using Rust.
  CARGO_PKG_HOMEPAGE: 
  CARGO_PKG_LICENSE: 
  CARGO_PKG_LICENSE_FILE: LICENSE
  CARGO_PKG_NAME: ring
  CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
  CARGO_PKG_VERSION: 0.16.12
  CARGO_PKG_VERSION_MAJOR: 0
  CARGO_PKG_VERSION_MINOR: 16
  CARGO_PKG_VERSION_PATCH: 12
  CARGO_PKG_VERSION_PRE: 
  DEBUG: true
  DYLD_FALLBACK_LIBRARY_PATH: /Users/xxx/code/solana/target/debug/deps:/Users/xxx/code/solana/target/debug:/Users/xxx/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib:/Users/xxx/.rustup/toolchains/stable-aarch64-apple-darwin/lib:/Users/xxx/lib:/usr/local/lib:/usr/lib
  HOME: /Users/xxx
  HOMEBREW_CELLAR: /oxxx/homebrew/Cellar
  HOMEBREW_PREFIX: /oxxx/homebrew
  HOMEBREW_REPOSITORY: /oxxx/homebrew
  HOST: aarch64-apple-darwin
  INFOPATH: /oxxx/homebrew/share/info:
  LANG: en_US.UTF-8
  LOGNAME: xxx
  LaunchInstanceID: 650AC464-90EC-415B-B3B7-BE5A658C89F1
  MANPATH: /oxxx/homebrew/share/man::
  NUM_JOBS: 8
  OLDPWD: /Users/xxx/code
  Oxxx_LEVEL: 0
  OUT_DIR: /Users/xxx/code/solana/target/debug/build/ring-51d6c5f00b9ac169/out
  PATH: /Users/xxx/.cargo/bin:/oxxx/homebrew/bin:/oxxx/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xxx/.cargo/bin
  PROFILE: debug
  PWD: /Users/xxx/code/solana
  RUSTC: rustc
  RUSTDOC: rustdoc
  RUSTUP_HOME: /Users/xxx/.rustup
  RUSTUP_TOOLCHAIN: stable-aarch64-apple-darwin
  RUST_RECURSION_COUNT: 1
  SECURITYSESSIONID: 186b9
  SHELL: /bin/zsh
  SHLVL: 1
  SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.ClxDtGfIwy/Listeners
  TARGET: aarch64-apple-darwin
  TERM: xterm-256color
  TERM_PROGRAM: Apple_Terminal
  TERM_PROGRAM_VERSION: 440
  TERM_SESSION_ID: 8998128C-3738-440D-9638-CBD45E430CAF
  TMPDIR: /var/folders/yy/vchg_vkn3b99gk27n12cs09c0000gn/T/
  USER: xxx
  XPC_FLAGS: 0x0
  XPC_SERVICE_NAME: 0
  _: /Users/xxx/.cargo/bin/cargo
  __CFBundleIdentifier: com.apple.Terminal
  __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
  all_proxy: socks5://127.0.0.1:7890
  http_proxy: http://127.0.0.1:7890
  https_proxy: http://127.0.0.1:7890
  Oxxx_LEVEL = Some("0")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  CC_aarch64-apple-darwin = None
  CC_aarch64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_aarch64-apple-darwin = None
  CFLAGS_aarch64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = None
  running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-gfull" "-DNDEBUG" "-c" "-o/Users/xxx/code/solana/target/debug/build/ring-51d6c5f00b9ac169/out/aesv8-armx-linux64.o" "/Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S"

  --- stderr
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:18:17: error: unexpected token in '.section' directive
  .section .rodata
                  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:28:1: error: unknown directive
  .hidden GFp_aes_hw_set_encryxxx_key
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:29:1: error: unknown directive
  .type GFp_aes_hw_set_encryxxx_key,%function
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:161:1: error: unknown directive
  .size GFp_aes_hw_set_encryxxx_key,.-GFp_aes_hw_set_encryxxx_key
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:163:1: error: unknown directive
  .hidden GFp_aes_hw_encryxxx
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:164:1: error: unknown directive
  .type GFp_aes_hw_encryxxx,%function
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:191:1: error: unknown directive
  .size GFp_aes_hw_encryxxx,.-GFp_aes_hw_encryxxx
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:193:1: error: unknown directive
  .hidden GFp_aes_hw_decryxxx
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:194:1: error: unknown directive
  .type GFp_aes_hw_decryxxx,%function
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:221:1: error: unknown directive
  .size GFp_aes_hw_decryxxx,.-GFp_aes_hw_decryxxx
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:223:1: error: unknown directive
  .hidden GFp_aes_hw_ctr32_encryxxx_blocks
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:224:1: error: unknown directive
  .type GFp_aes_hw_ctr32_encryxxx_blocks,%function
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:403:1: error: unknown directive
  .size GFp_aes_hw_ctr32_encryxxx_blocks,.-GFp_aes_hw_ctr32_encryxxx_blocks
  ^
  /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aesv8-armx-linux64.S:407:19: error: unexpected token in '.section' directive
  .section .note.GNU-stack,"",%progbits
                    ^
  thread 'main' panicked at 'execution failed', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/build.rs:641:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

```

### PR DESCRIPTION
**Pull request by cdrappi**
#### Problem
Solana does not build on computers with Mac M1 chips

#### Summary of Changes
- Upgrade `cc` crate
- Explicitly force `ring` to version `0.16.17`: It's required by [rustls](https://crates.io/crates/rustls/0.19.0/dependencies) which has some wiggle room on ring versions
- Remove memory profiling with `jemallocator`, now defaulting to the system allocator
- Exclude `target_os = "macOS"` from AVX check

Fixes #16072 

#### Current state
**Good**: It builds, runs (with `./run.sh`), and `cargo +nightly bench` works

**Bad**: `cargo test` and `cargo test --release` both fail different tests. After having run these many times each and getting a feel for their behavior, I've gotten similar but not exactly the same failures. I'd love to get some color on what you expect from these runs

##### `cargo test`
- `test_kill_heaviest_partition` fails every time with: `'assertion failed: loop_start.elapsed() < loop_timeout', local-cluster/src/cluster_tests.rs:284:9`
- `test_kill_partition_switch_threshold_no_progress` fails sometimes with a `'get_slot for 6iXMbNNczChSGvo4EAThk8udgApPK9Sk8vcsc1w4Nq3 failed', local-cluster/src/cluster_tests.rs:332:37`
- `test_future_tower_master_only` has failed but more rarely

##### `cargo test --release`
- `test_push_votes_with_tower` fails all the time, on either `assert_eq!(vote_slots.len(), MAX_LOCKOUT_HISTORY);` (with many different `vote_slots` lengths) or `assert!(vote_slot != 23);`. _From knowing almost nothing about Solana, I'm most concerned with the last type of failure case here_

### CODE REVIEW

**Comment by mvines** [comment]
Thanks for looking into this!

I think you could incorporate `install/MacM1.md` into the existing README instructions around https://github.com/solana-labs/solana#building

**Comment by cdrappi** [comment]
@mvines noted! This is getting closer and I updated the note above with a few questions. When you or another maintainer gets a chance, I'd love some feedback :)

**Comment by aeyakovenko** [comment]
@sakridge do we still need the jemalloc at all?  can we yank it?

**Comment by mvines** [comment]
> @sakridge do we still need the jemalloc at all? can we yank it?

Ripping out the jemalloc stuff seems preferable to more featurization to me

File: core/src/validator.rs [hunk 1]
```diff
@@ -1388,7 +1388,7 @@ fn report_target_features() {
         }
     );
 
-    #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
+    #[cfg(all(any(target_arch = "x86", target_arch = "x86_64"), not(target_os = "macos")))]
```
Comment (mvines) [inline core/src/validator.rs:1391]: macos m1 claims to be `target_arch = "x86"` or `target_arch = "x86_64"`, that seems terrible

Comment (sakridge) [reply core/src/validator.rs:1391]: But is that just for the interpreted? There is the mode on m1 to execute x86 code, so it has to report that.

**Comment by sakridge** [comment]
> > @sakridge do we still need the jemalloc at all? can we yank it?
> 
> Ripping out the jemalloc stuff seems preferable to more featurization to me

Can't say I use jemalloc. I would remove it. I think `heaptrack` is a better tool for finding memory use issues and that requires the system allocator.

File: core/src/validator.rs (hunk 1 above)
Comment (sakridge) [reply core/src/validator.rs:1391]: wouldn't this feature check affect the x86 macs which have AVX?

Comment (cdrappi) [reply core/src/validator.rs:1391]: To get this going on an M1, you have to install all of your stuff with Rosetta 2, a tool that allows you to run x86_64 software. This amounts to using a version of rust/cargo etc. that targets `x86_64` instead of `aarch64`. Which produces this extremely confusing feature flag

Without Rosetta, rust would target `aarch64` – I tried to do this initially, and gave up after a day as there were several more blockers upstream

**Comment by cdrappi** [comment]
Thank you @mvines and @sakridge! I will work on removing `jemalloc` and bug you when I think I have something :)

File: core/src/validator.rs (hunk 1 above)
Comment (mvines) [reply core/src/validator.rs:1391]: Ah, got it.  Would you mind sneaking in a comment in the code then here about why we're excluding macos.  Otherwise somebody with an intel mbp (everybody on the core team) is likely to remove this line later inadvertently

Comment (cdrappi) [reply core/src/validator.rs:1391]: @sakridge yes it would and is a clear downside of including this feature check. If you could think of a better way to get around this, I'm happy to implement it and be your Mac M1 guinea pig guy

@mvines yes of course! Was planning on this and appreciate the reminder

**Comment by cdrappi** [comment]
Hey @mvines and @sakridge, I've ripped out `jemalloc` from `solana-measure` and all its uses. Lmk what you think about these failing tests and anything I may have missed!

**Comment by mvines** [comment]
Thanks @cdrappi, looks like `programs/bpf/Cargo.lock` needs an update as well (it's another lock file we have in the tree :-/)
Would you mind also rebasing your PR  (`git pull --rebase`) to get rid of the merge commits in here.

The changes themselves all look great

**Comment by cdrappi** [comment]
Thank you @mvines we should be in business now!

**Comment by mvines** [comment]
`cargo fmt` please :)

**Comment by mvines** [comment]
Thank you for this contribution @cdrappi!

**Comment by zarex5** [comment]
Hi @cdrappi, thanks a lot for your PR. I was able to build from source under Rosetta 🎉
However, I get this message when starting solana-test-validator: "ERROR solana_core::validator] Your machine does not have AVX support, please rebuild from source on your machine" and then "Validator process aborted."
Are you able to run it on your side? Thanks in advance!

**Comment by cdrappi** [comment]
@zarex5 This is exactly the error I received before adding [this](https://github.com/solana-labs/solana/pull/16346/files#diff-8aa35f64ce162f53fcdda9823deb9a87ac8a0c35d0738533e35c2241c726e769R1393) twisted feature flag to the code. It was giving me this even though I was building it from my machine, like the situation you seem to be in. I'm surprised you're still getting this given the flag is in there now. This was helpful for me when I was tracking down what my computer was running (eg. making sure everything was using Rosetta):

Make a new bin, I called it arch-detector:
`cargo new --bin arch-detector && cd arch-detector`

Add a `build.rs` to the root with this content:

```
fn main() {
    println!(
        "cargo:rustc-env=TARGET={}",
        std::env::var("TARGET").unwrap()
    );
}
```

and edit your `src/main.rs` to look like this:

```
const TARGET: &str = env!("TARGET");

fn main() {
    println!("Target: {}", TARGET);
}
```

Then check the output of `cargo run`. Mine says:

`Target: x86_64-apple-darwin`

If you get this output, then you can be sure that feature flag will prevent `check_avx` from running. If not, my hunch is that some part of your install may not be using Rosetta. If this is still a problem, you and I can spitball a solution on Discord or something and then maybe add a little more detail to the M1 setup documentation

**Comment by cdrappi** [comment]
A ha! @zarex5 I think I know what you're talking about. If we install Solana via the install script, and then run `solana-test-validator`, it will show us the error you mention when we inspect the logs. Here's the output I get:

```
❯ solana-test-validator

Ledger location: test-ledger
Log: test-ledger/validator.log
⠉ Initializing...
Validator process aborted. The validator log may contain further details
```

The logs show me this:

```
[a bunch of stuff and then...]
ERROR solana_core::validator] Your machine does not have AVX support, please rebuild from source on your machine
```

This is because the version installed in that script does not include these changes yet. `v1.6.5` and greater will have these, going forward. For now, we will have to run a local solana node using `./run.sh` from the solana repo root. To my understanding, calling `./run.sh` will do the same thing as `solana-test-validator`, excepting using the version you built from source, rather than the solana-cli installed from that script mentioned above (currently version 1.6.3)

Let me know if that clears up confusion you may have! I say this with like 80% confidence I know what I'm talking about so happy to troubleshoot with you. It would probably help us both out :)

**Comment by zarex5** [comment]
Thats's exactly it, my x86 build was just fine but I was still using the version installed by the install script
Running ./run.sh works perfectly. Thank you so much for your help!
