### PR TITLE
Port various rent fixes to runtime feature

### LINKED ISSUE #10810: v1.3: Enable eager rent collect across gapped epochs on mainnet-beta
#### Problem

this needs to be updated for mainnet-beta:

https://github.com/solana-labs/solana/blob/50f7ed80c824cc844bcacff0bbbd299d193cc620/runtime/src/bank.rs#L1871-L1873

#### Context

#10206

### LINKED ISSUE #11545: v1.3: Enable retirement of rent collect in Bank::deposit() on mainnet-beta
#### Problem

this needs to be updated for mainnet-beta:

for v1.2 branch
https://github.com/solana-labs/solana/blob/e477501687d764bee98ed8fb1b14a6a91faae8a7/runtime/src/bank.rs#L2299

for v1.3 branch
https://github.com/solana-labs/solana/blob/53e917b54f6ba7c74cb7a1b3f1f072cb7226b3b0/runtime/src/bank.rs#L2549

#### Context

#10468 

#### Cousin

#11543

### LINKED ISSUE #11682: v1.3: Enable stricter check on rent-exempt accounts on mainnet-beta
#### Problem

this needs to be updated for testnet:
https://github.com/solana-labs/solana/blob/e2626dad83e597cbb769e0033fdc3ee597a910ec/runtime/src/rent_collector.rs#L68

#### Context

#11342 

#### Cousin

#11681

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

low priority various rent fixes still uses obsolete cluster type based gating.

#### Summary of Changes

port it to runtime feature.

because these fixes are active or inactive depending on clusters, we have to be careful to transition.... so #12841 must go first as a prior version update.

Fixes #11682, fixes #11545, fixes #10810.

### CODE REVIEW

File: runtime/src/bank.rs [hunk 1]
```diff
@@ -779,9 +779,7 @@ impl Bank {
             slots_per_year: parent.slots_per_year,
             epoch_schedule,
             collected_rent: AtomicU64::new(0),
-            rent_collector: parent
-                .rent_collector
-                .clone_with_epoch(epoch, parent.cluster_type()),
+            rent_collector: parent.rent_collector.clone_with_epoch(epoch),
```
Comment (ryoqun) [inline runtime/src/bank.rs:782]: change of plumbing by removing `RentCollecotr::cluster_type` wasn't avoidable exactly because of unavailability of feature set of new bank even before creating it.

File: runtime/src/bank.rs [hunk 2]
```diff
@@ -899,9 +897,7 @@ impl Bank {
             fee_rate_governor: fields.fee_rate_governor,
             collected_rent: AtomicU64::new(fields.collected_rent),
             // clone()-ing is needed to consider a gated behavior in rent_collector
-            rent_collector: fields
-                .rent_collector
-                .clone_with_epoch(fields.epoch, genesis_config.cluster_type),
+            rent_collector: fields.rent_collector.clone_with_epoch(fields.epoch),
```
Comment (ryoqun) [inline runtime/src/bank.rs:900]: change of plumbing by removing `RentCollecotr::cluster_type` wasn't avoidable exactly because of unavailability of feature set of new bank even before constructing the very first bank from the snapshot..

File: runtime/src/bank.rs [hunk 3]
```diff
@@ -3284,21 +3280,21 @@ impl Bank {
...
         // there are too many and subtly nuanced modification codepaths
         if !should_be_in_new_behavior {
             // previously we're too much collecting rents as if it existed since epoch 0...
             self.collected_rent.fetch_add(
-                self.rent_collector
-                    .collect_from_existing_account(pubkey, &mut account),
+                self.rent_collector.collect_from_existing_account(
+                    pubkey,
+                    &mut account,
+                    should_be_in_new_behavior,
```
Comment (ryoqun) [inline runtime/src/bank.rs:3296]: fuse the flags. :)

**Comment by ryoqun** [comment]
oops ci failed...

**Comment by ryoqun** [comment]
@mvines CI is green and could you take a look at this (this won't be merged for a while; so a SCHED_IDLE review task). ;)

File: runtime/src/accounts.rs [hunk 4]
```diff
@@ -144,6 +144,8 @@ impl Accounts {
             let mut payer_index = None;
             let mut tx_rent: TransactionRent = 0;
             let mut accounts = Vec::with_capacity(message.account_keys.len());
+            let fix_rent = feature_set.rent_fix_enabled();
```
Comment (mvines) [inline runtime/src/accounts.rs:147]: nit: name the var the same for easy future searching:
```suggestion
            let rent_fix_enabled = feature_set.rent_fix_enabled();
```

File: runtime/src/accounts.rs [hunk 5]
```diff
@@ -730,6 +738,7 @@ impl Accounts {
         rent_collector: &RentCollector,
         last_blockhash_with_fee_calculator: &(Hash, FeeCalculator),
         fix_recent_blockhashes_sysvar_delay: bool,
+        fix_rent: bool,
```
Comment (mvines) [inline runtime/src/accounts.rs:741]:
```suggestion
        rent_fix_enabled: bool,
```

File: runtime/src/feature_set.rs [hunk 6]
```diff
@@ -120,6 +120,11 @@ impl FeatureSet {
     pub fn is_active(&self, feature_id: &Pubkey) -> bool {
         self.active.contains(feature_id)
     }
+
+    pub fn rent_fix_enabled(&self) -> bool {
```
[the remark this answers is not in the document]
Comment (ryoqun) [reply runtime/src/feature_set.rs]: done. d258182d236426ff5e3382433d1ab0e3fefda705

File: runtime/src/accounts.rs (hunk 5 above)
Comment (ryoqun) [reply runtime/src/accounts.rs]: done d258182d236426ff5e3382433d1ab0e3fefda705

File: runtime/src/accounts.rs (hunk 4 above)
Comment (ryoqun) [reply runtime/src/accounts.rs]: done d258182d236426ff5e3382433d1ab0e3fefda705

**Comment by ryoqun** [comment]
Thanks for reviewing! Blame me for inconsistent naming... ;) How does the new naming taste for you? :)

**Review by mvines — DISMISSED** [review]
