### PR TITLE
Fix panic in BanksServer

### LINKED ISSUE #12167: v1.3: RpcBanksService::run panic
@brianlong noticed a panic in RpcBanksService.  More logs at https://gist.github.com/brianlong/ce96d20ebe554460edcf34abba15e40e

Disable BanksService by default before mainnet-beta moves to v1.3?   It's not used by anybody 

```
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
 8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
  12: rust_begin_unwind
             at src/libstd/panicking.rs:388
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: <tarpc::rpc::server::filter::ChannelFilter<S,K,F> as futures_core::stream::Stream>::poll_next
  16: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
  17: <futures_util::stream::stream::buffer_unordered::BufferUnordered<St> as futures_core::stream::Stream>::poll_next
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: solana_banks_server::rpc_banks_service::start_abortable_tcp_server::{{closure}}::{{closure}}::{{closure}}
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: tokio::runtime::thread_pool::ThreadPool::block_on
  23: tokio::runtime::context::enter
  24: tokio::runtime::Runtime::block_on
  25: solana_banks_server::rpc_banks_service::RpcBanksService::run
```

### PR DESCRIPTION
**Pull request by garious**
#### Problem

BanksServer can panic, probably because `peer_addr()` can return `None` if the client closes the connection before the server accepts it.

#### Summary of Changes

Don't `unwrap()`

Fixes #12167

@CriesofCarrots, fyi

Thanks @tikue for spotting this!

### CODE REVIEW

File: banks-server/src/banks_server.rs [hunk 1]
```diff
@@ -240,7 +240,12 @@ pub async fn start_tcp_server(
         .filter_map(|r| future::ready(r.ok()))
         .map(server::BaseChannel::with_defaults)
         // Limit channels to 1 per IP.
-        .max_channels_per_key(1, |t| t.as_ref().peer_addr().unwrap().ip())
+        .max_channels_per_key(1, |t| {
```
Comment (mvines) [inline banks-server/src/banks_server.rs:243]: ah, the ip echo service had this same bug at one point in the past too
