### PR TITLE
Remove drone network dependency 

### LINKED ISSUE #1819: JSON RPC airdrops are broken
This fails with "Internal error":
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"requestAirdrop", "params":["83astBRguLMdt2h5U1Tpdq5tjFoJ6noeGwaY3mDLVcri", 40]}' http://localhost:8899
```
but this doesn't:
```
$ cargo run --bin solana-wallet airdrop 1234
```

`solana-wallet` doesn't use the RPC API to make an airdrop request and instead goes directly to the drone, so that's one difference.

Suspected root cause is f683817b48167d403dfe5ce779793ba413d9ce88, where the thin_client now uses the JSON RPC API to fetch a last_id or check a signature.  

Blocks: https://github.com/solana-labs/solana-web3.js/pull/64

### PR DESCRIPTION
**Pull request by mvines**
Drone's sole job is now to sign airdrop transactions for the user.  The user is responsible for submitting the transaction and monitoring the result.

Fixes #1819

### CODE REVIEW

File: src/rpc_request.rs [hunk 1]
```diff
@@ -56,7 +56,7 @@ impl RpcRequest {
            "method": method,
         });
         if let Some(param_string) = params {
-            request["params"] = json!(vec![param_string]);
```
Comment (mvines) [inline src/rpc_request.rs]: This single line change caused a large ripple effect through this PR.  The automatic wrapping of a vector around the param_string meant that we couldn't actually send an RPC request with two or more parameters through rpc_request.rs
