### PR TITLE
Fix getting the golden snapshot hashes during bootstrap with Incremental Snapshots

### LINKED ISSUE #23509: Bootstrap snapshot download fails on testnet with incremental snapshots enabled
### Problem

v1.10 nodes are asserting during bootstrap when connecting to testnet. This is happening when querying the cluster for snapshot info to download. v1.10 also has incremental snapshots enabled by default, so its going through that code path.

For original context, see Discord here:
https://discord.com/channels/428295358100013066/670512312339398668/950418560201687081

I've reproduced this issue, but only on testnet. Probably because testnet is the only cluster where nodes that are serving snapshots have Incremental Snapshots enabled.

### Work-around

Disable incremental snapshots. On v1.10 and newer, pass `--no-incremental-snapshots` to `solana-validator`. On v1.9 and older _remove_ `--incremental-snapshots` from `solana-validator` (if it exists).

### Proposed Solution

Investigate and fix.

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

When incremental snapshots are enabled, bootstrapping may fail when getting the golden snapshot hashes from the known validators. This triggers an erroneous assert.

#### Summary of Changes

When getting the golden snapshot hashes, now ensure:
* A node's base snapshot hash exists in its full snapshot hashes
* If the golden snapshot hashes already has an entry for the full snapshot hash, do not reinitialize it's incremental snapshot hashes set back to zero...

Additionally:
* Refactor code to be testable
* Added test

Fixes #23509

Note: I'm not sure how helpful the diff will be here... It may be easiest/best to view the file and review the contents of `get_golden_snapshot_hashes_from_known_validators()` and `get_golden_snapshot_hashes()`.

### CODE REVIEW

File: validator/src/bootstrap.rs [hunk 1]
```diff
@@ -1125,6 +1129,10 @@ mod with_incremental_snapshots {
         peer_snapshot_hashes
     }
 
+    /// Map full snapshot hashes to a set of incremental snapshot hashes.  Each full snapshot hash
+    /// is treated as the base for its set of incremental snapshot hashes.
+    type GoldenSnapshotHashes = HashMap<(Slot, Hash), HashSet<(Slot, Hash)>>;
```
Comment (mvines) [inline validator/src/bootstrap.rs:1134]: I don't love the introduction of the new term, "golden snapshot".  What makes it golden?  These are local snapshots?

**Comment by mvines** [comment]
This affects v1.9 as well right?

**Comment by brooksprumo** [comment]
> This affects v1.9 as well right?

Yes. I'm assuming I would backport as well. Is that right?

File: validator/src/bootstrap.rs (hunk 1 above)
Comment (mvines) [reply validator/src/bootstrap.rs:1134]: known snapshot hashes?  We specify `--known-validators`, not `--golden-validators` after all.  I'll look at the full PR now, sorry last night my jet lagged brain was only good for some low-ROI bike shedding :)

File: validator/src/bootstrap.rs [hunk 2]
```diff
@@ -1135,71 +1143,158 @@ mod with_incremental_snapshots {
...
+            if let Some((base_snapshot_hash, incremental_snapshot_hashes)) =
+                get_incremental_snapshot_hashes_for_node(node)
+            {
+                // Incremental snapshots must be based off a valid full snapshot.  Ensure the node
+                // has a full snapshot hash that matches its base snapshot hash.
+                if !full_snapshot_hashes.contains(&base_snapshot_hash) {
+                    debug!(
+                        "Ignoring all incremental snapshot hashes from node {} since its base snapshot hash does not match any of its full snapshot hashes. base snapshot hash: {:?}, full snapshot hashes: {:?}",
+                        node,
+                        base_snapshot_hash ,
```
Comment (mvines) [inline validator/src/bootstrap.rs:1250]: `cargo fmt` fail 💔 
```suggestion
                        base_snapshot_hash,
```

File: validator/src/bootstrap.rs [hunk 3]
```diff
@@ -1135,71 +1143,158 @@ mod with_incremental_snapshots {
...
+                    golden_snapshot_hashes.keys(),
+                ) {
+                    // Insert a new full snapshot hash into the golden snapshot hashes IFF an entry
+                    // doesn't already exist.  This is to ensure we don't overwrite existing
+                    // incremental snapshot hashes that may be present for this full snapshot hash.
+                    golden_snapshot_hashes
+                        .entry(*full_snapshot_hash)
+                        .or_default();
+                } else {
+                    debug!(
```
Comment (mvines) [inline validator/src/bootstrap.rs:1230]: I feel like this could be a `warn!()` actually, as it probably indicates one of your known validators is broken.  The node operator probably wants to know about this.

File: validator/src/bootstrap.rs [hunk 4]
```diff
@@ -1135,71 +1143,158 @@ mod with_incremental_snapshots {
...
+                    // NOTE: Nodes should not produce snapshots at the same slot with _different_
+                    // hashes.  So if it happens, keep the first and ignore the rest.
+                    for incremental_snapshot_hash in &incremental_snapshot_hashes {
+                        if !is_any_same_slot_and_different_hash(
+                            incremental_snapshot_hash,
+                            golden_incremental_snapshot_hashes.iter(),
+                        ) {
+                            golden_incremental_snapshot_hashes.insert(*incremental_snapshot_hash);
+                        } else {
+                            debug!(
```
Comment (mvines) [inline validator/src/bootstrap.rs:1270]: Maybe `warn!()` here too?

**Review by mvines — COMMENTED** [review]
logic looks good!

File: validator/src/bootstrap.rs (hunk 3 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs:1230]: Ok, will do.

Comment (brooksprumo) [reply validator/src/bootstrap.rs]: Done!

File: validator/src/bootstrap.rs (hunk 2 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs]: Done!

File: validator/src/bootstrap.rs (hunk 1 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs]: Done! Renamed "golden" back to "known".

**Review by mvines — APPROVED** [review]
