### PR TITLE
Calculate distance between u64 without overflow

### LINKED ISSUE #9590: ContactInfo wallclock integer overflow
```
thread 'solana-broadcaster-transmit' panicked at 'attempt to subtract with overflow', core/src/broadcast_stage.rs:419:12                                                                                                                                                                                                                                                                                                                                                                        
   0: backtrace::backtrace::libunwind::trace                                                                                                                                                                                                                                                                                                                                                                                                                                                    
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88                                                                                                                                                                                                                                                                                                                                                                                  
   1: backtrace::backtrace::trace_unsynchronized                                                                                                                                                                                                                                                                                                                                                                                                                                                
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66                                                                                                                                                                                                                                                                                                                                                                                        
   2: std::sys_common::backtrace::_print_fmt                                                                                                                                                                                                                                                                                                                                                                                                                                                    
             at src/libstd/sys_common/backtrace.rs:77                                                                                                                                                                                                                                                                                                                                                                                                                                           
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt                                                                                                                                                                                                                                                                                                                                                                                                         
             at src/libstd/sys_common/backtrace.rs:59                                                                                                                                                                                                                                                                                                                                                                                                                                           
   4: core::fmt::write                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
             at src/libcore/fmt/mod.rs:1052                                                                                                                                                                                                                                                                                                                                                                                                                                                     
   5: std::io::Write::write_fmt                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
             at src/libstd/io/mod.rs:1426                                                                                                                                                                                                                                                                                                                                                                                                                                                       
   6: std::sys_common::backtrace::_print                                                                                                                                                                                                                                                                                                                                                                                                                                                        
             at src/libstd/sys_common/backtrace.rs:62                                                                                                                                                                                                                                                                                                                                                                                                                                           
   7: std::sys_common::backtrace::print                                                                                                                                                                                                                                                                                                                                                                                                                                                         
             at src/libstd/sys_common/backtrace.rs:49                                                                                                                                                                                                                                                                                                                                                                                                                                           
   8: std::panicking::default_hook::{{closure}}                                                                                                                                                                                                                                                                                                                                                                                                                                                 
             at src/libstd/panicking.rs:204                                                                                                                                                                                                                                                                                                                                                                                                                                                     
   9: std::panicking::default_hook                                                                                                                                                                                                                                                                                                                                                                                                                                                              
             at src/libstd/panicking.rs:224                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call                                                                                                                                                                                                                                                                                                                                                                                                                                
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1029                                                                                                                                                                                                                                                                                                                                                                                                      
  11: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}                                                                                                                                                                                                                                                                                                                                                                                                                         
             at metrics/src/metrics.rs:426                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  12: std::panicking::rust_panic_with_hook                                                                                                                                                                                                                                                                                                                                                                                                                                                      
             at src/libstd/panicking.rs:476                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  13: rust_begin_unwind                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
             at src/libstd/panicking.rs:380                                                                                                                                                                                                                                  
  14: core::panicking::panic_fmt                                                                                                                                                                                                                                             
             at src/libcore/panicking.rs:85                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  15: core::panicking::panic                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
             at src/libcore/panicking.rs:52                                                                                                                                                                                                                                 
  16: solana_core::broadcast_stage::num_live_peers::{{closure}}                                                                                                                                                                                                              
             at core/src/broadcast_stage.rs:419                                                                                                                                                                                                                                                                                                                                                                                                                                                
  17: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}                                                                                                                                                                                                                                                                                                                                                                                                                      
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:652                                                                                                                                                                      
  18: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}                                                                                                                                                                                                          
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1900                                                                                                                                                                                                                                                                                                                                                                                       
  19: core::iter::traits::iterator::Iterator::try_fold                                                                                                                                                                                                                                                                                                                                                                                                                                         
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1776                                                                                                                                                                     
  20: core::iter::traits::iterator::Iterator::fold                                                                                                                                                                                                                           
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1903                                                                                                                                                                                                                                                                                                                                                                                       
  21: core::iter::traits::iterator::Iterator::for_each                                                                                                                                                                                                                                                                                                                                                                                                                                         
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:655                                                                                                                                                                      
  22: solana_core::broadcast_stage::num_live_peers                                                                                                                                                                                                                           
             at core/src/broadcast_stage.rs:417                                                                                                                                                                                                                                                                                                                                                                                                                                                
  23: solana_core::broadcast_stage::broadcast_shreds                                                                                                                                                                                                                                                                                                                                                                                                                                           
             at core/src/broadcast_stage.rs:406                                                                                                                                                                                                                              
  24: solana_core::broadcast_stage::standard_broadcast_run::StandardBroadcastRun::broadcast                                                                                                                                                                                  
             at core/src/broadcast_stage/standard_broadcast_run.rs:305                                                                                                                                                                                                                                                                                                                                                                                                                         
  25: <solana_core::broadcast_stage::standard_broadcast_run::StandardBroadcastRun as solana_core::broadcast_stage::BroadcastRun>::transmit                                                                                                                                                                                                                                                                                                                                                     
             at core/src/broadcast_stage/standard_broadcast_run.rs:381                                                                                                                                                                                                       
  26: solana_core::broadcast_stage::BroadcastStage::new::{{closure}}                                                                                                                                                                                                         
             at core/src/broadcast_stage.rs:244                                                                                                                                                                                                                                                                                                                                                                                                                                                
```

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

u64 unchecked subtract 

#### Summary of Changes

calculate a numerical distance instead

Fixes #9590

### CODE REVIEW

File: core/src/broadcast_stage.rs [hunk 1]
```diff
@@ -412,11 +412,19 @@ pub fn broadcast_shreds(
     Ok(())
 }
 
+fn distance(a: u64, b: u64) -> u64 {
```
Comment (carllin) [inline core/src/broadcast_stage.rs:415]: Can we call this `abs` for absolute value? (same name as std::num crate)
