### PR TITLE
clap-utils: Forbid multiple values for `--signer`

### LINKED ISSUE #34453: Solana CLI Offline Transactions not working
#### Problem

Hello,

I tried a few things with the Solana CLI like, creating a wallet, delegate, transfer and so on and it works fine so far, but what is clearly not working are offline transactions.

This is the verion that I'm running.

```
$ solana --version
solana-cli 1.16.23 (src:85e3058b; feat:4033350765, client:SolanaLabs)
```

The first thing I did was create a paper wallet as described [here](https://docs.solana.com/wallet-guide/paper-wallet).

First of all what is [`recipient-keypair.json`](https://docs.solana.com/offline-signing#example-offline-signing-a-payment)? Why would I need to specify a keypair (secret and public key if I understand correctly) of the recipient, why not just the public key? In my example I specify the public key instead, because I do not have the private key of the recipient for example if it is an exchange.

Then when I follow the [docs which describe offline transactions](https://docs.solana.com/offline-signing#example-offline-signing-a-payment) like this

```
solana transfer --sign-only --blockhash <blockhash> <recipient-public-key> 0.01
```

then I get the following error.

```
Error: Dynamic program error: No default signer found, run "solana-keygen new -o /home/gernot/.config/solana/id.json" to create a new one
```

Ok, I guess I need to specify `--from` and `--fee-payer` right, because I'm using a paperwallet, right? This is what I do now.

```
solana transfer --from prompt:// --fee-payer  prompt:// --sign-only --blockhash <blockhash> <recipient-public-key> 0.01
```

then I get an output and no error and an output

```
Blockhash: <some-hash>
Signers (Pubkey=Signature):
 <some-string>
```

Then when I try to broadcast the transaction the problem arises. When I do the following as described in the [Submitting Offline Signed Transactions to the Network docs](https://docs.solana.com/offline-signing#submitting-offline-signed-transactions-to-the-network), but instead of `recipient-keypair.json` I again specify the public key, because of the same reason mentioned above

```
solana transfer --blockhash <blockhash> --signer <signers-output> <recipient-public-key-again> 0.01
```

I get

```
error: The following required arguments were not provided:
    <RECIPIENT_ADDRESS>
    <AMOUNT>

USAGE:
    solana transfer <RECIPIENT_ADDRESS> <AMOUNT> --blockhash <BLOCKHASH> --config <FILEPATH> --signer <PUBKEY=SIGNATURE>...

For more information try --help
```

So the docs are wrong here.

Ok, so I follow what's mentioned in the error message in contrast to the docs and do the following

```
solana transfer <recipient-public-key-again> 0.01 --blockhash <blockhash> --signer <signers-output>
```

Then I get

```
Error: Dynamic program error: No default signer found, run "solana-keygen new -o /home/gernot/.config/solana/id.json" to create a new one
```

And this is most likely a **bug**. There is no reason why it should ask for a signer when you want to just broadcast a signed transaction . The whole point of an offline transaction is that you do not need to sign anything on the online device and expose your secret to an online device. I assume this bug is in all [Commands Supporting Offline Signing](https://docs.solana.com/offline-signing#commands-supporting-offline-signing).

Furthermore why do you need to specify a recipient and the amount again when broadcasting the already signed transaction  which already includes the amount and recipient? I did the same thing at Ethereum and there you do not need to specify the amount and recipient again when broadcasting the signed transaction since it is already contained in the signed transaction. At Ethereum you just broadcast the signed transaction  string, that's it. I guess the same thing can also be said about the block-hash, I don't know? Can you please explain?

And why is in the syntax not a requirement for a nonce when signing the offline transaction  like I did above with `--sign-only`? On an offline PC the CLI cannot obtain the nonce by itself, but I do not get an error when I sign offline. What does it actually input as a nonce when I'm offline? Solana transactions also require a nonce right?

#### Proposed Solution

- The docu needs to be fixed like mentioned in the problem description
- The bug needs to be fixed which does not allow you to broadcast
- Clearification about the broadcast syntax especially about the recipient and amount requirements
- Clearification about missing nonce requirement when signing the offline transaction on an offline device

Thank you very much

### PR DESCRIPTION
**Pull request by joncinque**
#### Problem

The `--signer` arg doesn't exactly work as expected because it allows for multiple values. This means clap allows for someone to specify: `--signer <PUBKEY>=<SIG> <PUBKEY>=<SIG>`

This can be useful in some situations, but it's inconsistent with the documentation.

For example, https://docs.solana.com/offline-signing#submitting-offline-signed-transactions-to-the-network mentions to specify "--signer BASE58_PUBKEY=BASE58_SIGNATURE, one for each offline signer.", and the examples use multiple occurrences of `--signer`.

Also, the example command of:

```
solana@online$ solana transfer --blockhash 5Tx8F3jgSHx21CbtjwmdaKPLM5tWmreWAnPrbqHomSJF \
    --signer FhtzLVsmcV7S5XqGD79ErgoseCLhZYmEZnz9kQg1Rp7j=4vC38p4bz7XyiXrk6HtaooUqwxTWKocf45cstASGtmrD398biNJnmTcUCVEojE7wVQvgdYbjHJqRFZPpzfCQpmUN
    recipient-keypair.json 1
```

Does not work currently because `--signer` tries to parse multiple values. This means it tries to also parse `recipient-keypair.json` and `1`. Practically, this means that `--signer` must always come last in the command, which contradicts the docs.

Side note: for your reading pleasure here are the docs for `multiple_values` https://docs.rs/clap/3.2.23/clap/builder/struct.Arg.html#method.multiple_values in clap v3 and for `multiple` in clap v2 https://docs.rs/clap/2.34.0/clap/struct.Arg.html#method.multiple

#### Summary of Changes

Cap the number of *values* to 1 (clap v2) and do not allow multiple values per occurrence (clap v3). I'm not sure if this breaks any existing users, so I've put in a changelog entry.

Fixes #34453

### CODE REVIEW

File: clap-v3-utils/src/offline.rs [hunk 1]
```diff
@@ -53,7 +53,7 @@ fn signer_arg<'a>() -> Arg<'a> {
         .value_parser(value_parser!(PubkeySignature))
         .requires(BLOCKHASH_ARG.name)
         .multiple_occurrences(true)
-        .multiple_values(true)
+        .multiple_values(false)
```
Comment (t-nelson) [inline clap-v3-utils/src/offline.rs:56]: i think we can just delete the property here? single value is default iirc

**Review by t-nelson — COMMENTED** [review]
nice catch!

File: clap-v3-utils/src/offline.rs (hunk 1 above)
Comment (joncinque) [reply clap-v3-utils/src/offline.rs:56]: It's not clear from the documentation nor the code that it defaults to single value, so I wrote up a test to make sure, and you're right, it defaults to one value.

Since it's not clear just from reading the code / docs, I'd prefer to leave it as is for clarity, but I don't feel too strongly about it.

Comment (t-nelson) [reply clap-v3-utils/src/offline.rs:56]: sg :shipit:

**Review by t-nelson — APPROVED** [review]
oh thought i approved with the other review... now :shipit:

**Comment by joncinque** [comment]
Sorry, had a merge conflict to resolve, can you approve again please?

**Review by t-nelson — APPROVED** [review]

**Comment by joncinque** [comment]
Sorry, can I get one last approval here? I got scooped on the changelog again

**Review by t-nelson — APPROVED** [review]
