### PR TITLE
Fix test_bank_storage

### LINKED ISSUE #3236: Test of storage mining logic has commented assertion
#### Problem

Storage program is returning an error when it should not and an assert is commented in the test_bank_storage test.

#### Proposed Solution

Uncomment this assertion, debug why and fix it.

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

Storage program is returning an error when it should not and an assert is commented in the test_bank_storage test.

#### Summary of Changes

Fixed incorrect test logic

Fixes #3236

### CODE REVIEW

File: programs/storage/tests/storage.rs [hunk 1]
```diff
@@ -85,15 +85,15 @@ fn test_bank_storage() {
 
     // TODO: This triggers a ProgramError(0, InvalidArgument). Why?
```
Comment (garious) [inline programs/storage/tests/storage.rs]: Is this comment relevant after this fix?
