### PR TITLE
Snapshot pipefitting through the validator cli

### LINKED ISSUE #5599: Snapshots not working end-to-end
These commands should cause the new validator to pick up from the latest edge testnet snapshot:
```
$ rm -rf ledger/ 
$ solana-validator -l ledger -n edge.testnet.solana.com:8001
```
but instead the validator starts from genesis.

### PR DESCRIPTION
**Pull request by mvines**
Various minor fixes needed to get snapshots working from `solana-validator`

Fixes #5599

### CODE REVIEW

File: validator/src/main.rs [hunk 1]
```diff
@@ -30,7 +33,19 @@ fn port_range_validator(port_range: String) -> Result<(), String> {
     }
 }
 
-fn download_archive(
+static TRUCK: Emoji = Emoji("🚚 ", "");
+static SPARKLE: Emoji = Emoji("✨ ", "");
```
Comment (carllin) [inline validator/src/main.rs]: :O

Comment (mvines) [reply validator/src/main.rs]: ✨ ✨ ✨ ✨
