### PR TITLE
Fix solana CLI deploy

### LINKED ISSUE #11444: Deploying large programs using the CLI is slow and unreliable
#### Problem

When trying to deploy large programs (>300kb) using the CLI, only the first ~600chunks are confirmed. The rest of the transaction need to be resubmitted.

Still if the CLI thinks all chunks have been confirmed and tries to finalize the program account the transaction is never confirmed.

If I modify `DATA_CHUNK_SIZE` to use ~900byte chunks and fewer chunks need to be sent, the same program loads very fast and reliable.

Example:
[asciicast](https://asciinema.org/a/pYa0yaqp6Fb0VIKYAr8F7iKUH)

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
Deploying large programs using the solana cli is flaky. Frequently, the process will stall out at `Finalizing transaction ...` for the very last transaction (`loader_instruction::finalize`) and ultimately return an error after many seconds.

This is because `process_deploy` requests just one blockhash before building any of the transactions. The `loader_instruction::write` transactions may receive a refreshed blockhash inside `send_and_confirm_transactions_with_spinner()` if they fail to confirm, but `loader_instruction::finalize` does not. As a result, the blockhash sometimes expires before the finalize transaction is submitted/processed, thus that transaction is never confirmed.

#### Summary of Changes
- Refresh the blockhash before `loader_instruction::finalize`; also refresh the blockhash before the `loader_instruction::write` transactions are signed to increase the chances of their success first time.
- Also, a minor refactor of confirmation checks inside `send_and_confirm_transactions_with_spinner` using current methods and saving an RPC call per transaction. (All the `get_signature_status` requests were essentially a waste because they require max commitment. As such, they always return None, even when the transaction meets the threshold of > 1 confirmation.

Fixes #11444

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
I just used this to deploy spl-token-v1.0 to devnet and it worked, even though it took a solid minute just to send the transactions (RPC to devnet seems really loggy, for some reason).

File: cli/src/cli.rs [hunk 1]
```diff
@@ -1324,11 +1315,28 @@ fn process_deploy(
         CliError::DynamicProgramError("Program account allocation failed".to_string())
     })?;
 
+    let (blockhash, _, _) = rpc_client
+        .get_recent_blockhash_with_commitment(config.commitment)?
+        .value;
+
+    let mut write_transactions = vec![];
+    for message in write_messages.into_iter() {
+        let mut tx = Transaction::new_unsigned(message.clone());
```
Comment (t-nelson) [inline cli/src/cli.rs:1324]: NIT: You shouldn't need the `clone()` here since you're `into_iter()`ing, right?
