### PR TITLE
Get slot on bitvec needs a guard

### LINKED ISSUE #9591: epoch slots BitVec out of bounds
#### Problem

```
thread 'solana-repair-service' panicked at 'BitVec::get_bit: out of bounds', <::std::macros::panic macros>:2:4
stack backtrace:                                                                                                                                   
   0: backtrace::backtrace::libunwind::trace                                                                                                       
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88                                     
   1: backtrace::backtrace::trace_unsynchronized                                                                                                   
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66                                           
   2: std::sys_common::backtrace::_print_fmt                                                                                                       
             at src/libstd/sys_common/backtrace.rs:77                                                                                              
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt                                                            
             at src/libstd/sys_common/backtrace.rs:59                                                      
   4: core::fmt::write                                                                                                                             
             at src/libcore/fmt/mod.rs:1052                                                                                                        
   5: std::io::Write::write_fmt                                                                                                                    
             at src/libstd/io/mod.rs:1426                                                                                                          
   6: std::sys_common::backtrace::_print                                                                                                           
             at src/libstd/sys_common/backtrace.rs:62                                                                                              
   7: std::sys_common::backtrace::print                                                                    
             at src/libstd/sys_common/backtrace.rs:49                                                                                              
   8: std::panicking::default_hook::{{closure}}                                                                                                    
             at src/libstd/panicking.rs:204                                                                                                        
   9: std::panicking::default_hook                                                                                                                 
             at src/libstd/panicking.rs:224                                                                                                        
  10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}                                                                            
  11: std::panicking::rust_panic_with_hook                                                                                                         
             at src/libstd/panicking.rs:476                                                                
  12: std::panicking::begin_panic                                                                                                                                                                                                                                                                                                                                                                                                                                                                 13: solana_core::epoch_slots::Uncompressed::to_slots                                                                                                                                                                                                                                                                                                                                                                                                                                         
  14: solana_core::epoch_slots::CompressedSlots::to_slots                                                                                                                                      
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter                                                                               
  16: solana_core::cluster_slots::ClusterSlots::update                                                                                                                                                                            
  17: solana_core::repair_service::RepairService::run                                                                                       
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.    
```

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

Get slot on bitvec could panic

#### Summary of Changes

guard the call

Fixes #9591

tag: @mvines

### CODE REVIEW

File: core/src/epoch_slots.rs [hunk 1]
```diff
@@ -84,6 +84,9 @@ impl Uncompressed {
             (min_slot - self.first_slot) as usize
         };
         for i in start..self.num {
+            if i >= self.slots.len() as usize {
```
Comment (carllin) [inline core/src/epoch_slots.rs:87]: seems like this: https://github.com/solana-labs/solana/blob/master/core/src/epoch_slots.rs#L105, should guard this call, are we missing an edge case somewhere?

Comment (sakridge) [reply core/src/epoch_slots.rs:87]: That probably doesn't get called if we deserialize the object from the network right?

Comment (carllin) [reply core/src/epoch_slots.rs:87]: @sakridge yeah, somebody could give a bad length, but was that the case here? (was it malicious or just an edge case we're missing)?

Comment (carllin) [reply core/src/epoch_slots.rs:87]: Also side note, should this be https://github.com/solana-labs/solana/blob/master/core/src/epoch_slots.rs#L101

`self.slots.len()`, not `self.slots.capacity()`?

Comment (aeyakovenko) [reply core/src/epoch_slots.rs:87]: I think capacity is right.  Otherwise it should set the bit if it can.

Comment (carllin) [reply core/src/epoch_slots.rs:87]: https://github.com/solana-labs/solana/blob/master/core/src/epoch_slots.rs#L76, hmm but just like a `Vec`,  `len -1 ` is the maximal element you can access without an out of range exception. The `capacity` can be greater than the len(), but doesn't determine the range?

https://docs.rs/bv/0.10.0/bv/struct.BitVec.html#method.capacity
https://docs.rs/bv/0.10.0/bv/struct.BitVec.html#method.len

Comment (aeyakovenko) [reply core/src/epoch_slots.rs:87]: @carllin len is correct in this case, because even if capacity is higher none of those values are 1.

Comment (leoluk) [reply core/src/epoch_slots.rs:87]: > @sakridge yeah, somebody could give a bad length, but was that the case here? (was it malicious or just an edge case we're missing)?

Malicious

Comment (carllin) [reply core/src/epoch_slots.rs:87]: @aeyakovenko yea, but calling `set` on an index `>= len` should panic with out of bounds. It's interesting...so it works right now because `len == capacity` always when you call `new_fill` with a size that is a multiple of 8, which is what we're doing in `Uncompressed::new()`
