### PR TITLE
fix(web3.js): VoteAccount.fromAccountData() throws range error

### LINKED ISSUE #20786: web3.js VoteAccount.fromAccountData() throws RangeError on any vote account data
#### Problem
fromAccountData() seems to be broken. Tried several vote accounts with the same result. Script is for mainnet, but on the testnet it fails in the exact same way. Tried @solana/web3.js releases 1.29.1 and 1.29.2

```// any base58 pubkey of vote account
const pubkey = process.argv[2] || '644K33yWfSzc32VvY5fRUfUqphw8LTaLQntCkyEpJ8h7';
const sol = require('@solana/web3.js');
(async () => {
    const conn = new sol.Connection(sol.clusterApiUrl('mainnet-beta'), 'confirmed');
    const accInfo = await conn.getAccountInfo(new sol.PublicKey(pubkey));
    console.log(accInfo);
    console.log('data length:',accInfo.data.length);
    const va = sol.VoteAccount.fromAccountData(accInfo.data);
})().catch(e => console.log(e));
```
Error: 
```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3727. Received 3730
    at boundsError (internal/buffer.js:49:9)
    at Buffer.readUInt32LE (internal/buffer.js:181:5)
    at NearUInt64.decode (/opt/test/node_modules/@solana/buffer-layout/lib/Layout.js:774:27)
    at Structure.decode (/opt/test/node_modules/@solana/buffer-layout/lib/Layout.js:1273:40)
    at Sequence.decode (/opt/test/node_modules/@solana/buffer-layout/lib/Layout.js:1126:40)
    at Structure.decode (/opt/test/node_modules/@solana/buffer-layout/lib/Layout.js:1273:40)
    at Function.fromAccountData (/opt/test/node_modules/@solana/web3.js/lib/index.cjs.js:6869:34)
    at /opt/test/fromData.js:8:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### PR DESCRIPTION
**Pull request by cogoo**
- fix(vote-account): rangeError [ERR_OUT_OF_RANGE] error
- docs(vote account): update reference to match new payload

#### Problem

VoteAccount.fromAccountData() throws RangeError on any vote account data

#### Summary of Changes

- Update bufferLayout
- Update docs to match new payload

The web3 buffer layout is out-of-date with the current `VoteState` implementation. The buffer layout is updated to match the structure in https://github.com/solana-labs/solana/blob/master/account-decoder/src/parse_vote.rs

Fixes #20786

### CODE REVIEW

**Comment by cogoo** [comment]
@t-nelson I've seem to hit a blocker (potentially this is the expected output), but I cannot seem to deserialize these properties:

```js
 priorVoters: [],
 epochCredits: [],
 lastTimestamp: { slot: 0, timestamp: 0 }
```

They're are always empty. I'm not sure if this is by design or there's some issue with the layout I'm using to deserialize.

**Comment by cogoo** [comment]
> @t-nelson I've seem to hit a blocker (potentially this is the expected output), but I cannot seem to deserialize these properties:
> 
> ```js
>  priorVoters: [],
>  epochCredits: [],
>  lastTimestamp: { slot: 0, timestamp: 0 }
> ```
> 
> They're are always empty. I'm not sure if this is by design or there's some issue with the layout I'm using to deserialize.

resolved!

File: web3.js/src/vote-account.ts [hunk 1]
```diff
@@ -57,50 +100,51 @@ const VoteAccountLayout = BufferLayout.struct([
...
+    this.authorizedWithdrawer = args.authorizedWithdrawer;
     this.commission = args.commission;
-    this.votes = args.votes;
     this.rootSlot = args.rootSlot;
-    this.epoch = args.epoch;
-    this.credits = args.credits;
-    this.lastEpochCredits = args.lastEpochCredits;
+    this.votes = args.votes;
+    this.authorizedVoters = args.authorizedVoters;
+    this.priorVoters = args.priorVoters;
```
Comment (cogoo) [inline web3.js/src/vote-account.ts:145]: I suppose we could check if the `priorVoters.isEmpty` is true then send an empty buffer, rather than an array filled with `0`s

File: web3.js/src/vote-account.ts [hunk 2]
```diff
@@ -121,15 +166,36 @@ export class VoteAccount {
...
-      authorizedWithdrawerPubkey: new PublicKey(va.authorizedWithdrawerPubkey),
+      authorizedWithdrawer: new PublicKey(va.authorizedWithdrawer),
       commission: va.commission,
       votes: va.votes,
       rootSlot,
-      epoch: va.epoch,
-      credits: va.credits,
-      lastEpochCredits: va.lastEpochCredits,
+      authorizedVoters: va.authorizedVoters.map(parseAuthorizedVoter),
+      priorVoters: {
```
Comment (cogoo) [inline web3.js/src/vote-account.ts:174]: I suppose we could check if the `priorVoters.isEmpty` is true then send an empty buffer, rather than an array filled with `0`s

**Comment by cogoo** [comment]
🤔  would be nice to add some tests for this also, will possibly add some this week 🙏🏾

**Comment by t-nelson** [comment]
> @t-nelson I've seem to hit a blocker (potentially this is the expected output), but I cannot seem to deserialize these properties:
> 
> ```js
>  priorVoters: [],
>  epochCredits: [],
>  lastTimestamp: { slot: 0, timestamp: 0 }
> ```
> 
> They're are always empty. I'm not sure if this is by design or there's some issue with the layout I'm using to deserialize.

What vote account (and cluster) are you using to test?

**Comment by cogoo** [comment]
> > @t-nelson I've seem to hit a blocker (potentially this is the expected output), but I cannot seem to deserialize these properties:
> > ```js
> >  priorVoters: [],
> >  epochCredits: [],
> >  lastTimestamp: { slot: 0, timestamp: 0 }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > They're are always empty. I'm not sure if this is by design or there's some issue with the layout I'm using to deserialize.
> 
> What vote account (and cluster) are you using to test?

I resolved these issues. I'm using this script to test: connected to `mainnet`

https://github.com/solana-labs/solana/blob/master/docs/src/developing/clients/javascript-reference.md#voteaccount

**Comment by cogoo** [comment]
@t-nelson hey, just giving this a lil bump

File: web3.js/src/vote-account.ts [hunk 3]
```diff
@@ -17,21 +17,42 @@ export type Lockout = {
 /**
  * History of how many credits earned by the end of each epoch
  */
-export type EpochCredits = {
+export type EpochCredit = {
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:20]: please revert this so that remain consistent with the types in the rust sdk

File: web3.js/src/vote-account.ts [hunk 4]
```diff
@@ -17,21 +17,42 @@ export type Lockout = {
...
   credits: number;
   prevCredits: number;
 };
 
+export type AuthorizedVoter = {
+  epoch: number;
+  authorizedVoter: PublicKey;
+};
+
+export type PriorVoters = {
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:31]: I don't think we need to expose this type, could you instead transform the circ buf into an array which starts at `idx`?

File: web3.js/src/vote-account.ts [hunk 5]
```diff
@@ -57,50 +100,51 @@ const VoteAccountLayout = BufferLayout.struct([
...
   commission: number;
-  votes: Array<Lockout>;
   rootSlot: number | null;
-  epoch: number;
-  credits: number;
-  lastEpochCredits: number;
-  epochCredits: Array<EpochCredits>;
+  votes: Lockout[];
+  authorizedVoters: AuthorizedVoter[];
+  priorVoters: PriorVoters;
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:131]: How about we change this to a list of `PriorVoter`?

File: web3.js/src/vote-account.ts [hunk 6]
```diff
@@ -17,21 +17,42 @@ export type Lockout = {
...
+  isEmpty: boolean;
+};
+
+export type Buf = {
+  authorizedPubkey: PublicKey;
+  epochOfLastAuthorizedSwitch: number;
+  targetEpoch: number;
+};
+
+export type Timestamp = {
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:43]: Can you please rename this to `BlockTimestamp` to match the rust sdk?

File: web3.js/src/vote-account.ts [hunk 7]
```diff
@@ -17,21 +17,42 @@ export type Lockout = {
...
+  authorizedVoter: PublicKey;
+};
+
+export type PriorVoters = {
+  buf: Buf;
+  idx: number;
+  isEmpty: boolean;
+};
+
+export type Buf = {
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:37]: Please rename to `PriorVoter`

File: web3.js/src/vote-account.ts (hunk 2 above)
Comment (jstarry) [reply web3.js/src/vote-account.ts:174]: Sounds good to me

File: web3.js/src/vote-account.ts (hunk 4 above)
Comment (cogoo) [reply web3.js/src/vote-account.ts:31]: Im not sure I fully understand what you mean by "an array which starts at idx"

Could you explain that please, thanks!

Comment (jstarry) [reply web3.js/src/vote-account.ts:31]: Yeah I just mean that you could take the circ buffer into an array. The circ buffer starts at the element with index `idx` so that would be the first element of the array.

Comment (cogoo) [reply web3.js/src/vote-account.ts:31]: Awesome! that makes sense.

Thanks for taking the time to look at this. Should make the amends soon!

File: web3.js/src/vote-account.ts [hunk 8]
```diff
@@ -121,15 +160,33 @@ export class VoteAccount {
...
-      authorizedWithdrawerPubkey: new PublicKey(va.authorizedWithdrawerPubkey),
+      authorizedWithdrawer: new PublicKey(va.authorizedWithdrawer),
       commission: va.commission,
       votes: va.votes,
       rootSlot,
-      epoch: va.epoch,
-      credits: va.credits,
-      lastEpochCredits: va.lastEpochCredits,
+      authorizedVoters: va.authorizedVoters.map(parseAuthorizedVoter),
+      priorVoters: va.priorVoters.isEmpty ? [] : va.priorVoters.buf.map(parsePriorVoters),
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:168]: doesn't this need to start at `idx`?

Comment (cogoo) [reply web3.js/src/vote-account.ts]: yup, you're right, missed that.

updated!

File: web3.js/src/vote-account.ts [hunk 9]
```diff
@@ -165,7 +165,9 @@ export class VoteAccount {
       votes: va.votes,
       rootSlot,
       authorizedVoters: va.authorizedVoters.map(parseAuthorizedVoter),
-      priorVoters: va.priorVoters.isEmpty ? [] : va.priorVoters.buf.map(parsePriorVoters),
+      priorVoters: va.priorVoters.isEmpty
+        ? []
+        : va.priorVoters.buf.slice(va.priorVoters.idx).map(parsePriorVoters),
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:170]: you also have to append the slice before `idx` to the end

Comment (cogoo) [reply web3.js/src/vote-account.ts:170]: oh, to make sure I understand, you mean something along the lines of;

```js
const buf = va.priorVoters.buf;
const arrayToAppend = buf.slice(0, idx - 1);
const parsedVoters = buf.slice(idx).map(parsePriorVoters);
const priorVoters = [...parsedVoters, ...arrayToAppend];
```

Comment (jstarry) [reply web3.js/src/vote-account.ts:170]: Yes, exactly!

File: web3.js/src/vote-account.ts [hunk 10]
```diff
@@ -121,15 +160,49 @@ export class VoteAccount {
...
+}: {
+  buf: PriorVoter[];
+  idx: number;
+  isEmpty: boolean;
+}): PriorVoter[] {
+  if (isEmpty) {
+    return [];
+  }
+
+  return [...buf.slice(idx).map(parsePriorVoters), ...buf.slice(0, idx - 1)];
```
Comment (jstarry) [inline web3.js/src/vote-account.ts:207]: Sorry, I misled you. This should be:
```suggestion
  return [...buf.slice(idx + 1).map(parsePriorVoters), ...buf.slice(0, idx)];
```

Comment (jstarry) [reply web3.js/src/vote-account.ts:207]: This will ensure that the last "prior voter" is always the current one

Comment (cogoo) [reply web3.js/src/vote-account.ts:207]: Yup, this makes sense

**Review by jstarry — APPROVED** [review]
thanks for your patience on this!

**Comment by cogoo** [comment]
> thanks for your patience on this!

Awesome, it was a pleasure!
