### PR TITLE
Fix SlotMeta connected tracking

### LINKED ISSUE #27820: SlotMeta is_connected field isn't updated as expected
#### Problem

The `SlotMeta::is_connected` field was originally designed to indicate whether a given slot `n` had a full replayable sequence back to genesis without any holes. It follows that all slots in this sequence must be full in order to be replayable. In a more compact form, we're saying
```rust
is_connected(n) = is_connected(parent_of_n) && is_full(n)
```
where `n` is the direct child of `parent_of_n`.

What this design failed to account for is that validators might start from a snapshot at some slot `s` > 0. This is a perfectly valid way for a validator to bootstrap (recall that by definition, `s` is a root); however, that validator doesn't / didn't have a path back to genesis. As such, `is_connected` will be false for all slots that this validator processes. This has a potential ripple effect as the `is_connected` field is currently being used to signal to `ReplayStage` when there is more work to do. See https://github.com/solana-labs/solana/pull/27786, which is what sparked the dig into this issue.

#### Proposed Solution
From some discussion, an initial idea is to expand `is_connected` to link back to geneiss OR to a slot that we load snapshot from.
- Starting completely clean (no snapshot or blockstore) seems like it'd be easy enough; mark snapshot slot as connected (although we wouldn't technically have these shreds) and then as additional slots are inserted, they'll be able to get marked as is_connected inductively as well
- Starting with a fetched snapshot but existing blockstore would require a little extra. For example, suppose the blockstore has slots in the range `[b_start, b_end]` and we fetch a snapshot at slot `s`:
    - Fetching a snapshot for `s > b_end` has no issues; `s` marked as connected and progresses onward (so functionally similar to starting without any blockstore)
    - Fetching a snapshot for `b_start < s < b_end` would mark `s` as connected, but if slots `(s, b_end]` are already present in blockstore, their connected status wouldn't change.
        - Maybe we could update `blockstore_process::load_frozen_forks()` to mark these slots as connected ?
    - Fetching a snapshot for `s < b_start` would be similar to above case; mark `s` connected and then potentially need to update slots as connected in `load_frozen_forks()`

Technically, when we fetch a snapshot at slot `s`, we don't actually need `s` in the blockstore as the bank unpacked from the snapshot is frozen after playing `s`. There might be some subtlety with getting this correct 

#### Additional Context / Reading
The original design doc for [blockstore](https://docs.solana.com/validator/blockstore#blockstore-design) is here, and below is the `SlotMeta` struct in code.

https://github.com/solana-labs/solana/blob/1a4b8b5b79a91398dea83ae7f8d1a529e1a2174d/ledger/src/blockstore_meta.rs#L16-L45

### PR DESCRIPTION
**Pull request by steviez**
First off, kudos to @offerm for initially spotting something was awry in https://github.com/solana-labs/solana/issues/27729 and https://github.com/solana-labs/solana/pull/27786.

#### Problem
The SlotMeta `is_connected` field was found to not be functioning as expected. Namely, `is_connected` was permanently false for nodes starting from snapshots because the supplied definition of is_connected requires a "path" back to genesis. See more details in https://github.com/solana-labs/solana/issues/27820

#### Summary of Changes
Change `is_connected` boolean to bitflags to allow tracking more state
```rust
    pub struct ConnectedFlags:u8 {
        const CONNECTED        = 0b0000_0001;
        const PARENT_CONNECTED = 0b1000_0000;
    }
```

Now, when `load_frozen_forks()` is called, the first slot will be marked as connected, as starting will either be at slot 0 or from a snapshot. Snapshots are root slots, so we want to allow this slot to start an `is_connected` chain as well.

#### Compatability
The offered solution as-is in this PR offers compatibility in the scenario where an operator upgrades their client to include this features, but keeps their ledger from a version that did not include this feature.

However, the scenario of downgrading client to a pre-this-feature version and keeping a ledger around that was populated with the this feature is not supported. Trying to deserialize a byte into a bool where any bit except the LSB is 1 will error.

To address this concern, https://github.com/solana-labs/solana/pull/29001 was introduced and backported. This PR introduces the new bitflags and fields; however, it only uses one bit (the LSB). With this PR rebased on top of 29001, this PR doesn't introduce any new bits; it just starts using the bit that was introduced in 29001.

#### Perf Impact
https://github.com/solana-labs/solana/pull/28069#issuecomment-1383715801 details an experiment I ran that shows promising results between two unstaked nodes (one with the change, one without) running against mnb.

#### Rollout Strategy
The following things need to happen before this commit can be pushed out:
- [x] Submit https://github.com/solana-labs/solana/pull/29001 (this is the stub commit that will make software deserialize bitflags out of `SlotMeta` instead of a bool
- [x] Get above PR backported in current release branches
   - [x] v1.13 (Done in v1.13.6)
   - [x] v1.14 (Done in v1.14.10)
- [x] Wait for clusters to stabilize on above releases (assuming no abandoned release in between)
   - [x] Mainnet on v1.13.6+ OR v1.14.10+ if mainnet progress to v1.14 first
   - [x] Testnet on v1.14.10+
   - [x] Devnet on v1.14.10+

Fixes #27820

### CODE REVIEW

File: ledger/src/blockstore_meta.rs [hunk 1]
```diff
@@ -37,9 +46,8 @@ pub struct SlotMeta {
     // The list of slots, each of which contains a block that derives
     // from this one.
     pub next_slots: Vec<Slot>,
-    // True if this slot is full (consumed == last_index + 1) and if every
-    // slot that is a parent of this slot is also connected.
-    pub is_connected: bool,
+    // True if this slot's parent is connected
+    pub connected_flags: ConnectedFlags,
```
Comment (steviez) [inline ledger/src/blockstore_meta.rs:50]: @CriesofCarrots - We've talked about this / I know you've dealt with this kind of issue in the past, so was hoping I could get a sanity check on this. If you want more context as to why I'm messing with this at all, check out https://github.com/solana-labs/solana/issues/27820; otherwise, skip ahead to following paragraph.

I'm trying to add some extra info to the `SlotMeta` struct. So, I'm using bitflags to write a u8 in-place of the bool that was previously there that was also occupying a full byte.
- The tracking `is_connected` provides is currently broken (this bit is always false), but even if it weren't, the case where someone upgrades their client without wiping their ledger would work
- However, the downgrade case is a little more problematic. If a user runs with a new client (that sets multiple bits in this byte) and then reverts to a client that is setting a bool, deserialize will fail, complaining about an illegal value for the bool.

So, my thinking is that I could roll out the following commit in this order:
- Change master to use bitflag in place of bool
   - This change would only be for the datatype (ie no is_parent option YET)
- Backport this to our relevant release branches (I guess v1.14 / v1.13 / v1.10)
- Once all clusters are safely using versions that have the bitflags, introduce the functionality that comes with `is_parent` option
   - This is the point at which being able to deserialize into a bool (ie largescale rollback) is no longer works
   
Just want to make sure this seems like a sane plan - if so, I'll then bring this up in #releng channel to see if I can get everyone on board with that. I know we're in a strange spot with releases right now

Comment (t-nelson) [reply ledger/src/blockstore_meta.rs:50]: > Dropping this in place of the existing bool is backwards compatible with the serialized SlotMeta so no worries about compatibility breaks.

this isn't _quite_ true.  rust strictly defines `bool::false` to be `0` and `bool::true` to be `1`. so it'll fit in the same space, but bool deserialize will blow up if extra bits are set

Comment (steviez) [reply ledger/src/blockstore_meta.rs:50]: Agh, I didn't word that very well. What I meant to indicate is that this code will run with a ledger that was populated setting only the one bit as a bool. Ie, if this land in v1.15, it will work with a ledger that was filled using v1.14. 

Using the same assumption as above that this lands in v1.15, if someone has a ledger running with v1.15 and then tries to downgrade their client to v1.14, deserialize will blow up.

The "stub" solution I proposed here is meant to provide a way to run v1.14 on a ledger that was filled by v1.15

Comment (steviez) [reply ledger/src/blockstore_meta.rs:50]: Or rather, I made statement in the PR description before I experimentally learned that deserialize will complain about extra bits being set 😄

File: ledger/src/blockstore_meta.rs [hunk 2]
```diff
@@ -11,6 +12,14 @@ use {
     },
 };
 
+bitflags! {
+    #[derive(Default, Serialize, Deserialize)]
+    pub struct ConnectedFlags:u8 {
+        const CONNECTED        = 0b0000_0001;
+        const PARENT_CONNECTED = 0b1000_0000;
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_meta.rs:19]: Let's add a comment block stating the definition of `CONNECTED` and `PARENT_CONNECTED`.

I think the CONNECTED now means the current slot is full and all slots from the current slot up to the root are also connected.  Am I right at this part?

**Review by yhchiang-sol — COMMENTED** [review]
Thanks for working on this.  Here's my initial comments:

File: ledger/src/blockstore_meta.rs (hunk 2 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:29]: Yes, connected means this slot is a descendant of genesis, or a snapshot root. Added comments.

File: ledger/src/blockstore_meta.rs [hunk 3]
```diff
@@ -14,8 +14,18 @@ use {
 
 bitflags! {
     #[derive(Default, Serialize, Deserialize)]
+    /// Flags to indicate whether a slot is a descendant of a sot on the main fork
     pub struct ConnectedFlags:u8 {
+        // A slot can be connected in two scenarios:
+        // 1) If the parent is connected and if the slot is full. By this
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_meta.rs:20]: >         // A slot can be connected in two scenarios:
>         // 1) If the parent is connected and if the slot is full. By this

I think you're probably defining something based on its own definition xD.  How about something like the following:

```
A slot is connected if it is:
* A root, or
* is *full* and its parent is connected.
```

In other words, a connected slot is a slot where all slots within [most recent root, slot] are full.
And we probably want to briefly define what is full in the comment as well.

If it is somehow possible to have a root not connected to either snapshot or genesis, then we can replace root by snapshot or genesis in the above statement.

File: ledger/src/blockstore.rs [hunk 4]
```diff
@@ -3323,6 +3323,55 @@ impl Blockstore {
         );
         Ok(())
     }
+
+    /// Mark a root `slot` as connected, traverse `slot`'s children and update
+    /// the children's connected status if appropriate.
+    ///
+    /// A ledger with a full path of blocks from genesis to latest root would
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3330]: nit: latest root -> the latest root

File: ledger/src/blockstore.rs [hunk 5]
```diff
@@ -3815,21 +3854,34 @@ where
     Ok(())
 }
 
+// Update the meta for a slot whose parent is known to be connected.
+// Returns a bool indicating whether this slot is now connected which would
+// indicate that it's children are also in need of update.
+fn update_child_from_connected_parent(meta: &mut SlotMeta) -> bool {
+    meta.set_parent_connected(true);
+
+    // If this slot is full, this slot is now connected
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3863]: Probably better to describe the actual definition: if a slot is full and its parent is connected, then it is connected.

File: ledger/src/blockstore.rs [hunk 6]
```diff
@@ -3815,21 +3854,34 @@ where
     Ok(())
 }
 
+// Update the meta for a slot whose parent is known to be connected.
+// Returns a bool indicating whether this slot is now connected which would
+// indicate that it's children are also in need of update.
+fn update_child_from_connected_parent(meta: &mut SlotMeta) -> bool {
+    meta.set_parent_connected(true);
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3861]: If this function is only for updating purposes, we should first check `meta.is_connected`.
If `meta.is_connected` is true, then we simply return false, indicating there is no need to update.

File: ledger/src/blockstore_meta.rs [hunk 7]
```diff
@@ -214,6 +232,24 @@ impl SlotMeta {
...
+        self.connected_flags
+            .contains(ConnectedFlags::PARENT_CONNECTED)
+    }
+
+    pub fn set_connected(&mut self, value: bool) {
+        self.connected_flags.set(ConnectedFlags::CONNECTED, value);
+    }
+
+    pub fn set_parent_connected(&mut self, value: bool) {
+        self.connected_flags
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_meta.rs:249]: I think we need some assertion or check here to make sure everything works correctly.

* If PARENT_CONNECTED can only be changed from false to true, or true to true, then we need to add some assertion here.  (i.e., only allow PARENT_CONNECTED to be updated when PARENT_CONNECTED is false).
* If the above statement is false, then we need to make sure when we set PARENT_CONNECTED from true to false, then we also set the CONNECTED flag to false.

File: ledger/src/blockstore_meta.rs [hunk 8]
```diff
@@ -11,6 +12,24 @@ use {
...
+        // 1) If the parent is connected and if the slot is full. By this
+        //    definition alone, the node would need to have blocks all the way
+        //    way back to genesis that are connected.
+        // 2) If ledger processing began at this slot from a snapshot. Snapshots
+        //    are presumed roots, and as such, we extend the idea of being
+        //    connected to this slot so that nodes starting from snapshot can
+        //    build a connected chain.
+        const CONNECTED        = 0b0000_0001;
+        /// Whether this
+        const PARENT_CONNECTED = 0b1000_0000;
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_meta.rs:29]: The flag design here seems to allow PARENT_CONNECTED to be false and CONNECTED to be true (which should never be the case).  How about something like we have IS_FULL and PARENT_CONNECTED, and we define CONNECTED to be IS_FULL & PARENT_CONNECTED?

**Review by yhchiang-sol — COMMENTED** [review]
Some thoughts about the general design of this PR.  Feel free to schedule a VC if that's something can speed up the discussion.

File: ledger/src/blockstore_meta.rs (hunk 8 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:29]: > The flag design here seems to allow PARENT_CONNECTED to be false and CONNECTED to be true (which should never be the case).

So that is exactly the reason why we need the second bit (`is_connected` and `is_parent_connected`). When we load from a snapshot at slot `S`, we don't actually need the shreds for that slot since the loaded bank is the state after transactions have been replayed at `S`. Moreso, we won't even try to repair this slot if we're starting from a clean ledger, so that slot will explicitly not be full unless there is manual intervention (a user copies shreds from somewhere).

This slot is not full, so we can't rely on `is_parent_connected && is_full()` as the criteria for whether `S` is connected or not. Thus, we introduce the second bit

File: ledger/src/blockstore.rs (hunk 6 above)
Comment (steviez) [reply ledger/src/blockstore.rs:3861]: So I think this is kind of similar to your notes about the assertions for sanity checks.

This function gets called on slot `S` when `S`'s parent `P` has been marked connected. By definition, if `P` just became connected, then `S` could not have (or at least should not have) already been connected.

I guess one hypothetical scenario where my above statement would break down is if:
- User loads from snapshot at slot `S1` and progresses onwards
- User stops, and restart from a snapshot at slot `S2` where `S2 < S1`
   - `S2 < S1` should sound weird, validators don't delete their later snapshots to start at an older one
- User now replays from `S2` onward, where slots > `S2` will get marked connected
- Eventually, replay progresses from the second start hits `S1` again. `S1` is already connected but with existing logic, we would mark it connected again

There is nothing preventing someone from doing what I just described, but I don't why any operator running a node regularly would do something like this

File: ledger/src/blockstore_meta.rs (hunk 7 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:249]: I think some assertions could make sense / help illustrate the mechanism. Let me look at something with how we purge slots and come back to this comment

File: ledger/src/blockstore_meta.rs (hunk 8 above)
Comment (yhchiang-sol) [reply ledger/src/blockstore_meta.rs:29]: Let me see if I understand this.

So when we load from a snapshot at slot `S`, did the snapshot already include the complete replay of slot `S`?
If the answer is yes (and I think the answer should be yes), then slot `S` is connected (and at least was full before, otherwise the snapshot won't be able to include slot `S`).

So for slot `S`, can I know where we mark it as connected?  In addition, if we simply mark slot `S` as parent-connected and full, can I know what's the difference between marking `S` as connected (but not full)?

Because it seems to me that only the most recent slot in the snapshot could have such a special case, but the overall bit design could potential allow every slot to have such a special case.

File: ledger/src/blockstore_meta.rs (hunk 3 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs]: Pushed some updates, let me know what you think

File: ledger/src/blockstore_meta.rs (hunk 8 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:38]: > So when we load from a snapshot at slot S, did the snapshot already include the complete replay of slot S

Yes, a snapshot includes the frozen state that includes slot `S`'s transactions

> then slot S is connected (and at least was full before, otherwise the snapshot won't be able to include slot S

- This is true when considering a node that is loading from its' own snapshot.
- When a node has no local state (joining for the first time or joining with a wiped ledger), they have to get their snapshot from someone else. They download a snapshot at slot `S`, and unpacking / generating things re-establishes their bank/account state with `S` included / ready to play `S`'s child. Since the bank already has `S` reflected in it, they don't pull down the block (shreds) into rocksdb. As such, `S` will not be full in the blockstore on this node that just joined.

Building on the download snapshot case, we mark `S` connected. Now suppose that `T` is `S`'s child. When we download the shreds for `T`, we insert a SlotMeta for `T`. When inserting this, we check `S`'s SlotMeta, see that `S` is connected, and then mark `T`  as having its' parent connected. Then, when `T` gets the last shred it needs to become full, we update `T` to be connected, and then propagate the fact that `T` is connected to `T`'s children (by marking `T`'s children with the `PARENT_CONNECTED` bit).

> In addition, if we simply mark slot S as parent-connected and full, can I know what's the difference between marking S as connected (but not full)?

Fullness is reflective of if we have received all the shreds for a slot (the last shred in the block has a marker so we can know when we shouldn't expect anymore). Using the same example as above where `S` is a snapshot slot that we downloaded from the cluster, we can mark it is parent-connected, but marking it "full" would be inconsistent since we don't have the shreds.

That is why I left the `is_full()` to be determined based on what shreds are present, and called the bits `parent_connected` && `connected`

File: ledger/src/blockstore.rs [hunk 9]
```diff
@@ -3317,6 +3317,55 @@ impl Blockstore {
...
+    /// Mark a root `slot` as connected, traverse `slot`'s children and update
+    /// the children's connected status if appropriate.
+    ///
+    /// A ledger with a full path of blocks from genesis to the latest root will
+    /// have all of the rooted blocks marked as connected such that new blocks
+    /// could also be connected. However, starting from some root (such as from
+    /// a snapshot) is a valid way to join a cluster. For this case, mark this
+    /// root as connected such that the node that joined midway through can
+    /// have their slots considered connected.
+    pub fn set_and_chain_connected_on_root(&self, slot: Slot) -> Result<()> {
```
Comment (ryoqun) [inline ledger/src/blockstore.rs:3330]: nit: `set_and_chain_connected_on_root_and_children()` or `connect_child_slots_from_root()`.

Comment (ryoqun) [reply ledger/src/blockstore.rs:3330]: also, I'd prefer to hint the given Slot param to be expected having been _rooted_ as `, root: Slot) -> Result<...>`

File: ledger/src/blockstore.rs [hunk 10]
```diff
@@ -3317,6 +3317,55 @@ impl Blockstore {
...
+        info!(
+            "Marking slot {} and any full children slots as connected",
+            slot
+        );
+
+        let mut meta = self
```
Comment (ryoqun) [inline ledger/src/blockstore.rs:3336]: nit `let mut starting_meta`, so that it's more logically aligned with `child_meta`.

File: ledger/src/blockstore.rs [hunk 11]
```diff
@@ -3317,6 +3317,55 @@ impl Blockstore {
...
+        }
+
+        meta.set_connected(true);
+        let mut write_batch = self.db.batch()?;
+        write_batch.put::<cf::SlotMeta>(meta.slot, &meta)?;
+
+        let mut next_slots = VecDeque::from(meta.next_slots);
+        while !next_slots.is_empty() {
+            let current_slot = next_slots.pop_front().unwrap();
+            let mut current_meta = self.meta(current_slot)?.unwrap_or_else(|| {
```
Comment (ryoqun) [inline ledger/src/blockstore.rs:3353]: nit: `next_meta`

File: ledger/src/blockstore.rs (hunk 9 above)
Comment (ryoqun) [reply ledger/src/blockstore.rs:3330]: hmm, seems current codebase is inconsistent to mean the same thing: `next`, `child`, `descendant`... 

I'd prefer to stick to `next`, that's because it's set in stone (i.e. `blockstone`, lol)

File: ledger/src/blockstore.rs (hunk 11 above)
Comment (ryoqun) [reply ledger/src/blockstore.rs:3353]: hmm, after i read the code more closely, i think just `slot`/`meta` is also okay. (i.e. without `current_`)

File: ledger/src/blockstore.rs (hunk 9 above)
Comment (ryoqun) [reply ledger/src/blockstore.rs:3330]: also, no new unit test for this `fn`?

File: ledger/src/blockstore_meta.rs (hunk 8 above)
Comment (yhchiang-sol) [reply ledger/src/blockstore_meta.rs:38]: Thanks for the extra information.  It makes sense and sounds good.  Let's make it clear in the code comment about the definition of CONNECTED.  CONNECTED means:

* The slot has been a root (and this implicitly implies its parent slot is connected), or
* Its parent slot is connected and the slot itself is full.

So it means CONNECTED should also guarantee and cover PARENT_CONNECTED.

I think we should define the bits like the following:

* PARENT_CONNECTED: its parent is connected.
* FULLY_REPLAYABLE (or simply call REPLAYABLE): the Slot is fully replayable or has been fully replayed.
* CONNECTED:  PARENT_CONNECTED & FULLY_REPLAYABLE.

File: ledger/src/blockstore.rs (hunk 10 above)
Comment (steviez) [reply ledger/src/blockstore.rs:3336]: Good call, I'll go with `root_meta` to align with your suggestion to change the parameter name to `root`

File: ledger/src/blockstore.rs (hunk 9 above)
Comment (steviez) [reply ledger/src/blockstore.rs:3330]: > also, I'd prefer to hint the given Slot param to be expected having been rooted as , root: Slot) -> Result<...>
Done

> I'd prefer to stick to next (taken from meta.next_slots.), that's because it's set in stone (i.e. blockstone, lol)
I'll use `next` for now to match what is currently in there, but I might make a PR to change `next_slots` to `children_slots`. I think this aligns with our naming the field `parent_slot` in `SlotMeta` as opposed to saying `previous_slot`.

> also, no new unit test for this fn?
Had it tagged as a TODO item, now that fire fighting has subsided, I can add something in.

File: ledger/src/blockstore_meta.rs (hunk 8 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:38]: > So it means CONNECTED should also guarantee and cover PARENT_CONNECTED.

For any slot except a snapshot slot, yes. But again, the snapshot slot is the special case where we are saying that the slot is connected, despite its' parent not existing in the blockstore and us not actually having the shreds.

In regards to your suggestion of adding an extra bit, I disagree. In this case, `FULLY_REPLAYABLE` simply means that the slot is full. We already track this with other fields in the `SlotMeta`, so adding another bit that we'd have to update / keep aligned adds extra burden

Comment (yhchiang-sol) [reply ledger/src/blockstore_meta.rs:38]: The reason behind my suggestion is that I still feel it's quite odd to allow CONNECTED to be true but PARENT_CONNECTED to be false.  I understand the exception here are genesis and snapshot slot, but I feel allowing such a combination seems error-prone to me, and we also need to add assertions at proper places to make sure regular slots never have CONNECTED to be true but PARENT_CONNECTED to be false.

> In regards to your suggestion of adding an extra bit

I think you probably misunderstood my suggestion.  It is still two bits, but CONNECTED means both PARENT_CONNECTED and FULLY_REPLAYABLE are true.  So no extra bit for CONNECTED.  Fully replayable is not the same as full.  For instance, genesis slot and snapshot slots are both replayable as well.

File: ledger/src/blockstore.rs (hunk 9 above)
Comment (steviez) [reply ledger/src/blockstore.rs]: Unit test done

File: ledger/src/blockstore_meta.rs (hunk 8 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:38]: > For instance, genesis slot and snapshot slots are both replayable as well.

We recreate the bank from the snapshot and do not have the slot; thus, this slot is not replayable

Comment (yhchiang-sol) [reply ledger/src/blockstore_meta.rs:38]: Maybe we can pick a different name for that bit.  Originally I was thinking about REPLAYABLED_OR_REPLAYED, but I think given that a slot is already in a snapshot or is a genesis slot, it means the slot has already replayed in the past, so it was replayable before thus I simplified it to be REPLAYABLE.

I still feel using `11` to represent CONNECTED is better and less error-prone than allowing `10` and `11`.

File: ledger/src/blockstore_meta.rs (hunk 7 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:258]: Current usage never has us doing `true ==> false` transitions on either of these bits. In purges, if we purge slot `S`, we do not update `S`'s children to remove `S` as their parent slot. I think the idea here is that we're constantly purging the oldest data when we're full, so doesn't make sense to update metas, mark orphans.

File: ledger/src/blockstore_meta.rs (hunk 8 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:38]: > I still feel using 11 to represent CONNECTED is better and less error-prone than allowing 10 and 11 to both represent CONNECTED.

Thanks for stating this - I now fully understand your hangup here. Let me mull on this and then let's chat on Zoom to hash this out, should get to a resolution quicker that way

**Comment by offerm** [comment]
@steviez please see my note here https://github.com/solana-labs/solana/issues/27729#issuecomment-1281928100

Will be happy to test this branch when it is ready for mainnet. Let me know.

**Comment by steviez** [comment]
> Will be happy to test this branch when it is ready for mainnet. Let me know.

Hi @offerm, no need to post in both places, I saw your comment but just hadn't gotten around to testing.

In regards to timing / testing, thank you for offering. I have been running a node for a bit, and have promising data. However, the issue is that this PR changes the layout of SlotMeta in the blockstore. As such, it requires some tact to rollout while leaving a potential path to fallback. See the compatibility & rollout strategy sections of this PR for more details.

Getting the network fully on v1.13 (with QUIC only) is a priority, once that has happened and we have confidence that there are no issues, I'll begin executing the steps in rollout strategy. Given that the above is a blocker, I haven't been pushing this PR along super hard.

File: ledger/src/blockstore_meta.rs (hunk 7 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:258]: I did the following:
- Added an assertion that parent is connected in order to set connected
- I removed the `value` parameter since our transitions are only `false` ==> `true`
- I made snapshot slots get both bits set in the new function

File: ledger/src/blockstore_meta.rs (hunk 1 above)
Comment (t-nelson) [reply ledger/src/blockstore_meta.rs]: an alternative to changing the 1.14 layout could be to instead write a custom deserializer for that field that accepts the new format, only if valid, and discards any new format bits before emitting a `bool`

File: ledger/src/blockstore.rs (hunk 6 above)
Comment (steviez) [reply ledger/src/blockstore.rs]: Still don't think this scenario should occur often, but made the code defensive to avoid rewriting the same bit

File: ledger/src/blockstore.rs [hunk 12]
```diff
@@ -5384,12 +5445,13 @@ pub mod tests {
                 assert_eq!(meta.parent_slot, Some(slot - 1));
             }
             assert_eq!(meta.last_index, Some(shreds_per_slot as u64 - 1));
-            assert!(meta.is_connected);
+            assert!(meta.is_connected());
         }
     }
 
     #[test]
     fn test_handle_chaining_missing_slots() {
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5453]: Let's add some description about this test, specifically on why it expects is_parent_connected is true while is_connected is false.

File: ledger/src/blockstore.rs [hunk 13]
```diff
@@ -5556,6 +5621,67 @@ pub mod tests {
...
+
+    #[test]
+    fn test_set_and_chain_connected_on_root_and_next_slots() {
+        let ledger_path = get_tmp_ledger_path_auto_delete!();
+        let blockstore = Blockstore::open(ledger_path.path()).unwrap();
+
+        // Create enough entries to ensure 5 shreds result
+        let entries_per_slot = max_ticks_per_n_shreds(5, None);
+
+        // Start a chain from a slot not in blockstore, such is the case when
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5633]: nit: such is the case -> this simulates the case?

File: ledger/src/blockstore.rs [hunk 14]
```diff
@@ -5556,6 +5621,67 @@ pub mod tests {
...
+        blockstore
+            .set_and_chain_connected_on_root_and_next_slots(5)
+            .unwrap();
+        let slot_meta5 = blockstore.meta(5).unwrap().unwrap();
+        assert!(!slot_meta5.is_full());
+        assert!(slot_meta5.is_parent_connected());
+        assert!(slot_meta5.is_connected());
+
+        // Insert some slots and ensure they connect from slot 5 correctly
+        let (shreds, _) = make_many_slot_entries(6, 5, entries_per_slot);
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5646]: nit: Maybe do something like this to improve the readability?

```
make_many_slot_entries(
    6, // start_slot
    5, // num_slots
    entries_per_slot);
```

File: ledger/src/blockstore.rs [hunk 15]
```diff
@@ -5556,6 +5621,67 @@ pub mod tests {
...
+        blockstore.insert_shreds(shreds, None, false).unwrap();
+        for slot in 15..=19 {
+            let meta = blockstore.meta(slot).unwrap().unwrap();
+            assert!(!meta.is_parent_connected());
+            assert!(!meta.is_connected());
+        }
+        blockstore
+            .set_and_chain_connected_on_root_and_next_slots(15)
+            .unwrap();
+        for slot in 15..=19 {
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5677]: Can we also make some slots not full (e.g. 18) here and check we only have is_connected() and is_parent_connected() up to slot 17, and slot 18 has is_parent_connected() true but is_connected() false?

Comment (yhchiang-sol) [reply ledger/src/blockstore.rs:5677]: And then make the slot full, and invoke the function again to make sure every slot is both connected and parent_connected?

File: ledger/src/blockstore.rs [hunk 16]
```diff
@@ -5556,6 +5621,67 @@ pub mod tests {
...
+        blockstore
+            .set_and_chain_connected_on_root_and_next_slots(6)
+            .unwrap();
+        for slot in 6..=10 {
+            let meta = blockstore.meta(slot).unwrap().unwrap();
+            assert!(meta.is_parent_connected());
+            assert!(meta.is_connected());
+        }
+
+        // Insert some slots that are not connected and then ensure they connect
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5664]: nit: at a period at the end.

File: ledger/src/blockstore.rs [hunk 17]
```diff
@@ -3315,6 +3315,54 @@ impl Blockstore {
...
+    /// Mark a root `slot` as connected, traverse `slot`'s children and update
+    /// the children's connected status if appropriate.
+    ///
+    /// A ledger with a full path of blocks from genesis to the latest root will
+    /// have all of the rooted blocks marked as connected such that new blocks
+    /// could also be connected. However, starting from some root (such as from
+    /// a snapshot) is a valid way to join a cluster. For this case, mark this
+    /// root as connected such that the node that joined midway through can
+    /// have their slots considered connected.
+    pub fn set_and_chain_connected_on_root_and_next_slots(&self, root: Slot) -> Result<()> {
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3328]: Somehow I feel this should be implemented using two functions: set_connected_on_root() and chain_next_slots()?  The former set both connected and parent_connected to true, and the latter propagates the connectivity.  Since I feel once we've correctly set connected() and parent_connected() to true for the snapshot slot, then the propagation should be the same as the usual case.  Am I right on this part?

File: ledger/src/blockstore_meta.rs [hunk 18]
```diff
@@ -214,6 +241,25 @@ impl SlotMeta {
...
+    pub fn is_connected(&self) -> bool {
+        self.connected_flags.contains(ConnectedFlags::CONNECTED)
+    }
+
+    pub fn is_parent_connected(&self) -> bool {
+        self.connected_flags
+            .contains(ConnectedFlags::PARENT_CONNECTED)
+    }
+
+    pub fn set_connected(&mut self) {
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_meta.rs:253]: Maybe we should simply set two bits to true instead and have another function that only set the `01` bit to true?

File: ledger/src/blockstore_meta.rs [hunk 19]
```diff
@@ -214,6 +241,25 @@ impl SlotMeta {
         Some(self.consumed) == self.last_index.map(|ix| ix + 1)
     }
 
+    pub fn is_connected(&self) -> bool {
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_meta.rs:244]: I think we should check both ConnectedFlags::CONNECTED and ConnectedFlags::PARENT_CONNECTED true.

File: ledger/src/blockstore.rs [hunk 20]
```diff
@@ -3808,21 +3846,44 @@ where
     Ok(())
 }
 
+// Update the meta for a slot whose parent is known to be connected.
+// Returns a bool indicating whether this slot is now connected which would
+// indicate that it's children are also in need of update.
+fn update_child_from_connected_parent(meta: &mut SlotMeta) -> bool {
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3852]: I feel it's better to make this function a meta function.

File: ledger/src/blockstore.rs [hunk 21]
```diff
@@ -3808,21 +3846,44 @@ where
...
+    if meta.is_connected() {
+        return false;
+    }
+    meta.set_parent_connected();
+
+    // This slot's parent is known to be connected, so if
+    // it is also full, then the slot is now connected.
+    let is_full = meta.is_full();
+    if is_full {
+        meta.set_connected();
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3864]: I feel this call should only set the bit (`01`) that only represents part of the full connectivity, such as `set_completed()` or something.  And this bit together with the parent_connected() (`10`) means connected (`11`).

**Review by yhchiang-sol — COMMENTED** [review]
Thanks for working on this.

I still feel that it's probably better to have three functions:

* a function (I don't have a proper name) that sets `01` bit to true.  In the normal case, the condition is is_full.
  * the only exception where it can bypass is_full check is the `set_and_chain_connected_on_root_and_next_slots` function introduced in this PR, which set both `11` bits to true, and the function should only be called when the slot is from a snapshot.
* set_parent_connected() that sets `10` bit to true.
* is_connected() checks whether we have both `11` bits to be true.

File: ledger/src/blockstore.rs [hunk 22]
```diff
@@ -3835,8 +3896,8 @@ fn slot_has_updates(slot_meta: &SlotMeta, slot_meta_backup: &Option<SlotMeta>) -
     // We should signal that there are updates if we extended the chain of consecutive blocks starting
     // from block 0, which is true iff:
     // 1) The block with index prev_block_index is itself part of the trunk of consecutive blocks
-    // starting from block 0,
-    slot_meta.is_connected &&
+    // starting from block 0 or from a snapshot
```
Comment (t-nelson) [inline ledger/src/blockstore.rs:3899]:
```suggestion
    // starting from block 0 or from a snapshot, which is rooted by definition
```

**Comment by steviez** [comment]
I have introduced https://github.com/solana-labs/solana/pull/29001. This is the PR that will introduce the change from boolean to bitflags, and can be backported for compatibility purposes.

I will rebase on top of this PR and then address feedback more. Note that this PR will have some lag to get submitted given that we need clusters to be stable on releases with 29001

File: ledger/src/blockstore.rs (hunk 17 above)
[the remark this answers is not in the document]
Comment (steviez) [reply ledger/src/blockstore.rs:3321]: Correct, children slots of `self`. The use of `next` here is consistent with the terminology we use elsewhere, namely,
https://github.com/solana-labs/solana/blob/17b64005d3d77bdbf2c5f7f2002ce6351d8c59e3/ledger/src/blockstore_meta.rs#L77

For what it is worth, I don't love the use of `next` in this context (we use `parent_slot` so I would like to change to `child_slots`), but for the sake of this PR, I think we should use `next` so that the terminology is consistent.

File: ledger/src/blockstore.rs [hunk 23]
```diff
@@ -3808,21 +3846,44 @@ where
     Ok(())
 }
 
+// Update the meta for a slot whose parent is known to be connected.
+// Returns a bool indicating whether this slot is now connected which would
+// indicate that it's children are also in need of update.
+fn update_child_from_connected_parent(meta: &mut SlotMeta) -> bool {
+    // If this slot is already connected, its' children should
+    // also already be connected so cut the traversal here.
```
[the remark this answers is not in the document]
Comment (steviez) [reply ledger/src/blockstore.rs:3847]: Technically we could, but we would need to do so recursively.
- check the children
- check the children's children
- ...

Given that this function is only called at startup (and practically speaking, it should only traverse a couple hundred slots if people are using sane snapshot settings), doing the full traversal here wouldn't be terrible.

However, this PR's behavior for setting a slot to be connected is pretty tight so given that, I'm inclined to think that an assertion / double check is overkill. But, if the assumption is somehow not true, that would break the functionality of the connected flag until the next load from snapshot. So, maybe worth doing the traversal and setting flags again just incase?

File: ledger/src/blockstore.rs (hunk 20 above)
Comment (steviez) [reply ledger/src/blockstore.rs:3845]: Done, moved stuff to `SlotMeta::set_parent_connected`

File: ledger/src/blockstore.rs (hunk 15 above)
Comment (steviez) [reply ledger/src/blockstore.rs:5665]: Good call, done

File: ledger/src/blockstore.rs (hunk 17 above)
Comment (steviez) [reply ledger/src/blockstore.rs:3339]: > Somehow I feel this should be implemented using two functions: set_connected_on_root() and chain_next_slots()?
Well, we essentially do this but not in two separate functions for reasons I'll go into

> The former set both connected and parent_connected to true
This function currently does this, but not with a dedicated `SlotMeta` function. If you feel strongly enough about it, we can add it

> and the latter propagates the connectivity. Since I feel once we've correctly set connected() and parent_connected() to true for the snapshot slot, then the propagation should be the same as the usual case. Am I right on this part?

Yes, the propagation is essentially the same. However, we can't cleanly re-use the existing traversal function because that function will pull `Meta`'s from either the working set (that is built up during insertion) or from the db. This function is only pulling things from the DB, and then committing to a `WriteBatch`.

That being said, these functions utilize the same function that updates a meta and then says whether we should traverse its' children. The duplicated part is just the simple BFS of popping/pushing to a queue.

File: ledger/src/blockstore_meta.rs (hunk 18 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:260]: I think things might have changed slightly so marking this resolved; but please bring up again if you disagree.

File: ledger/src/blockstore_meta.rs (hunk 19 above)
Comment (steviez) [reply ledger/src/blockstore_meta.rs:255]: Given that `set_connected()` asserts that `is_parent_connected()` and we don't have a way to unset connected, this is overkill IMO.

File: ledger/src/blockstore.rs (hunk 21 above)
Comment (steviez) [reply ledger/src/blockstore.rs]: > I feel this call should only set the bit (01) that only represents part of the full connectivity, such as set_completed() or something. And this bit together with the parent_connected() (10) means connected (11).

We can only set connected iff parent_connected has previously been set. So, I think the scenario you described is an invalid one. Ie, we'll only set connected `(x1)` if parent_connected `(1y)` has already been set. Thus, it must be the case that `x = 1`. Additionally `y = 0` will always be true because we can't be connected before our parent was

**Comment by steviez** [comment]
I ran an experiment to measure how much this improved things. The setup:
- Two unstaked nodes with identical HW setup in same DC
- One node running tip-of-master, other node running tip-of-master + this PR
- Running against mnb at node steady-state
    - Nodes had been running against cluster for > 1 day

To measure the performance improvement, I pulled metrics from validator logs for when the last shred was received and when the bank was frozen (filtered results down to slots that were frozen). Then, I computed the difference in timestamps between bank_frozen and last_shred for each slot. With this set of time differences for each slot, I then compared across nodes (note that I'm not comparing absolute timestamps between nodes, only durations).

Here are the results for 1 day of runtime (~160k slots). I did `master_branch_times - pr_branch_times` which means that positive numbers on the histogram indicate the PR is an improvement whereas negative numbers imply a degradation.
image

We have a somewhat normal distribution, and the mean is sitting at ~137ms. So, pretty significant amount.

It is interesting to see the number of datapoints that did worse. This change itself doesn't directly slow anything down, so on the slots where the PR did worse, there must be some second order effect(s) coming into play. Could be an interesting investigation, although I'm not sure that is a pre-req for pushing this PR.

**Comment by offerm** [comment]
nice!

File: ledger/src/blockstore.rs [hunk 24]
```diff
@@ -3847,8 +3873,8 @@ fn slot_has_updates(slot_meta: &SlotMeta, slot_meta_backup: &Option<SlotMeta>) -
     // We should signal that there are updates if we extended the chain of consecutive blocks starting
     // from block 0, which is true iff:
     // 1) The block with index prev_block_index is itself part of the trunk of consecutive blocks
-    // starting from block 0,
-    slot_meta.is_connected() &&
+    // starting from block 0 or from a snapshot, which is rooted by definition
+    slot_meta.is_parent_connected() &&
         // AND either:
         // 1) The slot didn't exist in the database before, and now we have a consecutive
         // block for that slot
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3880]: A bit unrelated to this PR.  I feel the comment could be further simplified as the real condition below is simply whether the consumed count is updated (i.e., `slot_meta_backup.as_ref().unwrap().consumed != slot_meta.consumed`).

However, we need to break into two conditions and further check `slot_meta_backup.is_none()` because if slot_meta_backup doesn't exist, then we cannot check `slot_meta_backup.as_ref().unwrap().consumed != slot_meta.consumed` because it does not exist.

File: ledger/src/blockstore.rs [hunk 25]
```diff
@@ -5515,28 +5544,123 @@ pub mod tests {
...
+        // node starts with no blockstore and downloads a snapshot. In this
+        // scenario, the slot will be marked connected despite its' parent not
+        // being connected (or existing) and not being full.
+        blockstore
+            .set_and_chain_connected_on_root_and_next_slots(start_slot)
+            .unwrap();
+        let slot_meta5 = blockstore.meta(start_slot).unwrap().unwrap();
+        assert!(!slot_meta5.is_full());
+        assert!(slot_meta5.is_parent_connected());
+        assert!(slot_meta5.is_connected());
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5587]: 👍

File: ledger/src/blockstore.rs [hunk 26]
```diff
@@ -5515,28 +5544,123 @@ pub mod tests {
...
+            assert!(meta.is_connected());
+        }
+
+        // Start another chain that is disconnected from previous chain. But, insert
+        // a non-full slot and ensure this slot (and its' children) are not marked
+        // as connected.
+        start_slot += 2 * num_slots;
+        let (shreds, _) = make_many_slot_entries(start_slot, num_slots, entries_per_slot);
+        // Insert all shreds except for the shreds with index > 0 from non_full_slot
+        let non_full_slot = start_slot + 2;
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5617]: nit: probably replacing `2` by `num_slots / 2` would make this test more generalized.

File: ledger/src/blockstore.rs [hunk 27]
```diff
@@ -5515,28 +5544,123 @@ pub mod tests {
...
+
+        // Insert the missing shreds and ensure all slots connected now
+        blockstore
+            .insert_shreds(missing_shreds, None, false)
+            .unwrap();
+        for slot in start_slot..start_slot + num_slots {
+            let meta = blockstore.meta(slot).unwrap().unwrap();
+            assert!(meta.is_parent_connected());
+            assert!(meta.is_connected());
+        }
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:5661]: This test is great!  Like it!  It describes the exact scenarios that we want to test.

File: ledger/src/blockstore_meta.rs [hunk 28]
```diff
@@ -251,14 +251,42 @@ impl SlotMeta {
...
     }
 
+    /// Returns a boolean indicating whether the meta's parent is connected.
+    pub fn is_parent_connected(&self) -> bool {
+        self.connected_flags
+            .contains(ConnectedFlags::PARENT_CONNECTED)
+    }
+
+    /// Mark the meta's parent as connected.
+    /// If the meta is also, then the meta is now connected as well. Return a
```
Comment (yhchiang-sol) [inline ledger/src/blockstore_meta.rs:272]: nit: `If the meta is also` -> `If the meta is also full`?

**Review by yhchiang-sol — APPROVED** [review]
Thanks for running experiments.  The results look promising!
The PR looks good.  Only minor comments.

File: ledger/src/blockstore.rs (hunk 24 above)
Comment (steviez) [reply ledger/src/blockstore.rs:3880]: I ended up adding a function description and cleaning up the comment a bit. Like you said, not directly related to this function but still applicable to update this comment I think since this function is how we expose the (newly fixed) functionality outside of `Blockstore`

File: ledger/src/blockstore.rs [hunk 29]
```diff
@@ -3843,18 +3868,19 @@ fn is_newly_completed_slot(slot_meta: &SlotMeta, backup_slot_meta: &Option<SlotM
             || slot_meta.consumed != backup_slot_meta.as_ref().unwrap().consumed)
 }
 
+// Returns a boolean indicating whether a slot has received additional shreds
+// that can be replayed since the previous update to the slot's SlotMeta.
```
Comment (yhchiang-sol) [inline ledger/src/blockstore.rs:3872]: nit: Use `///` instead?

**Review by yhchiang-sol — APPROVED** [review]
LGTM

File: ledger/src/blockstore.rs (hunk 29 above)
Comment (steviez) [reply ledger/src/blockstore.rs]: It's a private but doesn't hurt; needed to rebase anyways so made the change

**Comment by steviez** [comment]
Rebased on the tip of master for the sake of leaving a test node running - no code changes, but also no need for reviewers to look again.

This previously had ship it, and we are still waiting for mnb to get onto v1.13.6 or v1.14.x

**Review by t-nelson — DISMISSED** [review]
> This previously had ship it, and we are still waiting for mnb to get onto v1.13.6 or v1.14.x

should be fine to merge into master now that 1.15.0 is cut.  just hold the bp

**Comment by steviez** [comment]
After a nudge from @t-nelson to check, `solana validators` reveals that the majority of the v1.13.5 stragglers (at least validators) have upgraded to v1.13.6:
```
Stake By Version:
1.14.17 -    3 current validators ( 0.95%)   1 delinquent validators ( 0.00%)
1.14.16 -   16 current validators ( 0.49%)
1.14.15 -    8 current validators ( 1.22%)
1.14.13 -    0 current validators ( 0.00%)   4 delinquent validators ( 0.00%)
1.14.10 -    0 current validators ( 0.00%)   1 delinquent validators ( 0.00%)
1.13.7  -    9 current validators ( 1.75%)
1.13.6  - 2049 current validators (91.19%) 264 delinquent validators ( 0.54%)
1.13.5  -   58 current validators ( 3.35%)  22 delinquent validators ( 0.02%)
1.13.4  -    1 current validators ( 0.22%)
1.8.14  -    0 current validators ( 0.00%)   1 delinquent validators ( 0.00%)
unknown -    2 current validators ( 0.03%) 719 delinquent validators ( 0.24%)
```
As noted in the main PR description (see compatibility and rollout strategy sections), I wanted to see this happen in the name of being very cautious. But, with above I think we're there so I'm going to rebase on tip of master to make sure nothing broke while this PR has been sitting on the back-burner. With a good CI run, I feel good shipping to master and we can then separately consider backporting

**Comment by steviez** [comment]
> With a good CI run, I feel good shipping to master and we can then separately consider backporting

Glad I checked, clippy requirements have changed and something I was doing is no longer allowed:
https://buildkite.com/solana-labs/solana/builds/91815#0186e2cb-b724-4feb-ab07-0bdc74004333

**Review by yhchiang-sol — APPROVED** [review]
Looks good.  Ship it!

**Review by t-nelson — APPROVED** [review]
:shipit: 

remind me of the prospects for making this sufficiently for/backward compatible for a safe 1.14 backport?  1.13?

**Comment by steviez** [comment]
> remind me of the prospects for making this sufficiently for/backward compatible for a safe 1.14 backport? 1.13?

See "Rollout Strategy" for more details, but this PR is compatible in both directions with `v1.13.6+` and `v1.14.10+`; those releases are the first on their respective branches that have the "stub" PR to convert bool to bitflags
