### PR TITLE
Fix blockstore_processor::load_frozen_forks() halt_at_slot behavior

### LINKED ISSUE #28236: 1.14.5 panicked at 'No bank hash was found for this bank, that should not be possible'
#### Problem
I manually updated `tv` to v1.14.5. About 90 seconds after startup it panicked. systemd restarted it and the validator successfully started and caught up. This log includes the panic and subsequent restart.
[tv_no_bank_hash_found.log](https://github.com/solana-labs/solana/files/9717155/tv_no_bank_hash_found.log)

The panicked instance wrote an incremental snapshot which may be why the second instance succeeded.

### PR DESCRIPTION
**Pull request by steviez**
#### Problem
load_frozen_forks() finds new slots to process by creating new Banks for the children of the current slot in process_next_slots(). Prior to this change, we would then immediately check if we had reached the halt_at_slot and correctly halt processing when appropriate. As such, it would be possible for Banks to be created for slots beyond the halt_at_slot.

While a potential child slot that is past halt_at_slot wouldn't be replayed, the Bank being created still alters some universal state in AccountsDb. Ie
```
[... ERROR solana_runtime::accounts_db] set_hash: already exists; multiple forks with shared slot <CHILD> as child (parent: <PARENT>)!?
```

`halt_at_slot` is specified in normal operation; we capture the largest slot available during startup and say we'll go no further than that in `load_frozen_forks()`
https://github.com/solana-labs/solana/blob/d500391006475e16d870f81647096799a6a2fa4b/core/src/validator.rs#L1421-L1423

#### Summary of Changes
So, this change moves the halt_at_slot check before we create children Banks in process_next_slots().

Fixes #28236 , see that issue for some log lines that led me to discovering this

### CODE REVIEW

File: ledger/src/blockstore_processor.rs [hunk 1]
```diff
@@ -1588,19 +1587,23 @@ fn load_frozen_forks(
...
 
-            process_next_slots(
-                &bank,
-                &meta,
-                blockstore,
-                leader_schedule_cache,
-                &mut pending_slots,
-            )?;
-
-            if slot >= halt_at_slot {
```
Comment (steviez) [inline ledger/src/blockstore_processor.rs:1599]: Important note here; we were creating the new Bank(s) in `process_next_slots()`, but not adding them `BankForks`. So, these `Bank`s were essentially orphaned, and explains why we'd try to create a Bank for the slot a second time when `ReplayStage` fired up

File: ledger/src/blockstore_processor.rs [hunk 2]
```diff
@@ -1588,19 +1587,23 @@ fn load_frozen_forks(
...
+            let done_processing = opts
+                .halt_at_slot
+                .map(|halt_at_slot| slot >= halt_at_slot)
+                .unwrap_or(false);
+            if done_processing {
                 if opts.run_final_accounts_hash_calc {
                     run_final_hash_calc(&bank, on_halt_store_hash_raw_data_for_debug);
                 }
                 break;
+            } else {
```
Comment (jeffwashington) [inline ledger/src/blockstore_processor.rs:1599]: you can get rid of this else

File: ledger/src/blockstore_processor.rs [hunk 3]
```diff
@@ -1440,9 +1440,8 @@ fn load_frozen_forks(
         &mut pending_slots,
     )?;
 
-    let halt_at_slot = opts.halt_at_slot.unwrap_or(std::u64::MAX);
```
Comment (jeffwashington) [inline ledger/src/blockstore_processor.rs:1443]: I like getting rid of the sentinel max value.

**Comment by jeffwashington** [comment]
@carllin, Steve solved the mystery.

**Review by jeffwashington — APPROVED** [review]
lgtm. I think @carllin should look at it.

File: ledger/src/blockstore_processor.rs (hunk 1 above)
Comment (steviez) [reply ledger/src/blockstore_processor.rs]: Using `halt_at_slot` is a change in behavior in v1.13 since we started grabbing new shreds while we're processing the local ledger (ie prevents load_frozen_forks() from running indefinitely). So, this is not an issue in v1.13 and I'll be removing the backport label

**Comment by steviez** [comment]
> lgtm. I think @carllin should look at it.

@carllin and I discussed this on a call and I got a verbal ship-it. One thing that Carl suggested is that we potentially promote the "set_hash: already_exists" ERROR that I included above to a panic right there. But, we decided we could discuss this separately so we can be more thorough in ensuring we don't break something else
