### PR TITLE
fix rewards points

### LINKED ISSUE #10872: Review inflation on testnet
We've had inflation enabled on testnet for a while.  There's been some concern that perhaps inflation rewards are too high:
```
$ solana balance aeydu5w2pqtTAk9p1rk1ruENuPSyMqukK1reb8Q1j7J -v
RPC URL: http://testnet.solana.com
Default Signer Path: /Users/mvines/.config/solana/id.json
6591257.120711175 SOL
```

image

Review the implementation and testnet inflation configuration, do the rewards make sense?

### PR DESCRIPTION
**Pull request by rwalker-com**
#### Problem
 Stakes.points overflows on a normal network, which leads to an inflated point_value, which leads to an overpayment of validators (excess inflation).

 #### Summary of Changes
 * promote "points" to u128
 * since Stakes.points is a u64 and expanding it to u128 would break bank deserialization from a snapshot, move calculation of points per epoch into pay_validator_rewards() instead of the incremental calculation previously performed by Stakes
 * remove tests for Stakes.points -> Stakes.unused
 * re-order the tuples that were `(voter_rewards, staker_rewards)` to `(staker_rewards, voter_rewards)` for a little bit more sanity

Fixes #10872

### CODE REVIEW

**Comment by aeyakovenko** [comment]
When casting back to u64, can we use into?  That should force an exception in release mode

**Comment by rwalker-com** [comment]
> When casting back to u64, can we use into? That should force an exception in release mode

which line?

**Comment by rwalker-com** [comment]
> Can we used checked_math? Also is the conversion back to u64 ok? I can’t tell if ‘as’ causes a runtime exception in release mode

```
fn main() {
    let x = (std::u64::MAX as f64) + 1.0;

    dbg!((x, x as u64));
}
```

**Comment by rwalker-com** [comment]
looks like [rug](https://docs.rs/rug/1.9.0/rug/) might help here.  the simple conversion from u64->f64->u64 that results in huge loss of value is what rug can help address

**Comment by aeyakovenko** [comment]
Why can’t we do the math in u128?

**Comment by rwalker-com** [comment]
> Why can’t we do the math in u128?

working on an update

**Comment by rwalker-com** [comment]
updated

you guys wanna try a CI run at some point?  I can't initiate.

**Comment by mvines** [comment]
> you guys wanna try a CI run at some point? I can't initiate.

Fixed, I added your github user id to the allow list

**Comment by mvines** [comment]
@sakridge - the next testnet restart ideally would include this inflation fix

File: programs/stake/src/stake_state.rs [hunk 1]
```diff
@@ -362,43 +362,57 @@ impl Authorized {
     }
 }
 
+/// captures a rewards round as lamports to be awarded
+///  and the total points over which those lamports
+///  are to be distributed
+//  basically read as rewards/points, but in integers instead of as an f64
+pub struct PointValue {
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:369]: nits: I'd like this to be named like `InflationRound` or something to be neutral to both of its members `rewards` and `points`.

**Comment by ryoqun** [comment]
Also, I think this must be released as a scheduled and coordinated update otherwise we must retain the old behavior with gating at a particular epoch. That gating sounds bothersome for the nature of this change.

File: runtime/src/bank.rs [hunk 2]
```diff
@@ -691,77 +691,106 @@ impl Bank {
...
             .iter()
             .map(|(stake_pubkey, delegation)| {
+                match (
+                    self.get_account(&stake_pubkey),
+                    self.get_account(&delegation.voter_pubkey),
+                ) {
+                    (Some(stake_account), Some(vote_account)) => stake_state::calculate_points(
+                        &stake_account,
+                        &vote_account,
+                        Some(&stake_history),
```
Comment (ryoqun) [inline runtime/src/bank.rs:736]: It looks like `calculate_points` can be changed to take `&StakeHistory` instead of `Option<&StakeHistory>`, eliminating accidental risk of passing `None` within production codebase.

File: runtime/src/bank.rs [hunk 3]
```diff
@@ -691,77 +691,106 @@ impl Bank {
...
                     self.get_account(&delegation.voter_pubkey),
                 ) {
                     (Some(mut stake_account), Some(mut vote_account)) => {
-                        let rewards = stake_state::redeem_rewards(
+                        let redeemed = stake_state::redeem_rewards(
                             &mut stake_account,
                             &mut vote_account,
-                            point_value,
+                            &point_value,
                             Some(&stake_history),
```
Comment (ryoqun) [inline runtime/src/bank.rs:765]: nits: Not related to this pr's change per se, but I'd like to change this to take `&StakeHistory` with similar spirit of [this](https://github.com/solana-labs/solana/pull/10914/files#r451370146).

File: runtime/src/bank.rs (hunk 2 above)
Comment (ryoqun) [reply runtime/src/bank.rs:736]: Also, this alleviates code reviewer/reader's cognitive load to some extent. :)

File: programs/stake/src/stake_state.rs [hunk 4]
```diff
@@ -863,6 +906,22 @@ pub fn redeem_rewards(
...
 
+// utility function, used by runtime
+pub fn calculate_points(
+    stake_account: &Account,
+    vote_account: &Account,
+    stake_history: Option<&StakeHistory>,
+) -> Result<u128, InstructionError> {
+    if let StakeState::Stake(_meta, stake) = stake_account.state()? {
+        let vote_state: VoteState =
+            StateMut::<VoteStateVersions>::state(vote_account)?.convert_to_current();
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:917]: nits: How about extracting this code identical with https://github.com/solana-labs/solana/pull/10914/files#diff-0c1e264efc2089624e55f89513c862b8R888-R890? That would ensure we use identical iteration condition when summing up point and paying rewards. (Yeah, I've tried to find a discrepancy but to no avail..)

File: runtime/src/bank.rs [hunk 5]
```diff
@@ -691,77 +691,106 @@ impl Bank {
...
+        let stake_delegations = self.stake_delegations();
+
+        // first, count total points
+        let points: u128 = stake_delegations
             .iter()
             .map(|(stake_pubkey, delegation)| {
+                match (
+                    self.get_account(&stake_pubkey),
+                    self.get_account(&delegation.voter_pubkey),
+                ) {
```
Comment (ryoqun) [inline runtime/src/bank.rs:732]: nits: similar to this: https://github.com/solana-labs/solana/pull/10914/files#r451380866, we could extract this iterator code identical with https://github.com/solana-labs/solana/pull/10914/files#diff-a7549f152920d85fb44e6a784b8e5e1fR753-R759,
into a generic helper `fn` which takes a closure

Comment (ryoqun) [reply runtime/src/bank.rs:732]: , which can ensure we're operating on the exactly identical set of accounts...

File: runtime/src/stakes.rs [hunk 6]
```diff
@@ -15,9 +15,8 @@ pub struct Stakes {
     /// stake_delegations
     stake_delegations: HashMap<Pubkey, Delegation>,
 
-    /// unclaimed points.
-    //  a point is a credit multiplied by the stake
-    points: u64,
+    /// unused
+    unused: u64,
```
Comment (ryoqun) [inline runtime/src/stakes.rs:19]: @rwalker-com Well, I just noticed that this changes ABI digest when merged. This field renaming should be no harm. Could you rebase this pr to be after #8012 and update the ABI digest of `Bank`?

File: programs/stake/src/stake_state.rs [hunk 7]
```diff
@@ -414,29 +428,57 @@ impl Stake {
                 0
             };
 
-            total_rewards +=
-                (self.delegation.stake(*epoch, stake_history) * epoch_credits) as f64 * point_value;
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:418]: nits: Also, it'd be great if we could add a tiny unit-test causing this actually to overflow to avoid any future regressions. :)

File: runtime/src/stakes.rs [hunk 8]
```diff
@@ -106,15 +112,6 @@ impl Stakes {
...
                 );
 
-                // count any increase in points, can only go forward
-                let old_credits = old
-                    .and_then(|(_stake, old_account)| VoteState::credits_from(old_account))
-                    .unwrap_or(0);
-
-                let credits = VoteState::credits_from(account).unwrap_or(old_credits);
-
-                self.points += credits.saturating_sub(old_credits) * stake;
```
Comment (ryoqun) [inline runtime/src/stakes.rs:116]: nits: same with [this](https://github.com/solana-labs/solana/pull/10914/files#r451941881)

File: runtime/src/bank.rs [hunk 9]
```diff
@@ -691,77 +691,106 @@ impl Bank {
...
                 validator_point_value,
             )
         });
 
-        let validator_rewards = self.pay_validator_rewards(validator_point_value);
+        let validator_rewards_paid =
+            self.stakes.read().unwrap().vote_balance_and_staked() - vote_balance_and_staked;
+
+        // verify that we didn't pay any more than we expected to
+        assert!(validator_rewards >= validator_rewards_paid);
```
Comment (rwalker-com) [inline runtime/src/bank.rs:712]: @aeyakovenko this is the check you wanted, I think.  we sum the vote and stake balances before and after and verify that it's less than the value of rewards

Comment (aeyakovenko) [reply runtime/src/bank.rs:712]: @sakridge @ryoqun wdyt?  Does that work as a secondary computation that would have caught a similar overflow bug?

File: programs/stake/src/stake_state.rs (hunk 7 above)
Comment (rwalker-com) [reply programs/stake/src/stake_state.rs:418]: done

File: programs/stake/src/stake_state.rs (hunk 4 above)
Comment (rwalker-com) [reply programs/stake/src/stake_state.rs:917]: these functions differ in account mutability...

File: runtime/src/bank.rs (hunk 2 above)
Comment (rwalker-com) [reply runtime/src/bank.rs:752]: lots of tests that don't have a StakeHistory depend on the option

File: runtime/src/stakes.rs (hunk 6 above)
Comment (rwalker-com) [reply runtime/src/stakes.rs:19]: I've rebased, but how do I ensure I've done the right thing here with a local test?

File: programs/stake/src/stake_state.rs (hunk 1 above)
Comment (rwalker-com) [reply programs/stake/src/stake_state.rs:369]: because the previous code used "point_value" as the name of an f64, I'm inclined to leave this as is because it matches previous meaning:
`PointValue: point_value`

There's more to an InflationRound than validator points...

File: runtime/src/bank.rs (hunk 5 above)
Comment (rwalker-com) [reply runtime/src/bank.rs:748]: unfortunately, bank and account mutability rule out a clean closure form.  I've written a function that boils the stake_delegations down to the parts we want to operate on in this function, instead

**Comment by rwalker-com** [comment]
> > you guys wanna try a CI run at some point? I can't initiate.
> 
> Fixed, I added your github user id to the allow list

Appears I am still unable to put a CI label on this.

**Comment by mvines** [comment]
> > > you guys wanna try a CI run at some point? I can't initiate.
> > 
> > 
> > Fixed, I added your github user id to the allow list
> 
> Appears I am still unable to put a CI label on this.

You shouldn't have to, CI will just start for you automatically. That seems to be happening now

File: runtime/src/stakes.rs (hunk 6 above)
Comment (mvines) [reply runtime/src/stakes.rs:19]: I don't think we have a way to add a test here, updating the digest is just a manual human thing

**Comment by mvines** [comment]
@sakridge - think you can help get this PR over the line so we can deploy it on testnet.  The total supply on testnet is still creeping up and we overflow u64 at 18b SOL right?

**Comment by rwalker-apple** [comment]
I've rebased this and hopefully fixed the conflicts

**Comment by rwalker-com** [comment]
rebased

**Comment by rwalker-com** [comment]
last rebase by me

File: runtime/src/stakes.rs (hunk 6 above)
Comment (rwalker-com) [reply runtime/src/stakes.rs:19]: "What steps does one use test the abi stuff locally?" was really my question.

Comment (mvines) [reply runtime/src/stakes.rs:19]: Just the 🧠, I'm afraid.  There's nothing nice here :-/

**Comment by mvines** [comment]
Thanks @rwalker-com, we'll take it from here!

File: runtime/src/stakes.rs (hunk 6 above)
Comment (rwalker-com) [reply runtime/src/stakes.rs:19]: sorry, even more specific: how do I run a test locally that fails when checking this hash?  I have tried a fair few things and failed to reproduce the failure that shows up in CI.

Comment (mvines) [reply runtime/src/stakes.rs:19]: Oh, sorry.  I see what you mean.   You just need to use a recent nightly I think, is that right @ryoqun?

Comment (ryoqun) [reply runtime/src/stakes.rs:19]: Yeah, just plain official recent nightly should be enough.

Comment (rwalker-com) [reply runtime/src/stakes.rs:19]: please guys: I'm a good ways out of the normal dev flow these days, using an old personal Mac or a WSL box to dev and test.  `cargo test` never completes locally for me.  I was looking for STR locally for this specific failure in CI.

perhaps it's:

`cargo +nightly test --package solana-runtime abi -- --nocapture` ?

Comment (ryoqun) [reply runtime/src/stakes.rs:19]: @rwalker-com Yeah exactly that will work.

I use this particular arguments (`--lib` reduces the build time a bit and abi tests doesn't need them): 

```
cargo test --lib -- --test-threads 2 test_abi_ --nocapture
```

Comment (ryoqun) [reply runtime/src/stakes.rs:19]: Oh, my rustup default is to use `nightly`, btw.

Comment (rwalker-com) [reply runtime/src/stakes.rs:19]: ok.  once one has reproduced this test failure, there's this suggestion:
`Confirm the diff by rerunning before and after this test failed with SOLANA_ABI_DUMP_DIR!', runtime/src/serde_snapshot/tests.rs:285:5`

File: programs/stake/src/stake_state.rs [hunk 10]
```diff
@@ -414,29 +428,57 @@ impl Stake {
...
 
-        let (voter_rewards, staker_rewards, is_split) = vote_state.commission_split(total_rewards);
+        let rewards = points
+            .checked_mul(u128::from(point_value.rewards))
+            .unwrap()
+            .checked_div(point_value.points)
+            .unwrap();
+
+        assert!(rewards <= u128::from(std::u64::MAX));
+        let rewards = rewards as u64;
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:466]: nits: I think we can use `try_from` like this: `let rewards = u64::try_from(rewards).unwrap()`

File: programs/stake/src/stake_state.rs [hunk 11]
```diff
@@ -2191,6 +2264,47 @@ mod tests {
         assert_eq!(stake.credits_observed, 2);
     }
 
+    #[test]
+    fn test_stake_state_calculate_points_with_typical_values() {
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:2268]: a good test. :)

File: programs/vote/src/vote_state/mod.rs [hunk 12]
```diff
@@ -253,13 +253,16 @@ impl VoteState {
...
-            0 => (0.0, on, false),
-            100 => (on, 0.0, false),
+            0 => (0, on, false),
+            100 => (on, 0, false),
             split => {
-                let mine = on * f64::from(split) / f64::from(100);
-                (mine, on - mine, true)
+                let on = u128::from(on);
+                let mine = on * u128::from(split) / 100u128;
+                let theirs = on * u128::from(100 - split) / 100u128;
```
Comment (ryoqun) [inline programs/vote/src/vote_state/mod.rs:263]: @rwalker-com Btw, is there any specific reason for changing the formula here slightly? This may cause 1 lamports to gone: https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=f8f4403a1b9638be9e2455e246ac40d6

If so, could you comment a bit on this pr? I'll copy that into the source code as well. :)

However, this won't cause capitalization/total-supply mismatches.

File: runtime/src/bank.rs (hunk 9 above)
Comment (ryoqun) [reply runtime/src/bank.rs:918]: Yeah, this should work, if we should be extremely careful (I think this is the case), I'd make `vote_balance_and_staked` return `u128` instead of `u64`. Also, I'll slightly modify the assertion like this:

```rust
    let pre_vote_balance_and_staked = ...vote_balance_and_staked();
    let max_vote_balance_and_staked = pre_vote_balance_and_staked + validator_rewards;

    // Do the fun math!
    ... self.pay_validator_rewards(validator_rewards);

    let post_vote_balance_and_staked = ...vote_balance_and_staked();

    assert!(max_vote_balance_and_staked >= post_vote_balance_and_staked && post_vote_balance_and_staked >= pre_vote_balance_and_staked);
```

The code rearrangement reason is that:
1. Don't further compute anything on possibly-contaminated (= might be already overflowing) values from riskier code (`pay_validator_rewards()`)
1. Assert the interval, not one-sided range. (This isn't perfect still, under possible overflow flaw assumption. it's still possible attacker can manage to get the crafted value into the interval. Anyway, this is better than one-sided only one `>=` assertion).

File: programs/stake/src/stake_state.rs (hunk 10 above)
Comment (rwalker-com) [reply programs/stake/src/stake_state.rs:466]: please feel free to push that update to my fork

File: runtime/src/bank.rs [hunk 13]
```diff
@@ -897,77 +897,116 @@ impl Bank {
...
-    fn pay_validator_rewards(&mut self, point_value: f64) -> u64 {
-        let stake_history = self.stakes.read().unwrap().history().clone();
-        let mut validator_rewards = HashMap::new();
-
-        let total_validator_rewards = self
+    /// map stake delegations into resolved (pubkey, account) pairs
+    ///  returns a vector (has to be copied) of loaded
+    ///   ( (staker info) (voter info) )
+    ///
+    fn stake_delegation_accounts(&self) -> Vec<((Pubkey, Account), (Pubkey, Account))> {
```
Comment (ryoqun) [inline runtime/src/bank.rs:928]: I love this helper fn. Reasoning got a lot easier. :)

File: programs/vote/src/vote_state/mod.rs (hunk 12 above)
Comment (rwalker-com) [reply programs/vote/src/vote_state/mod.rs:263]: Yes: a lamport may be lost with this version.  I was upset with the f64->u64 conversion wherein faithful conversion is capped at ~2^53.

This version is intended to catch the case where the small side gets paid 0 as a result of the integer math.

If the small side would receive zero when the split isn't 0 or 100, we don't pay either side.

File: runtime/src/bank.rs (hunk 9 above)
Comment (rwalker-com) [reply runtime/src/bank.rs:918]: 1. if`vote_balance_and_staked()` needs to be u128, so does `bank.capitalization()`.
2. I like the range check, but could also be accomplished (possibly more concisely) with a u64::checked_add() to capitalization

File: programs/vote/src/vote_state/mod.rs (hunk 12 above)
Comment (ryoqun) [reply programs/vote/src/vote_state/mod.rs:268]: @rwalker-com Thanks for explaining! I've tried to comment the intention combining your explanation with [these new test assertions](https://github.com/solana-labs/solana/pull/10914/files#diff-3666262446ea129567c6d96960c7e23cR1574-R1578): 29c444343e

Does this make sense?

File: runtime/src/bank.rs (hunk 9 above)
Comment (ryoqun) [reply runtime/src/bank.rs:918]: @rwalker-com

> * if`vote_balance_and_staked()` needs to be u128, so does `bank.capitalization()`.

I think `vote_balance_and_staked() -> u128` have some merit to detect otherwise possible overflow within the range of `u64` due to wrong calucation in `pay_validator_rewards`, while leaving `bank.capitalization()` to remain as `u64`. In other words, `vote_balance_and_staked() -> u128` can be justified for its sole and temporal sanity checking purpose.

> * I like the range check, but could also be accomplished (possibly more concisely) with a u64::checked_add() to capitalization

I like `u64::checked_add()` (but it's seems cumbersome to do with `AtomicU64`...)!
On the other hand, `u128` range check is still needed to detect really extreme overflows like wrapping u64::MAX twice in `pay_validator_rewards()`?

Or is it too much? Also, I think extra cpu cost due to these u128 basic math is negligible because it's just done once for an epoch.

**Comment by ryoqun** [comment]
Ok, CI has passed. :)

Status: This PR is merge-able and backport-able anytime if we decide to restart the halted cluster. The only remaining concern is https://github.com/solana-labs/solana/pull/10914#discussion_r454620416 (waiting on @rwalker-com's reply), but this is minor and shouldn't be a blocker because this is just an assertion adjustments.

**Comment by ryoqun** [comment]
I've found bug.... Please don't merge this. The bug first needs to be fixed...

File: runtime/src/bank.rs [hunk 14]
```diff
@@ -897,77 +897,116 @@ impl Bank {
             let inflation = self.inflation.read().unwrap();
 
             (*inflation).validator(year) * self.capitalization() as f64 * period
-        };
+        } as u64;
+
+        let vote_balance_and_staked = self.stakes.read().unwrap().vote_balance_and_staked();
```
Comment (ryoqun) [inline runtime/src/bank.rs:902]: MUST FIX: use of `vote_balance_and_staked()` here incorrectly accounts for the warm-up handling of stakes.

we need like this:

```patch
diff --git a/runtime/src/stakes.rs b/runtime/src/stakes.rs
index cb68d79ce4..9f2997632c 100644
--- a/runtime/src/stakes.rs
+++ b/runtime/src/stakes.rs
@@ -94,10 +94,22 @@ impl Stakes {
             .sum()
     }
 
+    pub fn total_vote_balance_and_stakes(&self) -> u64 {
+        self.stake_delegations
+            .iter()
+            .map(|(_, stake_delegation)| {
+                stake_delegation.stake
+            })
+            .sum::<u64>() +
+        self.vote_accounts
+            .iter()
+            .map(|(_pubkey, (_staked, vote_account))| vote_account.lamports)
+            .sum::<u64>()
+    }
+

```

File: runtime/src/bank.rs [hunk 15]
```diff
@@ -897,77 +897,116 @@ impl Bank {
...
+            |((stake_pubkey, stake_account), (vote_pubkey, vote_account))| {
+                let redeemed = stake_state::redeem_rewards(
+                    stake_account,
+                    vote_account,
+                    &point_value,
+                    Some(&stake_history),
+                );
+                if let Ok((stakers_reward, voters_reward)) = redeemed {
+                    self.store_account(&stake_pubkey, &stake_account);
+                    self.store_account(&vote_pubkey, &vote_account);
```
Comment (ryoqun) [inline runtime/src/bank.rs:989]: still not sure: when storing vote_pubkey happens multiple times, this overwrites any immediately written account state because we merely get_account at the start of this fn (with `stake_delegation_accounts`) and only once, reusing them. What's the correct behavior?

Comment (ryoqun) [reply runtime/src/bank.rs]: Well, this was another bug... fixed https://github.com/solana-labs/solana/pull/10914/commits/8472fc3f0825c1c2d4a68050bd667095d517081e

File: runtime/src/bank.rs (hunk 14 above)
Comment (ryoqun) [reply runtime/src/bank.rs:903]: Fixed https://github.com/solana-labs/solana/pull/10914/commits/0218d32705392151c5e8e4e043d7709aefbcef72

**Comment by ryoqun** [comment]
Just pushed all fixes and an assertion as a bonus.

Mostly tested with #11107 

todo: add unit-tests....

File: programs/stake/src/stake_state.rs [hunk 16]
```diff
@@ -836,17 +877,18 @@ impl<'a> StakeAccount for KeyedAccount<'a> {
...
 ) -> Result<(u64, u64), InstructionError> {
     if let StakeState::Stake(meta, mut stake) = stake_account.state()? {
         let vote_state: VoteState =
             StateMut::<VoteStateVersions>::state(vote_account)?.convert_to_current();
 
-        if let Some((voters_reward, stakers_reward)) =
+        if let Some((stakers_reward, voters_reward)) =
             stake.redeem_rewards(point_value, &vote_state, stake_history)
         {
             stake_account.lamports += stakers_reward;
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:894]: nits: btw https://github.com/solana-labs/solana/pull/10914/files#diff-0c1e264efc2089624e55f89513c862b8R897 needs to be `.unwrap()` and incremented `.lamports`. Otherwise, we might hide serious issues in the code, resulting in silently fail to deliver legitimate rewards to stakers because we're silently discarding errors for that accounts. 

Before reaching to that code, we've only done `redeem_rewards()` (note: doesn't return `Result`/`Option`; should always succeed.) after successfully restoring the stake state.

Comment (rwalker-apple) [reply programs/stake/src/stake_state.rs:894]: `redeem_rewards()` returns `None` in the case where no rewards are paid, to indicate that `credits_observed` shouldn't be changed

Comment (ryoqun) [reply programs/stake/src/stake_state.rs:894]: @rwalker-com Sorry, my comment was misleading.. I commented about the `?` in  `stake_account.set_state(...)`_**`?`**_ here:

https://github.com/solana-labs/solana/blob/d19cd3a18aee0a5cb859bba6aac07cd10e1af508/programs/stake/src/stake_state.rs#L855

I'm aware the case `redeem_rewards()` returning `None` is legitimate as you mentioned and I think it's not affected by converting the `?` on `.set_state()` to `unrwap()`.

File: runtime/src/bank.rs (hunk 13 above)
Comment (rwalker-com) [reply runtime/src/bank.rs]: @ryoqun I think this approach still has merit, if the `store_account()` phase is moved until after all the stakes have been processed, or if the vote_account is modified while in the vector

File: programs/stake/src/stake_state.rs (hunk 16 above)
Comment (rwalker-com) [reply programs/stake/src/stake_state.rs:894]: I think changing the '?' to '.unwrap()' might be problematic unless the `redeem_rewards()` instruction is no longer valid.

The error is not silently ignored.  Any failure in this path should prevent any `store_account()`.

Comment (ryoqun) [reply programs/stake/src/stake_state.rs:894]: Thanks for explaining further! Bear with me for following questions because I'm still new to the `stake` native program...

> I think changing the `?` to `.unwrap()` might be problematic unless the `redeem_rewards()` instruction is no longer valid.

Yeah, I think it's problematic if the instruction is still valid. At the same time, I think `RedeemVoteCredits` instruction is no longer valid since #7916. Assuming you're probably worried about `.unwrap()` on untrusted user-supplied transaction, is there something else that's open to attacks still? I thought the only valid call-path to this `redeem_rewards` function is now from `Bank::update_rewards()`, which can be regarded as processing on trusted data set.

Also, https://github.com/solana-labs/solana/blob/d19cd3a18aee0a5cb859bba6aac07cd10e1af508/programs/stake/src/stake_state.rs#L855 is ensured to `set_state()` something that is just successfully loaded from `StakeState::Stake(meta, mut stake)`.



> The error is not silently ignored. Any failure in this path should prevent any `store_account()`.

Yeah,  `store_account()` of both the stake and the vote _for that particular delegation_ isn't stored. For other delegations, they just succeeds because we're continuing the outer loop while ignoring the error: https://github.com/solana-labs/solana/blob/d19cd3a18aee0a5cb859bba6aac07cd10e1af508/runtime/src/bank.rs#L956-L962

I agree it's ok to continue the loop without doing `store_account()` in the case where no rewards are paid for some delegations. But I think it's problematic to ignore something that shouldn't occur ever (= bad state transition in `Stake::redeem_accounts(&mut self)`, where it's only setting `self.credits_ovserved` and incrementing `self.delegation.stake` by `stakers_reward`).

File: runtime/src/bank.rs [hunk 17]
```diff
@@ -898,77 +899,135 @@ impl Bank {
...
-    fn pay_validator_rewards(&mut self, point_value: f64) -> u64 {
-        let stake_history = self.stakes.read().unwrap().history().clone();
-        let mut validator_rewards = HashMap::new();
-
-        let total_validator_rewards = self
+    /// map stake delegations into resolved pubkeys
+    ///  returns a vector (has to be copied) of loaded
+    ///   ( staker pubkey voter pubkey )
+    ///
+    fn stake_delegation_pubkeys(&self) -> Vec<(Pubkey, Pubkey)> {
```
Comment (ryoqun) [inline runtime/src/bank.rs:936]: (repost of https://github.com/solana-labs/solana/commit/8472fc3f0825c1c2d4a68050bd667095d517081e#r40694986)

> nice catch.
> 
> this could also return a hashmap ordered by the voter pubkey, then we'd re-organize the loop to store the vote accounts just once

Comment (ryoqun) [reply runtime/src/bank.rs:936]: Commenting on https://github.com/solana-labs/solana/blob/0218d32705392151c5e8e4e043d7709aefbcef72/runtime/src/bank.rs#L941

(repost of https://github.com/solana-labs/solana/pull/10914#discussion_r457000764):

> @ryoqun I think this approach still has merit, if the `store_account()` phase is moved until after all the stakes have been processed, or if the vote_account is modified while in the vector

Comment (ryoqun) [reply runtime/src/bank.rs]: @rwalker-com Yeah, I generally agree that your suggestion is more cleaner than my hacky approach. Reverted mine (https://github.com/solana-labs/solana/pull/10914/commits/8608e4eb19f01bb79aa893355c8998d33fcb100a) and I think https://github.com/solana-labs/solana/pull/10914/commits/ef5f158ea47a8dd7bc8f63db49eeb74dc4500ceb is what you meant.

**Comment by ryoqun** [comment]
Ok, this is ready for review again!

@rwalker-com If it's not too much for you, could you review my changes? If not, I'm going to ask other to review this. :)

File: runtime/src/bank.rs [hunk 18]
```diff
@@ -898,77 +899,131 @@ impl Bank {
...
+                    }
+                } else {
+                    debug!(
+                        "stake_state::redeem_rewards() failed for {}: {:?}",
+                        stake_pubkey, redeemed
+                    );
+                }
+            }
+
+            if vote_account_changed {
```
[the remark this answers is not in the document]
Comment (ryoqun) [reply runtime/src/bank.rs:1019]: I think this optimization isn't crucial, but important and worthwhile considering the relatively low risk of introducing bugs (just simple flagging) and the anticipated reduction of work. This should reduce the needless writes at best to `1/2`, assuming there's disparity between the number of unique validator and stakers. For realistic example, say validators are 100 and stakers are 100,000, the write count is 200,000 (the original) vs 100100 (the optimized).

Also, I thought this is what you meant by this comment:

https://github.com/solana-labs/solana/commit/8472fc3f0825c1c2d4a68050bd667095d517081e#r40694986:

> ... we'd re-organize the loop to store the vote accounts just once

[the remark this answers is not in the document]
Comment (rwalker-com) [reply runtime/src/bank.rs:1019]: I was thinking that with a data structure that held each account just once, all the rewards could be calculated and paid into that mutable table and then they could be stored all in one go

**Comment by ryoqun** [comment]
I've compared new inflation calculation with latest mainnet-beta snapshot, utilizing recently added `ledger-tool capitalization` functionality:

```bash
$ ./target/release/solana-ledger-tool --ledger target/mainnet-beta15/ capitalization --warp-epoch +1 --enable-inflation >| target/mainnet-beta15/capitalization-no-overflow
...
[2020-07-21T03:55:03.843793367Z INFO  solana_runtime::bank] bank frozen: 23761802 hash: DrSCHayYWndjEK3M35hAMS5sQJkznFfLzRD6oZr9BZ26 accounts_delta: 83wrntxHZpFeAuS5rcSKseyJKL3d4vvKryMF8ktAjSL4 signature_count: 124 last_blockhash: 2HQcb76oRJLgH4pMoQtJm6nkMM6chZhjpmvFG99Dzd4v capitalization: 488626201531987508
[2020-07-21T03:55:03.843823664Z INFO  solana_runtime::bank] accounts hash slot: 23761802 stats: BankHashStats { num_updated_accounts: 251, num_removed_accounts: 0, num_lamports_stored: 52048188226095, total_data_len: 609092, num_executable_accounts: 0 }
...
[2020-07-21T03:55:03.969062767Z INFO  solana_runtime::bank] bank frozen: 24192000 hash: BnDiHCwYSszshnCmm54McYNdqP7FMVd5CGF1HYFF3Go2 accounts_delta: CCkJrFm9DrAnHg3P435rh1B5ieTXSx2miWQsdguEQxnw signature_count: 0 last_blockhash: 2HQcb76oRJLgH4pMoQtJm6nkMM6chZhjpmvFG99Dzd4v capitalization: 13709020889550056491
[2020-07-21T03:55:03.969087307Z INFO  solana_runtime::bank] accounts hash slot: 24192000 stats: BankHashStats { num_updated_accounts: 1381, num_removed_accounts: 0, num_lamports_stored: 14333192310963718245, total_data_len: 2878352, num_executable_accounts: 1 }
...
$ ./target/release/solana-ledger-tool --ledger target/mainnet-beta15/ capitalization --warp-epoch +1 --enable-inflation >| target/mainnet-beta15/capitalization-overflow
...
[2020-07-21T04:00:54.728785041Z INFO  solana_runtime::bank] bank frozen: 23761802 hash: DrSCHayYWndjEK3M35hAMS5sQJkznFfLzRD6oZr9BZ26 accounts_delta: 83wrntxHZpFeAuS5rcSKseyJKL3d4vvKryMF8ktAjSL4 signature_count: 124 last_blockhash: 2HQcb76oRJLgH4pMoQtJm6nkMM6chZhjpmvFG99Dzd4v capitalization: 488626201531987508
[2020-07-21T04:00:54.728813881Z INFO  solana_runtime::bank] accounts hash slot: 23761802 stats: BankHashStats { num_updated_accounts: 251, num_removed_accounts: 0, num_lamports_stored: 52048188226095, total_data_len: 609092, num_executable_accounts: 0 }
...
[2020-07-21T04:00:54.840529412Z INFO  solana_runtime::bank] bank frozen: 24192000 hash: HUA7misCajisCezFq3tUV9Sh9KE3ZVRKkwfvq8sukacM accounts_delta: iQbHAC1jPxmVnosqUYqgS3XQzgv2zoEoXDkZMuoqKnh signature_count: 0 last_blockhash: 2HQcb76oRJLgH4pMoQtJm6nkMM6chZhjpmvFG99Dzd4v capitalization: 488988943053896048
[2020-07-21T04:00:54.840550668Z INFO  solana_runtime::bank] accounts hash slot: 24192000 stats: BankHashStats { num_updated_accounts: 832, num_removed_accounts: 0, num_lamports_stored: 138381105387422228, total_data_len: 830033, num_executable_accounts: 1 }
...

$ diff -U100 <(cat -n target/mainnet-beta15/capitalization-overflow) <(cat -n target/mainnet-beta15/capitalization-no-overflow)  | tee >(grep -v '^[+-] ') >(sleep 1 && grep '^[+-] ' | sort --stable -k2 -n) > /dev/null | (sleep 2; cat)
```
And this is the result

```patch
--- /dev/fd/63  2020-07-21 12:41:22.046014583 +0900
+++ /dev/fd/62  2020-07-21 12:41:22.050014873 +0900
@@ -1,194 +1,194 @@
      1 Forcing to: Inflation { initial: 0.15, terminal: 0.015, taper: 0.15, foundation: 0.05, foundation_term: 7.0, storage: 0.0 } (was: Inflation { initial: 0.0, terminal: 0.0, taper: 0.0, foundation: 0.0, foundation_term: 0.0, storage: 0.0 })
      2 Slot: 23761802 => 24192000
      3 Epoch: 55 => 56
-     4 Capitalization: ◎488626201.531987508 => ◎13709020889.550056491 (+◎13220394688.018068983 2805.625413980713%)
+     4 Capitalization: ◎488626201.531987508 => ◎488988943.053896048 (+◎362741.521908540 100.07423701814828%)
-     5 1gqv7KGm888nQXsJoNFwGaDkNERUBztuekjzK3J3T7a(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3160446.460839645 (+◎3160446.433981005)
+     5 1gqv7KGm888nQXsJoNFwGaDkNERUBztuekjzK3J3T7a(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.201320323 (+◎38.174461683)
-     6 ChGuXymbpskcEjvL3xTQz13q8ym4Ud9xrHGchibh9ZP(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎51516989.838023896 (+◎51466989.838023896)
+     6 ChGuXymbpskcEjvL3xTQz13q8ym4Ud9xrHGchibh9ZP(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50642.138771540 (+◎642.138771540)
-     7 LneJvrSDJGqfpbsKHPfyaxSPecBtqRHTJnwyBzG4vPC(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎151930117.613680078 (+◎151930117.586821438)
+     7 LneJvrSDJGqfpbsKHPfyaxSPecBtqRHTJnwyBzG4vPC(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2176.649512368 (+◎2176.622653728)
-     8 LunaFpQkZsZVJL2P2BUqNDJqyVYqrw9buQnjQtMLXdK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎177577880.292861733 (+◎177577880.266003093)
+     8 LunaFpQkZsZVJL2P2BUqNDJqyVYqrw9buQnjQtMLXdK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2254.106509916 (+◎2254.079651276)
-     9 ReisexxCMaQsBut8iqbhR9hncCs1ofw9EDticAeNdmt(Stake11111111111111111111111111111111111111): ◎105.889950000 => ◎187263.111889559 (+◎187157.221939559)
+     9 ReisexxCMaQsBut8iqbhR9hncCs1ofw9EDticAeNdmt(Stake11111111111111111111111111111111111111): ◎105.889950000 => ◎106.455170313 (+◎0.565220313)
-    10 SFund7s2YPS7iCu7W2TobbuQEpVEAv9ZU7zHKiN1Gow(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎14226296.751289849 (+◎14226296.724431209)
+    10 SFund7s2YPS7iCu7W2TobbuQEpVEAv9ZU7zHKiN1Gow(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎252.990426556 (+◎252.963567916)
-    11 VNbW721iu6uVkrx246N2BiQth8u4b4SCPJwH3JvUovD(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3150124.679505763 (+◎3150124.652647123)
+    11 VNbW721iu6uVkrx246N2BiQth8u4b4SCPJwH3JvUovD(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.170148240 (+◎38.143289600)
-    12 VvsLEK3cRh8wPw4qrHKPHX7Jx3wHMng5xj2hLuc7ZFD(Stake11111111111111111111111111111111111111): ◎1000000.000000000 => ◎21048201.883909132 (+◎20048201.883909132)
+    12 VvsLEK3cRh8wPw4qrHKPHX7Jx3wHMng5xj2hLuc7ZFD(Stake11111111111111111111111111111111111111): ◎1000000.000000000 => ◎1001774.040916799 (+◎1774.040916799)
-    13 abc1zP7ihWsgQW8z5YmfQNqMckJE5Dfx8fwUNMNVNkY(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎115712926.085519685 (+◎115712926.058661045)
+    13 abc1zP7ihWsgQW8z5YmfQNqMckJE5Dfx8fwUNMNVNkY(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1594.880490448 (+◎1594.853631808)
-    14 ateamaZDqNWDztxnVKZhRsp4ac53KvT1rVKyU5LnL6o(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎247105573.706102108 (+◎247105573.679243468)
+    14 ateamaZDqNWDztxnVKZhRsp4ac53KvT1rVKyU5LnL6o(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎7188.002572875 (+◎7187.975714235)
-    15 beefKGBWeSpHzYBHZXwp5So7wdQGX6mu4ZHCsH3uTar(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎74682034.030915865 (+◎74682034.004057225)
+    15 beefKGBWeSpHzYBHZXwp5So7wdQGX6mu4ZHCsH3uTar(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1886.098387189 (+◎1886.071528549)
-    16 cover89z945JotsCRGdbjakJm4rnL5XspFSPgN1mVZj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3088118.907972998 (+◎3088118.881114358)
+    16 cover89z945JotsCRGdbjakJm4rnL5XspFSPgN1mVZj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎37.982888987 (+◎37.956030347)
-    17 g4MMQmzT7182jBvyUebMvsgvNM3RVrVFFJd9tRjWXhf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3162878.932748956 (+◎3162878.905890316)
+    17 g4MMQmzT7182jBvyUebMvsgvNM3RVrVFFJd9tRjWXhf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.208666460 (+◎38.181807820)
-    18 sCtiJieP8B3SwYnXemiLpRFRR8KJLMtsMVN25fAFWjW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎353690410.648316701 (+◎353690410.621458061)
+    18 sCtiJieP8B3SwYnXemiLpRFRR8KJLMtsMVN25fAFWjW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎36010.878232675 (+◎36010.851374035)
-    19 sz9u5XVqwTP2iuzdJ8eURcaWnaqtSxHPLoeNgdwe4oW(Stake11111111111111111111111111111111111111): ◎399999.000000000 => ◎32663361.702369984 (+◎32263362.702369984)
+    19 sz9u5XVqwTP2iuzdJ8eURcaWnaqtSxHPLoeNgdwe4oW(Stake11111111111111111111111111111111111111): ◎399999.000000000 => ◎402286.617573191 (+◎2287.617573191)
-    20 wF9ys4njgqqXYoDT8Gdbm9G6ux7oEYn6nxRWnvmxic9(Stake11111111111111111111111111111111111111): ◎35027.000000000 => ◎18514767.427603620 (+◎18479740.427603620)
+    20 wF9ys4njgqqXYoDT8Gdbm9G6ux7oEYn6nxRWnvmxic9(Stake11111111111111111111111111111111111111): ◎35027.000000000 => ◎35082.809359550 (+◎55.809359550)
-    21 21ryEourynXqhpLe1DsFz8yoeFKSXE14T8bKBFmzcYzt(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎321.862499952 (+◎321.835641312)
+    21 21ryEourynXqhpLe1DsFz8yoeFKSXE14T8bKBFmzcYzt(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎0.027830592 (+◎0.000971952)
-    22 23XCSrcK2QwZ9PmtAiic43ntBajM3PbbzrAXMSwiouQB(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎13334517.605135868 (+◎13329517.605135868)
+    22 23XCSrcK2QwZ9PmtAiic43ntBajM3PbbzrAXMSwiouQB(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎5040.255535166 (+◎40.255535166)
-    23 2PEyBgsPYBQ8pMdXQtEaPGNqWQHE9GCnmV2tTVN4GMru(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎106676929.984177390 (+◎106676929.957318750)
+    23 2PEyBgsPYBQ8pMdXQtEaPGNqWQHE9GCnmV2tTVN4GMru(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1725.055529295 (+◎1725.028670655)
-    24 2ZiRvaGXkw1LJXy3sn2ZUmJPjTLAKcXeMUKT2jeHDSoP(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎17846164.297847234 (+◎17796164.297847234)
+    24 2ZiRvaGXkw1LJXy3sn2ZUmJPjTLAKcXeMUKT2jeHDSoP(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50102.415634402 (+◎102.415634402)
-    25 2cFGQhgkuibqREEXvz7wEb5CwUqGHfBSTB2oa1hmhkcw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3160118.134408951 (+◎3160118.107550311)
+    25 2cFGQhgkuibqREEXvz7wEb5CwUqGHfBSTB2oa1hmhkcw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.200328767 (+◎38.173470127)
-    26 2dCciM6aFdDXeiirHNTmkxh9Sda1DwfPfF1HVNZSrPcE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3110354.013689921 (+◎3110353.986831281)
+    26 2dCciM6aFdDXeiirHNTmkxh9Sda1DwfPfF1HVNZSrPcE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.050039660 (+◎38.023181020)
-    27 2het6nBRLq9LLZER8fqUEk7j5pbLxq2mVGqSse2nS3tf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎178534013.992105852 (+◎178534013.965247212)
+    27 2het6nBRLq9LLZER8fqUEk7j5pbLxq2mVGqSse2nS3tf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2185.419510530 (+◎2185.392651890)
-    28 2hjoQMqRAG5ftTPCSkUavMEaVX35qbj3LK3Q3HDmv4mZ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3162793.112962428 (+◎3162793.086103788)
+    28 2hjoQMqRAG5ftTPCSkUavMEaVX35qbj3LK3Q3HDmv4mZ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.208407282 (+◎38.181548642)
-    29 2jvDEtiywY9sjx29gCAQjvxD5gJLcw89NVhkJ6ybajZC(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎95152328.466315010 (+◎95152328.439456370)
+    29 2jvDEtiywY9sjx29gCAQjvxD5gJLcw89NVhkJ6ybajZC(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1661.621073281 (+◎1661.594214641)
-    30 2mQNruSKNnn6fWqJjKNGsQtpsMnuxxMzHsrKT6iVR7tW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3160177.301399445 (+◎3160177.274540805)
+    30 2mQNruSKNnn6fWqJjKNGsQtpsMnuxxMzHsrKT6iVR7tW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.200507453 (+◎38.173648813)
-    31 2naPB8XC4FWp4er8M2nxDsphXHEyQH2CSQMFaSHxWWd8(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎106404579.789499852 (+◎106404579.762641212)
+    31 2naPB8XC4FWp4er8M2nxDsphXHEyQH2CSQMFaSHxWWd8(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1624.028651912 (+◎1624.001793272)
-    32 2oAy9LBgcCKtBhZ2oQf2z8J4NNKrYf7DCnWAQs7EZLpD(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎19270323.189181248 (+◎19220323.189181248)
+    32 2oAy9LBgcCKtBhZ2oQf2z8J4NNKrYf7DCnWAQs7EZLpD(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50110.724811007 (+◎110.724811007)
-    33 33Xtw1vowk5489E51ojTxJJj5rcocfGH3dDLVP84DMHq(Stake11111111111111111111111111111111111111): ◎400001.000000000 => ◎18188967.609508192 (+◎17788966.609508192)
+    33 33Xtw1vowk5489E51ojTxJJj5rcocfGH3dDLVP84DMHq(Stake11111111111111111111111111111111111111): ◎400001.000000000 => ◎400693.025050575 (+◎692.025050575)
-    34 3LAzTH2Fbsza2wbnKgrDcQKdaQRshQkb4w4vk12E5KH2(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3153656.349311174 (+◎3153656.322452534)
+    34 3LAzTH2Fbsza2wbnKgrDcQKdaQRshQkb4w4vk12E5KH2(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.180813987 (+◎38.153955347)
-    35 3TC4dtYuka6fhC54ZM7yicFLmSJq38GPs1KCSwap6CuT(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎88472211.915455816 (+◎88472211.888597176)
+    35 3TC4dtYuka6fhC54ZM7yicFLmSJq38GPs1KCSwap6CuT(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1641.446924847 (+◎1641.420066207)
-    36 3ZhXyB3T1uTnUPmehLnBUF5Go4Zyh1NQdCPseayr6BPq(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎75133670.798574735 (+◎75133670.771716095)
+    36 3ZhXyB3T1uTnUPmehLnBUF5Go4Zyh1NQdCPseayr6BPq(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1415.070305094 (+◎1415.043446454)
-    37 3byuwfBCZ4JLdbsuirv6yV3opAfgv2kw3BHjqjGUSDCd(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎68904680.319824133 (+◎68904680.292965493)
+    37 3byuwfBCZ4JLdbsuirv6yV3opAfgv2kw3BHjqjGUSDCd(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1296.054198877 (+◎1296.027340237)
-    38 3r5ZXC1yFqMmk8VwDdUJbEdPmZ8KZvEkzd5ThEYRetTk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎155755624.641999344 (+◎155755624.615140704)
+    38 3r5ZXC1yFqMmk8VwDdUJbEdPmZ8KZvEkzd5ThEYRetTk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2173.887745840 (+◎2173.860887200)
-    39 3wh9XTfhVPqy8ku2wGXzhnfoKQS7PE5oJ5Gz9ZkpVP5n(Stake11111111111111111111111111111111111111): ◎28897.000000000 => ◎17466780.873953976 (+◎17437883.873953976)
+    39 3wh9XTfhVPqy8ku2wGXzhnfoKQS7PE5oJ5Gz9ZkpVP5n(Stake11111111111111111111111111111111111111): ◎28897.000000000 => ◎28949.662922118 (+◎52.662922118)
-    40 3xL7J73kXPoeshEKRrkRQPSggbuQdJGeDwwVY5y43esk(Stake11111111111111111111111111111111111111): ◎133332.000000000 => ◎34263019.724716244 (+◎34129687.724716244)
+    40 3xL7J73kXPoeshEKRrkRQPSggbuQdJGeDwwVY5y43esk(Stake11111111111111111111111111111111111111): ◎133332.000000000 => ◎133619.448704710 (+◎287.448704710)
-    41 462gkiydfX1ks7bzS71j4k5uLZaonTzcz5mfJpgLGe9k(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2479023.655373279 (+◎2479023.628514639)
+    41 462gkiydfX1ks7bzS71j4k5uLZaonTzcz5mfJpgLGe9k(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎21.828493156 (+◎21.801634516)
-    42 4785anyR2rYSas6cQGHtykgzwYEtChvFYhcEgdDw3gGL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎374668955.373552022 (+◎374668955.346693382)
+    42 4785anyR2rYSas6cQGHtykgzwYEtChvFYhcEgdDw3gGL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎35659.101657295 (+◎35659.074798655)
-    43 488s19JMS6GRi3hNeNrjtfQnkEDCTaUwJbeX4NhKQW1x(Stake11111111111111111111111111111111111111): ◎1999999.000000000 => ◎4551452.385342916 (+◎2551453.385342916)
+    43 488s19JMS6GRi3hNeNrjtfQnkEDCTaUwJbeX4NhKQW1x(Stake11111111111111111111111111111111111111): ◎1999999.000000000 => ◎2000566.847902536 (+◎567.847902536)
-    44 49DJjUX3cwFvaZD5rCAwubiz7qdRWDez9xmB381XdHru(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎120691505.254507972 (+◎120691505.227649332)
+    44 49DJjUX3cwFvaZD5rCAwubiz7qdRWDez9xmB381XdHru(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1738.750138246 (+◎1738.723279606)
-    45 4PsiLMyoUQ7QRn1FFiFCvej4hsUTFzfvJnyN4bj1tmSN(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎90250151.454844224 (+◎90250151.427985584)
+    45 4PsiLMyoUQ7QRn1FFiFCvej4hsUTFzfvJnyN4bj1tmSN(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1646.816354542 (+◎1646.789495902)
-    46 4QhNoG3PN1FXXFhAEA2QWdor6xjXvM9pjq6MXAUV8Zg2(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎144261357.387278106 (+◎144261357.360419466)
+    46 4QhNoG3PN1FXXFhAEA2QWdor6xjXvM9pjq6MXAUV8Zg2(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2110.544900194 (+◎2110.518041554)
-    47 4ScTBfR4v2Lw9hWuzayJjfZdBKQVUeg7Rm92Rsq7HZkV(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎151549934.412023922 (+◎151549934.385165282)
+    47 4ScTBfR4v2Lw9hWuzayJjfZdBKQVUeg7Rm92Rsq7HZkV(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2161.186437663 (+◎2161.159579023)
-    48 4YppsfeYfk6uP2T5wohRcuinffsfEQxL4iFNRov1U4Mc(Stake11111111111111111111111111111111111111): ◎250000.000000000 => ◎44698018.532423312 (+◎44448018.532423312)
+    48 4YppsfeYfk6uP2T5wohRcuinffsfEQxL4iFNRov1U4Mc(Stake11111111111111111111111111111111111111): ◎250000.000000000 => ◎251164.907861472 (+◎1164.907861472)
-    49 4aFj9VyXDrqU4TnKWnMVuPaAVTaF4GZLLKZN2iZivW29(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎52433416.548269912 (+◎52433416.521411272)
+    49 4aFj9VyXDrqU4TnKWnMVuPaAVTaF4GZLLKZN2iZivW29(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎272.896600553 (+◎272.869741913)
-    50 4bLzJyQ6euk818XMHn6A5WbCfkaJ7f5D85iDb6kBGBi3(Stake11111111111111111111111111111111111111): ◎2.000000000 => ◎7344.684136807 (+◎7342.684136807)
+    50 4bLzJyQ6euk818XMHn6A5WbCfkaJ7f5D85iDb6kBGBi3(Stake11111111111111111111111111111111111111): ◎2.000000000 => ◎2.022175121 (+◎0.022175121)
-    51 4dmBLJcchyfucSxkVmrymmsnVpZm3rBkp7kbF7qHTTYW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3166245.201207146 (+◎3166245.174348506)
+    51 4dmBLJcchyfucSxkVmrymmsnVpZm3rBkp7kbF7qHTTYW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.218832690 (+◎38.191974050)
-    52 4k2gDTTEXatLzYnuknzfSrYniAbGjKZ7MQviKtaZSmsR(Stake11111111111111111111111111111111111111): ◎44443.000000000 => ◎28989325.719601512 (+◎28944882.719601512)
+    52 4k2gDTTEXatLzYnuknzfSrYniAbGjKZ7MQviKtaZSmsR(Stake11111111111111111111111111111111111111): ◎44443.000000000 => ◎44530.414397034 (+◎87.414397034)
-    53 4nQTSgKURZexbRj4oXKwMiqwVCPobTcaTyMph728J3XR(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎148122416.791800566 (+◎148122416.764941926)
+    53 4nQTSgKURZexbRj4oXKwMiqwVCPobTcaTyMph728J3XR(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2093.575592633 (+◎2093.548733993)
-    54 4yfFZH7oV4odLEJ1c8LnN2YpDXSr2xNWDBpZvKby5wwg(Stake11111111111111111111111111111111111111): ◎666666.000000000 => ◎1650618.582740767 (+◎983952.582740767)
+    54 4yfFZH7oV4odLEJ1c8LnN2YpDXSr2xNWDBpZvKby5wwg(Stake11111111111111111111111111111111111111): ◎666666.000000000 => ◎666836.456015719 (+◎170.456015719)
-    55 51JBzSTU5rAM8gLAVQKgp4WoZerQcSqWC7BitBzgUNAm(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎74311219.226101866 (+◎74311219.199243226)
+    55 51JBzSTU5rAM8gLAVQKgp4WoZerQcSqWC7BitBzgUNAm(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1283.752284862 (+◎1283.725426222)
-    56 52DDH9Z6tdkuDAmAPJDeuXmdn5iNMZ1xHCv9zWYyWxp8(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎37176157.191222154 (+◎37176157.164363514)
+    56 52DDH9Z6tdkuDAmAPJDeuXmdn5iNMZ1xHCv9zWYyWxp8(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎169.559587585 (+◎169.532728945)
-    57 54AkJByW5UrT6pSFcgDY3gXMiQXKJY81A1ua5CuGMttQ(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎11247317.961171052 (+◎11242317.961171052)
+    57 54AkJByW5UrT6pSFcgDY3gXMiQXKJY81A1ua5CuGMttQ(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎5033.952130860 (+◎33.952130860)
-    58 59we9sXxXgM1MGwMkSsb5QBgs79J6fdkZNSCL7e82s2Y(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎65710545.999012832 (+◎65660545.999012832)
+    58 59we9sXxXgM1MGwMkSsb5QBgs79J6fdkZNSCL7e82s2Y(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50685.576324966 (+◎685.576324966)
-    59 5AaAK8GTaKiH4y3LH6hoeEn4Zu1YAvLAoSw3xXi3EYm8(Stake11111111111111111111111111111111111111): ◎34527.000000000 => ◎9197318.089733296 (+◎9162791.089733296)
+    59 5AaAK8GTaKiH4y3LH6hoeEn4Zu1YAvLAoSw3xXi3EYm8(Stake11111111111111111111111111111111111111): ◎34527.000000000 => ◎34554.671898553 (+◎27.671898553)
-    60 5CgQubGD1uwodwCe5UXDADbC69SiqXR8qq6pDMSm7ut5(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎90298980.829761666 (+◎90298980.802903026)
+    60 5CgQubGD1uwodwCe5UXDADbC69SiqXR8qq6pDMSm7ut5(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1317.720884818 (+◎1317.694026178)
-    61 5K8qgC9nHzKHSSyo9fKLsMfYmavYdMgEaYx86cMmVKVv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎106832508.066882832 (+◎106832508.040024192)
+    61 5K8qgC9nHzKHSSyo9fKLsMfYmavYdMgEaYx86cMmVKVv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1725.525379679 (+◎1725.498521039)
-    62 5RCD4pZcKH3NHN4XHxvsnVAawSaConLgsZbreSN5dXpZ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎103826934.899540991 (+◎103826934.872682351)
+    62 5RCD4pZcKH3NHN4XHxvsnVAawSaConLgsZbreSN5dXpZ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1687.818639815 (+◎1687.791781175)
-    63 5TFdzjKE6LnkhQArxWjt26yVCXskPo3fUXE8F351Cfn7(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎110244860.385217573 (+◎110244860.358358933)
+    63 5TFdzjKE6LnkhQArxWjt26yVCXskPo3fUXE8F351Cfn7(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1707.200963523 (+◎1707.174104883)
-    64 5TkFPZf79rezPXzCTP6DjH4NLb7Hw3jRsAme1fv431oz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2757434.643306353 (+◎2757434.616447713)
+    64 5TkFPZf79rezPXzCTP6DjH4NLb7Hw3jRsAme1fv431oz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎22.669302527 (+◎22.642443887)
-    65 5dwMHTsS52QGYVGWyui1P555XkBPzGa8uoQc7aZunLGy(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎73751900.658047480 (+◎73751900.631188840)
+    65 5dwMHTsS52QGYVGWyui1P555XkBPzGa8uoQc7aZunLGy(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1396.582408379 (+◎1396.555549739)
-    66 5swjaAU8NapTsmgHGAPe8wUjrK1HYPL2G64AwyH4djhz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎91749845.083301289 (+◎91749845.056442649)
+    66 5swjaAU8NapTsmgHGAPe8wUjrK1HYPL2G64AwyH4djhz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1637.030563146 (+◎1637.003704506)
-    67 6559KMdiUseNSAkRcK9WcFcNTppoj6jWtKVedpMkBYCn(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎117753607.764499622 (+◎117753607.737640982)
+    67 6559KMdiUseNSAkRcK9WcFcNTppoj6jWtKVedpMkBYCn(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1729.877601427 (+◎1729.850742787)
-    68 6GJ23VmcWCVnm6iATqdmTjX6JeFDCCaG7PuRh5ehn9af(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎109704113.050290953 (+◎109704113.023432313)
+    68 6GJ23VmcWCVnm6iATqdmTjX6JeFDCCaG7PuRh5ehn9af(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1734.197711178 (+◎1734.170852538)
-    69 6Hr77bmtmxbs3eo5NTiXDqevUTVhumNHuiTYHEAyYyvJ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎188.112228037 (+◎188.085369397)
+    69 6Hr77bmtmxbs3eo5NTiXDqevUTVhumNHuiTYHEAyYyvJ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎0.027426655 (+◎0.000568015)
-    70 6UDU4Z9TTbYy8gcRKBd7RX3Lm2qMsSR4PMuzoyYPzLma(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎138254450.039418998 (+◎138254450.012560358)
+    70 6UDU4Z9TTbYy8gcRKBd7RX3Lm2qMsSR4PMuzoyYPzLma(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2092.403863350 (+◎2092.377004710)
-    71 6hkfqeNAbURk7CmAQsP4Qm6WwHVF4LxHupEvQf7Tkrf1(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎95680514.580117134 (+◎95680514.553258494)
+    71 6hkfqeNAbURk7CmAQsP4Qm6WwHVF4LxHupEvQf7Tkrf1(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1663.216210878 (+◎1663.189352238)
-    72 6mBks7oFrfRtn8qWQDMAzP6HYGmjWjDYfjpA6yndQaET(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎29322595.972747164 (+◎28822595.972747164)
+    72 6mBks7oFrfRtn8qWQDMAzP6HYGmjWjDYfjpA6yndQaET(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎501027.534691217 (+◎1027.534691217)
-    73 6mCs4Gi8L5RQ4ewnabmwCcVDQLBuvyqnaRcm5LGTciyz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2753602.345516027 (+◎2753602.318657387)
+    73 6mCs4Gi8L5RQ4ewnabmwCcVDQLBuvyqnaRcm5LGTciyz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎22.657728876 (+◎22.630870236)
-    74 6yg4Usyr8VkvY8m7wrbLHegKVnKaAQmEwS6cuGnwB6wT(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎40419853.807854212 (+◎40419853.780995572)
+    74 6yg4Usyr8VkvY8m7wrbLHegKVnKaAQmEwS6cuGnwB6wT(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎236.615287778 (+◎236.588429138)
-    75 76nwV8zz8tLz97SBRXH6uwHvgHXtqJDLQfF66jZhQ857(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎13478471.125145745 (+◎13478471.098287105)
+    75 76nwV8zz8tLz97SBRXH6uwHvgHXtqJDLQfF66jZhQ857(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎284.228861170 (+◎284.202002530)
-    76 7DJunpQm9vgLXnspokwjivkdX6UkugT3HZs4prjsPkG4(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2756606.336698324 (+◎2756606.309839684)
+    76 7DJunpQm9vgLXnspokwjivkdX6UkugT3HZs4prjsPkG4(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎22.666801017 (+◎22.639942377)
-    77 7Hs9z4qsGCbQE9cy2aqgsvWupeZZGiKJgeb1eG4ZKYUH(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎113902317.021722690 (+◎113902316.994864050)
+    77 7Hs9z4qsGCbQE9cy2aqgsvWupeZZGiKJgeb1eG4ZKYUH(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1718.246590125 (+◎1718.219731485)
-    78 7NwjYBhHVqEbqmMHqMqUnQ4thomaX9qXytMEULQFkAny(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎119495390.122588081 (+◎119495390.095729441)
+    78 7NwjYBhHVqEbqmMHqMqUnQ4thomaX9qXytMEULQFkAny(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1735.137835370 (+◎1735.110976730)
-    79 7PmWxxiTneGteGxEYvzj5pGDVMQ4nuN9DfUypEXmaA8o(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎152264293.481362600 (+◎152264293.454503960)
+    79 7PmWxxiTneGteGxEYvzj5pGDVMQ4nuN9DfUypEXmaA8o(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2177.658733316 (+◎2177.631874676)
-    80 7UKUPLwLrV7iLqL5ndTzYDav73mpoMxKjyM7EjMExTaw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎56167738.352299318 (+◎56167738.325440678)
+    80 7UKUPLwLrV7iLqL5ndTzYDav73mpoMxKjyM7EjMExTaw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1171.698798033 (+◎1171.671939393)
-    81 7VGU4ZwR1e1AFekqbqv2gvjeg47e1PwMPm4BfLt6rxNk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎417171308.176955448 (+◎417171308.150096808)
+    81 7VGU4ZwR1e1AFekqbqv2gvjeg47e1PwMPm4BfLt6rxNk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎4967.458233621 (+◎4967.431374981)
-    82 7X5QAMP54upioBdu75QZkz8hpYcwz7UmzAHGB2STq9da(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎77730484.981808105 (+◎77730484.954949465)
+    82 7X5QAMP54upioBdu75QZkz8hpYcwz7UmzAHGB2STq9da(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1394.282939784 (+◎1394.256081144)
-    83 7fjXS1Ljf3wEj7uC9y5MEin84MwDkeqWeHapZu8UMBYM(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎1331901.774271482 (+◎1326901.774271482)
+    83 7fjXS1Ljf3wEj7uC9y5MEin84MwDkeqWeHapZu8UMBYM(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎5004.007282380 (+◎4.007282380)
-    84 7kge23FTbCXc6dZxMPQfAWLnVFTgGzio5wpXUo9si2mV(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3163061.565809936 (+◎3163061.538951296)
+    84 7kge23FTbCXc6dZxMPQfAWLnVFTgGzio5wpXUo9si2mV(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.209218016 (+◎38.182359376)
-    85 7vJeGJzbaa3bghTsPsFi83T6VCy5uLaQ12r32JA6s8xc(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3144803.148897766 (+◎3144803.122039126)
+    85 7vJeGJzbaa3bghTsPsFi83T6VCy5uLaQ12r32JA6s8xc(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.154077060 (+◎38.127218420)
-    86 7yXM5mUSAtBuh2TcCABvSJa3LouZ8wcLps5zTEMiwxvj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎107800362.263125432 (+◎107800362.236266792)
+    86 7yXM5mUSAtBuh2TcCABvSJa3LouZ8wcLps5zTEMiwxvj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1699.818507305 (+◎1699.791648665)
-    87 81EzwqxAr4C3W8WWy5L2DKiTasDLMQtHzgYDp6UVLXBf(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎35714766.536109076 (+◎35214766.536109076)
+    87 81EzwqxAr4C3W8WWy5L2DKiTasDLMQtHzgYDp6UVLXBf(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎501107.248155577 (+◎1107.248155577)
-    88 8BbpzqTUCUa4oR71AMgcBiTQvd6Gta3xJHCG4xK9mKBp(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎106945887.092097340 (+◎106945887.065238700)
+    88 8BbpzqTUCUa4oR71AMgcBiTQvd6Gta3xJHCG4xK9mKBp(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1697.237967159 (+◎1697.211108519)
-    89 8HR5rCobbFMDe5EbgKdJLNDWVCeGG79w837BUxtsCngs(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎150722834.625055104 (+◎150722834.598196464)
+    89 8HR5rCobbFMDe5EbgKdJLNDWVCeGG79w837BUxtsCngs(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2631.080610398 (+◎2631.053751758)
-    90 8Vv2xVWSQtHji1Xf7Vj1vHKTa4em7zv7cAET96Vm2qt8(Stake11111111111111111111111111111111111111): ◎66666.000000000 => ◎21492300.170342452 (+◎21425634.170342452)
+    90 8Vv2xVWSQtHji1Xf7Vj1vHKTa4em7zv7cAET96Vm2qt8(Stake11111111111111111111111111111111111111): ◎66666.000000000 => ◎66809.724349894 (+◎143.724349894)
-    91 8XgHUtBRY6qePVYERxosyX3MUq8NQkjtmFDSzQ2WpHTJ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎333793065.631627482 (+◎333793065.604768842)
+    91 8XgHUtBRY6qePVYERxosyX3MUq8NQkjtmFDSzQ2WpHTJ(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎35864.898204047 (+◎35864.871345407)
-    92 8YznarspJJGQ1mpiUKxneb6ZyhxNJS9RKCu4aadxWwZg(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎29808003.488701636 (+◎29758003.488701636)
+    92 8YznarspJJGQ1mpiUKxneb6ZyhxNJS9RKCu4aadxWwZg(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50102.753464898 (+◎102.753464898)
-    93 8ge8UzG9FyW4NDZ6zzZiUypnbcNQ3nUfTBKndxsmWqSB(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2757892.114659976 (+◎2757892.087801336)
+    93 8ge8UzG9FyW4NDZ6zzZiUypnbcNQ3nUfTBKndxsmWqSB(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎22.670684104 (+◎22.643825464)
-    94 8jxSHbS4qAnh5yueFp4D9ABXubKqMwXqF3HtdzQGuphp(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎432252021.194289766 (+◎432252021.167431126)
+    94 8jxSHbS4qAnh5yueFp4D9ABXubKqMwXqF3HtdzQGuphp(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎5986.416327774 (+◎5986.389469134)
-    95 8rKN2jdSDUeDX4niaKhvcsuSbN31b9JsMJCDwuFVmqtv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3143028.922157852 (+◎3143028.895299212)
+    95 8rKN2jdSDUeDX4niaKhvcsuSbN31b9JsMJCDwuFVmqtv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.148718844 (+◎38.121860204)
-    96 8xV77wuFP5BkMDdb1845hRRWZNbDNAbcV75BjMuViWpf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2264615.788857944 (+◎2264615.761999304)
+    96 8xV77wuFP5BkMDdb1845hRRWZNbDNAbcV75BjMuViWpf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎6.866064838 (+◎6.839206198)
-    97 93E4vRVizTe1eT9RRNyi3gadGE1JW8oq5EXbxtFP5g5j(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎54916347.082801048 (+◎54866347.082801048)
+    97 93E4vRVizTe1eT9RRNyi3gadGE1JW8oq5EXbxtFP5g5j(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50686.760715001 (+◎686.760715001)
-    98 98gEkDwAgaJd5SzYgDeDCiS4fQuthwXMLPBBwWzpr8aD(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1.286309088 (+◎1.259450448)
+    98 98gEkDwAgaJd5SzYgDeDCiS4fQuthwXMLPBBwWzpr8aD(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎0.026862442 (+◎0.000003802)
-    99 9EJXJNzaXnycsMr4ZyiC5WUWYPkGNoSSYTGJLYfwnccK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎131857721.896328218 (+◎131857721.869469578)
+    99 9EJXJNzaXnycsMr4ZyiC5WUWYPkGNoSSYTGJLYfwnccK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1700.897889608 (+◎1700.871030968)
-   100 9FWqh2hwC5ymLBYzfouQqffPw5mSNRFeyaiNCdeGSmzZ(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎11387325.374293434 (+◎11382325.374293434)
+   100 9FWqh2hwC5ymLBYzfouQqffPw5mSNRFeyaiNCdeGSmzZ(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎5034.374957365 (+◎34.374957365)
-   101 9GJmEHGom9eWo4np4L5vC6b6ri1Df2xN8KFoWixvD1Bs(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎171958327.025806200 (+◎171958326.998947560)
+   101 9GJmEHGom9eWo4np4L5vC6b6ri1Df2xN8KFoWixvD1Bs(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2938.565896285 (+◎2938.539037645)
-   102 9K67smfw8hDXmtnR7uvP62WrKUcB7oZ8cvpsB1hmrCzf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2476915.240438513 (+◎2476915.213579873)
+   102 9K67smfw8hDXmtnR7uvP62WrKUcB7oZ8cvpsB1hmrCzf(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎21.822125681 (+◎21.795267041)
-   103 9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎133999375.533471630 (+◎133999375.506612990)
+   103 9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2122.498143972 (+◎2122.471285332)
-   104 9bRDrYShoQ77MZKYTMoAsoCkU7dAR24mxYCBjXLpfEJx(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎347291163.769698829 (+◎347291163.742840189)
+   104 9bRDrYShoQ77MZKYTMoAsoCkU7dAR24mxYCBjXLpfEJx(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎35318.751536923 (+◎35318.724678283)
-   105 9bwet11HasEXpoRedsk6yMt37u2p5ikUoYFjGVRrkpNp(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎33630880.549854358 (+◎33630880.522995718)
+   105 9bwet11HasEXpoRedsk6yMt37u2p5ikUoYFjGVRrkpNp(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎158.852747868 (+◎158.825889228)
-   106 9diFDvrfJD8RvBBF36cMLyQAnvafbeu3KFKAwv4od5nX(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎103501697.456492242 (+◎103501697.429633602)
+   106 9diFDvrfJD8RvBBF36cMLyQAnvafbeu3KFKAwv4od5nX(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1672.521502916 (+◎1672.494644276)
-   107 9iEFfC6qCU6DBTWxL84YQdpNmpZ9yBBu4sW62yeiEVKe(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎111745803.092336744 (+◎111745803.065478104)
+   107 9iEFfC6qCU6DBTWxL84YQdpNmpZ9yBBu4sW62yeiEVKe(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1711.733854637 (+◎1711.706995997)
-   108 9m54h2iW3nk1TeRqtW415zrTry8MfafzQgwRGxhcvjSR(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎35285113.684536623 (+◎35285113.657677983)
+   108 9m54h2iW3nk1TeRqtW415zrTry8MfafzQgwRGxhcvjSR(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎163.848580583 (+◎163.821721943)
-   109 9r3Xm9DJCZaHNU5HaWip5UMtnhJUgV8AoiuiLUxrmqDL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎6351656.673767086 (+◎6351656.646908446)
+   109 9r3Xm9DJCZaHNU5HaWip5UMtnhJUgV8AoiuiLUxrmqDL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎19.209048505 (+◎19.182189865)
-   110 9sWYTuuR4s12Q4SuSfo5CfWaFggQwA6Z8pf8dWowN5rk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎166464597.833387130 (+◎166464597.806528490)
+   110 9sWYTuuR4s12Q4SuSfo5CfWaFggQwA6Z8pf8dWowN5rk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2277.803711087 (+◎2277.776852447)
-   111 9sisHP6GefwFsxptaB18K1a8823akwY4QoT4i1JmCaNs(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎12274391.216460258 (+◎12269391.216460258)
+   111 9sisHP6GefwFsxptaB18K1a8823akwY4QoT4i1JmCaNs(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎5037.053922296 (+◎37.053922296)
-   112 9tPVqLPhbKzkALus5kTi9nLgGLRKjtDZgMpNuiriV1V7(Stake11111111111111111111111111111111111111): ◎820610.000000000 => ◎14617510.013524524 (+◎13796900.013524524)
+   112 9tPVqLPhbKzkALus5kTi9nLgGLRKjtDZgMpNuiriV1V7(Stake11111111111111111111111111111111111111): ◎820610.000000000 => ◎821771.093025727 (+◎1161.093025727)
-   113 9tedbEYypEKXAMkHcg42rn3fXY1B8hB6cdE3ZTFouXLL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎146043280.502357436 (+◎146043280.475498796)
+   113 9tedbEYypEKXAMkHcg42rn3fXY1B8hB6cdE3ZTFouXLL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2158.871091169 (+◎2158.844232529)
-   114 9v5gci7uDiaGKRmQ2dn6WJMB94YqFaVFBTiFzBzNhyaw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎23625097.237940606 (+◎23625097.211081966)
+   114 9v5gci7uDiaGKRmQ2dn6WJMB94YqFaVFBTiFzBzNhyaw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎326.896495041 (+◎326.869636401)
-   115 9wQQnnnkk5b5GkQWTW9L4kEA3CjFv6CqsQd5gt6tRsHK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3157322.133534281 (+◎3157322.106675641)
+   115 9wQQnnnkk5b5GkQWTW9L4kEA3CjFv6CqsQd5gt6tRsHK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.191884763 (+◎38.165026123)
-   116 9zwzFJTmYecdkDzidkHzVdhBsUoEoFwCMGuj7hqwo8Lz(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎378849.537275458 (+◎328849.537275458)
+   116 9zwzFJTmYecdkDzidkHzVdhBsUoEoFwCMGuj7hqwo8Lz(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50040.072840269 (+◎40.072840269)
-   117 A7tGsVBc96VPHqQVh9C1HixQJzZ1wtqr866aEH6dv4Uo(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3226089.992358534 (+◎3226089.965499894)
+   117 A7tGsVBc96VPHqQVh9C1HixQJzZ1wtqr866aEH6dv4Uo(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.399565719 (+◎38.372707079)
-   118 AFGrUcWQr9bja1wX9QVpAst9xGDSZ6YHxPKsZX6qixxu(Stake11111111111111111111111111111111111111): ◎2250.000000000 => ◎636296.367819714 (+◎634046.367819714)
+   118 AFGrUcWQr9bja1wX9QVpAst9xGDSZ6YHxPKsZX6qixxu(Stake11111111111111111111111111111111111111): ◎2250.000000000 => ◎2251.914838676 (+◎1.914838676)
-   119 AGXZemZbyZjz5NBhufcob2pf8AXnr9HaGFUGNCfooWrB(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎92043566.128638004 (+◎92043566.101779364)
+   119 AGXZemZbyZjz5NBhufcob2pf8AXnr9HaGFUGNCfooWrB(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1652.232519598 (+◎1652.205660958)
-   120 AKVsPFhBPNSZuYiqojQJZFj9K8oskc9sNXM5szmZ3F8D(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎59978833.410660744 (+◎59928833.410660744)
+   120 AKVsPFhBPNSZuYiqojQJZFj9K8oskc9sNXM5szmZ3F8D(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50753.583249509 (+◎753.583249509)
-   121 APG7GF8SKH4vTsvq8TGKGLrQEarxjRQ1xiQ6N5iqrZSN(Stake11111111111111111111111111111111111111): ◎0.100000000 => ◎35.463837601 (+◎35.363837601)
+   121 APG7GF8SKH4vTsvq8TGKGLrQEarxjRQ1xiQ6N5iqrZSN(Stake11111111111111111111111111111111111111): ◎0.100000000 => ◎0.100106799 (+◎0.000106799)
-   122 AU2mJcPbQx1eEQbXkMAvuRGnvAKsq6YUY23TMczhAS1W(Stake11111111111111111111111111111111111111): ◎499999.000000000 => ◎7636367.901543726 (+◎7136368.901543726)
+   122 AU2mJcPbQx1eEQbXkMAvuRGnvAKsq6YUY23TMczhAS1W(Stake11111111111111111111111111111111111111): ◎499999.000000000 => ◎500283.946392643 (+◎284.946392643)
-   123 AdtBv6jyEjY74XhkxZkowMuGfV1r58j44WCRyeToic99(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎105844689.368932024 (+◎105844689.342073384)
+   123 AdtBv6jyEjY74XhkxZkowMuGfV1r58j44WCRyeToic99(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1693.912317652 (+◎1693.885459012)
-   124 Ae8UD1RQBAR7PcyTJjmEsypojpuKmMGDBJxwiZorZA2M(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2475657.656550494 (+◎2475657.629691854)
+   124 Ae8UD1RQBAR7PcyTJjmEsypojpuKmMGDBJxwiZorZA2M(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎21.818327741 (+◎21.791469101)
-   125 AqSThC5LAYcfiPM73cdwDfgrCvDKHXe1TmCpUE5tnmSs(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2499800.855972701 (+◎2499800.829114061)
+   125 AqSThC5LAYcfiPM73cdwDfgrCvDKHXe1TmCpUE5tnmSs(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎21.891240913 (+◎21.864382273)
-   126 B6nDYYLc2iwYqY3zdmavMmU9GjUL2hf79MkufviM2bXv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎176569449.443654468 (+◎176569449.416795828)
+   126 B6nDYYLc2iwYqY3zdmavMmU9GjUL2hf79MkufviM2bXv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2294.005749861 (+◎2293.978891221)
-   127 BH7asDZbKkTmT3UWiNfmMVRgQEEpXoVThGPmQfgWwDhg(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎126345332.093548215 (+◎126345332.066689575)
+   127 BH7asDZbKkTmT3UWiNfmMVRgQEEpXoVThGPmQfgWwDhg(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1598.360848764 (+◎1598.333990124)
-   128 BHySMCEjkZxJpGvx1a2MYY84VTXDWDRKrpUEWgwDaDCW(Stake11111111111111111111111111111111111111): ◎44443.000000000 => ◎49656399.220418224 (+◎49611956.220418224)
+   128 BHySMCEjkZxJpGvx1a2MYY84VTXDWDRKrpUEWgwDaDCW(Stake11111111111111111111111111111111111111): ◎44443.000000000 => ◎44708.780339857 (+◎265.780339857)
-   129 BNTmegvdXzNVyc3UMTWSMSfJUryjr3fXEVErtdqrfs6y(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎110314551.713124418 (+◎110314551.686265778)
+   129 BNTmegvdXzNVyc3UMTWSMSfJUryjr3fXEVErtdqrfs6y(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1707.411433382 (+◎1707.384574742)
-   130 BUY3swp2NSTMsQmLDnYgoEoLNJyCX1MQZQjnAVL7SnSx(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2755413.395302991 (+◎2755413.368444351)
+   130 BUY3swp2NSTMsQmLDnYgoEoLNJyCX1MQZQjnAVL7SnSx(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎22.663198298 (+◎22.636339658)
-   131 BdM7KCd6ZYWcaCMmHVi8YeL4jFzDVM9cRLJUeRAGSvMS(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3147874.663919065 (+◎3147874.637060425)
+   131 BdM7KCd6ZYWcaCMmHVi8YeL4jFzDVM9cRLJUeRAGSvMS(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.163353127 (+◎38.136494487)
-   132 BfF3vg8UFcwTkFJNgQ7KQTAZBUWegF3spPm79d71WNwo(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3145131.589916792 (+◎3145131.563058152)
+   132 BfF3vg8UFcwTkFJNgQ7KQTAZBUWegF3spPm79d71WNwo(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.155068962 (+◎38.128210322)
-   133 BiXoQu54c2eGpM8ivniD6ETFRWojQQ7WkK41bN5KZaDq(Stake11111111111111111111111111111111111111): ◎100.000000000 => ◎372902.884335122 (+◎372802.884335122)
+   133 BiXoQu54c2eGpM8ivniD6ETFRWojQQ7WkK41bN5KZaDq(Stake11111111111111111111111111111111111111): ◎100.000000000 => ◎101.125875673 (+◎1.125875673)
-   134 BmSqr3gETEworaBGEZgzBgBAMZ7dXBrZe3SZ7B9mxB6d(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎19144656.077315032 (+◎19094656.077315032)
+   134 BmSqr3gETEworaBGEZgzBgBAMZ7dXBrZe3SZ7B9mxB6d(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50109.772696224 (+◎109.772696224)
-   135 BohPTSY4vvjGd9ARFqDJjRaHZKP4bde7ewBq65WgRGmA(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎130627683.875927210 (+◎130627683.849068570)
+   135 BohPTSY4vvjGd9ARFqDJjRaHZKP4bde7ewBq65WgRGmA(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2112.315536010 (+◎2112.288677370)
-   136 BxFf75Vtzro2Hy3coFHKxFMZo5au8W7J8BmLC3gCMotU(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎174355272.914178006 (+◎174355272.887319366)
+   136 BxFf75Vtzro2Hy3coFHKxFMZo5au8W7J8BmLC3gCMotU(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2315.948692135 (+◎2315.921833495)
-   137 C65wF1RsbYh4oAg2FG4cNmWRpXkzUywwhNU7WbrFGEaR(Stake11111111111111111111111111111111111111): ◎1000000.000000000 => ◎20932655.649320928 (+◎19932655.649320928)
+   137 C65wF1RsbYh4oAg2FG4cNmWRpXkzUywwhNU7WbrFGEaR(Stake11111111111111111111111111111111111111): ◎1000000.000000000 => ◎1001593.324094560 (+◎1593.324094560)
-   138 C6DEs3i448uhrsWMMnWYq7WsxkujcgADrCJQ4AMJ8ipj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎105194838.172869172 (+◎105194838.146010532)
+   138 C6DEs3i448uhrsWMMnWYq7WsxkujcgADrCJQ4AMJ8ipj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1691.949747928 (+◎1691.922889288)
-   139 C6uqzABsRPmFd14iL9Ej36AbddVxXPJWV6jwbLZYdYJM(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3163720.724712378 (+◎3163720.697853738)
+   139 C6uqzABsRPmFd14iL9Ej36AbddVxXPJWV6jwbLZYdYJM(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.211208696 (+◎38.184350056)
-   140 CAf8jfgqhia5VNrEF4A7Y9VLD3numMq9DVSceq7cPhNY(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎124881814.994039666 (+◎124881814.967181026)
+   140 CAf8jfgqhia5VNrEF4A7Y9VLD3numMq9DVSceq7cPhNY(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2094.962843010 (+◎2094.935984370)
-   141 CKBuZBQBsHwxSpgVsQC8p7p3fRgCxqGnwpAR7H54Mjom(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3157471.419629731 (+◎3157471.392771091)
+   141 CKBuZBQBsHwxSpgVsQC8p7p3fRgCxqGnwpAR7H54Mjom(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.192335611 (+◎38.165476971)
-   142 CRzMxdyS56N2vkb55X5q155sSdVkjZhiFedWcbscCf7K(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎161317285.932351441 (+◎161317285.905492801)
+   142 CRzMxdyS56N2vkb55X5q155sSdVkjZhiFedWcbscCf7K(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎17793.936304469 (+◎17793.909445829)
-   143 CYqN2y4bGWXbJUUxVNGMxq8bQVZCQYE8T2Ryfvra17RL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3818211.921651681 (+◎3818211.894793041)
+   143 CYqN2y4bGWXbJUUxVNGMxq8bQVZCQYE8T2Ryfvra17RL(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎40.187791358 (+◎40.160932718)
-   144 CcaHc2L43ZWjwCHART3oZoJvHLAe9hzT2DJNUpBzoTN1(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎92121940.282161196 (+◎92121940.255302556)
+   144 CcaHc2L43ZWjwCHART3oZoJvHLAe9hzT2DJNUpBzoTN1(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1652.469211846 (+◎1652.442353206)
-   145 CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎216164683.727976843 (+◎216164683.701118203)
+   145 CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎6321.555021449 (+◎6321.528162809)
-   146 Chorus6Kis8tFHA7AowrPMcRJk3LbApHTYpgSNXzY5KE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎20209607.580194761 (+◎20209607.553336121)
+   146 Chorus6Kis8tFHA7AowrPMcRJk3LbApHTYpgSNXzY5KE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎937.132975385 (+◎937.106116745)
-   147 Cpw2G9Nj2foefTrDVknTYnK23oHpeF3iz81arpLX2KqB(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎17353227.380768372 (+◎17303227.380768372)
+   147 Cpw2G9Nj2foefTrDVknTYnK23oHpeF3iz81arpLX2KqB(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50104.362528876 (+◎104.362528876)
-   148 CrdE3LLgvBDU7wkiPJHRH6mtspSWwZmUd9ybhrtG9adv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎19607210.478252695 (+◎19607210.451394055)
+   148 CrdE3LLgvBDU7wkiPJHRH6mtspSWwZmUd9ybhrtG9adv(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎87.871031327 (+◎87.844172687)
-   149 D3DfFvmLBKkX9JJNEpJRXpM1pYTVPQ5dpPQRc9F49xk4(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎153243963.713808548 (+◎153243963.686949908)
+   149 D3DfFvmLBKkX9JJNEpJRXpM1pYTVPQ5dpPQRc9F49xk4(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2180.617366228 (+◎2180.590507588)
-   150 D9iBN61a4MAt49gvaovohF77zqzoyQ5ERVZUoAfub3o2(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎153515271.032113010 (+◎153515271.005254370)
+   150 D9iBN61a4MAt49gvaovohF77zqzoyQ5ERVZUoAfub3o2(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2138.491991544 (+◎2138.465132904)
-   151 DEU9FLyWEMihJzWat5RzgftPRy9nrQhspSQHGh12wCxC(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎90239701.511166423 (+◎90239701.484307783)
+   151 DEU9FLyWEMihJzWat5RzgftPRy9nrQhspSQHGh12wCxC(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1475.005872343 (+◎1474.979013703)
-   152 DQ7D6ZRtKbBSxCcAunEkoTzQhCBKLPdzTjPRRnM6wo1f(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎101613446.100068337 (+◎101613446.073209697)
+   152 DQ7D6ZRtKbBSxCcAunEkoTzQhCBKLPdzTjPRRnM6wo1f(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1681.133838545 (+◎1681.106979905)
-   153 Da4wfeJZkLqZVJ1TGadvHNSY2J6TZV2R33s7fY3Ugn28(Stake11111111111111111111111111111111111111): ◎28897.000000000 => ◎16304681.693817954 (+◎16275784.693817954)
+   153 Da4wfeJZkLqZVJ1TGadvHNSY2J6TZV2R33s7fY3Ugn28(Stake11111111111111111111111111111111111111): ◎28897.000000000 => ◎28946.153348418 (+◎49.153348418)
-   154 DumiCKHVqoCQKD8roLApzR5Fit8qGV5fVQsJV9sTZk4a(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎467294736.231845740 (+◎467294736.204987100)
+   154 DumiCKHVqoCQKD8roLApzR5Fit8qGV5fVQsJV9sTZk4a(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎11102.464946991 (+◎11102.438088351)
-   155 DzCirYWNsCECVHgSaMVg1mqMzKwtGuN2Pqm2a4HqVpTE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎162990425.886017172 (+◎162990425.859158532)
+   155 DzCirYWNsCECVHgSaMVg1mqMzKwtGuN2Pqm2a4HqVpTE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2210.051968615 (+◎2210.025109975)
-   156 EXEGg4fRhq7YqK62oKejKeErBHLJqM9tb6iqWpVaHWDD(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3162198.160479366 (+◎3162198.133620726)
+   156 EXEGg4fRhq7YqK62oKejKeErBHLJqM9tb6iqWpVaHWDD(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.206610507 (+◎38.179751867)
-   157 EcftPWmVzE7KS7m1P3xySxEyGn52hbGfSip9ygAv2G4J(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎28863080.325129688 (+◎28813080.325129688)
+   157 EcftPWmVzE7KS7m1P3xySxEyGn52hbGfSip9ygAv2G4J(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50099.899769156 (+◎99.899769156)
-   158 Eif6bAMGBhdeNoVDGMjTL8UUNDoVyhW8d24mUEjNkc8A(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎12182530.630872642 (+◎12177530.630872642)
+   158 Eif6bAMGBhdeNoVDGMjTL8UUNDoVyhW8d24mUEjNkc8A(Stake11111111111111111111111111111111111111): ◎5000.000000000 => ◎5036.776500626 (+◎36.776500626)
-   159 EkLA4nA5jtM2t2FkNWo6XWAyvQyaJJUZoX5p7LMawoaz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎103199517.265282333 (+◎103199517.238423693)
+   159 EkLA4nA5jtM2t2FkNWo6XWAyvQyaJJUZoX5p7LMawoaz(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1685.923820109 (+◎1685.896961469)
-   160 EsEtxoyhFTgfvudcy2VwwQJ1qA6BScLUW39PKpYczuxF(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2346421.251080534 (+◎2346421.224221894)
+   160 EsEtxoyhFTgfvudcy2VwwQJ1qA6BScLUW39PKpYczuxF(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎7.113119741 (+◎7.086261101)
-   161 EtD9iqsyzMvuWAw7rQsmeUdvPBD9StjvgWoXp92ZrS3G(Stake11111111111111111111111111111111111111): ◎39.000000000 => ◎83178.209552043 (+◎83139.209552043)
+   161 EtD9iqsyzMvuWAw7rQsmeUdvPBD9StjvgWoXp92ZrS3G(Stake11111111111111111111111111111111111111): ◎39.000000000 => ◎39.251082857 (+◎0.251082857)
-   162 F5XcsWb5YCA39hLGP1tpUZDScTTgn1k2UeHXyaFpGXMj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎148611084.909301368 (+◎148611084.882442728)
+   162 F5XcsWb5YCA39hLGP1tpUZDScTTgn1k2UeHXyaFpGXMj(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2095.051384718 (+◎2095.024526078)
-   163 F5b1wSUtpaYDnpjLQonCZC7iyFvizLcNqTactZbwSEXK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎112269857.938517314 (+◎112269857.911658674)
+   163 F5b1wSUtpaYDnpjLQonCZC7iyFvizLcNqTactZbwSEXK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1699.001605430 (+◎1698.974746790)
-   164 FKsC411dik9ktS6xPADxs4Fk2SCENvAiuccQHLAPndvk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎81192031.435963432 (+◎81192031.409104792)
+   164 FKsC411dik9ktS6xPADxs4Fk2SCENvAiuccQHLAPndvk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1619.460565700 (+◎1619.433707060)
-   165 FQtMWMc1yo8NGpvPEFck2eCaTexa1434i87X5T9qDwqX(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2752905.440639152 (+◎2752905.413780512)
+   165 FQtMWMc1yo8NGpvPEFck2eCaTexa1434i87X5T9qDwqX(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎22.655624202 (+◎22.628765562)
-   166 FSj7gzzNHhALp1qVP7BLqbakcLSMNosEtykLn69vHXyk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎36781986.205879000 (+◎36781986.179020360)
+   166 FSj7gzzNHhALp1qVP7BLqbakcLSMNosEtykLn69vHXyk(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎912.744512878 (+◎912.717654238)
-   167 FSk4tbkqqdsU4LKEyfth2TnspgituJRDDimNocJna6fq(Stake11111111111111111111111111111111111111): ◎1529000.000000000 => ◎18999023.603074442 (+◎17470023.603074442)
+   167 FSk4tbkqqdsU4LKEyfth2TnspgituJRDDimNocJna6fq(Stake11111111111111111111111111111111111111): ◎1529000.000000000 => ◎1531436.192542506 (+◎2436.192542506)
-   168 FqUfeiVYd1LMNSDw1t9WE6fAXAKzjUVHf8YzZXWQjSMd(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2445220.295321019 (+◎2445220.268462379)
+   168 FqUfeiVYd1LMNSDw1t9WE6fAXAKzjUVHf8YzZXWQjSMd(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎21.726406014 (+◎21.699547374)
-   169 FxJRgcURWS5GJvhTLTFJ2se1fVu86jZCEshxsFEbShJh(Stake11111111111111111111111111111111111111): ◎3802.000000000 => ◎2055106.015856698 (+◎2051304.015856698)
+   169 FxJRgcURWS5GJvhTLTFJ2se1fVu86jZCEshxsFEbShJh(Stake11111111111111111111111111111111111111): ◎3802.000000000 => ◎3808.194998453 (+◎6.194998453)
-   170 FxXCvhMZGUCSi8ZwYFLVSZBFyBNyFGLEmLQxc8BLctDt(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2345322.088631808 (+◎2345322.061773168)
+   170 FxXCvhMZGUCSi8ZwYFLVSZBFyBNyFGLEmLQxc8BLctDt(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎7.109800238 (+◎7.082941598)
-   171 G7akZgkcuqr7Vw1bHXqerKeawQ2Uc1WK9VaYq9APWNLE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎107448325.607950296 (+◎107448325.581091656)
+   171 G7akZgkcuqr7Vw1bHXqerKeawQ2Uc1WK9VaYq9APWNLE(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1727.385166764 (+◎1727.358308124)
-   172 GB44NXtM7zGm6QnzQjzHZcRKSswkJbox8aJsKiXGbFJr(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎141111069.214329748 (+◎141111069.187471108)
+   172 GB44NXtM7zGm6QnzQjzHZcRKSswkJbox8aJsKiXGbFJr(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2143.975668030 (+◎2143.948809390)
-   173 GJPXfCUjDy9PjqQ2Cvh7pSEvPu8vRjMXz2kSULBBaSLt(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎78608059.457700788 (+◎78608059.430842148)
+   173 GJPXfCUjDy9PjqQ2Cvh7pSEvPu8vRjMXz2kSULBBaSLt(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1597.341984080 (+◎1597.315125440)
-   174 GMpKrAwQ9oa4sJqEYQezLr8Z2TUAU72tXD4iMyfoJjbh(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎146618325.209385678 (+◎146618325.182527038)
+   174 GMpKrAwQ9oa4sJqEYQezLr8Z2TUAU72tXD4iMyfoJjbh(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2604.369961001 (+◎2604.343102361)
-   175 GNJCWEvN3HWF1nFS3ZisjKiyHx8b3kfBEbVxdoWPobPr(Stake11111111111111111111111111111111111111): ◎28397.000000000 => ◎18783478.187602404 (+◎18755081.187602404)
+   175 GNJCWEvN3HWF1nFS3ZisjKiyHx8b3kfBEbVxdoWPobPr(Stake11111111111111111111111111111111111111): ◎28397.000000000 => ◎28453.640896742 (+◎56.640896742)
-   176 GhKEDkvGkf2kceG45ppzqnPD6BPXi1PyW1xGNWJdh5QW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎95758128.500391436 (+◎95758128.473532796)
+   176 GhKEDkvGkf2kceG45ppzqnPD6BPXi1PyW1xGNWJdh5QW(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1663.450607199 (+◎1663.423748559)
-   177 GjYzNftUGedbXZXMVm8P9HsvJDosFgPEwJSzjswuDZv6(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2743392.449811963 (+◎2743392.422953323)
+   177 GjYzNftUGedbXZXMVm8P9HsvJDosFgPEwJSzjswuDZv6(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎22.626894690 (+◎22.600036050)
-   178 Gm73jdcvnFXn1rGuZ5HdZwBkvQiMrvUEwXoiE2sroa7e(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎37446943.974678496 (+◎36946943.974678496)
+   178 Gm73jdcvnFXn1rGuZ5HdZwBkvQiMrvUEwXoiE2sroa7e(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎501024.156386109 (+◎1024.156386109)
-   179 GvZEwtCHZ7YtCkQCaLRVEXsyVvQkRDhJhQgB6akPme1e(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎101547937.217153450 (+◎101547937.190294810)
+   179 GvZEwtCHZ7YtCkQCaLRVEXsyVvQkRDhJhQgB6akPme1e(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1680.935999792 (+◎1680.909141152)
-   180 GzhZDPBjhZpeteBULgSuwpPRd76yTCH8P37PCMmtN1yh(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3135697.615790375 (+◎3135697.588931735)
+   180 GzhZDPBjhZpeteBULgSuwpPRd76yTCH8P37PCMmtN1yh(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.126578083 (+◎38.099719443)
-   181 H1wiu8FvJZ3UqUCGMNfVeAbtB7YJMcL9aHGPJdvPNKTm(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎149168646.296947368 (+◎149168646.270088728)
+   181 H1wiu8FvJZ3UqUCGMNfVeAbtB7YJMcL9aHGPJdvPNKTm(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎2111.050146762 (+◎2111.023288122)
-   182 H3GhqPMwvGLdxWg3QJGjXDSkFSJCsFk3Wx9XBTdYZykc(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎33582972.901391081 (+◎33582972.874532441)
+   182 H3GhqPMwvGLdxWg3QJGjXDSkFSJCsFk3Wx9XBTdYZykc(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1223.737388329 (+◎1223.710529689)
-   183 H8KYQBuNM4yizafzmiopfMbGcNMzBR4jndBB8HLwiE6V(Stake11111111111111111111111111111111111111): ◎0.400000000 => ◎8.673009334 (+◎8.273009334)
+   183 H8KYQBuNM4yizafzmiopfMbGcNMzBR4jndBB8HLwiE6V(Stake11111111111111111111111111111111111111): ◎0.400000000 => ◎0.400024984 (+◎0.000024984)
-   184 H8VT3V6EDiYiQqmeDgqZJf4Tt76Qe6WZjPhighAGPL5T(Stake11111111111111111111111111111111111111): ◎3999999.000000000 => ◎26735664.522715792 (+◎22735665.522715792)
+   184 H8VT3V6EDiYiQqmeDgqZJf4Tt76Qe6WZjPhighAGPL5T(Stake11111111111111111111111111111111111111): ◎3999999.000000000 => ◎4006955.424596802 (+◎6956.424596802)
-   185 HGDF7nJDyQaovCZnyMBMzhdMSJPf3BL39K7KSJQynvab(Stake11111111111111111111111111111111111111): ◎444442.000000000 => ◎31097624.791425760 (+◎30653182.791425760)
+   185 HGDF7nJDyQaovCZnyMBMzhdMSJPf3BL39K7KSJQynvab(Stake11111111111111111111111111111111111111): ◎444442.000000000 => ◎445316.167613413 (+◎874.167613413)
-   186 HJMC4aGmZtLYqhvp96NGvji57RB9Uk2YY1LA8fJHpdre(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎31190377.770544644 (+◎30690377.770544644)
+   186 HJMC4aGmZtLYqhvp96NGvji57RB9Uk2YY1LA8fJHpdre(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎501043.625331661 (+◎1043.625331661)
-   187 HQ6ywTaLZxjEVLJsR4rLeLjGw7ZDJKd2c5fSF8FHxaG7(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3156551.626321101 (+◎3156551.599462461)
+   187 HQ6ywTaLZxjEVLJsR4rLeLjGw7ZDJKd2c5fSF8FHxaG7(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.189557808 (+◎38.162699168)
-   188 HaLHtySMw2fe1gbKALepWLSS1VgnZhpT4iMgQ5gMgWCL(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎20850886.483219196 (+◎20800886.483219196)
+   188 HaLHtySMw2fe1gbKALepWLSS1VgnZhpT4iMgQ5gMgWCL(Stake11111111111111111111111111111111111111): ◎50000.000000000 => ◎50120.078929919 (+◎120.078929919)
-   189 HbR1ntSGQ4so5rdxch7kFoqCv7mYTCRttKqqHvhadYdL(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎37869228.538693776 (+◎37369228.538693776)
+   189 HbR1ntSGQ4so5rdxch7kFoqCv7mYTCRttKqqHvhadYdL(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎501200.789348536 (+◎1200.789348536)
-   190 HoFU1hVTYvh4ryBfbYCzTu9dBta73jX3Ag3rzzoqYJG6(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3168505.946361190 (+◎3168505.919502550)
+   190 HoFU1hVTYvh4ryBfbYCzTu9dBta73jX3Ag3rzzoqYJG6(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.225660206 (+◎38.198801566)
-   191 J13gPuDfN9UQdPcj9uTh4NEqFZ25Ng4KucLpC4EPnkXY(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎36164491.814217712 (+◎35664491.814217712)
+   191 J13gPuDfN9UQdPcj9uTh4NEqFZ25Ng4KucLpC4EPnkXY(Stake11111111111111111111111111111111111111): ◎500000.000000000 => ◎501097.727007349 (+◎1097.727007349)
-   192 J6hFEnGhsGxTyss6DNW9aNQskPZ98gD8P6Wo1F5MBsCK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎3166078.610923104 (+◎3166078.584064464)
+   192 J6hFEnGhsGxTyss6DNW9aNQskPZ98gD8P6Wo1F5MBsCK(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎38.218329582 (+◎38.191470942)
-   193 J9Go27V87fCdJtjMxmFJu48ctrHzFoe6xQpA6Ecq4Wkw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎107596704.623541767 (+◎107596704.596683127)
+   193 J9Go27V87fCdJtjMxmFJu48ctrHzFoe6xQpA6Ecq4Wkw(Vote111111111111111111111111111111111111111): ◎0.026858640 => ◎1699.203455243 (+◎1699.176596603)
-   194 Sum of lamports changes: ◎13220394688.018068983
+   194 Sum of lamports changes: ◎362741.521908540
```

File: runtime/src/bank.rs [hunk 19]
```diff
@@ -4774,6 +4825,89 @@ mod tests {
...
+        // not being eagerly-collected for exact rewards calculation
+        bank.lazy_rent_collection.store(true, Ordering::Relaxed);
+
+        assert_eq!(bank.capitalization(), 42 * 1_000_000_000);
+        assert_eq!(bank.rewards, None);
+
+        let vote_id = Pubkey::new_rand();
+        let mut vote_account = vote_state::create_account(&vote_id, &Pubkey::new_rand(), 50, 100);
+        let (stake_id1, stake_account1) = crate::stakes::tests::create_stake_account(123, &vote_id);
+        let (stake_id2, stake_account2) = crate::stakes::tests::create_stake_account(456, &vote_id);
```
Comment (ryoqun) [inline runtime/src/bank.rs:4863]: https://github.com/solana-labs/solana/pull/10914#commitcomment-40767916:

> lgtm, would love to see a test where 2 stakers point to the same voter

@rwalker-com Thanks for LGTM! Actually, we're testing that case here even with commission split.

**Comment by ryoqun** [comment]
> ```diff
> +   194 Sum of lamports changes: ◎362741.521908540
> ```

Cool. So, I'm fiddling **the code** which would juggle real ~$300k _every 2 day_.



> ```diff
> +     4 Capitalization: ◎488626201.531987508 => ◎488988943.053896048 (+◎362741.521908540 100.07423701814828%)
> ```

```
[6] pry(main)> 0.143 * (2.0/365.25) * 100
=> 0.07830253251197809

```

The overall realized initial inflation doesn't seem too off this time. :)

File: runtime/src/bank.rs (hunk 19 above)
Comment (rwalker-com) [reply runtime/src/bank.rs:4863]: nice: glad of it

**Comment by ryoqun** [comment]
FYI: I've done the last-minute check for testnet/tds as well:

```
$ bad
...
[2020-07-21T06:20:51.912935341Z INFO  solana_runtime::bank] bank frozen: 24750606 hash: 8zyxsoc8ZfjsQK7Ae5VQgcRx1jUGKYh6GrYmjW32E8dp accounts_delta: 5UAbhokfGLQrGRunpYBriBacWzkSdYnRFKUbgbA8mVj9 signature_count: 257 last_blockhash: HRfqkSoAjG3xiEV4eDcUALZbXZ8wZPTiCcPrrezHMynY capitalization: 2494293818434898011
[2020-07-21T06:20:51.913064008Z INFO  solana_runtime::bank] accounts hash slot: 24750606 stats: BankHashStats { num_updated_accounts: 437, num_removed_accounts: 0, num_lamports_stored: 14113338954984395373, total_data_len: 966694, num_executable_accounts: 0 }
...
[2020-07-21T06:20:58.504517540Z INFO  solana_runtime::bank] bank frozen: 25148256 hash: 8XfaoiZXmJub2HsJC9x2Jpv26dWC4uNctXm2wMjBS2uD accounts_delta: BagohkbuvgZDSzKs28vQ2gHrkd8rEYqGsuv2mHsNyKCV signature_count: 0 last_blockhash: HRfqkSoAjG3xiEV4eDcUALZbXZ8wZPTiCcPrrezHMynY capitalization: 2598992994769251166
[2020-07-21T06:20:58.504545698Z INFO  solana_runtime::bank] accounts hash slot: 25148256 stats: BankHashStats { num_updated_accounts: 156948, num_removed_accounts: 0, num_lamports_stored: 523257198622906063, total_data_len: 318258978, num_executable_accounts: 1 }
...

$ good
...
[2020-07-21T05:55:31.149559998Z INFO  solana_runtime::bank] bank frozen: 24750606 hash: 8zyxsoc8ZfjsQK7Ae5VQgcRx1jUGKYh6GrYmjW32E8dp accounts_delta: 5UAbhokfGLQrGRunpYBriBacWzkSdYnRFKUbgbA8mVj9 signature_count: 257 last_blockhash: HRfqkSoAjG3xiEV4eDcUALZbXZ8wZPTiCcPrrezHMynY capitalization: 2494293818434898011
[2020-07-21T05:55:31.155600544Z INFO  solana_runtime::bank] accounts hash slot: 24750606 stats: BankHashStats { num_updated_accounts: 437, num_removed_accounts: 0, num_lamports_stored: 14113338954984395373, total_data_len: 966694, num_executable_accounts: 0 }
...
[2020-07-21T05:55:36.350486068Z INFO  solana_runtime::bank] bank frozen: 25148256 hash: 3WuUVyxWuyvr3WCuX8FDPKxDnuxRHhaskKY1p1GR76Q5 accounts_delta: AcscitVra3c7JtwBQZKqg2jobGheSCYLfUoVmfrwRgqW signature_count: 0 last_blockhash: HRfqkSoAjG3xiEV4eDcUALZbXZ8wZPTiCcPrrezHMynY capitalization: 2494369134127873497
[2020-07-21T05:55:36.350512013Z INFO  solana_runtime::bank] accounts hash slot: 25148256 stats: BankHashStats { num_updated_accounts: 78638, num_removed_accounts: 0, num_lamports_stored: 18344131239914373508, total_data_len: 16471918, num_executable_accounts: 1 }
...

$ diff
...
```

```patch

--- /dev/fd/63  2020-07-21 15:28:25.778837488 +0900
+++ /dev/fd/62  2020-07-21 15:28:25.778837488 +0900
@@ -1,166 +1,166 @@
      1 Recalculating capitalization
      2 Forcing to: Inflation { initial: 0.15, terminal: 0.015, taper: 0.15, foundation: 0.05, foundation_term: 7.0, storage: 0.0 } (was: Inflation { initial: 0.0, terminal: 0.0, taper: 0.0, foundation: 0.0, foundation_term: 0.0, storage: 0.0 })
      3 Slot: 24750606 => 25148256
      4 Epoch: 70 => 71
-     5 Capitalization: ◎2492522401.278725094 => ◎2598992994.769251166 (+◎106470593.490526072 104.27160026469187%)
+     5 Capitalization: ◎2492522401.278725094 => ◎2494369134.127873497 (+◎1846732.849148403 100.07409092284189%)
-     6 123JiW1rwJ4JM5BxYqFkBi6wQJ52pt6qUH88JDqrtU9i(Vote111111111111111111111111111111111111111): ◎146601215.822034024 => ◎148487824.895352865 (+◎1886609.073318841)
+     6 123JiW1rwJ4JM5BxYqFkBi6wQJ52pt6qUH88JDqrtU9i(Vote111111111111111111111111111111111111111): ◎146601215.822034024 => ◎146640163.752437743 (+◎38947.930403719)
-     7 KBsdty1yfwQDke2wGj7hxnBD6KwUGgmahYKsjDed5fR(Vote111111111111111111111111111111111111111): ◎342461282.200113293 => ◎342775898.005506133 (+◎314615.805392840)
+     7 KBsdty1yfwQDke2wGj7hxnBD6KwUGgmahYKsjDed5fR(Vote111111111111111111111111111111111111111): ◎342461282.200113293 => ◎342477191.315968156 (+◎15909.115854863)
-     8 T8wATAmKD48XcdGuoN3m23vgFP1ofadcGzKu4qH1x7C(Vote111111111111111111111111111111111111111): ◎78205702.209417828 => ◎78207676.218970976 (+◎1974.009553148)
+     8 T8wATAmKD48XcdGuoN3m23vgFP1ofadcGzKu4qH1x7C(Vote111111111111111111111111111111111111111): ◎78205702.209417828 => ◎78205713.402630562 (+◎11.193212734)
-     9 WRwK9LxLp4gH6YZmo8q9jYvaAmMzUnCsZVtRLFDtmeN(Vote111111111111111111111111111111111111111): ◎5.513531802 => ◎5.564461326 (+◎0.050929524)
+     9 WRwK9LxLp4gH6YZmo8q9jYvaAmMzUnCsZVtRLFDtmeN(Vote111111111111111111111111111111111111111): ◎5.513531802 => ◎5.513820587 (+◎0.000288785)
-    10 bJ5xQ3uCRyKacwTJjgwFsjMHw4RA9cnZ69EcYzxD11d(Vote111111111111111111111111111111111111111): ◎13172106.083753866 => ◎13181406.507583147 (+◎9300.423829281)
+    10 bJ5xQ3uCRyKacwTJjgwFsjMHw4RA9cnZ69EcYzxD11d(Vote111111111111111111111111111111111111111): ◎13172106.083753866 => ◎13172158.819882862 (+◎52.736128996)
-    11 rY5tcivBEP4fdybqXBKojDWCVrvyNjWn1fdpkDCNRSs(Vote111111111111111111111111111111111111111): ◎12986375.967948335 => ◎13006406.252311716 (+◎20030.284363381)
+    11 rY5tcivBEP4fdybqXBKojDWCVrvyNjWn1fdpkDCNRSs(Vote111111111111111111111111111111111111111): ◎12986375.967948335 => ◎12986489.545531404 (+◎113.577583069)
-    12 uSVk7mLfVvfTEjHm3LhJu8wvf6bczneWHEwr6xLptGh(Vote111111111111111111111111111111111111111): ◎87041159.699869726 => ◎87041484.100222528 (+◎324.400352802)
+    12 uSVk7mLfVvfTEjHm3LhJu8wvf6bczneWHEwr6xLptGh(Vote111111111111111111111111111111111111111): ◎87041159.699869726 => ◎87041161.539314805 (+◎1.839445079)
-    13 xmCABVMB5MTwowJPS1bVQHt3u3o5E3YSHp4gjSKYizB(Vote111111111111111111111111111111111111111): ◎208250847.244540140 => ◎210030296.894269269 (+◎1779449.649729129)
+    13 xmCABVMB5MTwowJPS1bVQHt3u3o5E3YSHp4gjSKYizB(Vote111111111111111111111111111111111111111): ◎208250847.244540140 => ◎208289187.549651208 (+◎38340.305111068)
-    14 yxSPFbQ83rEwy6LLB5kYzaJnbzPT8ZDAfxRw7Wj6qiP(Vote111111111111111111111111111111111111111): ◎209057518.685791965 => ◎213147612.915341458 (+◎4090094.229549493)
+    14 yxSPFbQ83rEwy6LLB5kYzaJnbzPT8ZDAfxRw7Wj6qiP(Vote111111111111111111111111111111111111111): ◎209057518.685791965 => ◎209123086.174930405 (+◎65567.489138440)
-    15 2117AKQjaeQucLm3KzQbvnxdChpaswAW3f2RD9VgaxYp(Vote111111111111111111111111111111111111111): ◎84210.718526803 => ◎84592.078088098 (+◎381.359561295)
+    15 2117AKQjaeQucLm3KzQbvnxdChpaswAW3f2RD9VgaxYp(Vote111111111111111111111111111111111111111): ◎84210.718526803 => ◎84212.880947289 (+◎2.162420486)
-    16 21pQ7zxtEFeSdPkjXmfr87HvzmqKKj5vPEjsyXyfkYoN(Vote111111111111111111111111111111111111111): ◎85743.464124742 => ◎88867.932842871 (+◎3124.468718129)
+    16 21pQ7zxtEFeSdPkjXmfr87HvzmqKKj5vPEjsyXyfkYoN(Vote111111111111111111111111111111111111111): ◎85743.464124742 => ◎85761.180778131 (+◎17.716653389)
-    17 2CqUJ8sxy1CUomZMnvVaDgb4yvt61z8o1wfsJwES4Ct2(Vote111111111111111111111111111111111111111): ◎7026.976324874 => ◎7027.091180531 (+◎0.114855657)
+    17 2CqUJ8sxy1CUomZMnvVaDgb4yvt61z8o1wfsJwES4Ct2(Vote111111111111111111111111111111111111111): ◎7026.976324874 => ◎7026.976976139 (+◎0.000651265)
-    18 2F7UUBHoAvt6MTJytpFSCaiUg7sfmwdk1M5wYfX1e7SB(Vote111111111111111111111111111111111111111): ◎196779821.568582240 => ◎196972549.835996130 (+◎192728.267413890)
+    18 2F7UUBHoAvt6MTJytpFSCaiUg7sfmwdk1M5wYfX1e7SB(Vote111111111111111111111111111111111111111): ◎196779821.568582240 => ◎196780914.394345728 (+◎1092.825763488)
-    19 2FBYoCXLZ3NaeoxHPCR6mAkVnYUQmZ8FEoZJgukDEJ2E(Vote111111111111111111111111111111111111111): ◎85312.439322740 => ◎85694.841982398 (+◎382.402659658)
+    19 2FBYoCXLZ3NaeoxHPCR6mAkVnYUQmZ8FEoZJgukDEJ2E(Vote111111111111111111111111111111111111111): ◎85312.439322740 => ◎85314.607657898 (+◎2.168335158)
-    20 2GsjGTdyQ9hzLVmLuBH3bxQUp219Z9YCQi2DojWEM1U1(Vote111111111111111111111111111111111111111): ◎210747686.824483861 => ◎210944196.606528917 (+◎196509.782045056)
+    20 2GsjGTdyQ9hzLVmLuBH3bxQUp219Z9YCQi2DojWEM1U1(Vote111111111111111111111111111111111111111): ◎210747686.824483861 => ◎210748801.092543641 (+◎1114.268059780)
-    21 2HMrFxwnXCKp9PZCQ7wkPWAdj864M27FBQQcSDo8kvEc(Vote111111111111111111111111111111111111111): ◎23118543.092620193 => ◎23138573.088618789 (+◎20029.995998596)
+    21 2HMrFxwnXCKp9PZCQ7wkPWAdj864M27FBQQcSDo8kvEc(Vote111111111111111111111111111111111111111): ◎23118543.092620193 => ◎23118656.668568150 (+◎113.575947957)
-    22 2HUTvSShCGLFQDqahGXMLUhkW9c29P5Y3Qiui7VA7E8G(Vote111111111111111111111111111111111111111): ◎84885.182273481 => ◎85266.076873574 (+◎380.894600093)
+    22 2HUTvSShCGLFQDqahGXMLUhkW9c29P5Y3Qiui7VA7E8G(Vote111111111111111111111111111111111111111): ◎84885.182273481 => ◎84887.342057500 (+◎2.159784019)
-    23 2hAMR5dPGt6sRbYiF2G6wY7zc9VhYkjTbena2BRgZDJ1(Vote111111111111111111111111111111111111111): ◎85043.062323246 => ◎85423.879586952 (+◎380.817263706)
+    23 2hAMR5dPGt6sRbYiF2G6wY7zc9VhYkjTbena2BRgZDJ1(Vote111111111111111111111111111111111111111): ◎85043.062323246 => ◎85045.221668745 (+◎2.159345499)
-    24 2oz3828iNvJQ184dzDsymHYmuCHZhGKEUmQTJWSFc9QV(Vote111111111111111111111111111111111111111): ◎5.513173465 => ◎5.564092665 (+◎0.050919200)
+    24 2oz3828iNvJQ184dzDsymHYmuCHZhGKEUmQTJWSFc9QV(Vote111111111111111111111111111111111111111): ◎5.513173465 => ◎5.513462191 (+◎0.000288726)
-    25 2qjn31sgbmCbFqLoZemHvR45xurMi1S4Zqny813N98Lz(Vote111111111111111111111111111111111111111): ◎10868572.159901151 => ◎10870497.045958985 (+◎1924.886057834)
+    25 2qjn31sgbmCbFqLoZemHvR45xurMi1S4Zqny813N98Lz(Vote111111111111111111111111111111111111111): ◎10868572.159901151 => ◎10868583.074569269 (+◎10.914668118)
-    26 2sAXpqASy1tLKwo2z2UG2SPZhYfEpNFBrqZwxgvZhQ6b(Vote111111111111111111111111111111111111111): ◎3.481825368 => ◎3.524250532 (+◎0.042425164)
+    26 2sAXpqASy1tLKwo2z2UG2SPZhYfEpNFBrqZwxgvZhQ6b(Vote111111111111111111111111111111111111111): ◎3.481825368 => ◎3.482065931 (+◎0.000240563)
-    27 2zY1fMcEn9wiUjdMHzz2ZKokJ3oWFKhr4CX6ewznyJtB(Vote111111111111111111111111111111111111111): ◎36094.432750113 => ◎36094.547959555 (+◎0.115209442)
+    27 2zY1fMcEn9wiUjdMHzz2ZKokJ3oWFKhr4CX6ewznyJtB(Vote111111111111111111111111111111111111111): ◎36094.432750113 => ◎36094.433403384 (+◎0.000653271)
-    28 31QjBFNbPP2AwRE8hwawfLV6kt3Wcj7epzwAeP1RFEXT(Vote111111111111111111111111111111111111111): ◎190293932.986493641 => ◎190490458.999144376 (+◎196526.012650735)
+    28 31QjBFNbPP2AwRE8hwawfLV6kt3Wcj7epzwAeP1RFEXT(Vote111111111111111111111111111111111111111): ◎190293932.986493641 => ◎190295047.346585711 (+◎1114.360092070)
-    29 333SjzuU1RTErVjagyMEnwzdkXCnXjTAdGKF3SNk14k9(Vote111111111111111111111111111111111111111): ◎303401976.915983925 => ◎303681722.349064673 (+◎279745.433080748)
+    29 333SjzuU1RTErVjagyMEnwzdkXCnXjTAdGKF3SNk14k9(Vote111111111111111111111111111111111111111): ◎303401976.915983925 => ◎303417688.306607526 (+◎15711.390623601)
-    30 33GTUGdZRkKjyvt5AVAax15fXGfjM13JCNRcgzN2Hsn2(Vote111111111111111111111111111111111111111): ◎211424368.156070930 => ◎211620837.223677668 (+◎196469.067606738)
+    30 33GTUGdZRkKjyvt5AVAax15fXGfjM13JCNRcgzN2Hsn2(Vote111111111111111111111111111111111111111): ◎211424368.156070930 => ◎211425482.193267912 (+◎1114.037196982)
-    31 34iW9renEpXMGNeiicA34DgXjY97TLV3XXtEVgbPFvk9(Vote111111111111111111111111111111111111111): ◎24900292.232017318 => ◎24918668.445675805 (+◎18376.213658487)
+    31 34iW9renEpXMGNeiicA34DgXjY97TLV3XXtEVgbPFvk9(Vote111111111111111111111111111111111111111): ◎24900292.232017318 => ◎24900396.430534695 (+◎104.198517377)
-    32 3GCSwcpCeQhLzXpsNVp42AgF63FmfMEGX2Uray35yXht(Vote111111111111111111111111111111111111111): ◎218739296.129924393 => ◎218942022.252245894 (+◎202726.122321501)
+    32 3GCSwcpCeQhLzXpsNVp42AgF63FmfMEGX2Uray35yXht(Vote111111111111111111111111111111111111111): ◎218739296.129924393 => ◎218740445.646455505 (+◎1149.516531112)
-    33 3qVBmVAcnjiaiQb45gCR6FY7kxcuBEBG9Up87n8uyhK7(Vote111111111111111111111111111111111111111): ◎11731654.394758903 => ◎11733634.489649683 (+◎1980.094890780)
+    33 3qVBmVAcnjiaiQb45gCR6FY7kxcuBEBG9Up87n8uyhK7(Vote111111111111111111111111111111111111111): ◎11731654.394758903 => ◎11731665.622477285 (+◎11.227718382)
-    34 3tsLRkBboc3SJooz1A7ABn4oLiSpuEtUV6Lutnwz4S9f(Vote111111111111111111111111111111111111111): ◎84300.189417039 => ◎84682.412307521 (+◎382.222890482)
+    34 3tsLRkBboc3SJooz1A7ABn4oLiSpuEtUV6Lutnwz4S9f(Vote111111111111111111111111111111111111111): ◎84300.189417039 => ◎84302.356732854 (+◎2.167315815)
-    35 44j9MEHn8DBWRiwZ7an5koPLRgxMTQxpYHwD6fiAg1UW(Vote111111111111111111111111111111111111111): ◎375043132.954357425 => ◎377277419.099943123 (+◎2234286.145585698)
+    35 44j9MEHn8DBWRiwZ7an5koPLRgxMTQxpYHwD6fiAg1UW(Vote111111111111111111111111111111111111111): ◎375043132.954357425 => ◎375055802.011655896 (+◎12669.057298471)
-    36 4Djq9Vgkdiktq1dz38KTnRoYmHBDPyUZn7fsDUwCmPSh(Vote111111111111111111111111111111111111111): ◎87841903.608924766 => ◎87843903.166820055 (+◎1999.557895289)
+    36 4Djq9Vgkdiktq1dz38KTnRoYmHBDPyUZn7fsDUwCmPSh(Vote111111111111111111111111111111111111111): ◎87841903.608924766 => ◎87841914.947004088 (+◎11.338079322)
-    37 4N8tZu9Yn9AkkpJCYVSH2o7jCHMThkeG8SRNc3ThnrFL(Vote111111111111111111111111111111111111111): ◎22546367.407047828 => ◎22566347.492830549 (+◎19980.085782721)
+    37 4N8tZu9Yn9AkkpJCYVSH2o7jCHMThkeG8SRNc3ThnrFL(Vote111111111111111111111111111111111111111): ◎22546367.407047828 => ◎22546480.699990233 (+◎113.292942405)
-    38 4WN4YE6b66ZYTPDJKxnVmsUuu1drGaNaYpxYL1ATyXJR(Vote111111111111111111111111111111111111111): ◎166435598.755119778 => ◎166612303.293486456 (+◎176704.538366678)
+    38 4WN4YE6b66ZYTPDJKxnVmsUuu1drGaNaYpxYL1ATyXJR(Vote111111111111111111111111111111111111111): ◎166435598.755119778 => ◎166436600.721643130 (+◎1001.966523352)
-    39 4ZY1SpBLcmqLVDrEotXs7mtZ3HLQapUzWHfYv9wK22n4(Vote111111111111111111111111111111111111111): ◎24456706.683675855 => ◎24490867.449370887 (+◎34160.765695032)
+    39 4ZY1SpBLcmqLVDrEotXs7mtZ3HLQapUzWHfYv9wK22n4(Vote111111111111111111111111111111111111111): ◎24456706.683675855 => ◎24456900.385229616 (+◎193.701553761)
-    40 4cgvAxaKo6FbHNoy1hD3gZEDuwAhnLH2WF2wuwhdzSUP(Vote111111111111111111111111111111111111111): ◎205209897.027982236 => ◎205406075.972339151 (+◎196178.944356915)
+    40 4cgvAxaKo6FbHNoy1hD3gZEDuwAhnLH2WF2wuwhdzSUP(Vote111111111111111111111111111111111111111): ◎205209897.027982236 => ◎205211009.420095359 (+◎1112.392113123)
-    41 4i8zNJT18CcuSgwWP6zKecKQKhP3Yd1hyeKJFkpdgv2f(Vote111111111111111111111111111111111111111): ◎2733.381066803 => ◎2733.456915203 (+◎0.075848400)
+    41 4i8zNJT18CcuSgwWP6zKecKQKhP3Yd1hyeKJFkpdgv2f(Vote111111111111111111111111111111111111111): ◎2733.381066803 => ◎2733.381496885 (+◎0.000430082)
-    42 4p18NSCRqBHgsb8U8hZQ98gQePSnigJt2FxbZvqgY3SR(Vote111111111111111111111111111111111111111): ◎5.533417840 => ◎5.584553842 (+◎0.051136002)
+    42 4p18NSCRqBHgsb8U8hZQ98gQePSnigJt2FxbZvqgY3SR(Vote111111111111111111111111111111111111111): ◎5.533417840 => ◎5.533707796 (+◎0.000289956)
-    43 4pMHzPz3BiGbZofrZDZk6hTs4KYMsHL78weQqmgoJ7Y8(Vote111111111111111111111111111111111111111): ◎64200352.022589510 => ◎76949707.264476072 (+◎12749355.241886562)
+    43 4pMHzPz3BiGbZofrZDZk6hTs4KYMsHL78weQqmgoJ7Y8(Vote111111111111111111111111111111111111111): ◎64200352.022589510 => ◎64300894.907607576 (+◎100542.885018066)
-    44 4xARLQv1SoiVNbmXmVYyQzEjG3YA67X1LfH9KkTLtzKd(Vote111111111111111111111111111111111111111): ◎75104593.486992515 => ◎75106560.573376331 (+◎1967.086383816)
+    44 4xARLQv1SoiVNbmXmVYyQzEjG3YA67X1LfH9KkTLtzKd(Vote111111111111111111111111111111111111111): ◎75104593.486992515 => ◎75104604.640948849 (+◎11.153956334)
-    45 4zoHsMTdhuDAkHAHNwEZqNqEmFyyqRxUxHwGuSdeepyB(Vote111111111111111111111111111111111111111): ◎46454877.914311764 => ◎47763633.859443241 (+◎1308755.945131477)
+    45 4zoHsMTdhuDAkHAHNwEZqNqEmFyyqRxUxHwGuSdeepyB(Vote111111111111111111111111111111111111111): ◎46454877.914311764 => ◎46490549.248160867 (+◎35671.333849103)
-    46 51g26vnVeJo8H4mW3MgS2pGkCbD3J7u5eGEgu8UnhRAq(Vote111111111111111111111111111111111111111): ◎196560.132375323 => ◎197404.457395223 (+◎844.325019900)
+    46 51g26vnVeJo8H4mW3MgS2pGkCbD3J7u5eGEgu8UnhRAq(Vote111111111111111111111111111111111111111): ◎196560.132375323 => ◎196564.919945648 (+◎4.787570325)
-    47 55vVhhndbwYd5WnZNVs5YKrBi7rJ7R8fCfiyuDEX9n5j(Vote111111111111111111111111111111111111111): ◎22691387.241512070 => ◎22708468.658501400 (+◎17081.416989330)
+    47 55vVhhndbwYd5WnZNVs5YKrBi7rJ7R8fCfiyuDEX9n5j(Vote111111111111111111111111111111111111111): ◎22691387.241512070 => ◎22691484.098152838 (+◎96.856640768)
-    48 56y3GnfskxYGEi1LsqnEyfFbUZLG8NwSZarZKje2qYfo(Vote111111111111111111111111111111111111111): ◎206185249.055523235 => ◎206379158.301967679 (+◎193909.246444444)
+    48 56y3GnfskxYGEi1LsqnEyfFbUZLG8NwSZarZKje2qYfo(Vote111111111111111111111111111111111111111): ◎206185249.055523235 => ◎206186348.577783962 (+◎1099.522260727)
-    49 57v1WtdsodSRZzQ8cHcmYwD6ZHWjF4uy2YLxpXs3xQtV(Vote111111111111111111111111111111111111111): ◎24807159.789885547 => ◎24954661.185622627 (+◎147501.395737080)
+    49 57v1WtdsodSRZzQ8cHcmYwD6ZHWjF4uy2YLxpXs3xQtV(Vote111111111111111111111111111111111111111): ◎24807159.789885547 => ◎24807996.166030961 (+◎836.376145414)
-    50 59TjvREZcxyBmXkxvcc3kCSeCPn6WAF5Mjvkty2pCiMp(Vote111111111111111111111111111111111111111): ◎42877.700611726 => ◎43200.935102702 (+◎323.234490976)
+    50 59TjvREZcxyBmXkxvcc3kCSeCPn6WAF5Mjvkty2pCiMp(Vote111111111111111111111111111111111111111): ◎42877.700611726 => ◎42879.533446027 (+◎1.832834301)
-    51 5CSKsHA7JN5RozBZ2nDYCj1bNRgMvqsPtafyvdpgCJKC(Vote111111111111111111111111111111111111111): ◎260452779.168219742 => ◎261156464.954776865 (+◎703685.786557123)
+    51 5CSKsHA7JN5RozBZ2nDYCj1bNRgMvqsPtafyvdpgCJKC(Vote111111111111111111111111111111111111111): ◎260452779.168219742 => ◎260470894.424901385 (+◎18115.256681643)
-    52 5CgQubGD1uwodwCe5UXDADbC69SiqXR8qq6pDMSm7ut5(Vote111111111111111111111111111111111111111): ◎400429960.215100749 => ◎402469236.164350539 (+◎2039275.949249790)
+    52 5CgQubGD1uwodwCe5UXDADbC69SiqXR8qq6pDMSm7ut5(Vote111111111111111111111111111111111111111): ◎400429960.215100749 => ◎400441523.507429928 (+◎11563.292329179)
-    53 5Ed6UFf9nk4rWxtniHmYrHCLGmJGwTPePK3uLmG5Abya(Vote111111111111111111111111111111111111111): ◎197088311.271806769 => ◎197278088.733499629 (+◎189777.461692860)
+    53 5Ed6UFf9nk4rWxtniHmYrHCLGmJGwTPePK3uLmG5Abya(Vote111111111111111111111111111111111111111): ◎197088311.271806769 => ◎197089387.365636959 (+◎1076.093830190)
-    54 5FisMpT6KdE3U3LVcV4Hds7eEU4TUct21V4Jvjpyck9P(Vote111111111111111111111111111111111111111): ◎65696416.857967837 => ◎67626801.948555089 (+◎1930385.090587252)
+    54 5FisMpT6KdE3U3LVcV4Hds7eEU4TUct21V4Jvjpyck9P(Vote111111111111111111111111111111111111111): ◎65696416.857967837 => ◎65707362.707213282 (+◎10945.849245445)
-    55 5YJtXfJ4Wu8edgK8jGW24VwC8VoKYof8fLcFRtRxGE2e(Vote111111111111111111111111111111111111111): ◎348724005.497226051 => ◎349331649.887032531 (+◎607644.389806480)
+    55 5YJtXfJ4Wu8edgK8jGW24VwC8VoKYof8fLcFRtRxGE2e(Vote111111111111111111111111111111111111111): ◎348724005.497226051 => ◎348741576.171039083 (+◎17570.673813032)
-    56 5Zar3YdKDhvgoEWiaWCUN7nnF9mVdS9bh967sZyTsCoK(Vote111111111111111111111111111111111111111): ◎17306.899159458 => ◎17519.610114643 (+◎212.710955185)
+    56 5Zar3YdKDhvgoEWiaWCUN7nnF9mVdS9bh967sZyTsCoK(Vote111111111111111111111111111111111111111): ◎17306.899159458 => ◎17308.105292917 (+◎1.206133459)
-    57 5eryCB6q3orrFt8H9yCEJ7A62H6LY8g2o9zk5DdvS5ta(Vote111111111111111111111111111111111111111): ◎253640377.880129368 => ◎253805346.030733092 (+◎164968.150603724)
+    57 5eryCB6q3orrFt8H9yCEJ7A62H6LY8g2o9zk5DdvS5ta(Vote111111111111111111111111111111111111111): ◎253640377.880129368 => ◎253641313.297894254 (+◎935.417764886)
-    58 5hnfQ5kp19mZs4ACj9VYQH4zeyAVD1SZLrDHP6UHFrHe(Vote111111111111111111111111111111111111111): ◎85163.493688126 => ◎85544.194947249 (+◎380.701259123)
+    58 5hnfQ5kp19mZs4ACj9VYQH4zeyAVD1SZLrDHP6UHFrHe(Vote111111111111111111111111111111111111111): ◎85163.493688126 => ◎85165.652375845 (+◎2.158687719)
-    59 5nNH2Eb29yEXy7sSEDeXNy29XwmcNUwDdUxoVyhrEfXc(Vote111111111111111111111111111111111111111): ◎54682.627083452 => ◎55004.053464807 (+◎321.426381355)
+    59 5nNH2Eb29yEXy7sSEDeXNy29XwmcNUwDdUxoVyhrEfXc(Vote111111111111111111111111111111111111111): ◎54682.627083452 => ◎54684.449665242 (+◎1.822581790)
-    60 5rhxGv2XgBZCfo5u5hSXE1g5w7vrYSviwTfKc2rs23Av(Vote111111111111111111111111111111111111111): ◎18646502.452028160 => ◎18666488.614684662 (+◎19986.162656502)
+    60 5rhxGv2XgBZCfo5u5hSXE1g5w7vrYSviwTfKc2rs23Av(Vote111111111111111111111111111111111111111): ◎18646502.452028160 => ◎18646615.779428221 (+◎113.327400061)
-    61 67c2VfxSUwAscV2zuBPpAdCot28Mz2P5MgEZfjTc4o2y(Vote111111111111111111111111111111111111111): ◎83754806.167280310 => ◎83756789.869406863 (+◎1983.702126553)
+    61 67c2VfxSUwAscV2zuBPpAdCot28Mz2P5MgEZfjTc4o2y(Vote111111111111111111111111111111111111111): ◎83754806.167280310 => ◎83754817.415452776 (+◎11.248172466)
-    62 69rUCD1qk6hJ3AqEkCi236QaceHTBSv1isiCEW6EZnVa(Vote111111111111111111111111111111111111111): ◎331650036.725823636 => ◎336313174.909870414 (+◎4663138.184046778)
+    62 69rUCD1qk6hJ3AqEkCi236QaceHTBSv1isiCEW6EZnVa(Vote111111111111111111111111111111111111111): ◎331650036.725823636 => ◎331676478.086059025 (+◎26441.360235389)
-    63 6ATud3K5ESiKc8DPmZVJYL2XeFfR3Q63epjCWKG9Gcfy(Vote111111111111111111111111111111111111111): ◎25297683.624291474 => ◎25319668.457086828 (+◎21984.832795354)
+    63 6ATud3K5ESiKc8DPmZVJYL2XeFfR3Q63epjCWKG9Gcfy(Vote111111111111111111111111111111111111111): ◎25297683.624291474 => ◎25297808.284737017 (+◎124.660445543)
-    64 6SQtqspNjqaRRHRs9Cn7LGhZaWwTSb4T2rSqKgB3syz7(Vote111111111111111111111111111111111111111): ◎93985908.949554746 => ◎110369673.124367634 (+◎16383764.174812888)
+    64 6SQtqspNjqaRRHRs9Cn7LGhZaWwTSb4T2rSqKgB3syz7(Vote111111111111111111111111111111111111111): ◎93985908.949554746 => ◎94191810.910601410 (+◎205901.961046664)
-    65 6TBT3jZRBUtJeUCjfj4mCjsvr1PMFMFWAhPadijgmces(Vote111111111111111111111111111111111111111): ◎84184.949207812 => ◎84566.128371964 (+◎381.179164152)
+    65 6TBT3jZRBUtJeUCjfj4mCjsvr1PMFMFWAhPadijgmces(Vote111111111111111111111111111111111111111): ◎84184.949207812 => ◎84187.110605393 (+◎2.161397581)
-    66 6WFUdYQF63E9oYsAeLcWibjdCP5BN9fbk1PLZJtPiH4x(Vote111111111111111111111111111111111111111): ◎45338642.985125475 => ◎45459194.042634765 (+◎120551.057509290)
+    66 6WFUdYQF63E9oYsAeLcWibjdCP5BN9fbk1PLZJtPiH4x(Vote111111111111111111111111111111111111111): ◎45338642.985125475 => ◎45339326.544954190 (+◎683.559828715)
-    67 6Z3gtuwZyR5RVQMYMsRthngSPsXz2JaagXYGjQ4Ddy8K(Vote111111111111111111111111111111111111111): ◎89534489.408759658 => ◎89538493.194823511 (+◎4003.786063853)
+    67 6Z3gtuwZyR5RVQMYMsRthngSPsXz2JaagXYGjQ4Ddy8K(Vote111111111111111111111111111111111111111): ◎89534489.408759658 => ◎89534512.111400120 (+◎22.702640462)
-    68 6bM3U2nXvuyUmnSBsQtsweLXVURXndaFBGRZgRdBDPPE(Vote111111111111111111111111111111111111111): ◎8.230551985 => ◎8.288488436 (+◎0.057936451)
+    68 6bM3U2nXvuyUmnSBsQtsweLXVURXndaFBGRZgRdBDPPE(Vote111111111111111111111111111111111111111): ◎8.230551985 => ◎8.230880501 (+◎0.000328516)
-    69 6eMD1DSGpbTXvdNLT4H68nB1FbuqmUq6SFTRPVj9HKEQ(Vote111111111111111111111111111111111111111): ◎275369212.198468729 => ◎276058775.676915774 (+◎689563.478447045)
+    69 6eMD1DSGpbTXvdNLT4H68nB1FbuqmUq6SFTRPVj9HKEQ(Vote111111111111111111111111111111111111111): ◎275369212.198468729 => ◎275387247.377524242 (+◎18035.179055513)
-    70 6hyj8niif7GK2BnBCwFUDpXf6E48dZhJZmyZXTFoVurG(Vote111111111111111111111111111111111111111): ◎896244.588682623 => ◎896628.744279412 (+◎384.155596789)
+    70 6hyj8niif7GK2BnBCwFUDpXf6E48dZhJZmyZXTFoVurG(Vote111111111111111111111111111111111111111): ◎896244.588682623 => ◎896246.766957449 (+◎2.178274826)
-    71 6mvFR8vgweW3CygZqs4Ap7GBQrDF5Yuao93pm69DT1QE(Vote111111111111111111111111111111111111111): ◎186261611.479874719 => ◎186440293.895521466 (+◎178682.415646747)
+    71 6mvFR8vgweW3CygZqs4Ap7GBQrDF5Yuao93pm69DT1QE(Vote111111111111111111111111111111111111111): ◎186261611.479874719 => ◎186262624.661541950 (+◎1013.181667231)
-    72 76U22xYYhXHdQfzQS2VFGsvbkVtjgsLSbDjJ1T2SkakR(Vote111111111111111111111111111111111111111): ◎159176758.055966537 => ◎159268296.632808941 (+◎91538.576842404)
+    72 76U22xYYhXHdQfzQS2VFGsvbkVtjgsLSbDjJ1T2SkakR(Vote111111111111111111111111111111111111111): ◎159176758.055966537 => ◎159177277.106526523 (+◎519.050559986)
-    73 77ayyLnrjKia83JxkGTCZFhsJFnvGWeiBaW3mbKzSqVE(Vote111111111111111111111111111111111111111): ◎421344964.350928380 => ◎421538625.083872302 (+◎193660.732943922)
+    73 77ayyLnrjKia83JxkGTCZFhsJFnvGWeiBaW3mbKzSqVE(Vote111111111111111111111111111111111111111): ◎421344964.350928380 => ◎421346062.464044721 (+◎1098.113116341)
-    74 7C1guowdFu2gLa4u8RtLWEsSnhGjb24JwBzLUEL4J3Nd(Vote111111111111111111111111111111111111111): ◎488554.724561105 => ◎488935.646015052 (+◎380.921453947)
+    74 7C1guowdFu2gLa4u8RtLWEsSnhGjb24JwBzLUEL4J3Nd(Vote111111111111111111111111111111111111111): ◎488554.724561105 => ◎488556.884497394 (+◎2.159936289)
-    75 7CfCBGP1GqtokAULgJQoKSif9aCUTNZVyAbbGhEBZSHm(Vote111111111111111111111111111111111111111): ◎147821511.752538307 => ◎147823476.806749863 (+◎1965.054211556)
+    75 7CfCBGP1GqtokAULgJQoKSif9aCUTNZVyAbbGhEBZSHm(Vote111111111111111111111111111111111111111): ◎147821511.752538307 => ◎147821522.894971629 (+◎11.142433322)
-    76 7FXvhWS2tpod5XkdMx31MbDo6Wv4xTH15rT8hcQ6Kx9E(Vote111111111111111111111111111111111111111): ◎69343.312444397 => ◎69698.139235699 (+◎354.826791302)
+    76 7FXvhWS2tpod5XkdMx31MbDo6Wv4xTH15rT8hcQ6Kx9E(Vote111111111111111111111111111111111111111): ◎69343.312444397 => ◎69345.324416300 (+◎2.011971903)
-    77 7GhSfP48TwP32ZVYxA3FHncqVnc6GTZyfJPTJK1coPDQ(Vote111111111111111111111111111111111111111): ◎42364970.794014397 => ◎43544803.019046864 (+◎1179832.225032467)
+    77 7GhSfP48TwP32ZVYxA3FHncqVnc6GTZyfJPTJK1coPDQ(Vote111111111111111111111111111111111111111): ◎42364970.794014397 => ◎42428161.396637303 (+◎63190.602622906)
-    78 7Miv4RF8qNnvMSQ2DwXSs1DL3tHbskLwj8yjjXujCG2J(Vote111111111111111111111111111111111111111): ◎181126093.258353655 => ◎186428485.901554152 (+◎5302392.643200497)
+    78 7Miv4RF8qNnvMSQ2DwXSs1DL3tHbskLwj8yjjXujCG2J(Vote111111111111111111111111111111111111111): ◎181126093.258353655 => ◎181184409.682786651 (+◎58316.424432996)
-    79 7PCfYyD9ZGuERWqMFd4YWgfi86vcvQ9W8b5Hb5Ta8BB6(Vote111111111111111111111111111111111111111): ◎66845669.939904362 => ◎68872242.844867639 (+◎2026572.904963277)
+    79 7PCfYyD9ZGuERWqMFd4YWgfi86vcvQ9W8b5Hb5Ta8BB6(Vote111111111111111111111111111111111111111): ◎66845669.939904362 => ◎66857161.202249268 (+◎11491.262344906)
-    80 7cwT5hFDTkVGgc15nmriizgwXHr7BX6TJPs5ztoDThsi(Vote111111111111111111111111111111111111111): ◎873488.125699683 => ◎873882.899538852 (+◎394.773839169)
+    80 7cwT5hFDTkVGgc15nmriizgwXHr7BX6TJPs5ztoDThsi(Vote111111111111111111111111111111111111111): ◎873488.125699683 => ◎873490.364183056 (+◎2.238483373)
-    81 7f9hY4y3HueRutNtt2VbSEuASqtDemuxY4rfpVqXPbdc(Vote111111111111111111111111111111111111111): ◎114498000.957127987 => ◎114498297.146080731 (+◎296.188952744)
+    81 7f9hY4y3HueRutNtt2VbSEuASqtDemuxY4rfpVqXPbdc(Vote111111111111111111111111111111111111111): ◎114498000.957127987 => ◎114498002.636606159 (+◎1.679478172)
-    82 7oCPJphtq27mYhGRuPvra1iAN2eVXoxzQbAw71HG1rEq(Vote111111111111111111111111111111111111111): ◎168657604.243119938 => ◎168659404.994814175 (+◎1800.751694237)
+    82 7oCPJphtq27mYhGRuPvra1iAN2eVXoxzQbAw71HG1rEq(Vote111111111111111111111111111111111111111): ◎168657604.243119938 => ◎168657614.453909831 (+◎10.210789893)
-    83 89NNxV6jTYeqZZdcVMWJf8yH7SrnEJMv44eT2zY8V8ev(Vote111111111111111111111111111111111111111): ◎55702050.078390090 => ◎58903061.190139523 (+◎3201011.111749433)
+    83 89NNxV6jTYeqZZdcVMWJf8yH7SrnEJMv44eT2zY8V8ev(Vote111111111111111111111111111111111111111): ◎55702050.078390090 => ◎55762576.205666815 (+◎60526.127276725)
-    84 8HVukKLonqDNqHZqj5NAfof4gqwTZm3jZZNwHFeuj4V3(Vote111111111111111111111111111111111111111): ◎170406155.386638238 => ◎171218046.683779275 (+◎811891.297141037)
+    84 8HVukKLonqDNqHZqj5NAfof4gqwTZm3jZZNwHFeuj4V3(Vote111111111111111111111111111111111111111): ◎170406155.386638238 => ◎170424884.200279139 (+◎18728.813640901)
-    85 8LT77GoTWRnQ2msePrUJhTsDRPetBMRBLvwwP2tSX8NG(Vote111111111111111111111111111111111111111): ◎84396.019428413 => ◎84778.731007582 (+◎382.711579169)
+    85 8LT77GoTWRnQ2msePrUJhTsDRPetBMRBLvwwP2tSX8NG(Vote111111111111111111111111111111111111111): ◎84396.019428413 => ◎84398.189515236 (+◎2.170086823)
-    86 8Txb3ZyBERw5LsbUZ6sDDHwnb34gaeentSDXhJ74W7Ch(Vote111111111111111111111111111111111111111): ◎116104730.737973728 => ◎116106706.858210298 (+◎1976.120236570)
+    86 8Txb3ZyBERw5LsbUZ6sDDHwnb34gaeentSDXhJ74W7Ch(Vote111111111111111111111111111111111111111): ◎116104730.737973728 => ◎116104741.943154655 (+◎11.205180927)
-    87 8VnzWXSkbx9SyvBwSf1FS8KJKJWbucafVUprxiZiE8hH(Vote111111111111111111111111111111111111111): ◎16257677.188772217 => ◎16307934.788799233 (+◎50257.600027016)
+    87 8VnzWXSkbx9SyvBwSf1FS8KJKJWbucafVUprxiZiE8hH(Vote111111111111111111111111111111111111111): ◎16257677.188772217 => ◎16257962.164094503 (+◎284.975322286)
-    88 8qtJdcKNrFifY1RNpk7pecQypC729CNvUVGMXwpZaAwU(Vote111111111111111111111111111111111111111): ◎85661.015022733 => ◎86044.027587144 (+◎383.012564411)
+    88 8qtJdcKNrFifY1RNpk7pecQypC729CNvUVGMXwpZaAwU(Vote111111111111111111111111111111111111111): ◎85661.015022733 => ◎85663.186816230 (+◎2.171793497)
-    89 8r1f8mwrUiYdg2Rx9sxTh4M3UAUcCBBrmRA3nxk3Z6Lm(Vote111111111111111111111111111111111111111): ◎202024689.774985371 => ◎202220250.798328462 (+◎195561.023343091)
+    89 8r1f8mwrUiYdg2Rx9sxTh4M3UAUcCBBrmRA3nxk3Z6Lm(Vote111111111111111111111111111111111111111): ◎202024689.774985371 => ◎202025798.663305237 (+◎1108.888319866)
-    90 8rwRyW183TUWxDni67EpcpJHj4xA5HPq9zSfyH5JXEeX(Vote111111111111111111111111111111111111111): ◎129150131.060132142 => ◎129151717.885907383 (+◎1586.825775241)
+    90 8rwRyW183TUWxDni67EpcpJHj4xA5HPq9zSfyH5JXEeX(Vote111111111111111111111111111111111111111): ◎129150131.060132142 => ◎129150140.057899374 (+◎8.997767232)
-    91 8xrr4rypTxst7gJbK9eEKF94PQ3z9KsJeaMKdQxB1otc(Vote111111111111111111111111111111111111111): ◎302855479.937330329 => ◎303141223.649560212 (+◎285743.712229883)
+    91 8xrr4rypTxst7gJbK9eEKF94PQ3z9KsJeaMKdQxB1otc(Vote111111111111111111111111111111111111111): ◎302855479.937330329 => ◎302871225.339954757 (+◎15745.402624428)
-    92 8zipsAVJU28GyirnyUNwt2yjTNuNusq3ZiJoVn41EgJE(Vote111111111111111111111111111111111111111): ◎182729983.018236140 => ◎182929956.386216407 (+◎199973.367980267)
+    92 8zipsAVJU28GyirnyUNwt2yjTNuNusq3ZiJoVn41EgJE(Vote111111111111111111111111111111111111111): ◎182729983.018236140 => ◎182731116.925843325 (+◎1133.907607185)
-    93 9C3trDP7hcirt4TX4hgjqF6qQvAAAPHE1BnFDVULKAJ8(Vote111111111111111111111111111111111111111): ◎209326538.771283113 => ◎209522492.730656885 (+◎195953.959373772)
+    93 9C3trDP7hcirt4TX4hgjqF6qQvAAAPHE1BnFDVULKAJ8(Vote111111111111111111111111111111111111111): ◎209326538.771283113 => ◎209327649.887665439 (+◎1111.116382326)
-    94 9DraAh9P3BGVG7ngDqz4LtEyAxyFzJe2nJy63wPcCcvX(Vote111111111111111111111111111111111111111): ◎290685920.487701359 => ◎290957314.848401325 (+◎271394.360699966)
+    94 9DraAh9P3BGVG7ngDqz4LtEyAxyFzJe2nJy63wPcCcvX(Vote111111111111111111111111111111111111111): ◎290685920.487701359 => ◎290701584.525296922 (+◎15664.037595563)
-    95 9Fq8ZrQ5NbFUsn3q2Fbw7b1odpSC7aNBbzaV2YtM9yVx(Vote111111111111111111111111111111111111111): ◎45838421.885518209 => ◎45840348.912409459 (+◎1927.026891250)
+    95 9Fq8ZrQ5NbFUsn3q2Fbw7b1odpSC7aNBbzaV2YtM9yVx(Vote111111111111111111111111111111111111111): ◎45838421.885518209 => ◎45838432.812325479 (+◎10.926807270)
-    96 9LiHLA8jmFjvzfCuMabNVVtbXysB7m5vhXpxv8e6Cxsk(Vote111111111111111111111111111111111111111): ◎85477.727275035 => ◎85859.417885730 (+◎381.690610695)
+    96 9LiHLA8jmFjvzfCuMabNVVtbXysB7m5vhXpxv8e6Cxsk(Vote111111111111111111111111111111111111111): ◎85477.727275035 => ◎85479.891572668 (+◎2.164297633)
-    97 9ZdmWMR1Uz5C8AFCB3EoePNMCEsGCjJeegudLZ4uPsFm(Vote111111111111111111111111111111111111111): ◎80430155.759709578 => ◎80430480.376914347 (+◎324.617204769)
+    97 9ZdmWMR1Uz5C8AFCB3EoePNMCEsGCjJeegudLZ4uPsFm(Vote111111111111111111111111111111111111111): ◎80430155.759709578 => ◎80430157.600384271 (+◎1.840674693)
-    98 9h522ig8b5qXY9JfBMXpU1gEyioeKqQqJC8JoqpACRAs(Vote111111111111111111111111111111111111111): ◎84442.278779797 => ◎84823.561028031 (+◎381.282248234)
+    98 9h522ig8b5qXY9JfBMXpU1gEyioeKqQqJC8JoqpACRAs(Vote111111111111111111111111111111111111111): ◎84442.278779797 => ◎84444.440761895 (+◎2.161982098)
-    99 9ji8KWibtqhgGLazwSMXFoWxfQzFEaR4jhcUvMMrbhGU(Vote111111111111111111111111111111111111111): ◎80907914.375532138 => ◎80908268.118047824 (+◎353.742515686)
+    99 9ji8KWibtqhgGLazwSMXFoWxfQzFEaR4jhcUvMMrbhGU(Vote111111111111111111111111111111111111111): ◎80907914.375532138 => ◎80907916.381355881 (+◎2.005823743)
-   100 A3AqHSCCkyPRPZnZCfigfECJDYiqzYSR9G2eP35K1cBq(Vote111111111111111111111111111111111111111): ◎69330.305187851 => ◎69685.131979153 (+◎354.826791302)
+   100 A3AqHSCCkyPRPZnZCfigfECJDYiqzYSR9G2eP35K1cBq(Vote111111111111111111111111111111111111111): ◎69330.305187851 => ◎69332.317159754 (+◎2.011971903)
-   101 A8bzDfpyEYpxk5jcug9p5x48P6UMSPN2NMznTKHEC5Dp(Vote111111111111111111111111111111111111111): ◎83832.504957994 => ◎84214.238199087 (+◎381.733241093)
+   101 A8bzDfpyEYpxk5jcug9p5x48P6UMSPN2NMznTKHEC5Dp(Vote111111111111111111111111111111111111111): ◎83832.504957994 => ◎83834.669497354 (+◎2.164539360)
-   102 ASDjo1U2bJfThuZ1ftJ7Ku9XEz7Gn8gjEMiCoY7pRRvQ(Vote111111111111111111111111111111111111111): ◎100.475224107 => ◎10019.516185694 (+◎9919.040961587)
+   102 ASDjo1U2bJfThuZ1ftJ7Ku9XEz7Gn8gjEMiCoY7pRRvQ(Vote111111111111111111111111111111111111111): ◎100.475224107 => ◎156.719093551 (+◎56.243869444)
-   103 AUCzCaGAGjL3uyjFBtJs7KuJcgQWvNZu1Z2S9G3pw77G(Vote111111111111111111111111111111111111111): ◎147681626.252969805 => ◎148470582.791584656 (+◎788956.538614851)
+   103 AUCzCaGAGjL3uyjFBtJs7KuJcgQWvNZu1Z2S9G3pw77G(Vote111111111111111111111111111111111111111): ◎147681626.252969805 => ◎147686099.867781168 (+◎4473.614811363)
-   104 AaZjhAi2XMwJf8tJjU3TQA3fCnZN2hfzckFm2jmjLsMs(Vote111111111111111111111111111111111111111): ◎115650368.501610591 => ◎115650372.438540278 (+◎3.936929687)
+   104 AaZjhAi2XMwJf8tJjU3TQA3fCnZN2hfzckFm2jmjLsMs(Vote111111111111111111111111111111111111111): ◎115650368.501610591 => ◎115650368.523934136 (+◎0.022323545)
-   105 AbUN3Jq8U9GMmLt6kh7nDaAUcgSenSg3zYH3bKcDCmhr(Vote111111111111111111111111111111111111111): ◎85505.453194127 => ◎85887.463561396 (+◎382.010367269)
+   105 AbUN3Jq8U9GMmLt6kh7nDaAUcgSenSg3zYH3bKcDCmhr(Vote111111111111111111111111111111111111111): ◎85505.453194127 => ◎85507.619304872 (+◎2.166110745)
-   106 AcuRbRUstXN6VcxgDTLoBhUMxE4NDCCc7VQ9KdWZWDMQ(Vote111111111111111111111111111111111111111): ◎204721421.384858455 => ◎204916369.111858141 (+◎194947.726999686)
+   106 AcuRbRUstXN6VcxgDTLoBhUMxE4NDCCc7VQ9KdWZWDMQ(Vote111111111111111111111111111111111111111): ◎204721421.384858455 => ◎204722526.795608301 (+◎1105.410749846)
-   107 Ak7qkCrS6Xr2dNm2tHDCrX3gHwN4qXS1QVuFFTveVQ3G(Vote111111111111111111111111111111111111111): ◎25383612.741812810 => ◎25405614.763235099 (+◎22002.021422289)
+   107 Ak7qkCrS6Xr2dNm2tHDCrX3gHwN4qXS1QVuFFTveVQ3G(Vote111111111111111111111111111111111111111): ◎25383612.741812810 => ◎25383737.499722906 (+◎124.757910096)
-   108 AkRhkn2ZnjnEuVWYipaMxRJsKxgAyKxuWBTNKcmtDgSv(Vote111111111111111111111111111111111111111): ◎84231.690270319 => ◎84612.908091002 (+◎381.217820683)
+   108 AkRhkn2ZnjnEuVWYipaMxRJsKxgAyKxuWBTNKcmtDgSv(Vote111111111111111111111111111111111111111): ◎84231.690270319 => ◎84233.851887094 (+◎2.161616775)
-   109 AtyoQ87v5JD6NGsy8UFrXAhXFKwLCGwbx7pvUTJoCjWw(Vote111111111111111111111111111111111111111): ◎211125847.447618912 => ◎211321499.660914939 (+◎195652.213296027)
+   109 AtyoQ87v5JD6NGsy8UFrXAhXFKwLCGwbx7pvUTJoCjWw(Vote111111111111111111111111111111111111111): ◎211125847.447618912 => ◎211126956.853012539 (+◎1109.405393627)
-   110 AuSPxjDyGmzBkLuVL4yU5LYTo45koqQYr87X68xBpS2x(Vote111111111111111111111111111111111111111): ◎7293.505339566 => ◎7293.620467365 (+◎0.115127799)
+   110 AuSPxjDyGmzBkLuVL4yU5LYTo45koqQYr87X68xBpS2x(Vote111111111111111111111111111111111111111): ◎7293.505339566 => ◎7293.505992374 (+◎0.000652808)
-   111 B5vyvnuP1j78vu1J18yWpo3wmfFxvMXQfmhbAyoC3M5K(Vote111111111111111111111111111111111111111): ◎29990007.596010884 => ◎29991927.944689137 (+◎1920.348678253)
+   111 B5vyvnuP1j78vu1J18yWpo3wmfFxvMXQfmhbAyoC3M5K(Vote111111111111111111111111111111111111111): ◎29990007.596010884 => ◎29990018.484950729 (+◎10.888939845)
-   112 BSxPcwvsMszsPr7h9kufpSqnhiyFyzCVAgSDC8r2A7P8(Vote111111111111111111111111111111111111111): ◎82241.589228631 => ◎82624.313695881 (+◎382.724467250)
+   112 BSxPcwvsMszsPr7h9kufpSqnhiyFyzCVAgSDC8r2A7P8(Vote111111111111111111111111111111111111111): ◎82241.589228631 => ◎82243.759388533 (+◎2.170159902)
-   113 BZyNNfHMxS34P7NE5r8DyoXrsYzwddcGMX8ncnmhzWQj(Vote111111111111111111111111111111111111111): ◎638.400418746 => ◎638.515258852 (+◎0.114840106)
+   113 BZyNNfHMxS34P7NE5r8DyoXrsYzwddcGMX8ncnmhzWQj(Vote111111111111111111111111111111111111111): ◎638.400418746 => ◎638.401069923 (+◎0.000651177)
-   114 Bd6Edv5AkXGKtJj219GQEdqZcWUCwXYjHnrkXT3XwH8R(Vote111111111111111111111111111111111111111): ◎5.511328947 => ◎5.562341062 (+◎0.051012115)
+   114 Bd6Edv5AkXGKtJj219GQEdqZcWUCwXYjHnrkXT3XwH8R(Vote111111111111111111111111111111111111111): ◎5.511328947 => ◎5.511618200 (+◎0.000289253)
-   115 Bq54jkDFb5bfjSSzMZVT5tG6BUF6Qo1PEsSxK6Sf8FEv(Vote111111111111111111111111111111111111111): ◎8.238450900 => ◎8.296420681 (+◎0.057969781)
+   115 Bq54jkDFb5bfjSSzMZVT5tG6BUF6Qo1PEsSxK6Sf8FEv(Vote111111111111111111111111111111111111111): ◎8.238450900 => ◎8.238779605 (+◎0.000328705)
-   116 Bqfcic8HXFYVNWeUUmpizRXLajfjwTpPfvKEfwU8eioC(Vote111111111111111111111111111111111111111): ◎85575.928166192 => ◎85966.452504172 (+◎390.524337980)
+   116 Bqfcic8HXFYVNWeUUmpizRXLajfjwTpPfvKEfwU8eioC(Vote111111111111111111111111111111111111111): ◎85575.928166192 => ◎85578.142553647 (+◎2.214387455)
-   117 BrnegSsEA4zdMFPEoznzrwz5ka98PU9SjcF71YGkbM1q(Vote111111111111111111111111111111111111111): ◎20859669.014692187 => ◎20881674.004361898 (+◎22004.989669711)
+   117 BrnegSsEA4zdMFPEoznzrwz5ka98PU9SjcF71YGkbM1q(Vote111111111111111111111111111111111111111): ◎20859669.014692187 => ◎20859793.789433115 (+◎124.774740928)
-   118 BuYejA9pMhYxiPVmAfUyagLS5ZEqYb7P9Cz49Ksc88CT(Vote111111111111111111111111111111111111111): ◎84375.407737105 => ◎84756.999237585 (+◎381.591500480)
+   118 BuYejA9pMhYxiPVmAfUyagLS5ZEqYb7P9Cz49Ksc88CT(Vote111111111111111111111111111111111111111): ◎84375.407737105 => ◎84377.571472754 (+◎2.163735649)
-   119 CAACr5HuSiftfVxCEXfUMCGZRbehUVj72wy2JnaonTky(Vote111111111111111111111111111111111111111): ◎18920.637378200 => ◎20161.985832030 (+◎1241.348453830)
+   119 CAACr5HuSiftfVxCEXfUMCGZRbehUVj72wy2JnaonTky(Vote111111111111111111111111111111111111111): ◎18920.637378200 => ◎18927.676187761 (+◎7.038809561)
-   120 CAM8xcj2cT4aWbjzRXydU2cunBH15j2Tc1Xy9TSU8pJ2(Vote111111111111111111111111111111111111111): ◎11830656.790596548 => ◎12787445.499553577 (+◎956788.708957029)
+   120 CAM8xcj2cT4aWbjzRXydU2cunBH15j2Tc1Xy9TSU8pJ2(Vote111111111111111111111111111111111111111): ◎11830656.790596548 => ◎11836082.063004138 (+◎5425.272407590)
-   121 CCifzPyu7jrEDP2iRugvhcnrfR4JZ2P5XXH6QMqPf3qA(Vote111111111111111111111111111111111111111): ◎84509.708016993 => ◎84891.711853801 (+◎382.003836808)
+   121 CCifzPyu7jrEDP2iRugvhcnrfR4JZ2P5XXH6QMqPf3qA(Vote111111111111111111111111111111111111111): ◎84509.708016993 => ◎84511.874090710 (+◎2.166073717)
-   122 Cb9ZCgkCyq73u3RBSU5nr4NWyRzMbRTo8tXfvZdjA7qs(Vote111111111111111111111111111111111111111): ◎17398046.210821156 => ◎17400009.941630206 (+◎1963.730809050)
+   122 Cb9ZCgkCyq73u3RBSU5nr4NWyRzMbRTo8tXfvZdjA7qs(Vote111111111111111111111111111111111111111): ◎17398046.210821156 => ◎17398057.345750398 (+◎11.134929242)
-   123 Cgs5uBf9zBbk2GHe1Rn82QXpz3azysUYHsiVkFc49AK3(Vote111111111111111111111111111111111111111): ◎84587.492837647 => ◎84970.075536001 (+◎382.582698354)
+   123 Cgs5uBf9zBbk2GHe1Rn82QXpz3azysUYHsiVkFc49AK3(Vote111111111111111111111111111111111111111): ◎84587.492837647 => ◎84589.662193678 (+◎2.169356031)
-   124 CnrpyVoSVbQ59AEmKF9fXBVPb3MR45nE3gLresF4sKVZ(Vote111111111111111111111111111111111111111): ◎85424.756914482 => ◎85806.309758431 (+◎381.552843949)
+   124 CnrpyVoSVbQ59AEmKF9fXBVPb3MR45nE3gLresF4sKVZ(Vote111111111111111111111111111111111111111): ◎85424.756914482 => ◎85426.920430937 (+◎2.163516455)
-   125 CxzwTvRCvSNCAYhciargRq1wSSUHWt64cPU7feSSWZLz(Vote111111111111111111111111111111111111111): ◎25156252.783089144 => ◎25178228.816871240 (+◎21976.033782096)
+   125 CxzwTvRCvSNCAYhciargRq1wSSUHWt64cPU7feSSWZLz(Vote111111111111111111111111111111111111111): ◎25156252.783089144 => ◎25156377.393641703 (+◎124.610552559)
-   126 DKjuhH8YAgm7tpuQAcE2Ehh42uG3LNLda2SL7iiwqUBv(Vote111111111111111111111111111111111111111): ◎24759673.712827161 => ◎24781546.203040770 (+◎21872.490213609)
+   126 DKjuhH8YAgm7tpuQAcE2Ehh42uG3LNLda2SL7iiwqUBv(Vote111111111111111111111111111111111111111): ◎24759673.712827161 => ◎24759797.736257339 (+◎124.023430178)
-   127 Db98KcjFeHvv9zGQX13jgUGNb6HPK1xqH7T4MzusvLL3(Vote111111111111111111111111111111111111111): ◎84331.553840171 => ◎84713.415936366 (+◎381.862096195)
+   127 Db98KcjFeHvv9zGQX13jgUGNb6HPK1xqH7T4MzusvLL3(Vote111111111111111111111111111111111111111): ◎84331.553840171 => ◎84333.719110177 (+◎2.165270006)
-   128 Deb9asvcCau6T2oxU7U3asEcYXMbGgUHYSnNx2XKSoEY(Vote111111111111111111111111111111111111111): ◎83788.960571075 => ◎84171.952912368 (+◎382.992341293)
+   128 Deb9asvcCau6T2oxU7U3asEcYXMbGgUHYSnNx2XKSoEY(Vote111111111111111111111111111111111111111): ◎83788.960571075 => ◎83791.132249901 (+◎2.171678826)
-   129 Dht9r8gKos3p7wAQP4tFPb7VxsQT48y8ZfvxxeRa8eTT(Vote111111111111111111111111111111111111111): ◎184665485.157829392 => ◎190469332.085882223 (+◎5803846.928052831)
+   129 Dht9r8gKos3p7wAQP4tFPb7VxsQT48y8ZfvxxeRa8eTT(Vote111111111111111111111111111111111111111): ◎184665485.157829392 => ◎184966772.559483736 (+◎301287.401654344)
-   130 DqPr7pe2MpQnCxervJHKfRstMbcEBhkTmZag52Ki9rq4(Vote111111111111111111111111111111111111111): ◎359533921.565116064 => ◎360650808.356975593 (+◎1116886.791859529)
+   130 DqPr7pe2MpQnCxervJHKfRstMbcEBhkTmZag52Ki9rq4(Vote111111111111111111111111111111111111111): ◎359533921.565116064 => ◎359554379.792603977 (+◎20458.227487913)
-   131 EAxZxmdKuBJkodJ69hnouha1MdyzuVi7yRCrh9JC97B3(Vote111111111111111111111111111111111111111): ◎72125006.463497210 => ◎72327445.515787102 (+◎202439.052289892)
+   131 EAxZxmdKuBJkodJ69hnouha1MdyzuVi7yRCrh9JC97B3(Vote111111111111111111111111111111111111111): ◎72125006.463497210 => ◎72126154.352257105 (+◎1147.888759895)
-   132 EEf82BBMpKMvh6urJtNiAWmwEHXM58oNknCdLFvzWecz(Vote111111111111111111111111111111111111111): ◎1573854.610569317 => ◎1573858.598139533 (+◎3.987570216)
+   132 EEf82BBMpKMvh6urJtNiAWmwEHXM58oNknCdLFvzWecz(Vote111111111111111111111111111111111111111): ◎1573854.610569317 => ◎1573854.633180008 (+◎0.022610691)
-   133 EGB9YhPSbXhfoetBCofFEyn3DxGdt4LbbxDyGNMd9j3K(Vote111111111111111111111111111111111111111): ◎221296343.228908767 => ◎221498559.631152250 (+◎202216.402243483)
+   133 EGB9YhPSbXhfoetBCofFEyn3DxGdt4LbbxDyGNMd9j3K(Vote111111111111111111111111111111111111111): ◎221296343.228908767 => ◎221297489.855177642 (+◎1146.626268875)
-   134 ENSw7YavYqTS9uwUyYM8nWRnnapfb6y73Rx4zyT83VC4(Vote111111111111111111111111111111111111111): ◎69457453.855902667 => ◎69457750.044855411 (+◎296.188952744)
+   134 ENSw7YavYqTS9uwUyYM8nWRnnapfb6y73Rx4zyT83VC4(Vote111111111111111111111111111111111111111): ◎69457453.855902667 => ◎69457455.535380839 (+◎1.679478172)
-   135 ESujdS7pYiWEfvzfAfjNptnYEiW8i3sSJ3AB77tHheid(Vote111111111111111111111111111111111111111): ◎84361.085179687 => ◎84742.599367105 (+◎381.514187418)
+   135 ESujdS7pYiWEfvzfAfjNptnYEiW8i3sSJ3AB77tHheid(Vote111111111111111111111111111111111111111): ◎84361.085179687 => ◎84363.248476948 (+◎2.163297261)
-   136 ETufZPcJGoWX8MUNqgZvnpqmJetvVZ2TqEf8d1STcyGp(Vote111111111111111111111111111111111111111): ◎79404100.047842672 => ◎79404501.234074040 (+◎401.186231368)
+   136 ETufZPcJGoWX8MUNqgZvnpqmJetvVZ2TqEf8d1STcyGp(Vote111111111111111111111111111111111111111): ◎79404100.047842672 => ◎79404102.322686188 (+◎2.274843516)
-   137 EU4c88C1chxcE6vHbr9QGxGwNoABMU6tnoipebSTHsjL(Vote111111111111111111111111111111111111111): ◎29830075.724706821 => ◎29852062.438931519 (+◎21986.714224698)
+   137 EU4c88C1chxcE6vHbr9QGxGwNoABMU6tnoipebSTHsjL(Vote111111111111111111111111111111111111111): ◎29830075.724706821 => ◎29830200.395820620 (+◎124.671113799)
-   138 EdGRtUNRKPE9zvP12bd2okjn9cSoHS8gaon113AsKfLt(Vote111111111111111111111111111111111111111): ◎85279.208705538 => ◎85660.937981498 (+◎381.729275960)
+   138 EdGRtUNRKPE9zvP12bd2okjn9cSoHS8gaon113AsKfLt(Vote111111111111111111111111111111111111111): ◎85279.208705538 => ◎85281.373222413 (+◎2.164516875)
-   139 EiA4Y3FT2XcXCXDyZ3rsFvSENjnPy9ugBQG5N64rXVkv(Vote111111111111111111111111111111111111111): ◎93202605.301117814 => ◎94352735.609650823 (+◎1150130.308533009)
+   139 EiA4Y3FT2XcXCXDyZ3rsFvSENjnPy9ugBQG5N64rXVkv(Vote111111111111111111111111111111111111111): ◎93202605.301117814 => ◎93209126.877062015 (+◎6521.575944201)
-   140 EpYFiR1szbHQW1cLSJr1UMBeqJf48mgkNHREJhXBPbRa(Vote111111111111111111111111111111111111111): ◎47489.342754834 => ◎47813.569163887 (+◎324.226409053)
+   140 EpYFiR1szbHQW1cLSJr1UMBeqJf48mgkNHREJhXBPbRa(Vote111111111111111111111111111111111111111): ◎47489.342754834 => ◎47491.181213601 (+◎1.838458767)
-   141 F3WySbb7Cdbj4XvZumUvH76TcyUFfTwQbbAqbBq6An3z(Vote111111111111111111111111111111111111111): ◎85461.888515294 => ◎85843.711954958 (+◎381.823439664)
+   141 F3WySbb7Cdbj4XvZumUvH76TcyUFfTwQbbAqbBq6An3z(Vote111111111111111111111111111111111111111): ◎85461.888515294 => ◎85464.053566106 (+◎2.165050812)
-   142 FQD95FH6HdNUC51pdVqBhhvhqQVPqXMn1E2aeqXbUbFn(Vote111111111111111111111111111111111111111): ◎161432200.232938740 => ◎164543622.505147043 (+◎3111422.272208303)
+   142 FQD95FH6HdNUC51pdVqBhhvhqQVPqXMn1E2aeqXbUbFn(Vote111111111111111111111111111111111111111): ◎161432200.232938740 => ◎161548718.973344166 (+◎116518.740405426)
-   143 FUdmzVtQ4UEq1TcGRQDy81KM4nfaNNCKaKhCZNeWPveE(Vote111111111111111111111111111111111111111): ◎1000.436724312 => ◎7033911.036859362 (+◎7032910.600135050)
+   143 FUdmzVtQ4UEq1TcGRQDy81KM4nfaNNCKaKhCZNeWPveE(Vote111111111111111111111111111111111111111): ◎1000.436724312 => ◎182130.621388816 (+◎181130.184664504)
-   144 FqpvstKqfYi9wcm68Cctwnb5bu9C1agPoRAJwUQAUs83(Vote111111111111111111111111111111111111111): ◎7.152162430 => ◎7.210583155 (+◎0.058420725)
+   144 FqpvstKqfYi9wcm68Cctwnb5bu9C1agPoRAJwUQAUs83(Vote111111111111111111111111111111111111111): ◎7.152162430 => ◎7.152493692 (+◎0.000331262)
-   145 FrCLHvrzN9f6npbfEni71mtVqbPB8xxBF4CukdTEehme(Vote111111111111111111111111111111111111111): ◎203721603.711588551 => ◎203916763.007714739 (+◎195159.296126188)
+   145 FrCLHvrzN9f6npbfEni71mtVqbPB8xxBF4CukdTEehme(Vote111111111111111111111111111111111111111): ◎203721603.711588551 => ◎203722710.321997353 (+◎1106.610408802)
-   146 Ft7UA1oJ9sDvJuyUWDRHtJgrgdgXZwdpBmQXjKDccZxb(Vote111111111111111111111111111111111111111): ◎70396295.156689159 => ◎71381758.111938076 (+◎985462.955248917)
+   146 Ft7UA1oJ9sDvJuyUWDRHtJgrgdgXZwdpBmQXjKDccZxb(Vote111111111111111111111111111111111111111): ◎70396295.156689159 => ◎70401883.020477434 (+◎5587.863788275)
-   147 Fv4Xrng7DtscPLDNSLn2x6gtgXk3ZYAsGqkb4H8Gjzoc(Vote111111111111111111111111111111111111111): ◎83878.926530152 => ◎84259.500075322 (+◎380.573545170)
+   147 Fv4Xrng7DtscPLDNSLn2x6gtgXk3ZYAsGqkb4H8Gjzoc(Vote111111111111111111111111111111111111111): ◎83878.926530152 => ◎83881.084493696 (+◎2.157963544)
-   148 Fy4bjUvtDVtuy7HhmEYX2Sy7BeeQVhriKMbSkevt2KQd(Vote111111111111111111111111111111111111111): ◎35390077.332976450 => ◎36574963.215128989 (+◎1184885.882152539)
+   148 Fy4bjUvtDVtuy7HhmEYX2Sy7BeeQVhriKMbSkevt2KQd(Vote111111111111111111111111111111111111111): ◎35390077.332976450 => ◎35396795.983209680 (+◎6718.650233230)
-   149 G4SmJFr9ks9rCkYNY7GGAWbGBrCgZ8YSLa2LCUDAgVRr(Vote111111111111111111111111111111111111111): ◎6212684.907612975 => ◎6345665.232403946 (+◎132980.324790971)
+   149 G4SmJFr9ks9rCkYNY7GGAWbGBrCgZ8YSLa2LCUDAgVRr(Vote111111111111111111111111111111111111111): ◎6212684.907612975 => ◎6213438.945030104 (+◎754.037417129)
-   150 G9ZfVCWk1XFEaju4LwpQNcUHGBNCFZ9JU6L1q6qyY7W2(Vote111111111111111111111111111111111111111): ◎56836.182672047 => ◎57163.690266202 (+◎327.507594155)
+   150 G9ZfVCWk1XFEaju4LwpQNcUHGBNCFZ9JU6L1q6qyY7W2(Vote111111111111111111111111111111111111111): ◎56836.182672047 => ◎56838.039736095 (+◎1.857064048)
-   151 GHhFCxzZ8ZW7a9kRWPjEPj4Hzr4R3K5ZsLpF7ST2ra3Q(Vote111111111111111111111111111111111111111): ◎84178.357075756 => ◎84560.760363381 (+◎382.403287625)
+   151 GHhFCxzZ8ZW7a9kRWPjEPj4Hzr4R3K5ZsLpF7ST2ra3Q(Vote111111111111111111111111111111111111111): ◎84178.357075756 => ◎84180.525414476 (+◎2.168338720)
-   152 GWko9kakgkJdBzi9ukqx1NRRkLEVGZZisr7KJafjos4K(Vote111111111111111111111111111111111111111): ◎207655046.150472074 => ◎207849149.361303300 (+◎194103.210831226)
+   152 GWko9kakgkJdBzi9ukqx1NRRkLEVGZZisr7KJafjos4K(Vote111111111111111111111111111111111111111): ◎207655046.150472074 => ◎207656146.772567724 (+◎1100.622095650)
-   153 GkyJUaYmhtTGCNHFMsYdAsrth2JrC3ARfCX5hhm3aCRq(Vote111111111111111111111111111111111111111): ◎182476832.216161325 => ◎190655108.060452618 (+◎8178275.844291293)
+   153 GkyJUaYmhtTGCNHFMsYdAsrth2JrC3ARfCX5hhm3aCRq(Vote111111111111111111111111111111111111111): ◎182476832.216161325 => ◎182622081.501378357 (+◎145249.285217032)
-   154 GtqVRS2vVdmzP1ki1rTxwtvprtET5LfE14MsV4SrXbFn(Vote111111111111111111111111111111111111111): ◎19479749.418698762 => ◎19481389.373864067 (+◎1639.955165305)
+   154 GtqVRS2vVdmzP1ki1rTxwtvprtET5LfE14MsV4SrXbFn(Vote111111111111111111111111111111111111111): ◎19479749.418698762 => ◎19479758.717725207 (+◎9.299026445)
-   155 GzfYcjZWHsFf183nvJYwgUS8CqkHhzJTDKfNFS9D3X4K(Vote111111111111111111111111111111111111111): ◎44102.308429503 => ◎45596.622740069 (+◎1494.314310566)
+   155 GzfYcjZWHsFf183nvJYwgUS8CqkHhzJTDKfNFS9D3X4K(Vote111111111111111111111111111111111111111): ◎44102.308429503 => ◎44110.781629615 (+◎8.473200112)
-   156 H92cja4La9EvUsumPSpsBD3fSY3kfRoMQiFf3pHC2e5T(Vote111111111111111111111111111111111111111): ◎1.910464938 => ◎1.944383135 (+◎0.033918197)
+   156 H92cja4La9EvUsumPSpsBD3fSY3kfRoMQiFf3pHC2e5T(Vote111111111111111111111111111111111111111): ◎1.910464938 => ◎1.910657264 (+◎0.000192326)
-   157 HDGCHD1Y4gGmexeSN1uuerGSAJDwfgYuLsJg5kSGByKP(Vote111111111111111111111111111111111111111): ◎41693190.243232007 => ◎43354096.062808963 (+◎1660905.819576956)
+   157 HDGCHD1Y4gGmexeSN1uuerGSAJDwfgYuLsJg5kSGByKP(Vote111111111111111111111111111111111111111): ◎41693190.243232007 => ◎41730858.370081781 (+◎37668.126849774)
-   158 HFgV7J7FKY6QzSv1jsMaPx79c3EsQAA7GT8sFsCqk6gf(Vote111111111111111111111111111111111111111): ◎148037629.249305765 => ◎148547347.944316024 (+◎509718.695010259)
+   158 HFgV7J7FKY6QzSv1jsMaPx79c3EsQAA7GT8sFsCqk6gf(Vote111111111111111111111111111111111111111): ◎148037629.249305765 => ◎148054644.655727995 (+◎17015.406422230)
-   159 HMiJRKNrdSjUi3hMb2cvP3rhcGLxS6R5rei8AfGKRAGe(Vote111111111111111111111111111111111111111): ◎5.517551506 => ◎5.568553297 (+◎0.051001791)
+   159 HMiJRKNrdSjUi3hMb2cvP3rhcGLxS6R5rei8AfGKRAGe(Vote111111111111111111111111111111111111111): ◎5.517551506 => ◎5.517840701 (+◎0.000289195)
-   160 HNKxYYGBuxWnAU6puKh71Cto8fxSnZj7nNtY7F9Hscnc(Vote111111111111111111111111111111111111111): ◎63746989.848055721 => ◎63749308.747126000 (+◎2318.899070279)
+   160 HNKxYYGBuxWnAU6puKh71Cto8fxSnZj7nNtY7F9Hscnc(Vote111111111111111111111111111111111111111): ◎63746989.848055721 => ◎63747002.996893100 (+◎13.148837379)
-   161 HS1Apbh1616zumYBtGZA9jn9Fzcc1sL5Xz5uW5Mv4qMj(Vote111111111111111111111111111111111111111): ◎18881.176640054 => ◎19221.116909397 (+◎339.940269343)
+   161 HS1Apbh1616zumYBtGZA9jn9Fzcc1sL5Xz5uW5Mv4qMj(Vote111111111111111111111111111111111111111): ◎18881.176640054 => ◎18883.104201014 (+◎1.927560960)
-   162 HWGCWCHb9u2XJbV7J8nfpWbdmWYvEEpsaoZaozuPmDm7(Vote111111111111111111111111111111111111111): ◎3.481037253 => ◎3.523455261 (+◎0.042418008)
+   162 HWGCWCHb9u2XJbV7J8nfpWbdmWYvEEpsaoZaozuPmDm7(Vote111111111111111111111111111111111111111): ◎3.481037253 => ◎3.481277775 (+◎0.000240522)
-   163 HdzdTTjrmRLYVRy3umzZX4NcUmGTHu6hvYLQN2jGJo53(Vote111111111111111111111111111111111111111): ◎155513776.450674877 => ◎157898732.134720867 (+◎2384955.684045990)
+   163 HdzdTTjrmRLYVRy3umzZX4NcUmGTHu6hvYLQN2jGJo53(Vote111111111111111111111111111111111111111): ◎155513776.450674877 => ◎155555550.152469934 (+◎41773.701795057)
-   164 HnsHUwb8iXWJETj6bMMJ8NmDdzQfTfBQkTM6ZPVLyh6U(Vote111111111111111111111111111111111111111): ◎84278725.412763759 => ◎84282730.276998088 (+◎4004.864234329)
+   164 HnsHUwb8iXWJETj6bMMJ8NmDdzQfTfBQkTM6ZPVLyh6U(Vote111111111111111111111111111111111111111): ◎84278725.412763759 => ◎84278748.121517764 (+◎22.708754005)
-   165 J8raggzYStisYLjFrcHw2FKPrQLYuwgQVKcRVhKv6Pa7(Vote111111111111111111111111111111111111111): ◎48039845.903761035 => ◎49948035.958696639 (+◎1908190.054935604)
+   165 J8raggzYStisYLjFrcHw2FKPrQLYuwgQVKcRVhKv6Pa7(Vote111111111111111111111111111111111111111): ◎48039845.903761035 => ◎48093041.356729185 (+◎53195.452968150)
-   166 Sum of lamports changes: ◎106470593.490526072
+   166 Sum of lamports changes: ◎1846732.849148403
```

File: programs/stake/src/stake_state.rs [hunk 20]
```diff
@@ -362,43 +362,57 @@ impl Authorized {
...
+    ///   points were earned (credits * stake) and new value
+    ///   for credits_observed were the points paid
+    pub fn calculate_points_and_credits(
+        &self,
+        vote_state: &VoteState,
+        stake_history: Option<&StakeHistory>,
+    ) -> (u128, u64) {
         if self.credits_observed >= vote_state.credits() {
-            return None;
+            return (0, 0);
```
Comment (ryoqun) [inline programs/stake/src/stake_state.rs:411]: seems like I should have noticed `(..., 0)` can't be like this when reviewing and working on this.... ref: #13836

Comment (ryoqun) [reply programs/stake/src/stake_state.rs:411]: as an execute, I remember I thought it's logically straight forward to translate `None` to `(0, 0)` on its own at the time. I should pay more attention for more surrounding context.
