### PR TITLE
Fix accounts_db store counts in purging accounts logic

### LINKED ISSUE #8130: 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:462:9
It looks like the bootstrap leader on TdS is serving up a bad snapshot:
```
$ solana-validator -l ledger -n 35.230.25.59:8001 -o - --expected-shred-version 16135
.
.
.
[2020-02-05T16:29:45.572013797Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=615i
thread 'main' panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:462:9
```

Steps to reproduce on the 0.23.2 release:
1. Fetch and extract bad-snapshot.tgz from https://drive.google.com/drive/folders/1bBteuyTDRWDbCXhf-IgaTVog28teAjYn?usp=sharing
2. Run `solana-validator --ledger bad-snapshot/ -o -`

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

When deleting, purge_zero_lamport accounts doesn't re-adjust the store counts once an account is determined not to be purged.

#### Summary of Changes

Take a pass to readjust the store counts before determining which stores can be purged.

Fixes #8130

### CODE REVIEW

File: runtime/src/accounts_db.rs [hunk 1]
```diff
@@ -649,6 +649,21 @@ impl AccountsDB {
...
+        for account_infos in purges.values() {
+            let mut no_delete = false;
+            for (_slot_id, account_info) in account_infos {
+                if *store_counts.get(&account_info.store_id).unwrap() != 0 {
+                    no_delete = true;
+                    break;
+                }
+            }
+            if no_delete {
+                for (_slot_id, account_info) in account_infos {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: I carefully re-read the `purge_zero_lamport_accounts`. And I think this new logic works as intended. Very nice and thank you so much! It's sad for me not to notice nor write this... ;)

[My previous perception](https://github.com/solana-labs/solana/pull/8176#discussion_r376724915) was wrong... Especially the DAG thing. I wonder why I was urged to think so. Maybe, too tired...

And this makes `purge_zero_lamport_accounts` yet more conservative. So, regardless a hostile or normal situation, I think accumulated zero lamport accounts impose us no-op wasted CPU time by bunch of loops for each `snapshot_slot_interval` to some extent.

Especially, this loop exhibits some contaminating/cascading behavior, easily approaching to the worst cost of `O(N)` where N is the total number of all updates to every accounts which became 0 lamport in the past at least once. That's because making `no_delete` be `true` for vast of unrelated `pubkey`s can easily be done by triggering the avalanche counting just with a single zero account with many updates.

In near future, I think we'd need some compaction mechanism as implied by #8168...

**Comment by mvines** [comment]
Is this a possible fix for #8168?

**Comment by sakridge** [comment]
> Is this a possible fix for #8168?

No, it's for #8130

**Comment by mvines** [comment]
Sweet!  Read to land? :shipit:?

**Comment by sakridge** [comment]
> Sweet! Read to land? :shipit:?

yea
