### PR TITLE
Track a Bank's parent slot independently from parent bank

### LINKED ISSUE #7119: CPU-only nightlies are failing to maintain consensus
#### Problem
For the last several days, GCE & Colo CPU 5-node test has been failing consensus after a minute or two of the bench TPS client kicking off.  GPU-enabled testnets are not seeing this failure.

Latest result: https://metrics.solana.com:3000/d/testnet-edge/testnet-monitor-edge?var-testnet=gce-perf-cpu-only&from=1574661679616&to=1574662719109&refresh=60s&orgId=2
https://buildkite.com/solana-labs/system-performance-tests/builds/573

The last good nightly run without this issue was on Nov 21 against: 
https://github.com/solana-labs/solana/commit/d9024db68d6e5b35ebb791e2d82d448677fbe32b
The first time this issue came up was on the nightly on Nov 23 against: 
https://github.com/solana-labs/solana/commit/7f87ac4b650cbb525e982eb25c118f8c8967d429

History:
```
7f87ac4b6 Improve coverage.sh's environment awareness (#7101)
306fbd8bd install: Drop unneeded sha2 dependency (#7108)
3e0b272a2 Remove edge channel hardcode
6c89226cc Purge zero lamport accounts on snapshot ingestion (#7010)
f040987c9 Move date oracle to config program (#7105)
2a42ddbcb Don't panic if pubkeys are missing from Budget transaction (#7102)
8bb68c4e6 Really remove mentions of 'genesis_block' (#7099)
4485b978c Clean up accounts hash internal state api (#7090)
68bad56e7 Streamline multinode-demo/ restart logic (#7094)
ef55c1553 Remove unused --poll-for-new-genesis-config feature (#7093)
ce8d37984 Allow secure keypair input for solana-validator cli (#7080)
c8166aed9 Correctly indicate genesis activation_epoch (#7091)
0bd41f98e Avoid jemalloc in windows build (#7089)
d8ead57fb Use bs58 strings to declare IDs rather then raw bytes (#7082)
d9e7a5fcb Use fork weight instead of individual bank weight for fork selection. (#7079)
c965a110f Use unbounded channel (#7081)
8a879faac add genesis stake placeholders (#6969)
a2a9f1e33 Truncate new keypair files (#7078)
15d756803 Bump cbindgen from 0.9.1 to 0.10.0 (#7044)
8cbc45019 Create genesis.tar.bz2 in solana-genesis (#7039)
79199711b Add gpu resource usage tracking (#7075)
2c1b8fdd3 Add another test for bank state hashes (#7073)
d9024db68 Fix publish of move program (#7072)
```

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

When broadcast gets backed up,  the leader is setting roots way faster than they're able to broadcast. 
Eventually the leader reaches a point where the bank that's being broadcast is already a root and so has no parent information. 
So when they broadcast it they're supposed to mark what the parent slot is for the broadcast, but they don't know it anymore so they just say "0". Which is completely wrong.

#### Summary of Changes

Cache the parent's slot as soon as the bank is created and use that when broadcasting. 

Fixes #7119

@danpaul000

### CODE REVIEW

File: runtime/src/bank.rs [hunk 1]
```diff
@@ -180,6 +180,8 @@ pub struct Bank {
     /// Hash of this Bank's parent's state
     parent_hash: Hash,
 
+    parent_slot: u64,
```
Comment (rob-solana) [inline runtime/src/bank.rs]: `Slot`

File: runtime/src/bank.rs [hunk 2]
```diff
@@ -662,6 +665,10 @@ impl Bank {
         self.rc.parent.read().unwrap().clone()
     }
 
+    pub fn parent_slot(&self) -> u64 {
```
Comment (rob-solana) [inline runtime/src/bank.rs]: can return a `Slot`

Comment (sagar-solana) [reply runtime/src/bank.rs]: You're right. I'll fix it.
