### PR TITLE
Fix repair for a range of slots

### LINKED ISSUE #4274: "Repair in range" doesn't work as expected
#### Problem

"Repair in range" doesn't work if blocktree has no data for any of those slots. Repair service uses a blocktree iterator to check for holes within the slots, but this iterator skips over empty slots. 

#### Proposed Solution

Don't use the blocktree iterator, iterate over the range manually and check each slot that way

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

"Repair in range" was using a meta iterator, which skips empty slots. This meant that it was impossible to repair a range of slots that are all empty

#### Summary of Changes

Updated "repair in range" to iterate over the slots requests and generate repairs for them even if they are empty

Fixes #4274

### CODE REVIEW

File: core/src/repair_service.rs [hunk 1]
```diff
@@ -200,30 +200,31 @@ impl RepairService {
...
-        while repairs.len() < max_repairs && meta_iter.valid() {
-            let current_slot = meta_iter.key();
-            if current_slot.unwrap() > repair_range.end {
+        for slot in repair_range.start..=repair_range.end {
+            if repairs.len() >= max_repairs {
                 break;
             }
 
-            if current_slot.unwrap() > repair_info.max_slot {
+            if slot > repair_info.max_slot {
```
Comment (carllin) [inline core/src/repair_service.rs]: I think we can get rid of this `max_slot` logic and the optimistic trying to repair max_slot + 1 as the end of this function, since we know exactly what the range of slots we are trying to repair is
