### PR TITLE
local-cluster: fix flaky test_rpc_block_subscribe

### LINKED ISSUE #32863: Flaky Test: solana-local-cluster::local_cluster test_rpc_block_subscribe
_AUTO-GENERATED. DO NOT EDIT._

[📝 Buildkite Analytics](https://buildkite.com/organizations/solana-labs/analytics/suites/solana-1/tests/01884cb7-42b0-7640-a901-a26783254127)

### PR DESCRIPTION
**Pull request by AshwinSekar**
#### Problem
When a leader creates a bank, it will apply new entries to the working bank and then sends them to broadcast stage to be shredded and stored in blockstore/transmitted.

There is a race between replay and broadcast stage, and sometimes replay will vote on the bank before broadcast stage has a chance to shred the last batch of entries and store them in blockstore.

When replay votes on the bank, it will notify the rpc subscribers of the new block through the `AggregateCommitmentService`:
https://github.com/solana-labs/solana/blob/a2d7be0d07d54578b64dbed79ad482229bb7e25b/core/src/replay_stage.rs#L2249-L2255

However in the case mentioned, blockstore does not yet have all of the data shreds and the subscribers will be sent an `RpcBlockUpdateError` as the `RpcBlockUpdate` cannot be constructed:
https://github.com/solana-labs/solana/blob/a2d7be0d07d54578b64dbed79ad482229bb7e25b/ledger/src/blockstore.rs#L2189

The change https://github.com/solana-labs/solana/pull/34330 seems to exacerbate this race by increasing the # of shreds in the last FEC set. My naive hypothesis is that the extra coding shreds in the last FEC set slows down broadcast stage's blockstore insert such that the replay vote usually occurs first. 

#### Summary of Changes
Subscribe to the RPC of the non leader node, to avoid getting sent errors due to this race.

If we decide the race is necessary to fix, a solution could be to return an `Option<BlockUpdate>` with `None` in the case that `!slot_meta.is_full()` and we are the leader for that slot. This would not notify and not increment the last notified slot, so that it can be sent out on the next iteration:
https://github.com/solana-labs/solana/blob/383aa0451eb19f6d7299bf50effc1dc383054e6c/rpc/src/rpc_subscriptions.rs#L1034-L1050

Alternatively we could delay the leaders vote or rpc notification entirely until the last fec set has been inserted into blockstore.

Fixes #32863

### CODE REVIEW

**Comment by carllin** [comment]
> If we decide the race is necessary to fix, a solution could be to return an Option<BlockUpdate> with None in the case that !slot_meta.is_full() and we are the leader for that slot. This would not notify and not increment the last notified slot, so that it can be sent out on the next iteration:

Hmm interesting on failure on slot `S` right now, if `w_last_unnotified_slot` is not incremented, does that mean next time we get notification for slot `S+N`,  all blocks between `S` and `N`  show up `slots_to_notify`, even if some of those blocks were already notified?


Idealistically, think it makes sense in commitment service to keep a queue of unwritten blocks and periodically check those to notify. It  probably slows down non-block related updates though, but might be an acceptable tradeoff since thats only for leader slots

**Review by carllin — DISMISSED** [review]

File: local-cluster/tests/local_cluster.rs [hunk 1]
```diff
@@ -2562,35 +2562,38 @@ fn run_test_load_program_accounts_partition(scan_commitment: CommitmentConfig) {
...
 
     let validator_keys = [
         "28bN3xyvrP4E8LwEgtLjhnkb7cY4amQb6DrYAbAYjgRV4GAGgkVM2K7wnxnAS7WDneuavza7x21MiafLu1HkwQt4",
+        "2saHBBoTkLMmttmPQP8KfBkcCw45S5cwtV3wTdGCscRC8uxdgvHxpHiWXKx4LvJjNJtnNcbSv5NdheokFFqnNDt8",
     ]
     .iter()
     .map(|s| (Arc::new(Keypair::from_base58_string(s)), true))
     .take(node_stakes.len())
     .collect::<Vec<_>>();
+    let rpc_node_pubkey = &validator_keys[1].0.pubkey();
```
Comment (carllin) [inline local-cluster/tests/local_cluster.rs:2581]: Might be good to document or point to this PR for why we chose this validator key

**Comment by AshwinSekar** [comment]
>  does that mean next time we get notification for slot S+N, all blocks between S and N show up slots_to_notify:

correct. So for this example in the first iteration we would get a block update for slot 3 with 
```
RpcBlockUpdate { 
  slot: 3
  block: None,
  err: BlockStoreError
```
Then when slot 4 was voted on we would get 2 notifications
```
RpcBlockUpdate { 
  slot: 3
  block: <actual block>,
  err: None
}

RpcBlockUpdate { 
  slot: 4
  block: None,
  err: BlockStoreError
}
```

> Idealistically, think it makes sense for the written block notification to be decoupled from the block voted notification so we could notify separately, since block writing/block voting are necessarily coupled, and we wouldn't want block writing to delay notification of block voted

Agreed, I'm not sure why voting is the trigger here. At least for the `Processed` confirmation level I would assume subscribers would want to know about any block in blockstore, not just the ones we voted on.

File: local-cluster/tests/local_cluster.rs (hunk 1 above)
Comment (AshwinSekar) [reply local-cluster/tests/local_cluster.rs:2581]: added the comment to the subscribe call

**Review by carllin — APPROVED** [review]
