### PR TITLE
fix UPnP backout, fixes #969

### LINKED ISSUE #969: testnet-deploy.sh "node count" broken
this:

https://github.com/solana-labs/solana/commit/df5cde74b01f02efe2b4eee8d1064f4fcae43376

appears to have broken testnet-deploy.sh for master and perf testnets...

the issue is that solana-bench-tps *requires*  the "addr" argument by virtue of:

spy_node() calling unwrap on addr: https://github.com/solana-labs/solana/blob/5f6cbe0cf80317727c18b3c83c6255ec4dfc2c51/src/bin/bench-tps.rs#L645
which is passed by converge:
https://github.com/solana-labs/solana/blob/5f6cbe0cf80317727c18b3c83c6255ec4dfc2c51/src/bin/bench-tps.rs#L674
which comes from the command line:
https://github.com/solana-labs/solana/blob/5f6cbe0cf80317727c18b3c83c6255ec4dfc2c51/src/bin/bench-tps.rs#L473

### PR DESCRIPTION
**Pull request by rob-solana**

### CODE REVIEW

File: src/bin/bench-tps.rs [hunk 1]
```diff
@@ -469,9 +468,23 @@ fn main() {
         time_sec = s.to_string().parse().expect("integer");
     }
 
-    if let Some(s) = matches.value_of("addr") {
-        addr = Some(s.to_string());
-    }
+    let addr = if let Some(s) = matches.value_of("addr") {
+        match s.to_string().parse() {
```
Comment (mvines) [inline src/bin/bench-tps.rs]: nit: Whenever I see the `Ok(foo) => foo, Err(e) => ...` pattern I think of https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or_else myself, as a `match` feels a little to heavy.
