### PR TITLE
ledger-tool: Move AccountsDbConfig building to common helper function

### LINKED ISSUE #29934: ledger-tool fails to create snapshot from ledger with large number accounts  ~750M
#### Problem

On kin-sim, the following snapshot generation command failed.

```
RUST_BACKTRACE=1 ./src/solana/target/release/solana-ledger-tool --ledger /home/sol/ledger/ create-snapshot 1103712 --remove-account capRxUrBjNkkCpjrJxPGfPaWijB7q3JoDfsWXAnt46r --hard-fork 1103712
```

```
Bus error (core dumped)
```

#### Proposed Solution

Debug and fix it.

### PR DESCRIPTION
**Pull request by steviez**
#### Problem
Several subcommands may wish to specify AccountsDb configuration options. The matching is currently duplicated in both "verify" and "create-snapshot" command

#### Summary of Changes
Move the config to a common helper

Note that each subcommand that wishes to use any argument will still need to add the argument to its' argument list under App::new().

Fixes #29934

### CODE REVIEW

File: ledger-tool/src/main.rs [hunk 1]
```diff
@@ -2708,56 +2748,6 @@ fn main() {
...
-                    index: Some(accounts_index_config),
-                    accounts_hash_cache_path: Some(
-                        ledger_path.join(AccountsDb::ACCOUNTS_HASH_CACHE_DIR),
-                    ),
-                    filler_accounts_config,
-                    ancient_append_vec_offset: value_t!(
-                        matches,
-                        "accounts_db_ancient_append_vecs",
-                        i64
-                    )
```
Comment (steviez) [inline ledger-tool/src/main.rs:2752]: Another byproduct of this change is I discovered a bug with this arg (both verify and create-snapshot).

The logic is searching matches for `accounts_db_ancient_append_vecs`; however, `accounts_db_ancient_append_vecs` is an argument on the subcommand here:
https://github.com/solana-labs/solana/blob/ac7d0ff6331ed1376d39016bc500e99f1cfa22b1/ledger-tool/src/main.rs#L1793
and here
https://github.com/solana-labs/solana/blob/ac7d0ff6331ed1376d39016bc500e99f1cfa22b1/ledger-tool/src/main.rs#L1850

The match would actually be in `arg_matches` if it were present; thus, we'd never match even if the user passed it.

I have definitely burned myself on `matches` vs. `arg_matches` before; I think it is outside of the scope of this PR, but I might take a look at seeing if we can combine them or something to avoid this easy pitfall

Comment (steviez) [reply ledger-tool/src/main.rs:2752]: Decided to break out into https://github.com/solana-labs/solana/pull/29976 incase we want a backport.

File: ledger-tool/src/main.rs [hunk 2]
```diff
@@ -1021,6 +1021,52 @@ fn hardforks_of(matches: &ArgMatches<'_>, name: &str) -> Option<Vec<Slot>> {
...
+        } else {
+            IndexLimitMb::Unspecified
+        };
+    let accounts_index_drives: Vec<PathBuf> = if arg_matches.is_present("accounts_index_path") {
+        values_t_or_exit!(arg_matches, "accounts_index_path", String)
+            .into_iter()
+            .map(PathBuf::from)
+            .collect()
+    } else {
+        vec![ledger_path.join("accounts_index.ledger-tool")]
```
Comment (steviez) [inline ledger-tool/src/main.rs:1044]: @HaoranYi - You comment https://github.com/solana-labs/solana/issues/29934#issuecomment-1406680687 is reflected here.

Didn't mean to step on your toes seeing as you suggested it, but was already cleaning this up so figured it made sense to fix it while it was at the front of mind

Comment (HaoranYi) [reply ledger-tool/src/main.rs:1044]: yeah. this works. thanks!

Comment (HaoranYi) [reply ledger-tool/src/main.rs:1044]: yeah. Your fix is more general and better. 👍

**Review by HaoranYi — APPROVED** [review]
LGTM. Thanks!
Once this is merged, please close https://github.com/solana-labs/solana/issues/29934

**Review by jeffwashington — APPROVED** [review]
lgtm
