### PR TITLE
Bootstrap falls back to getting highest full snapshot

### LINKED ISSUE #21129: Bootstrap should fallback to getting highest full snapshot when incremental snapshots are not found
#### Problem

When incremental snapshots are enabled, bootstrap will fail to download a snapshot if there is not one that is a multiple of its full snapshot archive interval. This is not a good experience.

#### Proposed Solution

If bootstrap fails to find a snapshot that is a multiple, it should fallback to just finding the highest snapshot.

This issue is blocking #21127

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

When incremental snapshots are enabled, bootstrap will fail to download a snapshot if there is not one that is a multiple of its full snapshot archive interval. This is not a good experience.

#### Summary of Changes

If bootstrap fails to find a snapshot that is a multiple, it should fallback to just finding the highest snapshot.

Since there aren't tests that exercise this code path, I ran this on a GCE machine against mainnet and saw it correctly (1) try to get a snapshot with the right multiple, then (2) see there were none, then (3) fallback and download the highest snapshot, then (4) load from that snapshot and continue starting up.

Fixes #21129

### CODE REVIEW

**Comment by brooksprumo** [comment]
@mvines Let me know if you'd like any more explanation for the changes too. Thanks!

File: validator/src/bootstrap.rs [hunk 1]
```diff
@@ -1161,42 +1199,50 @@ mod with_incremental_snapshots {
         trusted_validators
             .iter()
             .for_each(|trusted_validator| {
+                // First get the Crds::SnapshotHashes for each trusted validator and add them as
+                // the keys in the trusted snapshot hashes HashMap.
+                let mut full_snapshot_hashes = Vec::new();
+                cluster_info.get_snapshot_hash_for_node(trusted_validator, |snapshot_hashes| {
```
Comment (mvines) [inline validator/src/bootstrap.rs:1205]: As a follow-up low-priority clean-up PR, could you please scrub `validator/...` of references to "trusted" validators (like `trusted_validator` here and in the comment above this line).  We call these "known" validators now at the command-line and in the docs to avoid using the loaded word "trust"

File: validator/src/bootstrap.rs [hunk 2]
```diff
@@ -1219,47 +1265,30 @@ mod with_incremental_snapshots {
...
+            // Get this peer's highest (full) snapshot hash.  We need to get these snapshot hashes
+            // (instead of just the IncrementalSnapshotHashes) in case the peer is either (1) not
+            // taking incremental snapshots, or (2) if the last snapshot taken was a full snapshot,
+            // which would get pushed to CRDS here (i.e. `crds_value::SnapshotHashes`) first.
+            let snapshot_hash = get_highest_full_snapshot_hash_for_peer(cluster_info, &rpc_peer.id);
+            if snapshot_hash > highest_snapshot_hash {
+                highest_snapshot_hash = snapshot_hash;
+            }
+
+            // ...and add the highest snapshot hash to our return vector!
```
Comment (mvines) [inline validator/src/bootstrap.rs:1285]: Nit: this comment doesn't add much.  The code it's talking about is trivial

File: validator/src/bootstrap.rs [hunk 3]
```diff
@@ -1219,47 +1265,30 @@ mod with_incremental_snapshots {
...
-                            peer_snapshot_hashes.push(PeerSnapshotHash {
-                                rpc_contact_info: rpc_peer.clone(),
-                                snapshot_hash: SnapshotHash {
-                                    full: *full_snapshot_hash,
-                                    incr: None,
-                                },
-                            })
-                        }
-                    })
+            // Get the highest incremental snapshot hash for this peer.
```
Comment (mvines) [inline validator/src/bootstrap.rs:1272]: Nit: this comment is also too chatty.  "// Get the highest incremental snapshot hash for this peer." over a line of code that calls a function named `get_highest_incremental_snapshot_hash_for_peer()`

File: validator/src/bootstrap.rs [hunk 4]
```diff
@@ -1111,29 +1111,67 @@ mod with_incremental_snapshots {
...
+                retain_peer_snapshot_hashes_with_a_multiple_of_full_snapshot_archive_interval(
+                    validator_config
+                        .snapshot_config
+                        .as_ref()
+                        .unwrap()
+                        .full_snapshot_archive_interval_slots,
+                    &mut peer_snapshot_hashes,
+                );
+
+                // However, if at this point peer_snasphot_hashes is empty, then retry from the
```
Comment (mvines) [inline validator/src/bootstrap.rs:1153]:
```suggestion
                // However, if at this point peer_snapshot_hashes is empty, then retry from the
```

File: validator/src/bootstrap.rs [hunk 5]
```diff
@@ -1111,29 +1111,67 @@ mod with_incremental_snapshots {
...
+        // Which strategy to use for getting the peer snapshot hashes?  The standard way is what's
+        // described in the function's documentation.  However, if there are no trusted peers that
+        // have enabled incremental snapshots, it may be possible that there are no snapshot hashes
+        // with a slot that is a multiple of our full snapshot archive interval.  If that happens,
+        // we retry with the "fallback" strategy that *does not* filter based on full snapshot
+        // archive interval.
+        #[derive(Debug, Copy, Clone, PartialEq, Eq)]
+        enum Strategy {
+            Standard,
+            Fallback,
```
Comment (mvines) [inline validator/src/bootstrap.rs:1123]: this is a little more wordy but also avoids needing to define what `Fallback` means:
```suggestion
            WithoutFullSnapshotArchiveIntervalFiltering,
```

**Review by mvines — APPROVED** [review]
PR looks good, I only have minor nits.  

Also "Boostrap" 👻

File: validator/src/bootstrap.rs (hunk 1 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs:1205]: Will do!

File: validator/src/bootstrap.rs (hunk 2 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs:1285]: True. Will remove.

File: validator/src/bootstrap.rs (hunk 3 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs:1272]: Will remove.

File: validator/src/bootstrap.rs (hunk 4 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs:1153]: Nice catch.

File: validator/src/bootstrap.rs (hunk 5 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs:1123]: Yeah, I debating doing something like this. I'll make this change.

File: validator/src/bootstrap.rs (hunk 1 above)
Comment (brooksprumo) [reply validator/src/bootstrap.rs:1205]: Follow-up issue for this task: #21169
