### PR TITLE
Set proper count value for account stores

### LINKED ISSUE #4735: solana::blocktree_processor: Unexpected validator error: ProgramAccountNotFound
When a validator is started from a snapshot, after processing X number of post-snapshot shots (where X is < ~100), the validator dies with an error that looks like:
```
solana::blocktree_processor] Unexpected validator error: ProgramAccountNotFound, tx: Transaction { signatures: [3BRZRhhxLqkzoCjAMzGZQHKRGBTkznYjSM2FKK2YjeLeMrr5hg41cAWxSe3k4DuCpszXj6P88fkEQsJn6mDhxwFm, 64F5q4BQxXb4wFc9n6JMmYH5XvZjs4wH3s5zqXoTVZZkbbtFS52r7gT2WgTkfQRn8h1t96Qvepq7Depxu9NuyNJV], message: Message { header: MessageHeader { num_required_signatures: 2, num_credit_only_signed_accounts: 0, num_credit_only_unsigned_accounts: 1 }, account_keys: [9Hyva99nAiDPaHEgTSJHfRc8TWMHr99QsqWeKvhymmXD, 7k7h7dzcHR8pqhTUd9Xe7MH4QXaxPSCrLTAaWadcEp2b, Sysca11S1otHashes11111111111111111111111111, Vote111111111111111111111111111111111111111], recent_blockhash: 7wVGqPp1t9mDSvrEDJnrQPoBS4W52v5wFYk34JNrgdjE, instructions: [CompiledInstruction { program_ids_index: 3, accounts: [1, 2], data: [2, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 174, 81, 0, 0, 0, 0, 0, 0, 155, 173, 3, 245, 223, 150, 9, 180, 155, 59, 85, 255, 86, 215, 5, 36, 202, 156, 49, 102, 193, 207, 141, 167, 15, 99, 173, 110, 104, 42, 142, 107, 175, 81, 0, 0, 0, 0, 0, 0, 142, 29, 122, 192, 230, 13, 248, 158, 99, 192, 157, 77, 83, 220, 55, 5, 44, 247, 244, 182, 43, 202, 198, 53, 167, 99, 68, 73, 234, 77, 87, 178, 176, 81, 0, 0, 0, 0, 0, 0, 150, 193, 203, 74, 50, 81, 33, 76, 25, 18, 149, 8, 62, 24, 108, 127, 71, 79, 149, 232, 141, 14, 47, 157, 103, 147, 225, 214, 158, 245, 174, 168, 177, 81, 0, 0, 0, 0, 0, 0, 14, 51, 209, 82, 169, 123, 51, 252, 16, 86, 213, 217, 4, 38, 140, 131, 172, 221, 245, 11, 123, 18, 152, 76, 219, 160, 227, 47, 241, 20, 68, 6, 178, 81, 0, 0, 0, 0, 0, 0, 229, 58, 218, 111, 245, 117, 184, 252, 56, 166, 12, 196, 208, 83, 222, 226, 90, 92, 34, 23, 168, 221, 7, 230, 96, 192, 192, 144, 108, 37, 22, 30, 179, 81, 0, 0, 0, 0, 0, 0, 31, 191, 24, 48, 21, 22, 166, 37, 65, 207, 157, 136, 11, 1, 87, 32, 170, 84, 183, 27, 227, 216, 192, 106, 50, 94, 225, 76, 136, 174, 40, 184, 180, 81, 0, 0, 0, 0, 0, 0, 202, 222, 121, 76, 15, 180, 232, 80, 12, 156, 10, 6, 210, 130, 99, 75, 66, 41, 13, 43, 3, 26, 147, 77, 165, 241, 170, 242, 185, 140, 241, 154, 181, 81, 0, 0, 0, 0, 0, 0, 193, 155, 107, 59, 125, 218, 228, 181, 185, 93, 113, 183, 177, 183, 64, 78, 100, 22, 94, 117, 191, 232, 107, 86, 218, 169, 144, 185, 111, 78, 107, 136, 182, 81, 0, 0, 0, 0, 0, 0, 163, 161, 105, 216, 40, 223, 68, 235, 33, 50, 82, 202, 112, 224, 156, 106, 134, 22, 201, 210, 57, 87, 197, 224, 209, 209, 185, 116, 138, 50, 128, 127, 183, 81, 0, 0, 0, 0, 0, 0, 124, 141, 93, 86, 58, 237, 63, 208, 120, 80, 71, 153, 243, 19, 227, 218, 250, 205, 100, 97, 45, 19, 189, 109, 146, 111, 148, 115, 12, 122, 7, 100, 184, 81, 0, 0, 0, 0, 0, 0, 87, 20, 97, 86, 187, 135, 43, 41, 45, 220, 12, 60, 207, 145, 115, 119, 19, 244, 194, 93, 239, 243, 67, 14, 32, 213, 56, 61, 159, 46, 146, 128, 185, 81, 0, 0, 0, 0, 0, 0, 140, 35, 186, 120, 250, 93, 102, 140, 24, 47, 15, 231, 108, 119, 72, 120, 22, 238, 80, 223, 190, 70, 19, 57, 39, 105, 60, 63, 39, 97, 195, 9, 186, 81, 0, 0, 0, 0, 0, 0, 241, 182, 90, 166, 12, 66, 196, 73, 164, 111, 173, 102, 236, 173, 125, 243, 46, 86, 202, 11, 60, 145, 216, 239, 69, 71, 65, 144, 0, 211, 189, 232, 187, 81, 0, 0, 0, 0, 0, 0, 32, 250, 98, 47, 16, 15, 206, 81, 234, 197, 255, 41, 102, 235, 235, 183, 208, 234, 244, 6, 238, 105, 252, 173, 203, 132, 29, 60, 140, 5, 251, 131, 188, 81, 0, 0, 0, 0, 0, 0, 208, 189, 123, 186, 64, 215, 12, 1, 2, 175, 189, 208, 243, 208, 163, 144, 60, 50, 204, 216, 189, 169, 56, 155, 249, 166, 164, 161, 88, 168, 41, 174, 189, 81, 0, 0, 0, 0, 0, 0, 174, 36, 250, 133, 51, 223, 66, 218, 165, 219, 196, 153, 121, 207, 57, 168, 218, 17, 222, 21, 176, 72, 18, 84, 173, 228, 248, 12, 200, 215, 173, 216] }] } }
```

Something wrong with how snapshots are saving program accounts?

STR:
1. Same as #4731 but with the local paths hacked to avoid tripping the bug in #4731

### PR DESCRIPTION
**Pull request by sambley**
#### Problem
When a validator is started from a snapshot, after processing X number of post-snapshot shots (where X is < ~100), the validator dies with an error that looks like:
solana::blocktree_processor] Unexpected validator error: ProgramAccountNotFound

#### Summary of Changes
The count value for the account store 0 gets improperly reset when the accounts are merged from the snapshots. This results in the store being removed from the roots causing the account to be not found. Make sure that the accounts are merged properly preserving the account store 0 values.

Fixes #4735

### CODE REVIEW

**Comment by mvines** [comment]
@garious and @pgarg66, can you please review today?  I’ll be AFK all day.

File: core/src/bank_forks.rs [hunk 1]
```diff
@@ -329,8 +329,9 @@ impl BankForks {
         names.sort();
         let mut bank_maps = vec![];
         let status_cache_rc = StatusCacheRc::default();
+        let id = (names[names.len() - 1] + 1) as usize;
         let mut bank0 =
-            Bank::create_with_genesis(&genesis_block, account_paths.clone(), &status_cache_rc);
+            Bank::create_with_genesis(&genesis_block, account_paths.clone(), &status_cache_rc, id);
```
Comment (rob-solana) [inline core/src/bank_forks.rs]: bank snapshots don't have much abstraction, do they?

File: runtime/src/accounts_db.rs [hunk 2]
```diff
@@ -260,7 +262,7 @@ pub struct AccountsDB {
     pub storage: RwLock<AccountStorage>,
 
     /// distribute the accounts across storage lists
-    next_id: AtomicUsize,
+    pub next_id: AtomicUsize,
```
Comment (rob-solana) [inline runtime/src/accounts_db.rs]: why is this pub, now?

File: runtime/src/bank.rs [hunk 3]
```diff
@@ -62,8 +62,9 @@ pub struct BankRc {
 }
 
 impl BankRc {
-    pub fn new(account_paths: Option<String>) -> Self {
+    pub fn new(account_paths: Option<String>, id: usize) -> Self {
```
Comment (rob-solana) [inline runtime/src/bank.rs]: what does "id" represent, can you use a type alias or another name so this is easier to read?

File: runtime/src/accounts_db.rs (hunk 2 above)
Comment (sambley) [reply runtime/src/accounts_db.rs]: The next_id needs to be initialized when the bank snapshots are restored and is set to the value of the next snapshot id which is used as the next AppendVecId to use. This value is set from the bank currently, if not pub would need to expose a set routine to set this value from accounts and accounts_db.

File: runtime/src/bank.rs (hunk 3 above)
Comment (sambley) [reply runtime/src/bank.rs]: this corresponds to AppendVecId, will replace to use AppendVecId

File: core/src/bank_forks.rs (hunk 1 above)
Comment (sambley) [reply core/src/bank_forks.rs]: if you can think of better way to abstract them, let me know and I can work on a separate PR on it.

**Comment by mvines** [comment]
@rob-solana - good enough for now?
