### PR TITLE
CLI: Error message cleanup

### LINKED ISSUE #7722: Ugly CLI errors, again
#### Problem

This is ugly and exposes implementation details such as the use of Rust crates `Reqwest` and `Hyper`:

```
$ solana show-block-production
Error: Custom { kind: Other, error: "GetEpochSchedule request failure: Reqwest(Error(Hyper(Error(Connect, Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })), "http://tds.solana.com:8899//%22))" }
```

#### Proposed Solution

```
$ solana show-block-production
error: connection refused: http://tds.solana.com:8899/
```

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

CLI produces error message that expose implementation details and are generally unfriendly to the user

#### Summary of Changes

- Consistent return types throughout client interface
- Stop abusing `io::Error`
- Surface full error stack to callers rather than squashing to a string

#### TODO
- [x] Handle remaining `io::Error` abusers in `RpcClient`
- [ ] ~Extend return type consistency to CLI~ `Box<dyn error::Error>` will do for now
- [x] Pretty error messages

Fixes #7722

### CODE REVIEW

File: sdk/src/transport.rs [hunk 1]
```diff
@@ -1,20 +1,15 @@
...
-            TransportError::IoError(err) => write!(formatter, "{:?}", err),
-            TransportError::TransactionError(err) => write!(formatter, "{:?}", err),
-        }
-    }
+    #[error("transport io error: {0}")]
+    IoError(#[from] io::Error),
+    #[error("transport transaction error: {0}")]
+    TransactionError(#[from] TransactionError),
+    #[error("transport custom error: {0}")]
+    Custom(String),
```
Comment (t-nelson) [inline sdk/src/transport.rs]: Might kill the `String` here in favor of https://crates.io/crates/anyhow if time permits.  Would allow removal of its companion variant in `ClientError`

Comment (garious) [reply sdk/src/transport.rs]: Tough call.  `anyhow` is another escape hatch.  The team tends to make use of those too often.

Comment (t-nelson) [reply sdk/src/transport.rs]: Yeah I was waffling on that notion.  Probably better to yank the dependency-based variants out of `ClientError` in favor of our own variants and some `From` impls

**Comment by garious** [comment]
Just started test-driving this locally. Got a double "Error: error:"

```
Error: error: Couldn't find keypair file: ...
```

Can you make that just:

```
error: Couldn't find keypair file: ...
```

At a glance, looks like that first "Error:" is correct, but should be "error:", and then the second one just shouldn't be there.

File: sdk/src/instruction.rs [hunk 2]
```diff
@@ -3,96 +3,124 @@
...
     /// Executable bit on account changed, but shouldn't have
+    #[error("instrcution changed executable bit")]
     ExecutableModified,
 
     /// Rent_epoch account changed, but shouldn't have
+    #[error("instruction modified rent epoch")]
     RentEpochModified,
 
     /// The instruction expected additional account keys
+    #[error("Insufficient account keys for instruction")]
```
Comment (garious) [inline sdk/src/instruction.rs]: rando capital letter

File: sdk/src/instruction.rs [hunk 3]
```diff
@@ -3,96 +3,124 @@
...
     /// The instruction expected an executable account
+    #[error("instruction expected an executable account")]
     AccountNotExecutable,
 
     /// Failed to borrow a reference to account data, already borrowed
+    #[error("instruction attempted to borrow already borrowed account")]
     AccountBorrowFailed,
 
     /// Account data has an outstanding reference after a program's execution
+    #[error("instruction left account data with outstanding borrow")]
```
Comment (garious) [inline sdk/src/instruction.rs]: missing "an" before "outstanding"

File: sdk/src/instruction.rs [hunk 4]
```diff
@@ -3,96 +3,124 @@
...
     /// The same account was multiply passed to an on-chain program's entrypoint, but the program
     /// modified them differently.  A program can only modify one instance of the account because
     /// the runtime cannot determine which changes to pick or how to merge them if both are modified
+    #[error("instruction modifications of multiply-passed account differ")]
     DuplicateAccountOutOfSync,
 
     /// Allows on-chain programs to implement program-specific error types and see them returned
     /// by the Solana runtime. A program-specific error may be any type that is represented as
     /// or serialized to a u32 integer.
+    #[error("custom instruction error: {0}")]
```
Comment (garious) [inline sdk/src/instruction.rs]: don't need the word "custom"

File: sdk/src/instruction.rs [hunk 5]
```diff
@@ -3,96 +3,124 @@
...
     /// A non-system program changed the size of the account data
+    #[error("non-system instruction changed account size")]
     AccountDataSizeChanged,
 
     /// The instruction expected an executable account
+    #[error("instruction expected an executable account")]
     AccountNotExecutable,
 
     /// Failed to borrow a reference to account data, already borrowed
+    #[error("instruction attempted to borrow already borrowed account")]
```
Comment (garious) [inline sdk/src/instruction.rs]: missing "an" before "already"

File: sdk/src/instruction.rs [hunk 6]
```diff
@@ -3,96 +3,124 @@
...
+    #[error("instruction modified data of read-only account")]
     ReadonlyDataModified,
 
     /// An account was referenced more than once in a single instruction
     // Deprecated, instructions can now contain duplicate accounts
+    #[error("instruction contains duplicate accounts")]
     DuplicateAccountIndex,
 
     /// Executable bit on account changed, but shouldn't have
+    #[error("instrcution changed executable bit")]
```
Comment (garious) [inline sdk/src/instruction.rs]: :set spell

File: sdk/src/instruction.rs [hunk 7]
```diff
@@ -3,96 +3,124 @@
...
-#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
+#[derive(Serialize, Deserialize, Debug, Error, PartialEq, Eq, Clone)]
 pub enum InstructionError {
     /// Deprecated! Use CustomError instead!
     /// The program instruction returned an error
+    #[error("generic instruction error")]
     GenericError,
 
     /// The arguments provided to a program instruction where invalid
+    #[error("invalid instruction argument")]
```
Comment (jackcmay) [inline sdk/src/instruction.rs]: Description refers to instruction but the error refers to a program getting bad arguments.  Other added `#[error`s are also doing that and probably shouldn't

**Comment by t-nelson** [comment]
> At a glance, looks like that first "Error:" is correct, but should be "error:", and then the second one just shouldn't be there.

Unfortunately `clap` has the wheel for both of these cases... "Error: " is prepended to `Debug` of whatever `main()` returns.  The second "error: " is an artifact of using `clap::Error` in a few spots.  I'll see what I can do about the latter, can you live with the former?

File: sdk/src/instruction.rs (hunk 3 above)
Comment (jackcmay) [inline sdk/src/instruction.rs]: Nix account

File: sdk/src/instruction.rs [hunk 8]
```diff
@@ -3,96 +3,124 @@
...
     InvalidArgument,
 
     /// An instruction's data contents was invalid
+    #[error("invalid instruction data")]
     InvalidInstructionData,
 
     /// An account's data contents was invalid
+    #[error("invalid account data for instruction")]
```
Comment (jackcmay) [inline sdk/src/instruction.rs]: Do we need "for instruction" on the end of these?

File: sdk/src/instruction.rs [hunk 9]
```diff
@@ -3,96 +3,124 @@
...
     /// An initialize instruction was sent to an account that has already been initialized.
+    #[error("already initialized account for instruction")]
     AccountAlreadyInitialized,
 
     /// An attempt to operate on an account that hasn't been initialized.
+    #[error("uninitialized account for instruction")]
     UninitializedAccount,
 
     /// Program's instruction lamport balance does not equal the balance after the instruction
+    #[error("balance mismatch after instruction")]
```
Comment (jackcmay) [inline sdk/src/instruction.rs]: This isn't a balance mismatch, its an unbalanced lamport balance after the instruction

File: sdk/src/instruction.rs [hunk 10]
```diff
@@ -3,96 +3,124 @@
...
     UnbalancedInstruction,
 
     /// Program modified an account's program id
+    #[error("instruction modified program id")]
```
Comment (jackcmay) [inline sdk/src/instruction.rs]: "modified an account's program id"

File: sdk/src/instruction.rs (hunk 8 above)
Comment (t-nelson) [reply sdk/src/instruction.rs]: Since these are for implementing `Display` I wanted to hint back to `InstructionError` for the developers sake.  Happy to kill them if you don't think it'll be a problem

File: sdk/src/instruction.rs [hunk 11]
```diff
@@ -3,96 +3,124 @@
...
     ModifiedProgramId,
 
     /// Program spent the lamports of an account that doesn't belong to it
+    #[error("instruction spent from account it does not own")]
```
Comment (jackcmay) [inline sdk/src/instruction.rs]: nit, spent what?

File: sdk/src/instruction.rs (hunk 5 above)
Comment (jackcmay) [reply sdk/src/instruction.rs]: Update both comment and error string to just say account rather then account data

File: sdk/src/instruction.rs (hunk 3 above)
Comment (jackcmay) [reply sdk/src/instruction.rs]: same comment here about "data"

File: sdk/src/instruction.rs (hunk 4 above)
Comment (jackcmay) [reply sdk/src/instruction.rs]: There are program errors

File: sdk/src/instruction.rs (hunk 9 above)
Comment (garious) [reply sdk/src/instruction.rs]: hehe, "unbalanced balance", gotta be a better way to say that.  Also, @t-nelson, please avoid the word "lamport" in user-facing messages. It's all SOL for them. Oftentimes best to say "amount" or "balance" - only use SOL if the added precision is helpful.

File: sdk/src/instruction.rs [hunk 12]
```diff
@@ -3,96 +3,124 @@
...
 
     /// Allows on-chain programs to implement program-specific error types and see them returned
     /// by the Solana runtime. A program-specific error may be any type that is represented as
     /// or serialized to a u32 integer.
+    #[error("custom instruction error: {0}")]
     CustomError(u32),
 
     /// The return value from the program was invalid.  Valid errors are either a defined builtin
     /// error value or a user-defined error in the lower 32 bits.
+    #[error("instruction error is invalid")]
```
Comment (jackcmay) [inline sdk/src/instruction.rs]: Program returned an invalid error code

**Comment by garious** [comment]
@t-nelson, would prefer Debug instances not be used, only Display.  Will take "Error:" if that's all that's possible, but don't love it.

File: sdk/src/instruction.rs (hunk 7 above)
Comment (garious) [reply sdk/src/instruction.rs]: And any time the error string becomes just as complete as the comment, go ahead and delete the comment.  Don't need the maintenance burden of having to make updates in both places or confusion from them getting out of sync.

**Comment by t-nelson** [comment]
> @t-nelson, would prefer Debug instances not be used, only Display. Will take "Error:" if that's all that's possible, but don't love it.

Agreed!  This is as close as I could get, https://github.com/solana-labs/solana/blob/2c210115c5cc9c89e55e07bf49b6aec012899015/cli/src/main.rs#L234-L246

File: sdk/src/instruction.rs (hunk 9 above)
Comment (t-nelson) [reply sdk/src/instruction.rs]: "unbalanced balance" is _exactly_ what I was dancing around :laughing:

File: sdk/src/instruction.rs (hunk 4 above)
Comment (t-nelson) [reply sdk/src/instruction.rs]: @jackcmay s/There/These/?

File: sdk/src/instruction.rs (hunk 8 above)
Comment (jackcmay) [reply sdk/src/instruction.rs]: Ok, yeah I figured that, leave it

File: cli/src/main.rs [hunk 13]
```diff
@@ -230,6 +230,25 @@ fn main() -> Result<(), Box<dyn error::Error>> {
...
+
+        #[derive(Error)]
+        #[error("")]
+        struct PrettyError(String);
+
+        impl std::fmt::Debug for PrettyError {
+            fn fmt(&self, fmt: &mut std::fmt::Formatter) -> std::fmt::Result {
+                write!(fmt, "{}", self.0)
+            }
+        }
```
Comment (CriesofCarrots) [inline cli/src/main.rs]: Any reason this stuff needs to be in `main()`? Not really consistent with how we typically structure things, esp the use statement.

File: sdk/src/instruction.rs (hunk 9 above)
Comment (jackcmay) [reply sdk/src/instruction.rs]: "Total account balances before and after instruction don't match"?

File: sdk/src/instruction.rs (hunk 4 above)
Comment (garious) [reply sdk/src/instruction.rs]: yes "program error: {0}" would be best

File: keygen/src/keygen.rs [hunk 14]
```diff
@@ -191,6 +191,26 @@ fn grind_parse_args(
...
+
+        #[derive(Error)]
+        #[error("")]
+        struct PrettyError(String);
+
+        impl std::fmt::Debug for PrettyError {
+            fn fmt(&self, fmt: &mut std::fmt::Formatter) -> std::fmt::Result {
+                write!(fmt, "{}", self.0)
+            }
+        }
```
Comment (CriesofCarrots) [inline keygen/src/keygen.rs]: Same comment here as in cli/src/main.rs

File: cli/src/main.rs (hunk 13 above)
Comment (t-nelson) [reply cli/src/main.rs]: Nah.  I was just in an "oh shit!" frenzy when I realized I broke return codes at the last minute.

I'll move it into `clap-utils` and give it a better name

Comment (CriesofCarrots) [reply cli/src/main.rs]: lol, I did the same thing when I tried to sneak a display->debug change into another cli pr

File: sdk/src/instruction.rs (hunk 7 above)
Comment (t-nelson) [reply sdk/src/instruction.rs]: @garious will we not lose the docs in that case?  I don't see where `thiserror` claims to generate them.  Maybe that's fine...

File: sdk/src/instruction.rs (hunk 3 above)
Comment (jackcmay) [reply sdk/src/instruction.rs]: Opps, I meant remove "data" in both comment and message

File: sdk/src/instruction.rs (hunk 7 above)
Comment (garious) [reply sdk/src/instruction.rs]: Good point!  I suppose we'll need to keep the duplication until we can convince ourselves nobody reads those docs. :)

File: sdk/src/instruction.rs (hunk 3 above)
Comment (t-nelson) [reply sdk/src/instruction.rs]: :+1: I was just assembling a reply with evidence of contradiction.  Thanks for saving me the trouble! :sweat_smile:

File: sdk/src/instruction.rs (hunk 7 above)
Comment (t-nelson) [reply sdk/src/instruction.rs]: Shouldn't take too long! :laughing:

**Comment by t-nelson** [comment]
@CriesofCarrots @garious @jackcmay I believe I've addressed all of the previous comments now

**Comment by garious** [comment]
:shipit: please. Want this in 1.0.6.

**Comment by t-nelson** [comment]
:robot: take the wheel!

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by mvines** [comment]
🤦

**Comment by garious** [comment]
https://www.donttouchyaface.com/
