### PR TITLE
removes feature gate code separating durable nonce from blockhash domain

### LINKED ISSUE #25950: Confusing durable nonce function call convention
#### Problem

From Halborn:

The nonce patch (#25788) changes definitions of several functions which previously required the caller to provide a DurableNonce and now require a tuple with a DurableNonce and a boolean, indicating the separation of blockhash and nonce domains.

If this boolean is set to true, DurableNonces are generated from a hash
of the most recent blockhash and a fixed seed to prevent transaction
replay.

This boolean parameter used is in multiple function calls across the
codebase and is usually accompanied by a comment. This inconsistency
might be confusing to developers unfamiliar with the bug and previous
nonce format, which may lead to them writing incorrect code.

#### Proposed Solution

Consider introducing a new type with a verbose name to better explain the
meaning of the separate_domains variable value.

### PR DESCRIPTION
**Pull request by behzadnouri**
#### Problem
Feature is activated on all clusters.

#### Summary of Changes
removed the feature gate code

closes #25950,  #25772

### CODE REVIEW

**Comment by behzadnouri** [comment]
**Not** to be merged until a couple more epochs, 
but wanted to clean this up while the code is still in my head.

File: runtime/src/nonce_keyed_account.rs [hunk 1]
```diff
@@ -281,15 +268,9 @@ pub fn authorize_nonce_account(
...
-                data.durable_nonce,
-                data.get_lamports_per_signature(),
-            );
-            account.set_state(&Versions::new(
-                State::Initialized(new_data),
-                separate_domains,
-            ))
+            // Safe to unwrap here because state is known to be Initialized.
+            let state = state.authorize(*nonce_authority).unwrap();
+            account.set_state(&state)
```
Comment (behzadnouri) [inline runtime/src/nonce_keyed_account.rs:273]: Note a bit of new code here.

File: sdk/program/src/nonce/state/mod.rs [hunk 2]
```diff
@@ -74,17 +56,34 @@ impl Versions {
...
+            data.get_lamports_per_signature(),
+        );
+        let state = Box::new(State::Initialized(data));
+        // Preserve Version variant since cannot
+        // change durable_nonce field here.
+        Some(match self {
+            Self::Legacy(_) => Self::Legacy(state),
+            Self::Current(_) => Self::Current(state),
+        })
+    }
```
Comment (behzadnouri) [inline sdk/program/src/nonce/state/mod.rs:86]: New code.

File: sdk/program/src/nonce/state/mod.rs [hunk 3]
```diff
@@ -74,17 +56,34 @@ impl Versions {
...
                         Some(Self::Current(state))
                     }
                 }
             }
             Self::Current(_) => None,
         }
     }
+
+    // Updates authority pubkey on the nonce account.
+    pub fn authorize(self, authority: Pubkey) -> Option<Self> {
```
Comment (jstarry) [inline sdk/program/src/nonce/state/mod.rs:69]: I think this method is doing too much. How about having a `update_state` method that just allows updating the state with a passed `state` argument while still preserving the version variant? I think that would result in less refactoring. The tests using this method could use a test-only authorize function if needed

File: sdk/program/src/nonce/state/mod.rs [hunk 4]
```diff
@@ -15,12 +15,8 @@ pub enum Versions {
 }
 
 impl Versions {
-    pub fn new(state: State, separate_domains: bool) -> Self {
-        if separate_domains {
-            Self::Current(Box::new(state))
-        } else {
-            Self::Legacy(Box::new(state))
-        }
+    pub fn new(state: State) -> Self {
```
[the remark this answers is not in the document]
Comment (behzadnouri) [reply sdk/program/src/nonce/state/mod.rs:18]: The goal here is to encapsulate any logic distinguishing Legacy vs Current in this module, so the call-sites wouldn't need to know or care which variant is underneath.

File: sdk/program/src/nonce/state/mod.rs (hunk 3 above)
Comment (behzadnouri) [reply sdk/program/src/nonce/state/mod.rs:70]: Similar to the other comment, I would rather not to expose any Current vs Legacy logic outside of this module;

File: sdk/program/src/nonce/state/mod.rs [hunk 5]
```diff
@@ -74,17 +56,35 @@ impl Versions {
...
         }
     }
+
+    /// Updates authority pubkey on the nonce account.
+    /// Returns None if the nonce account state in Uninitialized.
+    pub fn authorize(self, authority: Pubkey) -> Option<Self> {
+        let data = match self.state() {
+            State::Uninitialized => return None,
+            State::Initialized(data) => data,
+        };
```
Comment (t-nelson) [inline sdk/program/src/nonce/state/mod.rs:74]: hasn't the caller already resolved this?

File: runtime/src/nonce_keyed_account.rs (hunk 1 above)
Comment (behzadnouri) [reply runtime/src/nonce_keyed_account.rs:273]: It is part of removing `separate_domains` arg entirely from the code-base.

File: sdk/program/src/nonce/state/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (behzadnouri) [reply sdk/program/src/nonce/state/mod.rs:18]: > to what end?

Fewer bugs; better design. encapsulating implementation details, etc.

> i think the detail is going to be interesting to any human competent enough to be making changes around here. iirc the method was originally called new_current for that reason. i think there's a similar precedent in the vote program

I disagree. If it is something that the call-site does not need to know or care about then no need to add noise to call-sites.

File: sdk/program/src/nonce/state/mod.rs (hunk 5 above)
Comment (behzadnouri) [reply sdk/program/src/nonce/state/mod.rs:74]: the function is valid either way.

File: sdk/program/src/nonce/state/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (jstarry) [reply sdk/program/src/nonce/state/mod.rs:18]: If the struct wasn't named `Versions` I might agree with you @behzadnouri, but given its name, I think it's best to be explicit about which version is being constructed.

File: sdk/program/src/nonce/state/mod.rs (hunk 3 above)
Comment (jstarry) [reply sdk/program/src/nonce/state/mod.rs:70]: My suggestion doesn't result in exposing that logic outside of this module. It would be something like this:

https://github.com/solana-labs/solana/blob/52aa5acdf134a0888b6741f4a335c9dcf3911734/sdk/program/src/nonce/state/mod.rs#L68-L75

https://github.com/solana-labs/solana/blob/52aa5acdf134a0888b6741f4a335c9dcf3911734/runtime/src/nonce_keyed_account.rs#L272-L278

File: sdk/program/src/nonce/state/mod.rs (hunk 5 above)
Comment (jstarry) [reply sdk/program/src/nonce/state/mod.rs:74]: I also think it would be cleaner to avoid this redundant check in my suggested approach here: https://github.com/solana-labs/solana/pull/26055/files#r903486764

File: runtime/src/nonce_keyed_account.rs (hunk 1 above)
Comment (behzadnouri) [reply runtime/src/nonce_keyed_account.rs]: This is now broken into 2 commits:
* 1st commit encapsulates AuthorizeNonceAccount implementation in the nonce module.
* 2nd commit removes the feature gate code.

File: sdk/program/src/nonce/state/mod.rs (hunk 3 above)
Comment (behzadnouri) [reply sdk/program/src/nonce/state/mod.rs]: The downside of
```rust
fn update(self, state: Box<State>) -> Self
```

is that the api by itself is ambiguous why we need the state when `self` already has the state and then which state comes out at the end in `-> Self`? the one in `self` or in the other argument.

I have updated this code to encapsulates `AuthorizeNonceAccount` implementation in the nonce module.

**Comment by behzadnouri** [comment]
> can this change be made in a separate PR? better to keep the gate removal to pure removal and avoid refactors. already a lot of plumbing and rustfmt noise in here

It is now two separate commits. The 2nd one only removes the feature gate code.

File: sdk/program/src/nonce/state/mod.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (jstarry) [reply sdk/program/src/nonce/state/mod.rs:25]: You have two reviewers requesting to have more verbosity in the method name. Can you please yield here and update it? `Versions::new()` isn't great

File: sdk/program/src/nonce/state/mod.rs (hunk 3 above)
Comment (jstarry) [reply sdk/program/src/nonce/state/mod.rs]: I don't think there is any ambiguity of what happens when you pass an argument to a method called "update." But your latest change looks good, happy to go with that.

**Review by jstarry — DISMISSED** [review]
