### PR TITLE
Fail fast if account paths cannot be canonicalized

### LINKED ISSUE #7258: solana-validator accepts relative path for --ledger, but breaks snapshot creation
#### Problem

`solana-validator` accepts a relative path to the ledger for the --ledger option, and it mostly operates successfully. However, snapshot creation *fails*, _**silently**_. (Found by a tearful event in the journey of #7244).

The reason is simple, when creating snapshot, it creates a tmp dir populated by symlinks to real AppendVec files. And the created symlinks are broken when using relative paths. It seems that it doesn't take any consideration of relative path rewrite/calculation at all.

Error:

```
$ solana-validator --entrypoint tds.solana.com:8001 --ledger tds --no-voting --log - --rpc-port 8899

...

[2019-12-04T09:47:57.111575538Z WARN  solana_core::snapshot_packager_service] tar command failed with exit code: exit code: 1
[2019-12-04T09:47:57.111635808Z INFO  solana_core::snapshot_packager_service] tar stdout:
[2019-12-04T09:47:57.111654729Z INFO  solana_core::snapshot_packager_service] tar stderr: tar: accounts/440.446: File removed before we read it
    tar: accounts/334140.447590: File removed before we read it
    tar: accounts/340073.455998: File removed before we read it
    tar: accounts/340260.456216: File removed before we read it
    tar: accounts/404.410: File removed before we read it
    tar: accounts/357644.480884: File removed before we read it
    tar: accounts/352234.472967: File removed before we read it
    tar: accounts/357512.480667: File removed before we read it
    tar: accounts/352234.472965: File removed before we read it
    tar: accounts/211740.246940: File removed before we read it
    tar: accounts/212684.248536: File removed before we read it
    tar: accounts/134824.134862: File removed before we read it
```

When `--ledger` is relative path (bad):

```
$ ls -l accounts/
total 0
lrwxrwxrwx 1 ubuntu ubuntu 16 Dec  4 12:37 0.0 -> tds/accounts/0.0
lrwxrwxrwx 1 ubuntu ubuntu 16 Dec  4 12:37 0.1 -> tds/accounts/0.1
lrwxrwxrwx 1 ubuntu ubuntu 16 Dec  4 12:37 0.2 -> tds/accounts/0.2
lrwxrwxrwx 1 ubuntu ubuntu 16 Dec  4 12:37 0.3 -> tds/accounts/0.3
lrwxrwxrwx 1 ubuntu ubuntu 16 Dec  4 12:37 0.4 -> tds/accounts/0.4
lrwxrwxrwx 1 ubuntu ubuntu 16 Dec  4 12:37 0.5 -> tds/accounts/0.5
lrwxrwxrwx 1 ubuntu ubuntu 16 Dec  4 12:37 0.6 -> tds/accounts/0.6
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 134777.134812 -> tds/accounts/134777.134812
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 134777.134813 -> tds/accounts/134777.134813
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 134824.134862 -> tds/accounts/134824.134862
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 134824.134863 -> tds/accounts/134824.134863
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 141316.141693 -> tds/accounts/141316.141693
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 141316.141694 -> tds/accounts/141316.141694
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 141384.141783 -> tds/accounts/141384.141783
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 141384.141784 -> tds/accounts/141384.141784
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 142043.142675 -> tds/accounts/142043.142675
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 148912.152045 -> tds/accounts/148912.152045
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 148912.152046 -> tds/accounts/148912.152046
lrwxrwxrwx 1 ubuntu ubuntu 26 Dec  4 12:37 148960.152113 -> tds/accounts/148960.152113
```

When `--ledger` is absolute path (good):

```
$ ls -l accounts/
total 0
lrwxrwxrwx 1 ubuntu ubuntu 42 Dec  4 12:40 0.0 -> /mnt/solana-data/solana-data2/accounts/0.0
lrwxrwxrwx 1 ubuntu ubuntu 42 Dec  4 12:40 0.1 -> /mnt/solana-data/solana-data2/accounts/0.1
lrwxrwxrwx 1 ubuntu ubuntu 42 Dec  4 12:40 0.2 -> /mnt/solana-data/solana-data2/accounts/0.2
lrwxrwxrwx 1 ubuntu ubuntu 42 Dec  4 12:40 0.3 -> /mnt/solana-data/solana-data2/accounts/0.3
lrwxrwxrwx 1 ubuntu ubuntu 42 Dec  4 12:40 0.4 -> /mnt/solana-data/solana-data2/accounts/0.4
lrwxrwxrwx 1 ubuntu ubuntu 42 Dec  4 12:40 0.5 -> /mnt/solana-data/solana-data2/accounts/0.5
lrwxrwxrwx 1 ubuntu ubuntu 42 Dec  4 12:40 0.6 -> /mnt/solana-data/solana-data2/accounts/0.6
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 134777.134812 -> /mnt/solana-data/solana-data2/accounts/134777.134812
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 134777.134813 -> /mnt/solana-data/solana-data2/accounts/134777.134813
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 134824.134862 -> /mnt/solana-data/solana-data2/accounts/134824.134862
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 134824.134863 -> /mnt/solana-data/solana-data2/accounts/134824.134863
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 141316.141693 -> /mnt/solana-data/solana-data2/accounts/141316.141693
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 141316.141694 -> /mnt/solana-data/solana-data2/accounts/141316.141694
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 141384.141783 -> /mnt/solana-data/solana-data2/accounts/141384.141783
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 141384.141784 -> /mnt/solana-data/solana-data2/accounts/141384.141784
lrwxrwxrwx 1 ubuntu ubuntu 52 Dec  4 12:40 142043.142675 -> /mnt/solana-data/solana-data2/accounts/142043.142675

```

#### Proposed Solution

- Error when creating snapshot fails
- Error when relative path is given for `--ledger`, or:
  - Resolve to absolute before creating symlinks
  - Better yet create proper relative symlinks.

### PR DESCRIPTION
**Pull request by jstarry**
### Problem
solana-validator accepts a relative paths --accounts argument, we don't check if the paths can be canonicalized before attempting to do so during the snapshotting process

### Summary of Changes
- Change `account_paths` from `String` to `Vec<PathBuf>`
- Check that the account paths can be created and canonicalized during validator startup

Fixes #7258

### CODE REVIEW

File: validator/src/main.rs [hunk 1]
```diff
@@ -591,12 +591,28 @@ pub fn main() {
...
+        account_paths.split(',').map(PathBuf::from).collect()
     } else {
-        validator_config.account_paths =
-            Some(ledger_path.join("accounts").to_str().unwrap().to_string());
-    }
+        vec![ledger_path.join("accounts")]
+    };
+
+    // Create and canonicalize account paths to avoid issues with symlink creation
+    validator_config.account_paths = account_paths
```
Comment (jstarry) [inline validator/src/main.rs]: This is the key part of the PR, the other changes are just cleanup.

**Comment by mvines** [comment]
Nice, you'd been hovering over that green merge button for hours 'eh
