### PR TITLE
Fix metrics when leader does not report metrics

### LINKED ISSUE #5170: Metrics dashboard goes dark when a 3rd party node becomes leader
Some of the metrics only come from the leader node, so if the leader node is not hooked up with metrics then the dashboard starts to go bad.   Everything in this screenshot is fed by the leader node, and between 19:47 and 19:48 a 3rd party node became leader:
image

We probably need to remove all/most leader-specific metrics to be exposed by all validators

### PR DESCRIPTION
**Pull request by jstarry**
#### Summary of Changes

*Metrics Reporting*:
* Added `host_id` influx tag to enable aggregating metrics across nodes
* All nodes will now announce how many nodes are in the cluster
* In addition to announcing when they become leader, nodes will also announce when another node becomes leader
* Transaction counts are reported different ways to have both fine-grained and aggregate metrics:
  * From leader as they execute transactions
  * From validators as they replay transactions
  * From the banking stage as it processes transactions (all nodes report this)

*Metrics Dashboard*:
* Both the node count stat and graph now show up to date values as long as one validator has metrics enabled. The median of all reported node counts will be displayed
* Transaction metrics use the reported tx count from the banking stage. The median of counts from all nodes is used
* Vote counts were being double counted before, now we take the median of the processed vote counts from all nodes
* Current leader is calculated from the mode of all reported leaders
* Leader change graph now determines the current slot by taking the median reported slot from all nodes

Fixes #5170

### CODE REVIEW

File: core/src/replay_stage.rs [hunk 1]
```diff
@@ -250,7 +261,7 @@ impl ReplayStage {
 
         assert!(!poh_recorder.lock().unwrap().has_bank());
 
-        let (reached_leader_tick, grace_ticks, poh_slot, parent_slot) =
+        let (reached_leader_tick, _, poh_slot, parent_slot) =
```
Comment (mvines) [inline core/src/replay_stage.rs]: nit: My preference is to use `_grace_ticks` instead of `_` for unused tuple items.   This helps prevents an unreadable mess when more items are unused (eg,  `let (_, _, _, foo, _, _) = ..`)

File: core/src/replay_stage.rs [hunk 2]
```diff
@@ -899,7 +915,8 @@ mod test {
             progress.insert(bank0.slot(), ForkProgress::new(last_blockhash));
             let blob = blob_to_insert(&last_blockhash);
             blocktree.insert_data_blobs(&[blob]).unwrap();
-            let res = ReplayStage::replay_blocktree_into_bank(&bank0, &blocktree, &mut progress);
+            let (res, _) =
```
Comment (mvines) [inline core/src/replay_stage.rs]: same: `let (res, _entries) = ` please

File: core/src/replay_stage.rs [hunk 3]
```diff
@@ -328,10 +339,12 @@ impl ReplayStage {
...
-    ) -> Result<()> {
+    ) -> (Result<()>, Vec<Entry>) {
+        let mut entries = Vec::new();
         let result =
-            Self::load_blocktree_entries(bank, blocktree, progress).and_then(|(entries, num)| {
-                Self::replay_entries_into_bank(bank, entries, progress, num)
+            Self::load_blocktree_entries(bank, blocktree, progress).and_then(|(e, num)| {
+                entries = e;
+                Self::replay_entries_into_bank(bank, &entries, progress, num)
             });
```
Comment (mvines) [inline core/src/replay_stage.rs]: I think this would work too and avoids creating a `mut`
```rust
let (result, entries) =
    Self::load_blocktree_entries(bank, blocktree, progress).and_then(|(entries, num)| {
        (Self::replay_entries_into_bank(bank, &entries, progress, num), entries)
    });
```

File: metrics/src/metrics.rs [hunk 4]
```diff
@@ -245,6 +245,7 @@ impl MetricsAgent {
 
         let extra = influxdb::Point::new("metrics")
             .add_timestamp(timing::timestamp() as i64)
+            .add_tag("host_id", influxdb::Value::String(HOST_ID.to_string()))
```
Comment (mvines) [inline metrics/src/metrics.rs]: Sending `host_id` as both a tag and field is a little yucky for bandwidth.  Can we just send `host_id` as a tag?

File: core/src/replay_stage.rs (hunk 3 above)
Comment (jstarry) [reply core/src/replay_stage.rs]: I was really hoping to find a more elegant way to write this! The problem is that I want to do two things, map the result and pull out the entries or default to an empty vec. Your suggestion won't compile because `and_then` has return type `Result` while you are returning a tuple.

File: metrics/src/metrics.rs [hunk 5]
```diff
@@ -56,11 +56,6 @@ macro_rules! datapoint {
     (@point $name:expr) => {
         $crate::influxdb::Point::new(&$name)
     };
-    ($name:expr) => {
```
Comment (jstarry) [inline metrics/src/metrics.rs]: Each data point needs at least one field and since we no longer add the `host_id` field by default, this is no longer allowed

File: core/src/replay_stage.rs (hunk 3 above)
Comment (mvines) [reply core/src/replay_stage.rs]: Wait the only consumer of `entries` is this line right?
```rust
tx_count += entries.iter().map(|e| e.transactions.len()).sum::<usize>();
```

We could just return the tx_count as `Result<(), u64>`.

Comment (jstarry) [reply core/src/replay_stage.rs]: Do you mean a `(Result<()>, u64)`? Yeah, we can do that! I guess I would just worry that a u64 isn't self-documenting. What's the motivation to return a `u64` instead of a `Vec<Entry>`?

Comment (mvines) [reply core/src/replay_stage.rs]: > What's the motivation to return a u64 instead of a Vec<Entry>?

Just to reduce the API surface to the caller, as they currently only need the transaction count and not the full list of Entries.   Future refactoring is so much easier if the dependencies between all the things contain only the essentials
