### PR TITLE
Skip shrink until startup verification is complete

### LINKED ISSUE #34180: Initial accounts hash verification panics if shrink is in progress
#### Problem

Initial report: https://discord.com/channels/428295358100013066/1027231858565586985/1176191946990043278

A testnet canary, `tcs1`, running v1.16.21 panicked at startup during the initial accounts hash verification because `shrink` was in progress:
```
thread 'solBgHashVerify' panicked at 'assertion failed: self.no_shrink_in_progress()', runtime/src/account_storage.rs:122:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: solana_runtime::accounts_db::AccountsDb::get_snapshot_storages
   4: solana_runtime::accounts_db::AccountsDb::verify_accounts_hash_and_lamports
```

Looking at the log, indeed `shrink` *was* running. But why was this an issue?

To calculate the accounts hash, we use snapshot storages. Normally, this is done in the AccountsBackgroundSerivce -> AccountsHashVerifier pipeline. In ABS, getting the snapshot storages is serialized with shrink; only one or the other can run at a time.

At startup, the initial accounts hash verification does *not* go through ABS -> AHV, it is a separate thing. Because of this, it *is* possible for `shrink` to be running in `ABS`, and for the initial accounts hash verification to call `get_snapshot_storages()`, and thus panic.

#### Proposed Solution

Before starting the initial accounts hash verification, get the snapshot storages and then pass them into `verify_accounts_hash()`:
https://github.com/solana-labs/solana/blob/302238bfd9e68aaca0cdce761270efedb0e7123b/runtime/src/bank.rs#L6992-L7001

#### Alternative Solution

Do not run `shrink` until after the initial accounts hash calculation has completed.

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Please refer to #34180.

#### Summary of Changes

Skip 'shrink' until after startup verification has completed.

This implementation was chosen instead of getting all the snapshot storages as passing them into `verify_accounts_hash()` so that the fix would be the least invasive. As this will be more of an issue once IncrementalAccountsHash is enabled (because we do two accounts hash calculations at startup), we want to backport this fix all the way to v1.16, and thus a minimal PR is preferred.

Skipping shrink until the startup verification is complete is also safe. We used to pause *everything* until startup verification was complete, so reigning in one thing should be fine. (Note this will not affect correctness of the foreground transaction processing at all.)

Fixes #34180

### CODE REVIEW

File: runtime/src/accounts_background_service.rs [hunk 1]
```diff
@@ -707,9 +707,21 @@ impl AccountsBackgroundService {
                             bank.force_flush_accounts_cache();
                             bank.clean_accounts(last_full_snapshot_slot);
                             last_cleaned_block_height = bank.block_height();
-                            bank.shrink_ancient_slots();
+                            // See justification below for why we skip 'shrink' here.
+                            if bank.is_startup_verification_complete() {
+                                bank.shrink_ancient_slots();
```
Comment (HaoranYi) [inline runtime/src/accounts_background_service.rs:712]: nit: Can we add a log when we skip shrink due to startup verification?

**Review by HaoranYi — APPROVED** [review]
lgtm

**Review by jeffwashington — APPROVED** [review]
lgtm. ty
