### PR TITLE
Cover tests for clippy

### LINKED ISSUE #9951: Clippy errors in the test suite
#### Problem

CI isn't running Clippy over the tests configuration. There are lots of good warnings there, such as unnecessary clones that may be slowing execution down, and float comparisons that might add instability.

Steps to reproduce:
1. `cargo clippy --tests`

#### Proposed Solution

Fix the warnings and errors. Once all fixed, enable the tests configuration (only) in CI.

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

tests are not covered under `clippy`

#### Summary of Changes

Do so!
Great thanks to @svenski123 for precedent works #10030 #10172

Fixes #9951

### CODE REVIEW

File: ci/test-checks.sh [hunk 1]
```diff
@@ -25,7 +25,7 @@ fi
 _ cargo +"$rust_stable" fmt --all -- --check
 
 _ cargo +"$rust_stable" clippy --version
-_ cargo +"$rust_stable" clippy --workspace -- --deny=warnings
+_ cargo +"$rust_stable" clippy --workspace --tests -- --deny=warnings
```
Comment (ryoqun) [inline ci/test-checks.sh:28]: @svenski123 Btw, I'd like to add `--all-targets` (this includes `--benches`), but currently I can't. Interested? :)

Comment (svenski123) [reply ci/test-checks.sh:28]: Have a look at #10445

**Comment by ryoqun** [comment]
This CI check is further enhanced by #10463 and #10464
