### PR TITLE
Make config_api more robust

### LINKED ISSUE #4973: config_api concerns
#### Problem
from #4970

* deserialize().unwrap() (crashes node)
* keyed_accounts[index] from a deserialized message (crashes node)
* the need to present config keys in the message in the same order as in the account data, which looks brittle
* if the account creator can say who has to sign to change the config, should we require that the account pubkey be forever among that set?

#### Proposed Solution
consider, address above

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
Config_api brittle in several ways

#### Summary of Changes
- Maps ConfigKeys deserialize() error to appropriate InstructionError
- Uses Vec::get() instead of index to prevent panic
- Makes `keyed_accounts[0].signer_key()` check contingent on no signer keys specified in account data

Fixes #4973

### CODE REVIEW

File: programs/config_api/src/config_processor.rs [hunk 1]
```diff
@@ -138,7 +150,7 @@ mod tests {
 
         let my_config = MyConfig::new(42);
 
-        let instruction = config_instruction::store(&config_pubkey, keys.clone(), &my_config);
+        let instruction = config_instruction::store(&config_pubkey, true, keys.clone(), &my_config);
```
Comment (rob-solana) [inline programs/config_api/src/config_processor.rs]: no way to add a signer or re-assign signers (only remove them back to the account keypair)?

if this mechanism is supposed to be present, can you describe the procedure?

if the mechanism is deliberately absent, what's the rationale?

Comment (CriesofCarrots) [reply programs/config_api/src/config_processor.rs]: @rob-solana , I don't understand your question. Are you asking about adding or re-assigning signers from the built Instruction?
Or adding/removing signers when updating the Config account data?
