### PR TITLE
Connect TPU's broadcast service with TVU's blob fetch stage

### LINKED ISSUE #2586: Edge perf testnet is broken
#### Problem
Perf testnet deployed from master branch does not stay up for more than a few minutes.

#### Proposed Solution
Debug and fix it.

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
The testnet is stopping within a few minutes of start.

#2468 change removed ledger writing from broadcast service. The ledger is only written in TVU now. However, the channel between broadcast service and TVU was not setup.
 
#### Summary of Changes
Expose the TVU channel (blob fetch receiver) to TPU's broadcast service.

Fixes #2586

### CODE REVIEW

File: tests/multinode.rs [hunk 1]
```diff
@@ -1734,9 +1735,14 @@ fn test_broadcast_last_tick() {
     let blob_fetch_stages: Vec<_> = listening_nodes
         .iter_mut()
         .map(|(_, _, node, _)| {
-            BlobFetchStage::new(
-                Arc::new(node.sockets.tvu.pop().unwrap()),
-                blob_receiver_exit.clone(),
+            let (blob_fetch_sender, blob_fetch_receiver) = channel();
```
Comment (mvines) [inline tests/multinode.rs]: Can this test be in-ignored?  Seems like it’s the only test that would be affected by this patch, which really means that it’s all untested (beyond running a full-blown testnet)

Comment (pgarg66) [reply tests/multinode.rs]: There are tests in TVU which should exercise this change, as BlobFetchStage is part of TVU.
I am not sure why this test is ignored. Maybe a separate PR to test/unignore it?

**Comment by garious** [comment]
Seems a little bizarre architecturally. Check out: https://github.com/solana-labs/solana/blob/master/book/art/fullnode.bob 

Does this PR remove that arrow that's going from TPU to Bank and add one from BroadcastService to TVU?  If so, that seems less desirable in that it'd mean sigverify and process_transactions has to be run twice for every transaction.

File: src/fullnode.rs [hunk 2]
```diff
@@ -314,6 +317,7 @@ impl Fullnode {
             tpu_sockets: node.sockets.tpu,
             broadcast_socket: node.sockets.broadcast,
             role_notifiers: (to_leader_receiver, to_validator_receiver),
+            blob_sender: Some(blob_sender),
```
Comment (carllin) [inline src/fullnode.rs]: Maybe this would be better owned by the Tvu struct? That way  the exit() function for tvu can take care of dropping this instead of fullnode having to drop it on exit

Comment (pgarg66) [reply src/fullnode.rs]: yes, but doesn't that require tvu::exit() to take a mutable reference to self? Same problem here as well, if we want to drop it in fullnode.

**Comment by pgarg66** [comment]
@garious , It doesn't remove the arrow from TPU to bank. The bank will run the transactions twice for now. I agree that it's not desirable. But this will get streamlined via bank forking PR.

**Comment by garious** [comment]
@pgarg66, the intent of @sagar-solana's PR was that the TPU would LBYL (Look Before You Leap), and not write anything to its Bank fork that the TVU can't use directly. I thought we had worked out how that should be possible and that the PR implemented it. Is it not possible until the forking PR is in?  Is all this churn a short-term band-aid that's going to slow us down when the forking PR is merged?

**Comment by garious** [comment]
By "all this churn", I just mean the architectural rewiring and its implications. The code changes are quite tiny. ;)

**Comment by pgarg66** [comment]
@garious my understanding is that this work was supposed to be part of Sagar's PR. Maybe we can wait for bank forking PR to be merged before fixing (if at all required) this.

However, the perf testnet on master will be broken till then.

**Comment by garious** [comment]
perf testnet on master being broken in the short-term is no problem. Whatever gets the forking bank PR stable and integrated needs to be the top priority. Any work outside that can assume the forking bank functionality exists.

File: src/fullnode.rs (hunk 2 above)
Comment (carllin) [reply src/fullnode.rs]: yea it does, so it would just move this chunk of logic surround the Option<BlobSender> into the tvu's exit function. The benefit of this is that the current fullnode's exit() will encapsulate the entire shutdown process without having special case logic here in the fullnode that's specific to the TVU. Right now that test is failing because some of the code in the codebase assumes that calling exit() on fullnode exits the tpu/tvu, when in fact with this change, only close() does that.

**Comment by rob-solana** [comment]
> Seems a little bizarre architecturally. Check out: https://github.com/solana-labs/solana/blob/master/book/art/fullnode.bob
> 
> Does this PR remove that arrow that's going from TPU to Bank and add one from BroadcastService to TVU? If so, that seems less desirable in that it'd mean sigverify and process_transactions has to be run twice for every transaction.

@garious this is the correct band-aid until we have a forking bank
