### PR TITLE
work on ledger

### LINKED ISSUE #910: Validator fails to attach to testnet-master
STR:
1. Install the latest snap: `sudo snap install solana --edge --devmode`
2. Configure the validator: `sudo snap set solana mode=validator leader-address=$(dig +short master.testnet.solana.com)`
3. Watch the validator log: `tail -f /var/snap/solana/current/validator/current -n200`

There may be a `thread 'main' panicked at 'process_ledger: AccountNotFound` panic.

Two parts to this issue:
* [x] Add the above STR to `ci/testnet-sanity.sh` to validate in automation
* [x] Fix

### PR DESCRIPTION
**Pull request by rob-solana**
* add some flushing to ledger to improve recovery times, which
       can be non-trivial with our large index BufWriter
* in non-snaps builds, move multinode-demo out of the source
        tree, to ~/.solana to help cargo

fixes #910

### CODE REVIEW

File: multinode-demo/common.sh [hunk 1]
```diff
@@ -188,10 +188,10 @@ oom_score_adj() {
   fi
 }
 
-SOLANA_CONFIG_DIR=${SNAP_DATA:-$PWD}/config
-SOLANA_CONFIG_PRIVATE_DIR=${SNAP_DATA:-$PWD}/config-private
-SOLANA_CONFIG_VALIDATOR_DIR=${SNAP_DATA:-$PWD}/config-validator
-SOLANA_CONFIG_CLIENT_DIR=${SNAP_USER_DATA:-$PWD}/config-client
+SOLANA_CONFIG_DIR=${SNAP_DATA:-~/.solana}/config
```
Comment (mvines) [inline multinode-demo/common.sh]: I'm not a fan of writing outside of the tree.  But if we do it then I think we need to generate a unique dir, perhaps with `mktemp`?  This as written will cause a collision when using multiple workspaces on the same machine

File: multinode-demo/validator.sh [hunk 2]
```diff
@@ -94,8 +94,7 @@ rsync_leader_url=$(rsync_url "$leader")
 tune_networking
 
 set -ex
-$rsync --append --verbose --partial --progress --recursive \
-  "$rsync_leader_url"/config/ "$SOLANA_LEADER_CONFIG_DIR"
+$rsync -vPr "$rsync_leader_url"/config/ "$SOLANA_LEADER_CONFIG_DIR"
```
Comment (mvines) [inline multinode-demo/validator.sh]: why not `--append`?

File: ci/testnet-sanity.sh [hunk 3]
```diff
@@ -44,4 +44,17 @@ else
   )
 fi
 
+echo "--- $NET_URL: validator sanity"
+sudo snap set solana mode=validator leader-address=$(dig +short $NET_URL)
```
[the remark this answers is not in the document]
Comment (mvines) [reply ci/testnet-sanity.sh]: Ok here's a different way to do the same but with the benefit of 
1. Keeps the leader running
2. Actually kills the validator when testnet-sanity.sh exits
3. Avoids the need to stand up a different agent to run this script.

```bash
$ export USE_SNAP=1
$ ./multinode-demo/setup.sh -t validator
$ set -e pipefail
$ timeout 10s ./multinode-demo/validator.sh $NET_URL 2>&1 | tee log
```

File: multinode-demo/validator.sh (hunk 2 above)
Comment (rob-solana) [reply multinode-demo/validator.sh]: I'm coming to the conclusion that --append and buffered I/O may interact poorly.

I haven't root-caused 910 yet, even after a day of mucking around.  I've seen leaders corrupt their own ledgers and validator.sh corrupting ledgers on restart, but  don't know how it could happen.

The ledger code does some pretty conservative recovery automatically, but this still isn't catching the issue.

File: multinode-demo/common.sh (hunk 1 above)
Comment (rob-solana) [reply multinode-demo/common.sh]: I can key the ~/.solana entry to a hash of the working tree to support multiple.  Fact is these scripts don't support multiple working trees as-is with the networking conflicts...

mktemp would require we somehow carry that info across the various scripts, which are already conveying too much.

File: ci/testnet-sanity.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (rob-solana) [reply ci/testnet-sanity.sh]: I didn't understand when this script runs or where, so this was a bit of a stab in the dark.  Thanks for the snippet.

File: multinode-demo/common.sh (hunk 1 above)
Comment (mvines) [reply multinode-demo/common.sh]: What's motivating ~/.solana?  This is essentially creating a global variable without any kind of synchronization and a memory leak.

Comment (rob-solana) [reply multinode-demo/common.sh]: cargo build times :-(

Comment (mvines) [reply multinode-demo/common.sh]: Yeah I was hoping we’d first get to the bottom of why this is even an issue first

Comment (mvines) [reply multinode-demo/common.sh]: I'd be ok with landing ~/.solana with the promise that we revert it as soon as we figure out why incremental `cargo build`s are busted

Comment (garious) [reply multinode-demo/common.sh]: And a promise comes in the form of an assigned github issue attached to a milestone before this PR is merged? :)
