### PR TITLE
Move long-running local-cluster tests to local-cluster-slow

### LINKED ISSUE #24940: Move long-running local-cluster tests to local-cluster-slow
#### Problem

Some local-cluster tests take a long time to run, which causes the CI local-cluster job to timeout and fail.

#### Proposed Solution

Move tests that take over 100 seconds to run to local-cluster-slow.

<details><summary>Test output, run 1</summary>

Here's the output after running the local-cluster tests on a beefy GCE instance

```
$ cargo +nightly test -- --test-threads=1 -Z unstable-options --report-time

test test_cluster_partition_1_1 ... ok <93.427s>
test test_cluster_partition_1_1_1 ... ok <113.526s>
test test_consistency_halt ... ok <193.465s>
test test_fail_entry_verification_leader ... ignored
test test_fake_shreds_broadcast_leader ... ignored
test test_forwarding ... ok <23.607s>
test test_future_tower_master_only ... ok <57.528s>
test test_future_tower_master_slave ... ok <43.377s>
test test_hard_fork_invalidates_tower ... ok <71.565s>
ok <49.089s>
ok <79.867s>
test test_leader_failure_4 ... ok <93.605s>
test test_ledger_cleanup_service ... ok <130.435s>
test test_local_cluster_signature_subscribe ... ok <18.192s>
test test_local_cluster_start_and_exit ... ok <13.560s>
test test_local_cluster_start_and_exit_with_config ... ok <13.398s>
test test_mainnet_beta_cluster_type ... ok <13.347s>
test test_no_voting ... ok <23.909s>
test test_optimistic_confirmation_violation_detection ... FAILED <86.896s>
test test_restart_node ... ok <56.186s>
test test_restart_tower_rollback ... ok <43.626s>
test test_run_test_load_program_accounts_partition_root ... ok <104.157s>
test test_run_test_load_program_accounts_root ... ok <78.192s>
test test_slot_hash_expiry ... ok <135.513s>
ok <53.838s>
test test_snapshot_restart_tower ... ok <53.391s>
test test_snapshots_blockstore_floor ... ok <40.545s>
test test_snapshots_restart_validity ... ok <81.038s>
test test_spend_and_verify_all_nodes_1 ... ok <13.747s>
test test_spend_and_verify_all_nodes_2 ... ok <23.784s>
test test_spend_and_verify_all_nodes_3 ... ok <28.570s>
test test_spend_and_verify_all_nodes_env_num_nodes ... ignored
test test_two_unbalanced_stakes ... ok <48.917s>
test test_validator_saves_tower ... ok <61.246s>
test test_votes_land_in_fork_during_long_partition ... ok <70.396s>
test test_wait_for_max_stake ... ok <38.357s>
```
I'm not sure why some lines just say `ok` without the test name in front...

</details>

<details><summary>Test output, run 2</summary>

```
running 36 tests
test test_cluster_partition_1_1 ... ok <56.925s>
test test_cluster_partition_1_1_1 ... ok <83.397s>
test test_consistency_halt ... ok <193.457s>
test test_fail_entry_verification_leader ... ignored
test test_fake_shreds_broadcast_leader ... ignored
test test_forwarding ... ok <23.403s>
test test_future_tower_master_only ... ok <57.705s>
test test_future_tower_master_slave ... ok <43.483s>
test test_hard_fork_invalidates_tower ... ok <71.616s>
ok <49.142s>
ok <70.644s>
test test_leader_failure_4 ... ok <93.563s>
test test_ledger_cleanup_service ... ok <130.468s>
test test_local_cluster_signature_subscribe ... ok <18.189s>
test test_local_cluster_start_and_exit ... ok <13.406s>
test test_local_cluster_start_and_exit_with_config ... ok <13.578s>
test test_mainnet_beta_cluster_type ... ok <13.375s>
test test_no_voting ... ok <23.841s>
test test_optimistic_confirmation_violation_detection ... FAILED <86.931s>
test test_restart_node ... ok <56.129s>
test test_restart_tower_rollback ... ok <43.751s>
test test_run_test_load_program_accounts_partition_root ... ok <104.428s>
test test_run_test_load_program_accounts_root ... ok <54.380s>
test test_slot_hash_expiry ... ok <135.276s>
ok <54.048s>
test test_snapshot_restart_tower ... ok <53.590s>
test test_snapshots_blockstore_floor ... ok <40.554s>
test test_snapshots_restart_validity ... ok <81.469s>
test test_spend_and_verify_all_nodes_1 ... ok <13.375s>
test test_spend_and_verify_all_nodes_2 ... ok <23.417s>
test test_spend_and_verify_all_nodes_3 ... ok <27.939s>
test test_spend_and_verify_all_nodes_env_num_nodes ... ignored
test test_two_unbalanced_stakes ... ok <48.843s>
test test_validator_saves_tower ... ok <61.269s>
test test_votes_land_in_fork_during_long_partition ... ok <67.147s>
test test_wait_for_max_stake ... ok <48.431s>
```

</details>

<details><summary>Test output, run 3 with nextest</summary>

```
$ cargo +nightly nextest run -j 1 --no-fail-fast
        PASS [  93.498s]        solana-local-cluster::local_cluster test_cluster_partition_1_1
        PASS [  63.453s]        solana-local-cluster::local_cluster test_cluster_partition_1_1_1
        PASS [ 193.527s]        solana-local-cluster::local_cluster test_consistency_halt
        PASS [  23.474s]        solana-local-cluster::local_cluster test_forwarding
        PASS [  57.694s]        solana-local-cluster::local_cluster test_future_tower_master_only
        PASS [  43.460s]        solana-local-cluster::local_cluster test_future_tower_master_slave
        PASS [  71.745s]        solana-local-cluster::local_cluster test_hard_fork_invalidates_tower
        PASS [  49.311s]        solana-local-cluster::local_cluster test_incremental_snapshot_download
        PASS [  71.211s]        solana-local-cluster::local_cluster test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup
        PASS [  93.571s]        solana-local-cluster::local_cluster test_leader_failure_4
        PASS [ 130.723s]        solana-local-cluster::local_cluster test_ledger_cleanup_service
        PASS [  18.368s]        solana-local-cluster::local_cluster test_local_cluster_signature_subscribe
        PASS [  13.539s]        solana-local-cluster::local_cluster test_local_cluster_start_and_exit
        PASS [  13.448s]        solana-local-cluster::local_cluster test_local_cluster_start_and_exit_with_config
        PASS [  13.393s]        solana-local-cluster::local_cluster test_mainnet_beta_cluster_type
        PASS [  23.921s]        solana-local-cluster::local_cluster test_no_voting
        PASS [  77.008s]        solana-local-cluster::local_cluster test_optimistic_confirmation_violation_detection
        PASS [  56.401s]        solana-local-cluster::local_cluster test_restart_node
        PASS [  43.466s]        solana-local-cluster::local_cluster test_restart_tower_rollback
        PASS [ 104.207s]        solana-local-cluster::local_cluster test_run_test_load_program_accounts_partition_root
        PASS [  48.181s]        solana-local-cluster::local_cluster test_run_test_load_program_accounts_root
        PASS [ 135.538s]        solana-local-cluster::local_cluster test_slot_hash_expiry
        PASS [  54.210s]        solana-local-cluster::local_cluster test_snapshot_download
        PASS [  53.465s]        solana-local-cluster::local_cluster test_snapshot_restart_tower
        PASS [  40.696s]        solana-local-cluster::local_cluster test_snapshots_blockstore_floor
        PASS [  80.734s]        solana-local-cluster::local_cluster test_snapshots_restart_validity
        PASS [  13.391s]        solana-local-cluster::local_cluster test_spend_and_verify_all_nodes_1
        PASS [  23.426s]        solana-local-cluster::local_cluster test_spend_and_verify_all_nodes_2
        PASS [  28.371s]        solana-local-cluster::local_cluster test_spend_and_verify_all_nodes_3
        PASS [  49.042s]        solana-local-cluster::local_cluster test_two_unbalanced_stakes
        PASS [  61.258s]        solana-local-cluster::local_cluster test_validator_saves_tower
        PASS [  70.724s]        solana-local-cluster::local_cluster test_votes_land_in_fork_during_long_partition
        PASS [  38.741s]        solana-local-cluster::local_cluster test_wait_for_max_stake
```

</details>

I propose moving the following tests:

- test_cluster_partition_1_1
- test_cluster_partition_1_1_1
- test_consistency_halt
- test_leader_failure_4
- test_ledger_cleanup_service
- test_slot_hash_expiry

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Some local-cluster tests take a long time to run, which causes the CI local-cluster job to timeout and fail.

#### Summary of Changes

1. Move tests to local-cluster-slow. Specifically these ones:

- test_cluster_partition_1_1
- test_cluster_partition_1_1_1
- test_consistency_halt
- test_leader_failure_4
- test_ledger_cleanup_service
- test_slot_hash_expiry

2. Split local-cluster-slow into two. The original is renamed to `-1`, and the tests listed above go into `-2`.

Fixes #24940

### CODE REVIEW

**Review by jstarry — APPROVED** [review]
I didn't review too closely, but at a high level this looks good!

**Comment by jstarry** [comment]
Worth backporting as well?

**Comment by brooksprumo** [comment]
> Worth backporting as well?

Maybe? I haven't done much backporting recently, so I'm not sure how good/bad the local-cluster CI is in v1.9/v1.10. I'll defer to the folks with that first-hand knowledge.

**Comment by jstarry** [comment]
I see timeouts on v1.10: https://buildkite.com/solana-labs/solana/builds?branch=v1.10 adding that one

File: ci/buildkite-pipeline.sh [hunk 1]
```diff
@@ -305,8 +305,12 @@ EOF
...
     10
 
-  command_step "local-cluster-slow" \
-    ". ci/rust-version.sh; ci/docker-run.sh \$\$rust_stable_docker_image ci/test-local-cluster-slow.sh" \
+  command_step "local-cluster-slow-1" \
+    ". ci/rust-version.sh; ci/docker-run.sh \$\$rust_stable_docker_image ci/test-local-cluster-slow-1.sh" \
+    40
+
+  command_step "local-cluster-slow-2" \
+    ". ci/rust-version.sh; ci/docker-run.sh \$\$rust_stable_docker_image ci/test-local-cluster-slow-2.sh" \
```
Comment (t-nelson) [inline ci/buildkite-pipeline.sh:313]: what was the motivation for splitting the job instead of just extending the first slow job?  This is going to consume an extra CI agent

Comment (brooksprumo) [reply ci/buildkite-pipeline.sh:313]: Trying to reduce the pain of having to retry a failed single big local-cluster-slow job. Typing that out makes me think maybe those tests should go into flakey instead. Want me to smoosh these back together into a single slow job?

Comment (t-nelson) [reply ci/buildkite-pipeline.sh:313]: I one would be better for CI.  Agreed that if a test needs retried for failure (not timeout) it should be in flaky.  If someone deflakes and it's still slow, it can go to slow

Comment (CriesofCarrots) [reply ci/buildkite-pipeline.sh:313]: I'm personally of the opinion that using more CI agents for shorter periods of time is better for development speed and progress. I know that setting up each job has a non-zero compute cost, but worth the trade off imho

**Comment by kerimsari** [comment]
Does that fix the problem. I got the latest master and these two tests are still failing for me? please see below

failures:

---- test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup stdout ----
thread 'test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Other, error: "send_transaction failed with error Error { request: None, kind: RpcError(RpcRequestError(\"cluster version query failed: error sending request for url (http://127.0.0.1:41546/): error trying to connect: tcp connect error: Can't assign requested address (os error 49)\")) }" })', local-cluster/tests/local_cluster.rs:1003:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_mainnet_beta_cluster_type stdout ----
thread 'test_mainnet_beta_cluster_type' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("RpcRequestError(\"cluster version query failed: error sending request for url (http://127.0.0.1:59390/): error trying to connect: tcp connect error: Can't assign requested address (os error 49)\")")', local-cluster/tests/local_cluster.rs:442:22


failures:
    test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup
    test_mainnet_beta_cluster_type

test result: FAILED. 24 passed; 2 failed; 5 ignored; 0 measured; 0 filtered out; finished in 1756.34s

error: test failed, to rerun pass `-p solana-local-cluster --test local_cluster`
