### PR TITLE
local-cluster: fix flaky optimistic_confirmation tests

### LINKED ISSUE #29221: fix local-cluster-flakey tests
#### Problem

Investigate and fix local_cluster_flakey tests

An example failure log
```
[2022-12-12T21:19:22.949402625Z INFO  local_cluster_flakey] Create validator
C's ledger [2022-12-12T21:19:22.992800408Z INFO  local_cluster_flakey] Create
validator A's ledger [2022-12-12T21:19:23.079169152Z INFO
local_cluster_flakey] Checking A's tower for a vote on slot descended from
slot `next_slot_on_a` [2022-12-12T21:19:23.098472257Z INFO
local_cluster_flakey] Removing tower! [2022-12-12T21:19:23.099375667Z INFO
local_cluster_flakey] Restart validator C again!!!
[2022-12-12T21:19:26.123293290Z INFO  local_cluster_flakey] collected
validator C's votes: {29, 30, 31, 32} [2022-12-12T21:19:26.123306395Z INFO
local_cluster_flakey] Restart validator A again!!!
[2022-12-12T21:19:26.633276484Z ERROR solana_core::validator] Rebuilding a new
tower from the latest vote account due to failed tower restore: IO Error: No
such file or directory (os error 2) [2022-12-12T21:19:38.035273429Z INFO
local_cluster_flakey] Observed A's votes on: [26, 26, 26, 26, 27, 27, 27, 27,
27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27] thread 'main'
panicked at 'Violation expected because of removed persisted tower!',
local-cluster/tests/local_cluster_flakey.rs:351:13 stack backtrace:    0:
rust_begin_unwind              at
/rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt              at
/rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
2:
local_cluster_flakey::do_test_optimistic_confirmation_violation_with_or_without_tower
3: serial_test::serial_code_lock::local_serial_core    4:
core::ops::function::FnOnce::call_once    5:
core::ops::function::FnOnce::call_once              at
/rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose
backtrace. FAILED  failures:  failures:
test_optimistic_confirmation_violation_without_tower
```

A rerun with sucess log
```
[2022-12-12T21:52:58.443640037Z INFO  local_cluster_flakey] Waiting on both
validators A and B to vote on fork at slot 27 [2022-12-12T21:53:13.269944257Z
INFO  local_cluster_flakey] Create validator C's ledger
[2022-12-12T21:53:13.390689919Z INFO  local_cluster_flakey] Create validator
A's ledger [2022-12-12T21:53:13.647698343Z INFO  local_cluster_flakey]
Checking A's tower for a vote on slot descended from slot `next_slot_on_a`
[2022-12-12T21:53:13.697183806Z INFO  local_cluster_flakey] Removing tower!
[2022-12-12T21:53:13.701354097Z INFO  local_cluster_flakey] Restart validator
C again!!! [2022-12-12T21:53:18.901249687Z INFO  local_cluster_flakey]
collected validator C's votes: {29, 30, 31, 32}
[2022-12-12T21:53:18.901300033Z INFO  local_cluster_flakey] Restart validator
A again!!! [2022-12-12T21:53:21.553643995Z ERROR solana_core::validator]
Rebuilding a new tower from the latest vote account due to failed tower
restore: IO Error: No such file or directory (os error 2)
[2022-12-12T21:53:22.179317214Z INFO  local_cluster_flakey] Observed A's votes
on: [26, 26, 26, 26, 30] [2022-12-12T21:53:22.179366507Z INFO
local_cluster_flakey] THIS TEST expected violations. And indeed, there was
some, because of removed persisted tower. test
test_optimistic_confirmation_violation_without_tower ... ok  test result: ok.
2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 111.31s
```

#### Proposed Solution

Debug and fix the failure to make the test robust

### PR DESCRIPTION
**Pull request by AshwinSekar**
#### Problem
* C can produce blocks before it is initially killed
* This could cause duplicate blocks on C's restart with purge
* This could also cause a block past the fork slot to get OC and repaired by A on restart 
* If A is slower to start than B, B could end up producing blocks in the second cycle of the leader schedule which might chain to C's leader slots / not be purged properly

#### Summary of Changes
Use a custom leader schedule such that C never produces blocks after restart and B only produces blocks up until the initial fork

Fixes #29221 #34102 #33669

### CODE REVIEW

**Comment by carllin** [comment]
> This could also cause a block past the fork slot to get OC and repaired by A on restart

This makes sense, we thought all these blocks were truncated from the ledger by the blockstore purge from all the validators after they're shut down: https://github.com/solana-labs/solana/blob/cb6d6cdf7c2acd485577ca31687a47e4e9f1cd14/local-cluster/tests/local_cluster.rs#L3297, but is the culprit  because validator `D` is still running and propagating the old version of the blocks from `C`?

File: local-cluster/tests/local_cluster.rs [hunk 1]
```diff
@@ -3336,17 +3343,36 @@ fn do_test_optimistic_confirmation_violation_with_or_without_tower(with_tower: b
...
+            votes_on_c_fork: {:?}",
+            base_slot,
+            elapsed.as_secs(),
+            last_vote,
+            votes_on_c_fork,
+        );
         sleep(Duration::from_millis(100));
 
-        if let Some((last_vote, _)) = last_vote_in_tower(&val_c_ledger_path, &validator_c_pubkey) {
+        if let Some((latest_vote, _)) = last_vote_in_tower(&val_c_ledger_path, &validator_c_pubkey)
```
Comment (carllin) [inline local-cluster/tests/local_cluster.rs:3373]: nit: `latest_vote -> newest_vote`

File: local-cluster/tests/local_cluster.rs [hunk 2]
```diff
@@ -3172,29 +3172,36 @@ fn do_test_optimistic_confirmation_violation_with_or_without_tower(with_tower: b
     // below only for slots <= `next_slot_on_a`, validator A will not know how it's last vote chains
     // to the other forks, and may violate switching proofs on restart.
     let mut default_config = ValidatorConfig::default_for_test();
-    // Split leader schedule 50-50 between validators B and C, don't give validator A any slots because
+    // Ensure B can make leader blocks up till the fork slot, and give remaining to C, don't give validator A any slots because
```
Comment (carllin) [inline local-cluster/tests/local_cluster.rs:3175]: nit: `and give the remaining blocks to C`

File: local-cluster/tests/local_cluster.rs [hunk 3]
```diff
@@ -3172,29 +3172,36 @@ fn do_test_optimistic_confirmation_violation_with_or_without_tower(with_tower: b
...
     // it's going to be deleting its ledger, so may create versions of slots it's already created, but
     // on a different fork.
     let validator_to_slots = vec![
         // Ensure validator b is leader for slots <= `next_slot_on_a`
         (validator_b_pubkey, next_slot_on_a as usize + 1),
-        (validator_c_pubkey, next_slot_on_a as usize + 1),
+        (validator_c_pubkey, DEFAULT_SLOTS_PER_EPOCH as usize),
     ];
+    // Trick C into not producing any blocks, in case it takes too long to kill it
```
Comment (carllin) [inline local-cluster/tests/local_cluster.rs:3183]: nit: `in case `C` takes a long time to kill`

**Review by carllin — DISMISSED** [review]
Good catch! Just some nits

**Review by carllin — APPROVED** [review]
