### PR TITLE
Fix race condition between shrinking and cleaning

### LINKED ISSUE #11232: Replay stage panicked on mainnet-beta API node
#### Problem

```
thread 'solana-replay-stage' panicked at 'called `Option::unwrap()` on a `None` value', runtime/src/accounts_db.rs:857:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86

  ...

  15: solana_runtime::accounts_db::AccountsDB::clean_accounts
  16: solana_ledger::snapshot_utils::add_snapshot
  17: solana_ledger::bank_forks::BankForks::generate_snapshot
  18: solana_ledger::bank_forks::BankForks::set_root
  19: solana_core::replay_stage::ReplayStage::new::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

log: https://drive.google.com/file/d/1zkxKc6QDoKm_myODIC03BS-Y6q20_cM6/view?usp=sharing

This node was running the v1.1.22 release

#### Proposed Solution

Triage and resolve

tag: @ryoqun @sakridge

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

Slot shrinking violates an assumption of account cleaning: stores of slots should generally be immutable once rooted, especially when doing the cleaning process.

So, `panic!` can be triggered intermittently if the background slot shrinking touches to-be-cleaned slots while the cleaning process is running and vice versa.

Note: this is a possible DOS attack vector.

#### Summary of Changes

Ensure not to run slot shrinking if account cleaning is in progress by holding shared lock (`shrink_candidate_slots`) from each processing with appropriate lifetime.

Fixes #11232

### CODE REVIEW

File: runtime/src/accounts_db.rs [hunk 1]
```diff
@@ -640,6 +642,11 @@ impl AccountsDB {
     // Only remove those accounts where the entire rooted history of the account
     // can be purged because there are no live append vecs in the ancestors
     pub fn clean_accounts(&self) {
+        // hold a lock to prevent slot shrinking from running because it might modify some rooted
+        // slot storages which can not happen as long as we're cleaning accounts because we're also
+        // modifying the rooted slot storages!
+        let mut candidates = self.shrink_candidate_slots.lock().unwrap();
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:648]: In the `master` branch, this lock can be regarded as being basically moved from here: https://github.com/solana-labs/solana/pull/11235/files#diff-2099c5256db4eb5975c8834af38f6456L563-L565

File: runtime/src/accounts_db.rs [hunk 2]
```diff
@@ -558,12 +558,14 @@ impl AccountsDB {
         inc_new_counter_info!("clean-old-root-reclaim-ms", measure.as_ms() as usize);
     }
 
-    fn reset_uncleaned_roots(&self) {
+    fn do_reset_uncleaned_roots(&self, candidates: &mut MutexGuard<Vec<Slot>>) {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:561]: take reference for `candidates` to outlive `do_reset_uncleaned_roots`.

File: runtime/src/accounts_db.rs [hunk 3]
```diff
@@ -977,11 +994,17 @@ impl AccountsDB {
 
     pub fn process_stale_slot(&self) -> usize {
         let mut measure = Measure::start("stale_slot_shrink-ms");
-        let count = if let Some(slot) = self.next_shrink_slot() {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:980]: `next_shrink_slot` is artifically moved inside `shrink_stale_slot` by passing `candidates` to indicate locked `candidates`'s intended lifetime as a code.

File: runtime/src/accounts_db.rs (hunk 1 above)
Comment (ryoqun) [reply runtime/src/accounts_db.rs:648]: Moving this line immediately before calling `do_reset_uncleaned_roots` below easily causes  `test_shrink_and_clean` failures

**Comment by ryoqun** [comment]
I've finished local testing!
