### PR TITLE
Fix issues with bench-tps

### LINKED ISSUE #3983: Bench tps causes many AccountNotFound errors
#### Problem

Bench tps doesn't verify that all the accounts it tries to fund actually got funded successfully. It then does repeated back and forth transfers using those account id's. Leading to thousands of AccountNotFound errors. 

#### Proposed Solution

Debug and fix why this is happening. There appear to be no transaction errors on the nodes. Yet the accounts don't exist when checked via rpc. 

Tag: @carllin @sakridge @pgarg66

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problems

1. Bench tps doesn't make sure all generated keys are actually funded and alive. Resulting in numerous account not found errors. 

2. Bench tps doesn't wait for transaction signatures and aggressively loops while trying to send new transactions with a new blockhash. Our blockhashes don't cycle fast enough and so it floods the network with duplicate transactions. 

#### Summary of Changes

- [X] Fix account not found errors by fixing how many keys are generated to make sure the minimum set of accounts we care about (--tx_count *  2) are always funded. 
- [X] Fix duplicate transactions by waiting for a new blockhash in the generate_txs loop. 

Thanks for all the help @pgarg66

Fixes #3983

### CODE REVIEW

**Comment by sagar-solana** [comment]
Side effect seems to be dramatically reduced memory consumption. But that isn't confirmed so didn't stick it in the description.

**Comment by sagar-solana** [comment]
@sakridge @jackcmay, I'm not familiar with the exchange enough to recognize what it can use from this PR, if anything.

**Comment by sagar-solana** [comment]
Here's a perf testnet run with the PR. 

https://metrics.solana.com:3000/d/U9-26Cqmk/testnet-monitor-cloud?panelId=53&orgId=2&var-testnet=testnet-dev-pgarg&var-hostid=All&from=1556242015070&to=1556242301290

There does appear to be a tps hit, but all the AccountNotFound and DuplicateSignatures (only ones visible are from gossiped votes) are gone. Our current guess as to why the tps takes a hit is that we're doing real work on each tx now instead of dropping them on the floor. Accounts seem to take some time too (~200ms peaks). This run also has an aggressive rpc poll for the next blockhash, which I removed in the latest commit.

@aeyakovenko @garious fyi.

**Comment by aeyakovenko** [comment]
@sagar-solana, can you add more ssds?

**Comment by sagar-solana** [comment]
@aeyakovenko This was @pgarg66's setup, so maybe. I see banking stage taking nearly the entire slot (700+ms consistently) even when the account squashes don't take too long. But since we've actually got all these accounts getting used now maybe locking is slowing us down?

**Comment by aeyakovenko** [comment]
@sagar-solana is the TPS hit due to the client not sending as many transactions, or taking longer to fund all the accounts?  can you add more clients?

**Comment by sagar-solana** [comment]
Maybe, I'll hunt for more perf tomorrow. But I think the leader is maxed out since it's banking stage is taking 700ms. 200ms from sigverify, 700ms from all banking threads I don't know how much we're leaving on the table. But yeah we can start more clients and see what happens. I'll first work on getting the PR green. We can hold off on merge till we better understand perf impact.

File: bench-tps/src/bench.rs [hunk 1]
```diff
@@ -144,13 +146,19 @@ pub fn do_bench_tps<T>(
         // this seems to be faster than trying to determine the balance of individual
         // accounts
         let len = tx_count as usize;
+        let mut new_blockhash = client.get_recent_blockhash().unwrap();
+        while new_blockhash == blockhash {
+            sleep(Duration::from_millis(100));
+            new_blockhash = client.get_recent_blockhash().unwrap();
```
Comment (sagar-solana) [inline bench-tps/src/bench.rs]: @pgarg66 I'm seeing this panic on testnet. Unsure what it's supposed to do if we can't get a recent blockhash lol

Comment (pgarg66) [reply bench-tps/src/bench.rs]: Let's debug it today.

**Comment by pgarg66** [comment]
It's a pain to add a second SSD thru scripts. Maybe we can try to add it manually just to test out the perf hit. It that solves the problem, I'll file an issue for v15.

**Comment by aeyakovenko** [comment]
@sagar-solana you would need to pass a variable of all the directories to be used for state storage that represent a different disk

File: bench-tps/src/bench.rs [hunk 2]
```diff
@@ -630,9 +641,13 @@ pub fn generate_keypairs(id: &Keypair, tx_count: usize) -> Vec<Keypair> {
 
     let mut total_keys = 0;
     let mut target = tx_count * 2;
-    while target > 0 {
+    while target > 1 {
         total_keys += target;
-        target /= MAX_SPENDS_PER_TX;
+        // Use the upper bound for this division otherwise it may not generate enough keys
+        target = match target.checked_rem(MAX_SPENDS_PER_TX) {
+            Some(0) => target / MAX_SPENDS_PER_TX,
```
Comment (sakridge) [inline bench-tps/src/bench.rs]: can you just do `(target + MAX_SPENDS_PER_TX + 1) / MAX_SPENDS_PER_TX`

File: bench-tps/src/bench.rs [hunk 3]
```diff
@@ -711,6 +727,22 @@ mod tests {
         let keypairs = generate_keypairs(&config.id, config.tx_count);
         fund_keys(&clients[0], &config.id, &keypairs, 20);
 
+        let exit = Arc::new(AtomicBool::new(false));
+        let exit1 = exit.clone();
+        // A thread to produce ticks so that the bank's blockhash keeps moving
+        let t_ticker = Builder::new()
```
Comment (sakridge) [inline bench-tps/src/bench.rs]: Maybe this should be part of BankClient.

File: bench-tps/src/main.rs [hunk 4]
```diff
@@ -77,6 +77,8 @@ fn main() {
         println!("adding more lamports {}", extra);
         fund_keys(&clients[0], &id, &keypairs, extra);
     }
+    // `generate_keypairs` generates more keys than we care about. filter down to tx_count * 2 for correct spends later
+    keypairs.truncate(2 * tx_count);
```
Comment (sakridge) [inline bench-tps/src/main.rs]: Why not just generate that many to begin with? Also, the above logic with looks at the last keypair and that keypair may be truncated here, so it doesn't seem right.

File: bench-tps/src/bench.rs (hunk 3 above)
Comment (sagar-solana) [reply bench-tps/src/bench.rs]: hm yeah I think that would be cleaner. I could just remove it altogether. It'll just do 1 batch of bench-tps and then exit. Which is no different from before since it would pretend to do more batches but all the rest would fail with duplicate sigs.

File: bench-tps/src/bench.rs [hunk 5]
```diff
@@ -134,23 +135,34 @@ pub fn do_bench_tps<T>(
...
+    let mut blockhash = Hash::default();
     while start.elapsed() < duration {
-        let balance = client.get_balance(&id.pubkey()).unwrap_or(0);
-        metrics_submit_lamport_balance(balance);
-
         // ping-pong between source and destination accounts for each loop iteration
         // this seems to be faster than trying to determine the balance of individual
         // accounts
         let len = tx_count as usize;
+        let new_blockhash = client.get_recent_blockhash().unwrap_or_default();
```
Comment (sakridge) [inline bench-tps/src/bench.rs]: Would `get_new_blockhash` here be any cleaner?

File: bench-tps/src/main.rs (hunk 4 above)
Comment (sagar-solana) [reply bench-tps/src/main.rs]: It does this trick thing to parallelize the funding of the tx_count * 2 accounts. We create enough sacrificial accounts to allow us to "fanout" the clients balance into all the accounts tx_count * 2 in parallel. 
Hard to explain without a diagram but we those "extra" keypairs are left empty and so we shouldn't be dealing with them once funding is done.

File: bench-tps/src/bench.rs (hunk 5 above)
Comment (sakridge) [reply bench-tps/src/bench.rs]: And seems like if we can't get a blockhash, just ignoring it with unwrap_or_default seems like the wrong thing to do.. either we cannot connect to the network to get a blockhash at all and we should just panic, or we do something like try to look at other nodes.

Comment (sagar-solana) [reply bench-tps/src/bench.rs]: Yes definitely! Thanks!

Comment (sagar-solana) [reply bench-tps/src/bench.rs]: The network has stalled but aside from notifying the user I don't know what else it can do. A panic here results in many many panics on testnet (keeps restarting the client).

Comment (sagar-solana) [reply bench-tps/src/bench.rs]: I guess `get_new_blockhash` will panic so it'll be fatal when I switch to that

File: bench-tps/src/main.rs (hunk 4 above)
Comment (sakridge) [reply bench-tps/src/main.rs]: ok. maybe keypair0_balance should be then `keypairs[tx_count * 2 - 1]` and update the comment to say last keypair and update this comment to say 'generate_keypairs' generates extra keys to be able to have size-aligned funding batches for `fund_keys`.

File: bench-tps/src/bench.rs (hunk 2 above)
Comment (sagar-solana) [reply bench-tps/src/bench.rs]: yup this should work.

File: bench-tps/src/bench.rs (hunk 5 above)
Comment (sakridge) [reply bench-tps/src/bench.rs]: Well, need to figure out the source of not being able to fetch it. If it's just not waiting long enough, then maybe the timeout should be increased. Maybe we should try switching to another node.

Comment (sagar-solana) [reply bench-tps/src/bench.rs]: I see what you mean. Yeah it's waiting plenty long but the network just stalls completely some times. Switching to another node might work but in our current testnets this should _never_ happen.

**Comment by sakridge** [comment]
> There does appear to be a tps hit, but all the AccountNotFound and DuplicateSignatures (only ones visible are from gossiped votes) are gone. Our current guess as to why the tps takes a hit is that we're doing real work on each tx now instead of dropping them on the floor(errors count towards tps too). Accounts seem to take some time too (~200ms peaks).

Errors shouldn't count toward TPS, right?
```
        for (r, tx) in executed.iter().zip(txs.iter()) {
            if r.is_ok() {
                tx_count += 1;

        self.increment_transaction_count(tx_count);
        inc_new_counter_info!("bank-process_transactions-txs", tx_count);
```

https://github.com/solana-labs/solana/blob/3e678511d2bb1155163898ef574cdfeccb57ffd1/runtime/src/bank.rs#L667

**Comment by sagar-solana** [comment]
@sakridge the banking stage counter which reports to the dashboard doesn't check tx results.

**Comment by jackcmay** [comment]
@sagar-solana Which counter is used to calculate TPS?  From a quick look, it appears that the reported number of transactions by the banking_stage is the number of transactions sent to the bank, whether or not they resulted in errors or not

**Comment by sagar-solana** [comment]
Yeah that's the one. Which is why I was saying errors count towards tps. (which is fair-ish imo since the leader spent time on them)

**Comment by sakridge** [comment]
Ah, that's right, it is the banking_stage one for the TPS counter. We should have the bank one on the dashboard somewhere though.

**Comment by sagar-solana** [comment]
@sakridge, we used to but that thing was waay over estimating since every node repeats each tx and so we'd see a tps proportional to num nodes.

**Comment by jackcmay** [comment]
@Sagar does the banking_stage counter use increment_transaction_count?

**Comment by sagar-solana** [comment]
@jackcmay here's the counter https://github.com/solana-labs/solana/blob/9c7ccc0e2b0cc24ad27674d73d65a0db3fb8eacf/core/src/banking_stage.rs#L612. It inc's the metric counter by `new_tx_count` every time. `new_tx_count` is the total of all txs that were given to a bank in a particular pass of the banking_stage thread
