### PR TITLE
accounts_clean: Convert stack dependency calculation with iterative

### LINKED ISSUE #11066: TdS crash from bench-tps 1.2.10
#### Problem
```
thread 'solana-accounts-background' has overflowed its stack
```

#### Proposed Solution

fix it

tag: @ryoqun @sakridge @carllin

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Stack overflow with large number of store dependencies.

#### Summary of Changes

Convert to clean dependency checking to iterative algorithm.

This also improves performance from ~400ms for a 10,000 account dependency chain to ~10ms from the `store_id => hashset<pubkey>` reverse lookup it creates instead of re-creating the affected key set for each store id.

Fixes #11066

### CODE REVIEW

File: runtime/src/accounts_db.rs [hunk 1]
```diff
@@ -611,21 +579,37 @@ impl AccountsDB {
...
             if no_delete {
+                let mut pending_store_ids: HashSet<usize> = HashSet::new();
                 for (_slot_id, account_info) in account_infos {
-                    Self::inc_store_counts(
-                        account_info.store_id,
-                        &purges,
-                        store_counts,
-                        &mut already_counted,
-                    );
+                    if !already_counted.contains(&account_info.store_id) {
```
Comment (carllin) [inline runtime/src/accounts_db.rs:592]: Is this `already_counted` still necessary? Seems like all stores in `pending_store_ids` will be unique/only processed once

Comment (sakridge) [reply runtime/src/accounts_db.rs:592]: I think it's needed. Even with the case where you have two accounts depend on the same slot, they will enqueue each other forever if it's not checked.

Comment (carllin) [reply runtime/src/accounts_db.rs:592]: nvm, i see it's necessary for line 608
