### PR TITLE
Remove needless last_root for better reclaims

### LINKED ISSUE #8130: 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:462:9
It looks like the bootstrap leader on TdS is serving up a bad snapshot:
```
$ solana-validator -l ledger -n 35.230.25.59:8001 -o - --expected-shred-version 16135
.
.
.
[2020-02-05T16:29:45.572013797Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=615i
thread 'main' panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:462:9
```

Steps to reproduce on the 0.23.2 release:
1. Fetch and extract bad-snapshot.tgz from https://drive.google.com/drive/folders/1bBteuyTDRWDbCXhf-IgaTVog28teAjYn?usp=sharing
2. Run `solana-validator --ledger bad-snapshot/ -o -`

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

last_root wasn't correctly restored from snapshot and its related range check is bad for `purge_zero_lamport_account`, which ultimately causes dangling storage entries some times when restoring from snapshot.

(a lot of original investigation report for #8130 is moved to new PR: #8176)

#### Summary of changes

After careful code scrutinization, I'm pretty sure the `last_root` thing can go away.

Just remove `last_root`

#### Background

I found this as part of investigation for #8130.

Part of #7167.

### CODE REVIEW

**Comment by sakridge** [comment]
Seems right to me.

**Comment by ryoqun** [comment]
Sad status report: It seems the description is wrong. I can't create a valid test demonstrating the described error condition... And I cannot find another alternative bad scenario at the moment....

This bug is hard. ;)

File: runtime/src/accounts_db.rs [hunk 1]
```diff
@@ -1156,9 +1153,7 @@ impl AccountsDB {
         dead_slots
     }
 
-    fn cleanup_dead_slots(&self, dead_slots: &mut HashSet<Slot>, last_root: u64) {
-        // a slot is not totally dead until it is older than the root
-        dead_slots.retain(|slot| *slot < last_root);
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: I just realized all inputs of this function is ensured to be older or equal to `last_root`.

Notice the `or equal to` part, this assertion must be `*slot <= last_root` for `purge_zero_lamport_accounts`. But, we don't need this to begin with, as said above.

File: runtime/src/accounts_index.rs [hunk 2]
```diff
@@ -161,11 +154,6 @@ impl<T: Clone> AccountsIndex<T> {
     }
 
     pub fn add_root(&mut self, slot: Slot) {
-        assert!(
-            (self.last_root == 0 && slot == 0) || (slot >= self.last_root),
```
Comment (ryoqun) [inline runtime/src/accounts_index.rs]: I think removing this assertion is ok to remove `last_root`, first of all.

File: runtime/src/accounts_db.rs (hunk 1 above)
Comment (sakridge) [reply runtime/src/accounts_db.rs]: sorry, why are they guaranteed to be older than last_root?

Comment (ryoqun) [reply runtime/src/accounts_db.rs]: I can explain this by reading the code from here upwards the call graph.

Firstly, this [`cleanup_dead_slots(dead_slots, last_root)`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L1159) is only called from [`handle_reclaims(reclaims)`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L689).
`dead_slots` are derived from `reclaims` by calling [`remove_dead_accounts()`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L1127) inside `handle_reclaims()`, which does just simple 1-to-1 storage -> slot mapping. Thus, we just need to explain in terms of `reclaims` further on.

`handle_reclaims()` are called only from `purge_zero_lamport_accounts()`(1) and `store_with_hashes()` (2). These are the only 2 code paths reaching to this function.

(1) For the [`purge_zero_lamport_accounts()`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L623) cod epath, reasoning is simple:

The `reclaims` is a [collection](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L671) of  results of [`accounts_index.purge(&pubkey)`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L667), which in turn the sum of [`get_rooted_entries()`](https://github.com/solana-labs/solana/pull/8148/files#diff-ef68c28d9d63e66355c44904d9877825L50) for all such zero lamport `pubkey`s. So, `reclaims` (thus, `dead_slots`) are always rooted slots only. This is true for normal operation because the validator calls [`add_root()`](https://github.com/solana-labs/solana/pull/8148/files#diff-ef68c28d9d63e66355c44904d9877825L163) as it roots slots.

Also this is also true for snapshot restoration because [`generate_index()`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L1263) is called before `purge_zero_lamport_accounts()` and `generate_index()` does [`accounts_index.roots.insert(*slot_id)`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L1292).

(2) For the `store_with_hashes()`, reasoning is a bit longer:

The `reclaims` is ultimately only generated at [`accounts_index.update()`](https://github.com/solana-labs/solana/pull/8148/files#diff-ef68c28d9d63e66355c44904d9877825L111). There is intermediately `fn`s like [`accounts_db.update_index()`](https://github.com/solana-labs/solana/pull/8148/files#diff-2099c5256db4eb5975c8834af38f6456L1095) and[ `accounts_index.insert()`](https://github.com/solana-labs/solana/pull/8148/files#diff-ef68c28d9d63e66355c44904d9877825L93), but the destination of this call graph is same.

Next, `accounts_index.update(slot, ...)` creates `reclaims` by concatenating two sets:
A: [`can_purge`-able (= `slot` < `max_root`) entries](https://github.com/solana-labs/solana/pull/8148/files#diff-ef68c28d9d63e66355c44904d9877825L130-L134)
B: [Old entries in `slot` by replacing with updated one](https://github.com/solana-labs/solana/pull/8148/files#diff-ef68c28d9d63e66355c44904d9877825L122)

A is obviously fine because `max_root` is always member of `accounts_index.roots`. B is ensured not to be `dead` at `remove_dead_accounts()` because the case B is always inserting an updated latest entry into the `slot`.

So, as a normal operation, `cleanup_dead_slots()` never removes anything such that `last_root > slot`.

And leaving `retain` causes halfway-deallocated state because `cleanup_dead_slots()` is only called once ever for each given slot. That's because later invocations of `remove_dead_accounts()` would remove any slots whose storage are already removed.

Thanks for reading a rather long comment. :)
 
So I think this `retain` does add little value and complicates code reading with seemingly overlapping and spread responsibility for ensuring `purge`-able slots at caller-site or at callee-site.

As a second thought, if you're a bit concerned for future changes that might break these assumptions, this PR can be changed to `assert!` that.

Comment (sakridge) [reply runtime/src/accounts_db.rs]: Ok. Thanks for the description. I think it can be removed.

**Comment by ryoqun** [comment]
Removing the `v0.23` label, as this is not strictly fix for #8130.

**Comment by ryoqun** [comment]
@sakridge Thanks for checking this! I've just merged!

**Comment by ryoqun** [comment]
This is needed for #8436.
