### PR TITLE
Move notifications after store_accounts

### LINKED ISSUE #1529: Bank notifications sent too early
Problem:

If the last instruction fails in a single transaction, notifications from earlier successful transactions will have already been sent.

Proposed solution:

Move notifications until *at least* all instructions have been successfully executed. After `store_accounts()` would probably be better, so that the bank can reject malicious writes to userdata.

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
Bank notifications were being sent too early, before all instructions in a transaction had been successfully executed.

#### Summary of Changes
Moves notification handling on of `execute_instruction` into `execute_and_commit_transaction`, with actual notifications following `store_accounts()`

Fixes #1529

### CODE REVIEW

File: src/bank.rs [hunk 1]
```diff
@@ -1011,6 +1019,18 @@ impl Bank {
         let execution_elapsed = now.elapsed();
         let now = Instant::now();
         self.store_accounts(txs, &executed, &loaded_accounts);
+
+        // Send notifications
+        {
+            let accounts = self.accounts.read().unwrap();
```
Comment (rob-solana) [inline src/bank.rs]: would it be harmful to just always send the resulting value, i.e. assume the transaction caused a change?

Comment (rob-solana) [reply src/bank.rs]: one reason I can think of for doing the simplest thing here is that rollbacks cause the same notifications, and we're not doing any diffing in that code

Comment (rob-solana) [reply src/bank.rs]: finally, do we have a test for the "don't notify unless changed" case?

**Comment by garious** [comment]
How about moving both those chunks of code into separate functions so that we can painlessly move them around as needed by the new rollback functionality?

File: src/bank.rs (hunk 1 above)
Comment (CriesofCarrots) [reply src/bank.rs]: I've been meaning to check in with @mvines on this one: what do you think about notifying on the assumption that the transaction caused a change?
It would certainly make the code a lot simpler.

Comment (mvines) [reply src/bank.rs]: A rollback event I think should be signaled differently regardless: "You've just been wormholed to a different universe, you may not even exist here. Cold reboot the front-end."

The proposal is to notify on all accounts that a transaction instruction *could* have written to, even if it didnt?  This won't break any of our existing demos (and if so good, because they're buggy and we should fix), so beyond unnecessary notifications that perhaps we can optimize away elsewhere I don't see any issue with removing the diffing.

**Comment by garious** [comment]
Is more work needed here? Merging this would allow me to move `execute_instruction()` out of the bank, which I want to do for the markdown book.

**Comment by CriesofCarrots** [comment]
I think it’s ready. @rob-solana , any other thoughts?
