### PR TITLE
bench-tps: Avoid accidential tx_count mismatches when using an accounts file

### LINKED ISSUE #6050: solana-bench-tps panicks at high tx_count values
#### Problem

`solana-bench-tps` panicks at higher tx_count values.  The below error is seen when `tx_count` is set above 10922.  100% reproducible on a GCE testnet with 25 GPU nodes on `02647c25`

```
solana@testnet-dev-dan-client:~$ RUST_BACKTRACE=full .cargo/bin/solana-bench-tps --entrypoint 10.138.0.9:8001 --drone 10.138.0.9:9900 --duration 7500 --sustained --thread-batch-sleep-ms 1000 --read-client-keys solana/client-accounts.yml --threads 4 --tx_count 50000
Connecting to the cluster
[2019-09-24T16:29:02.604583435Z INFO  solana_core::gossip_service] Gossip entry point: V4(10.138.0.9:8001)
[2019-09-24T16:29:02.604601403Z INFO  solana_core::gossip_service] Spy node id: 5pEHfuYFe3Lqei5irgC7e4e3zXqPnMtndUmYeQuFDbPV
[2019-09-24T16:29:02.604622784Z INFO  solana_core::gossip_service] discovering...
 Node contact info             | Age     | Node identifier
-------------------------------+---------+-----------------------------------
- gossip: none                 |     0ms | 5pEHfuYFe3Lqei5irgC7e4e3zXqPnMtndUmYeQuFDbPV (me)
  tpu:    none                 |         |
  rpc:    none                 |         |
Nodes: 0
Spies: 1
[2019-09-24T16:29:02.708138195Z INFO  solana_core::gossip_service] discover success in 0s...
 Node contact info             | Age     | Node identifier
-------------------------------+---------+-----------------------------------
- gossip: none                 |   104ms | 5pEHfuYFe3Lqei5irgC7e4e3zXqPnMtndUmYeQuFDbPV (me)
  tpu:    none                 |         |
  rpc:    none                 |         |
- gossip: 10.138.0.108:8001    |   101ms | 5ru6YTGatkeTasgU3hxNgo92FP8MHZqpJ7dtBs8Qq1wY
  tpu:    10.138.0.108:8701    |         |
  rpc:    10.138.0.108:8899    |         |
- gossip: 10.138.0.117:8001    |     1ms | 8NUy9DaFKfSyVfM2Hq4RCWp2p3Ko37JaLnobm8EdakC7
  tpu:    10.138.0.117:9361    |         |
  rpc:    10.138.0.117:8899    |         |
- gossip: 10.138.0.116:8001    |     1ms | kG9JNkSnyDgyMzVSmDAF42BK27rKviUsLtS3bRb6wZm
  tpu:    10.138.0.116:8547    |         |
  rpc:    10.138.0.116:8899    |         |
- gossip: 10.138.0.109:8001    |   100ms | nHjzLFAbEfz1TXDd1aQ3CTTgdys7wXpSqVMrPwskbf3
  tpu:    10.138.0.109:9988    |         |
  rpc:    10.138.0.109:8899    |         |
- gossip: 10.138.0.37:8001     |     1ms | 4hdwQ73vBWAXC66P2zsCgTsXLaoVxmrZyHpqFkmybnSH
  tpu:    10.138.0.37:8812     |         |
  rpc:    10.138.0.37:8899     |         |
- gossip: 10.138.0.46:8001     |    96ms | EQyYbWai3khHADzPaQ9pJFddonFvUPT5MZ37pKK9VMcP
  tpu:    10.138.0.46:9796     |         |
  rpc:    10.138.0.46:8899     |         |
- gossip: 10.138.0.10:8001     |    99ms | 2YwakNQaNuRDt3bFdrx3zoGreA8Faog8AJKsmvRfBQu8
  tpu:    10.138.0.10:9301     |         |
  rpc:    10.138.0.10:8899     |         |
- gossip: 10.138.0.110:8001    |     1ms | AQYyMVq2d6iuYit776vh2tfdJpza888sUerPTLvJ77m1
  tpu:    10.138.0.110:9356    |         |
  rpc:    10.138.0.110:8899    |         |
- gossip: 10.138.0.107:8001    |    99ms | 583E2xcx5C6qF1EqojwVs4zPFbUT3axDrQxcdtVQUZyE
  tpu:    10.138.0.107:9380    |         |
  rpc:    10.138.0.107:8899    |         |
- gossip: 10.138.0.112:8001    |     1ms | 2psezFj2R8t1rJSawaZ5azLvpo4hgDU2eRuiuD6tCqr5
  tpu:    10.138.0.112:9276    |         |
  rpc:    10.138.0.112:8899    |         |
- gossip: 10.138.0.79:8001     |    98ms | 7qALFF2zDect9CgDmRW7QSafLT54jRNWA19a9ofqScwz
  tpu:    10.138.0.79:9730     |         |
  rpc:    10.138.0.79:8899     |         |
- gossip: 10.138.0.55:8001     |     1ms | 8eNqmqzEyYWcLAchV43jM6aaonKgErEogzNXnn5LgD51
  tpu:    10.138.0.55:8368     |         |
  rpc:    10.138.0.55:8899     |         |
- gossip: 10.138.0.113:8001    |    98ms | ANu8WBJfLznEEjSDEBY8Dzk7Jts413YfxMDMYkQBdPcz
  tpu:    10.138.0.113:8976    |         |
  rpc:    10.138.0.113:8899    |         |
- gossip: 10.138.0.106:8001    |    98ms | Cncwok7Wua1RRkR1BtBbLg5ctNgdvhDm6sNLqi21Pbby
  tpu:    10.138.0.106:9967    |         |
  rpc:    10.138.0.106:8899    |         |
- gossip: 10.138.0.118:8001    |    97ms | 8sxzuEqtGdtSmFCDJf1yZv6TQFuzqLZmHekHc1wE4iuX
  tpu:    10.138.0.118:9976    |         |
  rpc:    10.138.0.118:8899    |         |
- gossip: 10.138.0.111:8001    |    97ms | 2c7hMb2Ue8hDqRCNWdWbXHgbZq7MTjiPo9fWrsipKkjr
  tpu:    10.138.0.111:9565    |         |
  rpc:    10.138.0.111:8899    |         |
- gossip: 10.138.0.61:8001     |    97ms | 5FKKzJERgpwJF93ofw2rLPusmNDxroWHS9BY5e7XywZ5
  tpu:    10.138.0.61:8497     |         |
  rpc:    10.138.0.61:8899     |         |
- gossip: 10.138.0.105:8001    |     1ms | Fzrvd1YSvck6U39BRrrmct9pnpWYUAV1GoPie1Ffw21i
  tpu:    10.138.0.105:8198    |         |
  rpc:    10.138.0.105:8899    |         |
- gossip: 10.138.0.50:8001     |     1ms | Ek8bp6hSoyxPaRowdiGak4cZ4wa6DnJUZJGG4SEDdwyS
  tpu:    10.138.0.50:9249     |         |
  rpc:    10.138.0.50:8899     |         |
- gossip: 10.138.0.9:8001      |    96ms | Aw2D8JxnzAbKj5uKTvthDSK5w5NXbhXeL2PME5EWvUnZ
  tpu:    10.138.0.9:9121      |         |
  rpc:    10.138.0.9:8899      |         |
Nodes: 20
Spies: 1
thread 'main' panicked at 'slice index starts at 18446744073709473460 but ends at 21844', src/libcore/slice/mod.rs:2561:5
stack backtrace:
   0:     0x555f1ad0f3cb - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x555f1ad0f3cb - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x555f1ad0f3cb - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x555f1ad0f3cb - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x555f1ad0f3cb - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x555f1ad0f0a7 - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:214
   6:     0x555f1abce9ae - solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}::hc3380571e5f26d36
   7:     0x555f1ad0fc29 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:481
   8:     0x555f1ad0f6c2 - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                               at src/libstd/panicking.rs:384
   9:     0x555f1ad0f5a6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
  10:     0x555f1ad30d5d - core::panicking::panic_fmt::h2daf88b2616ca2b2
                               at src/libcore/panicking.rs:85
  11:     0x555f1ad31326 - core::slice::slice_index_order_fail::ha75fa70416d3bc2f
                               at src/libcore/slice/mod.rs:2561
  12:     0x555f1a67ac8c - solana_bench_tps::bench::do_bench_tps::hffff14a3abc09b70
  13:     0x555f1a65ff5d - solana_bench_tps::main::h94979b9e3118bb05
  14:     0x555f1a648783 - std::rt::lang_start::{{closure}}::hdde01238b98cd048
  15:     0x555f1ad0f543 - std::rt::lang_start_internal::{{closure}}::h447d8812e3ee306d
                               at src/libstd/rt.rs:49
  16:     0x555f1ad0f543 - std::panicking::try::do_call::h4a61cb372364c745
                               at src/libstd/panicking.rs:296
  17:     0x555f1ad1841a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  18:     0x555f1ad1010d - std::panicking::try::hdf71f938885bca42
                               at src/libstd/panicking.rs:275
  19:     0x555f1ad1010d - std::panic::catch_unwind::h7e85dbf162b1611a
                               at src/libstd/panic.rs:394
  20:     0x555f1ad1010d - std::rt::lang_start_internal::h1e06cc26b9fc25ea
                               at src/libstd/rt.rs:48
  21:     0x555f1a661e92 - main
  22:     0x7f2ff3e51b97 - __libc_start_main
  23:     0x555f1a64297a - _start
  24:                0x0 - <unknown>
[2019-09-24T16:29:04.372495095Z INFO  solana_metrics::metrics] metrics disabled: SOLANA_METRICS_CONFIG: environment variable not found
[2019-09-24T16:29:04.372643502Z ERROR solana_metrics::metrics] datapoint: panic program="bench-tps" thread="main" one=1i message="panicked at 'slice index starts at 18446744073709473460 but ends at 21844', src/libcore/slice/mod.rs:2561:5" location="src/libcore/slice/mod.rs:2561:5"
```

### PR DESCRIPTION
**Pull request by mvines**
Fixes #6050

### CODE REVIEW

File: bench-tps/src/main.rs [hunk 1]
```diff
@@ -96,6 +99,16 @@ fn main() {
...
             });
+
+        if keypairs.len() != tx_count * 2 {
+            eprintln!(
+                "Expected {} accounts in {}, only received {} (--tx_count mismatch?)",
+                tx_count * 2,
+                client_ids_and_stake_file,
+                keypairs.len(),
+            );
+            exit(1);
```
Comment (sakridge) [inline bench-tps/src/main.rs]: Should we bail or just warn? Because as @danpaul000 noted it does work in some cases even with a mismatch.

Comment (mvines) [reply bench-tps/src/main.rs]: I went for bail cause I didn't want to bother thinking about under what conditions it would succeed, maybe if the tx_count ls lower?  But in all cases this seems like a misuse by the user and it's better they know right away they're doing something not really supported

Comment (sakridge) [reply bench-tps/src/main.rs]: Don't need to think about it, just 
```
if tx_count != expected_tx_count {
    warn!("Mismatched tx_count detected. User, you are on your own. \
             Hope you know what you're doing.");
}
```
But I can see how that might not be super visible in warning someone when dealing with a multi-machine network full of logs.

Comment (mvines) [reply bench-tps/src/main.rs]: Yeah I see your point.  Both of them :)
Imma leave it as is.  If somebody is bothered by the excessive hand-holding, they're always welcome to send another PR
