### PR TITLE
change blocktree*::storage_size() to return Option<u64> to handle live fs changes

### LINKED ISSUE #7389: Ledger Cleanup thread crashes when reading directory size
#### Problem

STR: 
1- Ran a testnet with 5 validators and 2 clients pushing 10000 tx_count with 250ms sleep with `--limit-ledger-size` enabled and its num_slots set to 1192 slots (also updated `pub const DEFAULT_DEV_SLOTS_PER_EPOCH: u64 = 1192;
`)
2- After about 15 mins some nodes' limit ledger size threads crashed

```
solana-ledger-cleanup | panicked at 'failure while reading ledger directory size: Error { kind: NotFound, message: "entity not found" }', src/libcore/result.rs:1165:5
```

### PR DESCRIPTION
**Pull request by sunnygleason**
#### Problem

* ledger cleanup thread panics when reading file system directory size (see #7389)

#### Summary of Changes

* modify `blocktree*::storage_size()` to return `Option<u64>` instead of "`u64` via  `expect()`"

Fixes #7389

### CODE REVIEW

File: ledger/src/blocktree_db.rs [hunk 1]
```diff
@@ -580,8 +580,8 @@ impl Database {
         self.backend.write(batch.write_batch)
     }
 
-    pub fn storage_size(&self) -> u64 {
-        get_size(&self.path).expect("failure while reading ledger directory size")
+    pub fn storage_size(&self) -> Option<u64> {
```
Comment (sagar-solana) [inline ledger/src/blocktree_db.rs]: Might be nice to have a comment here as to why it's an option. Feel free to do it in a followup

Comment (garious) [reply ledger/src/blocktree_db.rs]: Seems like returning the Result would be self-documenting

Comment (sunnygleason) [reply ledger/src/blocktree_db.rs]: oops didn't see this, will touch the code up along these lines
