### PR TITLE
Fix accounts indexing

### LINKED ISSUE #9817: Transaction account index out of bounds
#### Problem

Sending this transaction crashes the recipient validator:

```
Transaction { signatures: [2mLnk7gnYyA16csWPeR2EMMqzat4oBmpDp3XGDeLwGitSU4XakAr58DK9kFYx3bCDHLbB7cwfQrAeWQ5Cs69DCc8], message: Message { header: MessageHeader {
 num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 3 }, account_keys: [4xiPEuAwnFWkH1Q2LmrwCCZd5Y5278B9cde6NhAs5Zgx, AiUH1Lgj433NsSNDvzPusAkkRqnrxQfJWZcGKXQAGJwq, SysvarS1otHashes111111111111111
111111111111, SysvarC1ock11111111111111111111111111111111, Vote111111111111111111111111111111111111111, 4SSgv5jfR66ptc434Ezk3d55FRa2Wki4Us5C8Ssbu8ky, 7MwUEw8E1eRQ84GBz6brQHaQQbgNM2jbAJQzUdk6gKz1, BTkHhB3YFKL5ouvdcXcfLTSUMzTyjB3TzY5f3uwWi
zK6, Du6oEMBQf1yc9WxPngPf2KxNk1N1Sj76Baq3ct1RJoGg, BVW3FsdVPzece7XK4RNxCz6hpsDNQGqcADa1QPE631g, 3HwcSRADs6FxdmZHuD2o2qb1AoBFr7f4G6U9AjKmDEvL, 2WvPJZVbNK3XPMxG6D4B2gVHQJcximP5bgP6n5rn5PJJ, C1foYm87pLuP4Fx5AScX5YvzeMPX4sbLY9KUSjiMd5oz, 71m
F584RPGXRECZarVCSdsyiA4sW4e79kB5vZZZjFtG6, 54ZxZL897bqacq2nhBgLhhTg84uzGbazqmr1ZjbGyYpN], recent_blockhash: 65cuWiNwcqmvda8x37qwyud5k9xj3ehtE5568GonDa62, instructions: [CompiledInstruction { program_id_index: 4, accounts: [14, 2, 3, 0], 
data: [2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 33, 210, 0, 0, 0, 0, 0, 0, 34, 210, 0, 0, 0, 0, 0, 0, 35, 210, 0, 0, 0, 0, 0, 0, 182, 92, 104, 49, 100, 174, 32, 101, 152, 170, 46, 7, 186, 176, 193, 110, 42, 208, 132, 71, 236, 202, 218, 205, 1
38, 88, 155, 29, 112, 29, 107, 238, 0] }] } }
```

Crash:

```
[2020-04-30T01:07:32.936732196Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-ban
king-stage-tx" one=1i message="panicked at 'index out of bounds: the len is 14 but the index is 14', runtime/src/messa
ge_processor.rs:254:31" location="runtime/src/message_processor.rs:254:31"
  15: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  16: solana_runtime::message_processor::MessageProcessor::create_pre_accounts::{{closure}}
             at runtime/src/message_processor.rs:254
  17: solana_sdk::instruction::CompiledInstruction::visit_each_account
             at sdk/src/instruction.rs:259
  18: solana_runtime::message_processor::MessageProcessor::create_pre_accounts
             at runtime/src/message_processor.rs:258
  19: solana_runtime::message_processor::MessageProcessor::execute_instruction
             at runtime/src/message_processor.rs:326
  20: solana_runtime::message_processor::MessageProcessor::process_message
             at runtime/src/message_processor.rs:355
  21: solana_runtime::bank::Bank::load_and_execute_transactions::{{closure}}
             at runtime/src/bank.rs:1378
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:285
  23: core::option::Option<T>::map
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/option.rs:450
  24: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:791
  25: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:2007
  26: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1919
  27: core::iter::traits::iterator::Iterator::collect
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1558
  28: solana_runtime::bank::Bank::load_and_execute_transactions
             at runtime/src/bank.rs:1367
  29: solana_core::banking_stage::BankingStage::process_and_record_transactions_locked
             at core/src/banking_stage.rs:511
  30: solana_core::banking_stage::BankingStage::process_and_record_transactions
             at core/src/banking_stage.rs:581
  31: solana_core::banking_stage::BankingStage::process_transactions
             at core/src/banking_stage.rs:623
  32: solana_core::banking_stage::BankingStage::process_received_packets
             at core/src/banking_stage.rs:772
  33: solana_core::banking_stage::BankingStage::process_packets
             at core/src/banking_stage.rs:888
  34: solana_core::banking_stage::BankingStage::process_loop
             at core/src/banking_stage.rs:391
```

HEAD at 972381ef.

#### Proposed Solution

Determine size of instruction accounts array in the sanitize impl by filtering account_keys the same way load_tx_accounts does (i.e. on `is_non_loader_key`).

Or just catch this error in load_tx_accounts?

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Indexing into `accounts` vec assumes that the accounts are 1-1 with the indexes in `account_keys`.

#### Summary of Changes

Fill in empty accounts for program slots so indexing is 1:1, detect first non-program account as the payer.

Fixes #9817

### CODE REVIEW

File: runtime/src/accounts.rs [hunk 1]
```diff
@@ -151,50 +151,65 @@ impl Accounts {
...
+                                        Some((account, 0))
+                                    }
+                                })
+                                .unwrap_or_default();
+
+                        tx_rent += rent;
+                        account
+                    } else {
+                        // Fill in an empty account for the program slots.
+                        Account::default()
```
Comment (sakridge) [inline runtime/src/accounts.rs:181]: @jackcmay do you feel that we need to actually load the program accounts?

File: runtime/src/accounts.rs [hunk 2]
```diff
@@ -151,50 +151,65 @@ impl Accounts {
...
-                    .and_then(|(mut account, _)| {
-                        if message.is_writable(i) && !account.executable {
-                            let rent_due = rent_collector.update(&key, &mut account);
-                            Some((account, rent_due))
-                        } else {
-                            Some((account, 0))
+                .map(|(i, key)| {
+                    if Self::is_non_loader_key(message, key, i) {
+                        if payer_index.is_none() {
+                            payer_index = Some(i);
```
Comment (t-nelson) [inline runtime/src/accounts.rs:163]: @CriesofCarrots we're going to need to figure out how to support this client side

Comment (sakridge) [reply runtime/src/accounts.rs:163]: We do? Should be no change for the client, right?

Comment (t-nelson) [reply runtime/src/accounts.rs:163]: There are assumptions of fee-payer == keys[0] in several places.  CLI at least to do fee-payer balance checks, Ledger uses it to present the fee-payer account.  Those are the two I'm aware of off hand

Comment (sakridge) [reply runtime/src/accounts.rs:163]: Huh... the code was always that the first non-program id is the payer. This change doesn't change that. Why did they assume a program id can be payer?

Comment (CriesofCarrots) [reply runtime/src/accounts.rs:163]: In what sense?

Comment (t-nelson) [reply runtime/src/accounts.rs:163]: I think this might be an instance of "standardizing an implementation detail"

File: runtime/src/accounts.rs (hunk 1 above)
Comment (jackcmay) [reply runtime/src/accounts.rs:181]: No, don't need to, default accounts are probaby ok for now

File: sdk/src/message.rs [hunk 3]
```diff
@@ -165,9 +165,17 @@ pub struct Message {
...
     fn sanitize(&self) -> std::result::Result<(), SanitizeError> {
-        if self.header.num_required_signatures as usize > self.account_keys.len() {
+        if self.header.num_required_signatures as usize
+            + self.header.num_readonly_unsigned_accounts as usize
+            > self.account_keys.len()
+        {
+            return Err(SanitizeError::IndexOutOfBounds);
+        }
+
+        if self.header.num_readonly_signed_accounts > self.header.num_required_signatures {
```
Comment (CriesofCarrots) [inline sdk/src/message.rs:175]: I think this needs to be `>=`
If `num_readonly_signed_accounts == num_required_signatures`, there will be no signer that can be debited for the tx fees.

File: sdk/src/message.rs [hunk 4]
```diff
@@ -165,9 +165,17 @@ pub struct Message {
...
             return Err(SanitizeError::IndexOutOfBounds);
         }
+
```
Comment (CriesofCarrots) [inline sdk/src/message.rs:178]: Same for check below: should be `>=` to ensure at least one RW account

File: sdk/src/message.rs (hunk 3 above)
Comment (CriesofCarrots) [reply sdk/src/message.rs:175]: That said, I assume we're including these just to be comprehensive about our transaction assumptions in one place. Because the sigverify check always happens first, right? If so, transactions can't make it to `sanitize` in `Bank::check_refs()` and still be in violation of this check.

Comment (sakridge) [reply sdk/src/message.rs:175]: yea, sigverify check should filter this in the full validator. As you said, to be comprehensive.

File: sdk/src/message.rs [hunk 5]
```diff
@@ -178,6 +186,10 @@ impl Sanitize for Message {
             if ci.program_id_index as usize >= self.account_keys.len() {
                 return Err(SanitizeError::IndexOutOfBounds);
             }
+            // A program cannot be a payer.
+            if ci.program_id_index == 0 {
```
Comment (t-nelson) [inline sdk/src/message.rs:190]: Does this jive with the first non-loader key as fee-payer in `load_tx_accounts()` ?

File: sdk/src/message.rs (hunk 4 above)
Comment (sakridge) [reply sdk/src/message.rs:178]: I think this check can be removed actually.

Since `num_readonly_signed_accounts < num_required_signatures`
and
 `(num_required_signatures + num_readonly_unsigned_accounts) < keys.len()` 

then this has to be true: 
`(num_readonly_signed_accounts + num_readonly_unsigned_accounts) < keys.len()`

File: sdk/src/message.rs (hunk 3 above)
Comment (sakridge) [reply sdk/src/message.rs:175]: Will change to <=

File: sdk/src/message.rs (hunk 4 above)
Comment (sakridge) [reply sdk/src/message.rs:178]: agree?

Comment (CriesofCarrots) [reply sdk/src/message.rs:180]: Yep! I agree 🔪

File: sdk/src/message.rs (hunk 5 above)
Comment (sakridge) [reply sdk/src/message.rs:186]: I think so, I believe it just means that `account_keys[0]` and also `accounts[0]` should always be considered the fee-payer and should not be referenced as a program index.

Technically I think it means we don't need to do the payer_index calculation, but I feel a bit better with it. What do you think?

File: sdk/src/message.rs (hunk 3 above)
Comment (sakridge) [reply sdk/src/message.rs]: We do have this though:
https://github.com/solana-labs/solana/blob/79a6b4b596b522f321c70ad26b6b3b3c1f7ccf25/runtime/src/bank.rs#L4589

File: sdk/src/message.rs (hunk 5 above)
Comment (t-nelson) [reply sdk/src/message.rs:186]: Yep, agreed!  Maybe log a warning in the payer_index calculation if payer_index != 0 ?

File: sdk/src/message.rs (hunk 3 above)
Comment (sakridge) [reply sdk/src/message.rs]: Hmm. it allows a read-only account to pay the fee, but then does not collect that account to store... tricky..

Comment (CriesofCarrots) [reply sdk/src/message.rs]: Oh that is tricky. Didn't realize we supported that, and it seems like the sigverify check actually prevents successful zero-signature transactions from being processed, even though the bank allows it.

Do we want to support zero-signature transactions?

If not, we can just ax this test.

Comment (sakridge) [reply sdk/src/message.rs]: I adjusted the test to expect an error.
