### PR TITLE
Fix vote_accounts test

### LINKED ISSUE #2994: get_vote_accounts() doesn't work with forks
#### Problem
when setting a vote account balance to zero in a child fork, the parent fork is also cleared

#### Proposed Solution
introduce a forks-oriented index for the vote accounts cache

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

vote_accounts cache is not updated correctly when an account is removed from a branch, but still present in other branches.

#### Summary of Changes

Only remove from the vote_index if the account is not present in any branch.

Fixes #2994

### CODE REVIEW

File: runtime/src/accounts.rs [hunk 1]
```diff
@@ -246,13 +246,21 @@ impl AccountsDB {
...
             .vote_index
             .read()
             .unwrap()
             .iter()
-            .filter_map(|pubkey| self.load(fork, pubkey, true))
+            .filter_map(|pubkey| {
+                let account = self.load(fork, pubkey, true);
+                if let Some(account) = account {
+                    if account.tokens != 0 {
+                        return Some(account);
```
Comment (sakridge) [inline runtime/src/accounts.rs]: @rob-solana maybe this will better describe, so if I update the vote index to contain accounts on every fork as it should, then I need to filter here to remove accounts which are shielding their parents accounts where tokens == 0 otherwise I will hit the assert in the test on line 1603. I can change that to len==7, and then add another test at the accounts level to test the filtering.

Comment (rob-solana) [reply runtime/src/accounts.rs]: yep, that works

the important part is just ensuring that parents are unaffected by changes in children, especially after squash()

Comment (rob-solana) [reply runtime/src/accounts.rs]: doing the shielding at the Accounts level is just fine

**Comment by rob-solana** [comment]
@sakridge note that the reason I found this is because I was going after coverage.  most uncovered lines have something to do with get_vote_accounts() and forks
