### PR TITLE
Always and fully deinitialize stored 0-lamport accts.

### LINKED ISSUE #8590: TdS cluster halted due to the vote hash mismatch
#### Problem

The cluster started to diverge around slot `2486174`

```
     53 2486166], hash: 5oTDhTPVEcZsdbS2EDSRJHATet7hhHBhaT7guLB6ESfZ, timestamp: None } failed to match hash 5oTDhTPVEcZsdbS2EDSRJHATet7hhHBhaT7guLB6ESfZ 3CZJDTbagzKRnfydM1sCpMegMTC5r7Zi9mtXSnmWrWHE
     53 2486167], hash: 8jv963yGauBo2ha1mxztLpCxA3K8uh9GdW4KLc7R54TF, timestamp: None } failed to match hash 8jv963yGauBo2ha1mxztLpCxA3K8uh9GdW4KLc7R54TF 1351pKJs6U1CpERkFkaz5iUB8Z6unNwCBZ67bkhyNKkP
     52 2486172], hash: 5Q5Q63rgjJhndZGDThmADsws4FmkVjJncSKZAnr8Krdh, timestamp: None } failed to match hash 5Q5Q63rgjJhndZGDThmADsws4FmkVjJncSKZAnr8Krdh EY1soLRRWZsU6wLdVtFDMh7trCx3WnimNvnvSjHXZmcQ
     52 2486173], hash: 6fDUcXKemxrK6LGKQjqyikWFg8izeWegPLSAxicmkax2, timestamp: None } failed to match hash 6fDUcXKemxrK6LGKQjqyikWFg8izeWegPLSAxicmkax2 4FHLHBUWgAFPvSUfy9GAEoSTvY7fNY6cZcCwAz2soQW6
     42 2486174], hash: 5KeEYM9s4Hd95TZVVWyM24YorEStRqUzYtSvcjQZPTwE, timestamp: None } failed to match hash 5KeEYM9s4Hd95TZVVWyM24YorEStRqUzYtSvcjQZPTwE JCtkDDQTJWMKAPhnhL5nabFadhLFZ4PeKoNHz72QWEyL
     11 2486174], hash: pH3RUd43joXvtQRDis3zciDsHYm71TTJL1Zs9qfHoHy, timestamp: None } failed to match hash pH3RUd43joXvtQRDis3zciDsHYm71TTJL1Zs9qfHoHy JCtkDDQTJWMKAPhnhL5nabFadhLFZ4PeKoNHz72QWEyL
     42 2486175], hash: 2qA9ztez3zmGUxNzZYgQLVLnEPwXkYGaZc7avWAznk45, timestamp: None } failed to match hash 2qA9ztez3zmGUxNzZYgQLVLnEPwXkYGaZc7avWAznk45 H8qGd6F8LVegq9LNuVtY3PNFmqkonNqD76qJFPRAZrGQ
     11 2486175], hash: 7Whtb89po5tL9dwNLBGmHFLUr9wW9M562d2rxm8tJuxR, timestamp: None } failed to match hash 7Whtb89po5tL9dwNLBGmHFLUr9wW9M562d2rxm8tJuxR H8qGd6F8LVegq9LNuVtY3PNFmqkonNqD76qJFPRAZrGQ
     42 2486176], hash: 5jF5ezWyPDtEeNcMrt1ozJDpUZqoKTTu16g5FizqTj9K, timestamp: None } failed to match hash 5jF5ezWyPDtEeNcMrt1ozJDpUZqoKTTu16g5FizqTj9K E3qwVYNoBFtRFHZGVb2zHfNp8NwxiUr1eriZYyec7fkB
     11 2486176], hash: 8vSbefhYSVtNsXHkDh6noeoZ65mM6pcDTKr1P5UzReA2, timestamp: None } failed to match hash 8vSbefhYSVtNsXHkDh6noeoZ65mM6pcDTKr1P5UzReA2 E3qwVYNoBFtRFHZGVb2zHfNp8NwxiUr1eriZYyec7fkB

```

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

Recently, the TdS cluster died because of differing behavior in regards to handling a seemingly normal transaction, [resulting into two irreconcilable perpetual forks.](https://github.com/solana-labs/solana/issues/8590#issuecomment-594080164)

The direct cause is that `system_instruction_processor::allocate()`'s check differed in that it triggered and aborted the transaction or it processed the transaction normally.

The difference is caused by the fact that the state of the given account (with 0-lamport balance at the time) differed across the two forks. As a matter of fact, the transaction tried to recreate an account at the pubkey which recently got 0-lamport. Also note that the transaction should succeed because 0-lamport accounts should be equivalent to non-existing and shouldn't affect the succeeding transactions in any way.

Ultimately, the content of previous account differed because the one fork had called `Bank::clean_account()`, purged the 0-lamport account completely and passed a `Account::default()` to `system_instruction_processor::allocate()`. The other hadn't done so and 
passed an partially-deinitialized account to `system_instruction_processor::allocate()`, which was't same as `Account::default()` because there was lingering bad 0-lamport account index entry.

Currently, `Bank::clean_accounts()` could be called at any time while running validators because it's called as one of preparation steps of snapshot generation. In turn, snapshot timings are not synchronized across the cluster, meaning a validator can start to create a snapshot at any time.

#### Summary of Changes

Eliminate observable AccontsDB state difference depending on calling `Bank::clean_accounts()` or not by fully deinitializing accounts with 0-lamport before storing and indexing.

Originally, I thought tweaking `system_instruction_processor::allocate()` by adding `if account.lamports == 0`, but it created another error like this:

```
[2020-03-05T06:47:46.727369588Z DEBUG solana_runtime::bank] tx error: Err(InstructionError(0, AccountDataSizeChanged)) Transaction { signatures: [2V2NDFP5ztU28MEEk5suNEVoTdQhMCbxabx9zoT47BFnhezFo4CNLHjWWYJWLMSDFyaCUUaSdD9NBbwojpCQaHt4, 53dNNch84nZ2RMPnWeHRV1YpdaLetdanm45b4Udq3CvDuGyj85q38NpWVqW8HWe6NdFzULzYqpa1VJ9MUxtv9aas], message: Message { header: MessageHeader { num_required_signatures: 2, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 1 }, account_keys: [HPTqfUWRkjZSidPeTKKWS4JcicDjNp3jPuQtcSnLSNZj, G4NRURUNpx3VLDg7W88acurxVxspAdoTNacV7sHFvNPM, 11111111111111111111111111111111], recent_blockhash: Cid6k1HiuF883YfAHdSoZgF2b5TxPNBS3sNT2Ua84Hd, instructions: [CompiledInstruction { program_id_index: 2, accounts: [0, 1], data: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 124, 0, 0, 0, 0, 0, 0, 0, 12, 155, 202, 84, 85, 242, 65, 121, 26, 152, 218, 87, 52, 59, 3, 36, 37, 164, 4, 23, 156, 202, 177, 215, 57, 234, 34, 173, 23, 218, 158, 238] }] } }
```

Ultimately, I've just noticed the stored 0-lamport account is of bad state:

```
[2020-03-05T05:52:39.322573307Z ERROR solana_runtime::system_instruction_processor] Account { lamports: 0 data.len: 0 owner: 6gtT3EUdxyDc2CR2wT6a9eDy6pLj8oi3LMFWeiukKPFo executable: false rent_epoch: 0 hash: 11111111111111111111111111111111 }
```

And I found that system_instruction level condition tweaking is fruiteless and found the root cause at the `AccountsDB::store()`.

Fixes #8590

### CODE REVIEW

File: runtime/src/system_instruction_processor.rs [hunk 1]
```diff
@@ -933,6 +934,78 @@ mod tests {
...
+        let r = bank_client.send_message(&[&alice_keypair, &bob_keypair], message);
+        assert!(r.is_ok());
+    }
+
+    #[test]
+    fn test_create_zero_lamport_with_clean() {
+        with_create_zero_lamport(|bank| {
+            bank.squash();
+            // do clean and assert that it actually did its job
+            assert_eq!(3, bank.get_snapshot_storages().len());
```
Comment (sakridge) [inline runtime/src/system_instruction_processor.rs]: Checking a specific storage count is a bit fragile. I would prefer to find a better condition, but we can clean it up later.
