### PR TITLE
Forward transactions to the leader for next Nth slot

### LINKED ISSUE #4610: Transaction forwarding changes if leader is scheduled for 1 slot
#### Problem
The transaction forwarding code may not work effectively if leader is rotated every slot. The transactions are buffered and forwarded based on leader of next slot. If the transactions are backed up, the next slot leader may not have enough opportunity to process the transactions. This will result in transaction drops.

#### Proposed Solution
One option is to forward it to leader for next Nth slot (and buffer it). Need to analyze other possible options and rework the design.

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
Currently the transactions are forwarded to the leader for the next slot. This scheme breaks if we reduce the slot duration, and the nodes are scheduled to be a leader for 1 slot. Enough time may have passed (network delay and sig verification delay) by the time the forwarded transaction reaches the next slot leader. The receiving node will either re-forward the transaction, or drop it if it's too old. This impacts performance of the network, while nodes are doing wasteful work.

#### Summary of Changes
Check if the current node will be leader in next N-1 slots. If so, hold the transaction. If not, forward the transaction to the leader for the next Nth slot.

Fixes #4610

### CODE REVIEW

**Comment by pgarg66** [comment]
For reference, I am running this PR along with 400ms slot, and 1 slot rotation. It's pretty stable. TPS took a hit (43K compared to ~60K)

image

**Comment by aeyakovenko** [comment]
@pgarg66 does this work on a decent sized network across the world?  50+ nodes or something with some geographical distribution?

**Comment by pgarg66** [comment]
> @pgarg66 does this work on a decent sized network across the world? 50+ nodes or something with some geographical distribution?

I haven't tried that yet. I am currently running it on 5 node network. All nodes are in the same zone.

File: core/src/banking_stage.rs [hunk 1]
```diff
@@ -611,7 +615,12 @@ impl BankingStage {
         let result = bank.check_transactions(
             transactions,
             &filter,
-            (MAX_RECENT_BLOCKHASHES - MAX_TRANSACTION_FORWARDING_DELAY) / 2,
+            (MAX_RECENT_BLOCKHASHES / 2)
+                .saturating_sub(MAX_TRANSACTION_FORWARDING_DELAY)
+                .saturating_sub(
+                    (FORWARD_TRANSACTIONS_TO_LEADER_AT_SLOT_OFFSET * DEFAULT_TICKS_PER_SLOT
```
Comment (carllin) [inline core/src/banking_stage.rs]: Can we grab the actual values from the fullnodeconfig rather than using default values? Some of the tests don't use default values.

File: core/src/poh_recorder.rs [hunk 2]
```diff
@@ -105,6 +105,13 @@ impl PohRecorder {
         self.leader_schedule_cache.slot_leader_at(slot + 1, None)
     }
 
+    pub fn leader_after_slots(&self, slots: u64) -> Option<Pubkey> {
+        let slot =
+            leader_schedule_utils::tick_height_to_slot(self.ticks_per_slot, self.tick_height());
+        self.leader_schedule_cache
+            .slot_leader_at(slot + slots, None)
```
Comment (carllin) [inline core/src/poh_recorder.rs]: passing None to the leader_schedule_cache might be a problem on epoch boundaries, because the leader schedule cache needs a bank in order to calculate the schedule for the next epoch. Maybe the poh_recorder should cache the latest bank that it saw so that it can use it here?

File: core/src/banking_stage.rs [hunk 3]
```diff
@@ -249,17 +252,15 @@ impl BankingStage {
...
-                Self::consume_or_forward_packets(
-                    next_leader,
-                    poh.bank().is_some(),
-                    poh.would_be_leader(DEFAULT_TICKS_PER_SLOT * 2),
-                    my_pubkey,
+            Self::consume_or_forward_packets(
+                poh.next_slot_leader(),
+                poh.bank().is_some(),
+                poh.would_be_leader(
+                    (FORWARD_TRANSACTIONS_TO_LEADER_AT_SLOT_OFFSET - 1) * DEFAULT_TICKS_PER_SLOT,
```
Comment (carllin) [inline core/src/banking_stage.rs]: why is this -1?

File: core/src/banking_stage.rs (hunk 1 above)
Comment (carllin) [reply core/src/banking_stage.rs]: Can we also add a comment explaining the reasoning behind this computation?

File: core/src/banking_stage.rs (hunk 3 above)
Comment (pgarg66) [reply core/src/banking_stage.rs]: If the current node will be leader in next N-1 slots...

File: core/src/banking_stage.rs (hunk 1 above)
Comment (pgarg66) [reply core/src/banking_stage.rs]: 👍

File: core/src/poh_recorder.rs (hunk 2 above)
Comment (pgarg66) [reply core/src/poh_recorder.rs]: Or, the caller of the function can handle it? The function is returning an Option. So the caller will know that the next leader is not known.

Comment (carllin) [reply core/src/poh_recorder.rs]: The problem is, the caller (banking stage) can't do much with that information. It will just hold the txs instead of forwarding them to the correct leader.

In this case, the next leader at an epoch boundary is known, we just need a bank to use for calculating the leader schedule.

File: core/src/banking_stage.rs (hunk 1 above)
Comment (carllin) [reply core/src/banking_stage.rs]: There are also a bunch of other default values used in this file, can we clean them up while we're at it (the list of ones we use are the ones we import in the header)

**Comment by manfr3d** [comment]
What happens if the leader is under DDoS ???

**Comment by aeyakovenko** [comment]
@manfr3d DDoS mitigation is a separate topic.  The public ingress address for a leader can be overlayed with private ingress addresses for each validator it is connected to.
