### PR TITLE
undo cost tracker changes for non-retryable failed transactions

### LINKED ISSUE #24197: Need to undo cost tracker changes for non-retryable failed transactions
#### Problem

Transaction cost is applied to cost_tracker before execution, if the transaction failed and not qualify for retry, it's cost should be undo from cost_tracker. 

See @jstarry comment [here](https://github.com/solana-labs/solana/pull/24182#discussion_r846204232). 

#### Proposed Solution

- zip `load_and_execute_transactions_output.execution_results` with `transaction_costs` and `transactions_qos_results`, undo cost for not `execution_result.was_executed_successfully()`

### PR DESCRIPTION
**Pull request by taozhu-chicago**
#### Problem
Transactions allowed by qos_service consumed space from cost_tracker. If they failed execution and not landed in block, their cost should be removed from cost_tracker.

#### Summary of Changes
- return `execution_results` from `execute_and_commit_transactions_locked()`
- zip it to `transaction_costs` and `qos_inclusion_results` to remove costs if not `execution_result.was_executed()`
- add tests

Fixes #24197

### CODE REVIEW

**Comment by taozhu-chicago** [comment]
Tag @ckamm

**Comment by taozhu-chicago** [comment]
banking-bench result
```
     Running `target/release/solana-banking-bench`
{'name': 'banking_bench_total', 'median': '52804.99'}
{'name': 'banking_bench_tx_total', 'median': '58101.63'}
{'name': 'banking_bench_success_tx_total', 'median': '52804.99'}
```

File: core/src/qos_service.rs [hunk 1]
```diff
@@ -177,24 +177,22 @@ impl QosService {
...
-                    // Will have to plumb it in next; For now, keep estimated costs.
-                    //
-                    // let actual_execution_cost = 0;
-                    // cost_tracker.update_execution_cost(tx_cost, actual_execution_cost);
+            .zip(execution_results)
+            .for_each(|((tx_cost, qos_inclusion_result), execution_result)| {
+                // Only transactions that the qos service included have to be
+                // checked for remove or update/commit
+                if qos_inclusion_result.is_ok() {
+                    if execution_result.was_executed_successfully() {
```
Comment (ckamm) [inline core/src/qos_service.rs:191]: It sounds to me like we should use `was_executed()` here: failed transactions should contribute to block cost.

File: core/src/banking_stage.rs [hunk 2]
```diff
@@ -1339,6 +1342,7 @@ impl BankingStage {
             retryable_transaction_indexes,
             commit_transactions_result: Ok(()),
             execute_and_commit_timings,
+            execution_results,
```
Comment (ckamm) [inline core/src/banking_stage.rs:1345]: Hmm, it looks like there is still a problem when `record_transactions()` errors. It can potentially mark all tx as retryable, even the ones that executed successfully.

File: core/src/banking_stage.rs [hunk 3]
```diff
@@ -1267,7 +1270,7 @@ impl BankingStage {
                     bank.commit_transactions(
                         sanitized_txs,
                         &mut loaded_transactions,
-                        execution_results,
+                        execution_results.clone(),
```
Comment (ckamm) [inline core/src/banking_stage.rs:1273]: This `clone()` should be unnecessary, it looks like `execution_results` gets passed back out as `tx_results.execution_results`?

File: runtime/src/cost_tracker.rs [hunk 4]
```diff
@@ -97,10 +97,21 @@ impl CostTracker {
...
-        // TODO: adjust block_cost / vote_cost / account_cost by (actual_execution_cost - execution_cost)
+        if let Some(actual_execution_units) = actual_execution_units {
+            let mut adjustment =
+                TransactionCost::new_with_capacity(estimated_tx_cost.writable_accounts.len());
+            adjustment
+                .writable_accounts
+                .extend(&estimated_tx_cost.writable_accounts);
+            adjustment.execution_cost = estimated_tx_cost
+                .execution_cost
+                .saturating_sub(actual_execution_units);
```
Comment (ckamm) [inline runtime/src/cost_tracker.rs:111]: Why not allow a correction of the cost in both directions? We don't know if the true cost is larger or smaller than the estimate.

File: runtime/src/cost_tracker.rs [hunk 5]
```diff
@@ -97,10 +97,21 @@ impl CostTracker {
...
+        estimated_tx_cost: &TransactionCost,
+        actual_execution_units: Option<u64>,
     ) {
-        // TODO: adjust block_cost / vote_cost / account_cost by (actual_execution_cost - execution_cost)
+        if let Some(actual_execution_units) = actual_execution_units {
+            let mut adjustment =
+                TransactionCost::new_with_capacity(estimated_tx_cost.writable_accounts.len());
+            adjustment
+                .writable_accounts
+                .extend(&estimated_tx_cost.writable_accounts);
```
Comment (ckamm) [inline runtime/src/cost_tracker.rs:108]: There should be a way to do this without copying `writable_accounts` by writing a special-case function for this adjustment.

File: core/src/qos_service.rs (hunk 1 above)
Comment (microwavedcola1) [reply core/src/qos_service.rs:191]: AFAICS I think the PR and the issue mention removing `non-retryable failed` from costs, this code is removing`non-retryable failed` & `retryable`, it should only remove `retryable` which is !was_executed() as ckamm mentions

File: runtime/src/cost_tracker.rs (hunk 4 above)
Comment (t-nelson) [reply runtime/src/cost_tracker.rs:111]: yeah i don't think saturating math is going to work here. seems like cost should be signed for this all to not need a bunch of contrived conversions (separate PR)

File: runtime/src/cost_tracker.rs (hunk 5 above)
Comment (t-nelson) [reply runtime/src/cost_tracker.rs:108]: lower-level function can take an independent iterator and this can wrap it

File: core/src/qos_service.rs (hunk 1 above)
Comment (taozhu-chicago) [reply core/src/qos_service.rs]: good call, fixed.

File: core/src/banking_stage.rs (hunk 2 above)
Comment (taozhu-chicago) [reply core/src/banking_stage.rs:1345]: So record only fails when MaxHeightReached. So those executed transactions will have to be retried in _next_slot. It should no longer impact _this_ block, does it?

File: core/src/banking_stage.rs (hunk 3 above)
Comment (taozhu-chicago) [reply core/src/banking_stage.rs:1273]: Yea, but later in same closure, `transaction_status_sender` consumes the `tx_results.execution_results`. I didn't want to dig down that path early, but let me see what can be done. Will make this change in next commit.

File: runtime/src/cost_tracker.rs (hunk 4 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs]: agree, thought about it after PR too, made change to support units being adjust up or down as `i128`
Also agreed with @t-nelson, don't really like converting between `u64` and `i128` back-n-forth, maybe just make cost signed later.

File: runtime/src/cost_tracker.rs (hunk 5 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs]: add function to specifically handle execution units update, avoid copying accounts hashmap

File: core/src/qos_service.rs [hunk 6]
```diff
@@ -599,4 +597,157 @@ mod tests {
...
+                    } else {
+                        TransactionExecutionResult::Executed(TransactionExecutionDetails {
+                            status: Ok(()),
+                            log_messages: None,
+                            inner_instructions: None,
+                            durable_nonce_fee: None,
+                            return_data: None,
+                        })
+                    }
+                })
```
[the remark this answers is not in the document]
Comment (taozhu-chicago) [reply core/src/qos_service.rs:742]: added.

File: runtime/src/cost_tracker.rs [hunk 7]
```diff
@@ -242,6 +251,23 @@ impl CostTracker {
...
+                .entry(*account_key)
+                .or_insert(0);
+            *account_cost = u64::try_from(i128::from(*account_cost).saturating_add(adjustment))
+                .unwrap_or(*account_cost);
+        }
+        self.block_cost = u64::try_from(i128::from(self.block_cost).saturating_add(adjustment))
+            .unwrap_or(self.block_cost);
+        if tx_cost.is_simple_vote {
+            self.vote_cost = u64::try_from(i128::from(self.vote_cost).saturating_add(adjustment))
+                .unwrap_or(self.vote_cost);
```
Comment (ckamm) [inline runtime/src/cost_tracker.rs:268]: Oof. Yeah, either make cost signed, or make a function to add i64 to u64, like in https://doc.rust-lang.org/std/primitive.u64.html#method.saturating_add_signed, implemented in https://github.com/rust-lang/rust/blob/master/library/core/src/num/uint_macros.rs#L1064

(the adjustment could be checked to fit i64 once)

File: core/src/banking_stage.rs (hunk 3 above)
Comment (jstarry) [reply core/src/banking_stage.rs:1273]: Agreed with @ckamm, the qos tracker just needs a list of booleans that say whether the transaction was committed to the block or not, cloning here is overkill.

Comment (jstarry) [reply core/src/banking_stage.rs:1273]: A list of `executed_indexes` could work too

Comment (taozhu-chicago) [reply core/src/banking_stage.rs]: [commit](d34a42ac85d3468edfbc4143a1066a487d80087d) extract `was_executed()` from execution_result into vec<bool>.

File: core/src/banking_stage.rs (hunk 2 above)
Comment (taozhu-chicago) [reply core/src/banking_stage.rs]: Just to clarify: `record_transactions()` tries to send a list of executed transactions to `recorder` in all-or-none fashion. And it can only fail with error `MaxHeightReached` (or panic, which is not the case we are trying to handle here). When that happens it marks all executed-yet-not-recorded transactions as retryable, but `execution_records` are not altered. Therefore we would have transactions that are executed (eg have counted units in _this_ bank's cost_tracker), but not actually recorded. To make the metrics accurate, we should remove those executed-but-not-recorded transactions' units from tracker too.

Comment (taozhu-chicago) [reply core/src/banking_stage.rs]: [commit](15443cf3ebc7ba43624cfa2509dc14884bfdf36b)

File: runtime/src/cost_tracker.rs (hunk 7 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs:268]: Not super comfortable with cost being signed  - it makes sense that _adjustment_.cost has sign, but not so much of saying a transaction has `-100` units. 

Another option is to define adjustment as struct:
```
struct CostAdjustment {
    units: u64,
    adjust_op: enum{ Up, Down},
}

impl CostAdjustment {
    fn apply_to(&self, &mut cost) {
        match self.adjust_op {
            Up => cost.saturating_add(self.units),
            Down => cost.saturating_sub(self.units),
        }
    }
}
```
so the use site code would be: 
```
let adjustment = if lhs>rhs { CostAdjustment{ units = lhs-rhs, adjust_op = Down, } else {...};
adjustment.apply_to(lhs);
```
I don't know  if I like this any better after all. Open for ideas, maybe just take `u64.saturating_signe_add(i64)` approach?

File: core/src/banking_stage.rs [hunk 8]
```diff
@@ -120,6 +120,8 @@ pub struct ExecuteAndCommitTransactionsOutput {
     // how many such transactions were committed
     commit_transactions_result: Result<(), PohRecorderError>,
     execute_and_commit_timings: LeaderExecuteAndCommitTimings,
+    // True if transaction was-executed()
+    transactions_execute_and_record_status: Vec<bool>,
```
Comment (jstarry) [inline core/src/banking_stage.rs:124]: I think it's better to remove this field and move this info into `commit_transactions_result` so that its type becomes `Result<Vec<bool>, PohRecorderError>`

File: core/src/qos_service.rs [hunk 9]
```diff
@@ -177,24 +177,22 @@ impl QosService {
...
-                if qos_inclusion_result.is_ok() && retryable_transaction_indexes.contains(&index) {
-                    cost_tracker.remove(tx_cost);
-                } else {
-                    // TODO: Update the cost tracker with the actual execution compute units.
-                    // Will have to plumb it in next; For now, keep estimated costs.
-                    //
-                    // let actual_execution_cost = 0;
-                    // cost_tracker.update_execution_cost(tx_cost, actual_execution_cost);
+            .zip(transaction_executed_status)
+            .for_each(|((tx_cost, qos_inclusion_result), executed_status)| {
```
Comment (jstarry) [inline core/src/qos_service.rs:187]: nit: rename to `was_committed`

File: core/src/qos_service.rs [hunk 10]
```diff
@@ -177,24 +177,22 @@ impl QosService {
     pub fn update_or_remove_transaction_costs<'a>(
         transaction_costs: impl Iterator<Item = &'a TransactionCost>,
         transaction_qos_results: impl Iterator<Item = &'a transaction::Result<()>>,
-        retryable_transaction_indexes: &[usize],
+        transaction_executed_status: impl Iterator<Item = &'a bool>,
```
Comment (jstarry) [inline core/src/qos_service.rs:180]: nit: rename to `transaction_commitment_status`

File: runtime/src/cost_tracker.rs (hunk 7 above)
Comment (jstarry) [reply runtime/src/cost_tracker.rs:268]: I think we should copy and use the `checked_add_signed` implementation from here https://github.com/rust-lang/rust/pull/87601/files. And then handle the case where `None` is returned as @t-nelson is suggesting

Comment (jstarry) [reply runtime/src/cost_tracker.rs:268]: > I think i64 is plenty here, no need for the i128 hit

Agreed, the rust-lang impl does exactly that

File: core/src/qos_service.rs (hunk 10 above)
Comment (jstarry) [reply core/src/qos_service.rs:180]: Ah that's what I meant, thanks!

File: runtime/src/cost_tracker.rs (hunk 7 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs:268]: Sounds good. As for handling overflow caused by adjustment, what do you think to immediately bump cost_tracker to its up limits to prevent writing more transactions into current block, so avoid making large blocks?

Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs]: [commit](f1371e2b7e0c35a1dcef0d98ea4cab3bf7367dd5) for math.

File: core/src/qos_service.rs (hunk 9 above)
Comment (taozhu-chicago) [reply core/src/qos_service.rs]: ✅

File: core/src/qos_service.rs (hunk 10 above)
Comment (taozhu-chicago) [reply core/src/qos_service.rs]: ✅

File: runtime/src/cost_tracker.rs [hunk 11]
```diff
@@ -9,6 +9,43 @@ use {
     std::collections::HashMap,
 };
 
+/// Copied nightly-only experimental `checked_add_signed` implementation
+/// from https://github.com/rust-lang/rust/pull/87601/files
+/// Should be removed once the feature is added to standard library.
+trait ArithmeticUtil {
```
Comment (t-nelson) [inline runtime/src/cost_tracker.rs:15]: I think this should live in sdk instead

File: runtime/src/cost_tracker.rs [hunk 12]
```diff
@@ -106,8 +143,9 @@ impl CostTracker {
                 return;
             }
 
-            let adjustment =
-                i128::from(actual_execution_units) - i128::from(estimated_execution_units);
+            let (res, _overflowed) =
+                actual_execution_units.overflowing_sub(estimated_execution_units);
+            let adjustment = res as i64;
```
Comment (t-nelson) [inline runtime/src/cost_tracker.rs:148]: we need to respond to both overflow and `res` too large for `i64` here as well

File: runtime/src/cost_tracker.rs [hunk 13]
```diff
@@ -740,7 +788,7 @@ mod tests {
 
         // adjust up
         {
-            let adjustment: i128 = 50;
+            let adjustment: i64 = 50;
```
Comment (t-nelson) [inline runtime/src/cost_tracker.rs:791]: could be lazy here and just drop the types :wink:

File: runtime/src/cost_tracker.rs [hunk 14]
```diff
@@ -242,6 +289,32 @@ impl CostTracker {
...
+    /// Apply execution units adjustment to cost-tracker.
+    /// If adjustment causes arithmetic overflow, it bumps costs to their limits to
+    /// prevent adding further transactions into current block.
+    fn adjust_transaction_execution_cost(&mut self, tx_cost: &TransactionCost, adjustment: i64) {
+        for account_key in tx_cost.writable_accounts.iter() {
+            let account_cost = self
+                .cost_by_writable_accounts
+                .entry(*account_key)
+                .or_insert(0);
+            match ArithmeticUtil::checked_add_signed(*account_cost, adjustment) {
```
Comment (ckamm) [inline runtime/src/cost_tracker.rs:302]: @t-nelson I don't understand why checking for overflow here instead of saturating is useful. If there's a bug and
- there's overflow, then the behavior is effectively the same as with `saturating_add_signed()`, but it hides the bug from the metrics by setting the cost to a plausible value
- there's an underflow, then that bug now causes the block to stop accepting transactions; not sure if this is better or worse than potentially packing the block too full by saturating to 0

Also I think that doing checked math here, and saturating math in the simple add/remove functions is weirdly inconsistent.

File: runtime/src/cost_tracker.rs (hunk 12 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs:148]: I can't find any way better than what @ckamm suggested above if have to take care of `res` is too big for `i64`. But sounds like the consensus is `saturating` is not the ideal solution. I hesitant to copy `saturating_add_unsigned` implementation into our code space for an undesired solution. 

ig if we are going to compare `a` and `b` before math, we may as well check `if abs(a-b)> i64::MAX`. Then the real question is if it's true, 1. what to do with the presumably bad adjustment, throw it away? 2. what to do with current block, stop adding more txs into it to be safe, or reset its cost to zero therefore risking making a heavy block (and  long replay time)?

File: runtime/src/cost_tracker.rs (hunk 14 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs:302]: Checking potentially allows us to do different handling than just clip to u64::MAX. 

imho, stop accepting TXs to current block when overflow detected is safer than reset cost_tracker to zero therefore producing an oversized block. A underpacked block waster some space, but next block will start anew, while a overpacked block can cause long replay time, and potentially forking. 

But I agree the inconsistency of how `checked_*` and `saturating_*` are used in code, maybe should leave that for another time.

File: core/src/qos_service.rs [hunk 15]
```diff
@@ -177,28 +177,62 @@ impl QosService {
...
-                    //
-                    // let actual_execution_cost = 0;
-                    // cost_tracker.update_execution_cost(tx_cost, actual_execution_cost);
+            .zip(transaction_committed_status)
+            .for_each(|((tx_cost, qos_inclusion_result), was_committed)| {
+                // Only transactions that the qos service included have to be
+                // checked for update
+                if qos_inclusion_result.is_ok() {
+                    if *was_committed {
+                        cost_tracker.update_execution_cost(tx_cost, None);
```
Comment (jstarry) [inline core/src/qos_service.rs:211]: Can we leave this as a todo for now and follow up in a new PR when the actual cost is available here?

**Review by jstarry — COMMENTED** [review]
Looks good to me but I would take the arithmetic changes out for now

File: core/src/qos_service.rs (hunk 15 above)
Comment (taozhu-chicago) [reply core/src/qos_service.rs:211]: Let's leave the piping work here, the next work #24311 is standing by as soon as this PR is merged.

Comment (jstarry) [reply core/src/qos_service.rs:211]: Why? This stuff is not related the issue that this PR is solving and it is slowing down review

File: runtime/src/cost_tracker.rs (hunk 11 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs]: move to sdk in [commit](89397ea8d43a73a637b31ad58662a88d84b2f53a)

File: runtime/src/cost_tracker.rs (hunk 12 above)
Comment (taozhu-chicago) [reply runtime/src/cost_tracker.rs]: Ya, OK sounds good. changes in [commit](89397ea8d43a73a637b31ad58662a88d84b2f53a)

File: core/src/qos_service.rs (hunk 15 above)
Comment (taozhu-chicago) [reply core/src/qos_service.rs:211]: Yea, I see your point, and that's why it's 'None' there. 
For practical purpose, I just updated PR to address comments around the math, which is largely within `update_execution_cost()`, would be good to just push it through. 
But I am open to take this part of code into separate PR if that helps to merge this one quicker.

**Comment by taozhu-chicago** [comment]
@ckamm @t-nelson @jstarry Have pushed last commit to address arithmetic changes, moved to `sdk`. Appreciate for another look.

File: core/src/qos_service.rs (hunk 15 above)
Comment (jstarry) [reply core/src/qos_service.rs:211]: Yeah please take it out to keep this PR focused on one functional change, thanks!

Comment (taozhu-chicago) [reply core/src/qos_service.rs]: Okie, removed

**Review by ckamm — APPROVED** [review]
nit: since num_util is unused in this PR, it should probably move to the one that does the adjustment for true-cu

**Comment by jstarry** [comment]
> nit: since num_util is unused in this PR, it should probably move to the one that does the adjustment for true-cu

Agreed, will approve when it's removed

File: core/src/qos_service.rs (hunk 15 above)
Comment (jstarry) [reply core/src/qos_service.rs]: Thanks!

File: core/src/qos_service.rs [hunk 16]
```diff
@@ -177,28 +177,58 @@ impl QosService {
...
+
+    fn update_transaction_costs<'a>(
+        transaction_costs: impl Iterator<Item = &'a TransactionCost>,
+        transaction_qos_results: impl Iterator<Item = &'a transaction::Result<()>>,
+        transaction_committed_status: &Vec<bool>,
         bank: &Arc<Bank>,
     ) {
         let mut cost_tracker = bank.write_cost_tracker().unwrap();
         transaction_costs
             .zip(transaction_qos_results)
```
Comment (t-nelson) [inline core/src/qos_service.rs:204]: let's create an iterator that filters `transaction_qos_results` by `transaction_committed_status` here, then pass it along with `transaction_costs` through to `remove_transaction_costs()` and avoid the replicode in the `and_then()`

File: sdk/src/lib.rs [hunk 17]
```diff
@@ -34,6 +34,7 @@ pub mod keyed_account;
 pub mod log;
 pub mod native_loader;
 pub mod nonce_account;
+pub mod num_utils;
```
Comment (t-nelson) [inline sdk/src/lib.rs:37]: I'll echo @ckamm here. Let's move the introduction of this module to the PR where it will be used

**Review by t-nelson — COMMENTED** [review]
almost there!

**Comment by taozhu-chicago** [comment]
> nit: since num_util is unused in this PR, it should probably move to the one that does the adjustment for true-cu

Ooops, forgot to remove the actual `num_util.rs` file ... will remove it

File: core/src/qos_service.rs (hunk 16 above)
Comment (taozhu-chicago) [reply core/src/qos_service.rs:204]: Can use some help on this one. How do I create an iterator of `transaction_qos_results` where its corresponding `transaction_committed_status` is false, that can still be zipped with `transaction_costs`? If I use `filter()` then the result iterator may not be the same length as `transaction_costs`; if use `map()`, do I have to clone a new set of `Result<>`s?

**Review by jstarry — DISMISSED** [review]

File: core/src/qos_service.rs (hunk 16 above)
Comment (t-nelson) [reply core/src/qos_service.rs:204]: something like this should do it
```rust
let uncommited_qos_results = transaction_qos_results
    .zip(transaction_committed_status)
    .filter_map(|(qos_result, committed)| (!*committed).then(|| qos_result)));
remove_transaction_costs(transactions_costs, uncommitted_qos_results, bank);
```

Comment (taozhu-chicago) [reply core/src/qos_service.rs:204]: With `filter_map`, wouldn't `uncommited_qos_results` have less items if some of `transaction_committed_status` is `true`, therefore it can't be `zip` with `transactions_costs`?
