### PR TITLE
Fix incorrectly signed CrdsValues

### LINKED ISSUE #6694: CrdsValues need to be signed, not just the data they contain
#### Problem

CrdsValue's need to be signed, not just the data they contain.  Attacker could change the enum type of the CrdsValue potentially rerouting or corrupting a nodes ContactInfo.

#### Proposed Solution

Signature should be wrapping CrdsValue.

tag: @sagar-solana

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

CrdsValue's need to be signed, not just the data they contain. Attacker could change the enum type of the CrdsValue potentially rerouting or corrupting a nodes ContactInfo.

#### Summary of Changes

Refactored CrdsValue to contain a CrdsData type. CrdsData is signed entirely now. 

Fixes #6694

### CODE REVIEW

File: core/src/crds_value.rs [hunk 1]
```diff
@@ -8,9 +8,34 @@ use std::collections::BTreeSet;
 use std::fmt;
 
 /// CrdsValue that is replicated across the cluster
+#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
```
Comment (sagar-solana) [inline core/src/crds_value.rs]: @aeyakovenko @carllin the meat of the change is in this file
