### PR TITLE
Validate account locks on buffering

### LINKED ISSUE #34221: solBnkTxSched panic on canary node
#### Problem

One of the canary nodes panicked running f36ab08f:
```
thread 'solBnkTxSched' panicked at /home/sol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prio-graph-0.1.0/src/prio_graph.rs:105:17:
blocking node must exist
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: prio_graph::prio_graph::PrioGraph<Id,Rk,Tl,Pfn>::insert_transaction::{{closure}}
   3: prio_graph::prio_graph::PrioGraph<Id,Rk,Tl,Pfn>::insert_transaction
   4: solana_core::banking_stage::transaction_scheduler::prio_graph_scheduler::PrioGraphScheduler::schedule
   5: solana_core::banking_stage::transaction_scheduler::scheduler_controller::SchedulerController::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2023-11-25T19:31:49.802987422Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solBnkTxSched" one=1i message="panicked at /home/sol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prio-graph-0.1.0/src/prio_graph.rs:105:17:
    blocking node must exist" location="/home/sol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prio-graph-0.1.0/src/prio_graph.rs:105:17" version="1.18.0 (src:f36ab08f; feat:1429699964, client:SolanaLabs)"
```

The node that panicked was `sce3`, and the log has been set aside at
`/home/sol/logs/2023.11.25_panic.log`

#### Proposed Solution
Debug why the node panicked. It is interesting that the panic occurred in a dependency; potentially a bug in the dependency or violating some assumption of the API.

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
Prio-graph has an assumption that account locks are not duplicate - see crash #34221
prio-graph crate **should** be fixed, but these transactions are not valid and should be dropped as soon as reasonably possible.

#### Summary of Changes
- Check for too many or duplicate locks during sanitization/buffering.
- Add metric for number of txs discarded due to locks

Fixes #34221

### CODE REVIEW

File: core/src/banking_stage/transaction_scheduler/scheduler_controller.rs [hunk 1]
```diff
@@ -209,6 +212,18 @@ impl SchedulerController {
...
+            // If it does, transaction is not valid and should be dropped here.
+            if SanitizedTransaction::validate_account_locks(
+                transaction.message(),
+                transaction_account_lock_limit,
+            )
+            .is_err()
+            {
+                saturating_add_assign!(self.count_metrics.num_dropped_on_validate_locks, 1);
+                continue;
+            }
```
Comment (taozhu-chicago) [inline core/src/banking_stage/transaction_scheduler/scheduler_controller.rs:225]: perhaps move this all the way up to `ImmutableDeserializedPacket::new()` or somewhere during packet receiving to drop bad packets before inserting into storage?

Comment (apfitzge) [reply core/src/banking_stage/transaction_scheduler/scheduler_controller.rs:225]: This is done before we insert to storage.
We can't do it in `ImmutableDeserializedPacket::new` because we haven't resolved look up tables at that point.
This is immediately after we resolve look up tables, which I think is the earliest we can do this.

Potentially, it could/**should** be done in `SanitizedTransaction::try_new` but that's changing the definition of a `SanitizedTransaction`. Not sure we want to do that?

Comment (taozhu-chicago) [reply core/src/banking_stage/transaction_scheduler/scheduler_controller.rs:225]: I got confused by thread-local-MI and central-scheduler code. So this is somewhat parallel to `unprocessed_transactino_storage::consume_scan_should_process_packet()` where immmutable_deserialized_packet is sanitized then accounts locks checked, which should be OK then.

Leave `SanitizedTransaction` to solana-transaction-types crate :D, there maybe can add a type for "sanitized and account locks validated" type

**Review by taozhu-chicago — APPROVED** [review]
lgtm for now
