### PR TITLE
Fix rules for fork selection

### LINKED ISSUE #6880: Consensus rule for following the heaviest fork and filtering votable forks are backwards.
#### Problem

Consensus rule for following the heaviest fork and filtering votable forks are backwards.  This causes nodes that are on a minority partition to continuously pick their own fork, because the larger partition is not votable.

#### Proposed Solution

1. Find the heaviest fork first, then check if its votable.
2. If the heaviest fork is not votable, don't vote.
3. We should probably not produce new blocks, but this is a secondary issue.

tag: @carllin

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

Fork selection was picking the best votable bank, instead of the heaviest bank and waiting for it to be votable.

#### Summary of Changes

1. find all the frozen banks
2. filter
  * banks that have already been voted
  * failed the threshold check
  * older than the most recent vote
3. sort the banks by weight
4. select the heaviest one
5. vote on the oldest relative of the heaviest bank that satisfies the lockout rule
6. If there is no vote, reset PoH to the heaviest bank

6 is partition detection and resolution.  If the heaviest bank is not votable, then the network needs to attach a block to it high enough that it’s votable.

* Implement a partition framework for LocalCluster that hooks into window service.

Fixes #6880

### CODE REVIEW

File: core/src/replay_stage.rs [hunk 1]
```diff
@@ -645,58 +640,52 @@ impl ReplayStage {
...
+                let has_voted = tower.has_voted(bank.slot());
+                trace!("bank has_voted: {} {}", bank.slot(), has_voted);
                 !has_voted
             })
-            .filter(|b| {
-                let is_locked_out = tower.is_locked_out(b.slot(), &ancestors);
-                trace!("bank is is_locked_out: {} {}", b.slot(), is_locked_out);
-                !is_locked_out
+            .filter(|bank| {
+                let leaf = children.get(&bank.slot()).map(|set| set.is_empty());
```
Comment (rob-solana) [inline core/src/replay_stage.rs]: we only ever want to vote on leaves?

Comment (aeyakovenko) [reply core/src/replay_stage.rs]: @rob-solana I think you are right.  If we vote on older heavier banks, we can vote on the child on the next round.  So this is redundant.

File: core/src/replay_stage.rs [hunk 2]
```diff
@@ -708,8 +687,28 @@ impl ReplayStage {
...
+        let vote_threshold =
+            tower.check_vote_stake_threshold(bank.slot(), &stake_lockouts, *total_staked);
+        if !vote_threshold {
+            inc_new_counter_info!("replay_stage-fork_selection-heavy_bank_threshold", 1);
+            return None;
+        }
+        let is_locked_out = tower.is_locked_out(bank.slot(), &ancestors);
+        if is_locked_out {
+            inc_new_counter_info!("replay_stage-fork_selection-heavy_bank_lockout", 1);
+            return None;
```
Comment (carllin) [inline core/src/replay_stage.rs]: What happens if the heaviest fork dies and stops making process before your lockout expires?

Comment (aeyakovenko) [reply core/src/replay_stage.rs]: @carllin how do we know its "expired"?  The way this is written is that it will vote on it, and then it will be filtered out as an already voted fork.

Comment (carllin) [reply core/src/replay_stage.rs]: From the validiator's perspective, if they see the heaviest bank on some fork here, but the validator is locked out on another fork, then it returns None here. if that heaviest fork then stops making progress, we will keep returning None here and never vote?

Comment (aeyakovenko) [reply core/src/replay_stage.rs]: @carllin how would it stop making progress?  It's a frozen bank we haven't voted on.

Comment (carllin) [reply core/src/replay_stage.rs]: You don't need to vote on the frozen heaviest bank in order to be locked out on it. If you've voted on any other bank > frozen heaviest bank, you will be locked out on the heaviest bank. This will stop progress unless the heaviest bank changes (which doesn't seem is guaranteed to happen)

Comment (aeyakovenko) [reply core/src/replay_stage.rs]: @carllin ah right, you can't vote backwards.  This is why I thought we might need to consider leafs.

Comment (aeyakovenko) [reply core/src/replay_stage.rs]: @carllin I added a filter to only consider leafs of banks

File: core/src/replay_stage.rs [hunk 3]
```diff
@@ -708,8 +697,28 @@ impl ReplayStage {
             );
         }
         inc_new_counter_info!("replay_stage-tower_duration", ms as usize);
+        rv
+    }
 
-        votable
+    #[allow(clippy::type_complexity)]
```
Comment (garious) [inline core/src/replay_stage.rs]: Such a great warning. Why disable?

File: core/src/replay_stage.rs (hunk 2 above)
Comment (aeyakovenko) [reply core/src/replay_stage.rs]: fixed, only vote on banks that are newer that the last vote

File: core/src/replay_stage.rs (hunk 3 above)
Comment (aeyakovenko) [reply core/src/replay_stage.rs]: doesn't like tuples of size 4

Comment (garious) [reply core/src/replay_stage.rs]: But your convinced the code is better with a tuple of size 4?

File: core/src/replay_stage.rs [hunk 4]
```diff
@@ -645,71 +641,103 @@ impl ReplayStage {
...
+                    stake_lockouts,
+                    total_staked,
                 )
             })
-            .filter(|(b, (stake_lockouts, total_staked))| {
+            .filter(|(bank, _, _)| {
+                let last_slot = *tower.last_vote().slots.last().unwrap_or(&0);
+                let first_slot = *tower.last_vote().slots.first().unwrap_or(&0);
+                assert!(first_slot <= last_slot);
+                let new_bank = bank.slot() > last_slot;
```
Comment (carllin) [inline core/src/replay_stage.rs]: i think there's still an issue if the heaviest bank is:

1) Greater than the last voted slot
2) Validators are locked out on that heaviest bank:
3) That heaviest bank has no descendants

I imagine the case with 3 validators, with A: 24%, B: 24%, C: 24%, D: 28% of the stake, where 

A is the leader for slots 1-4, B: 4-8, C: 9-10, and D 11-14. If they each create their own forks then vote on their own forks, D will have the heaviest fork. If D then dies, none of the other validators will vote and make any progress.

File: core/src/replay_stage.rs [hunk 5]
```diff
@@ -645,71 +641,103 @@ impl ReplayStage {
...
-        votable
+    #[allow(clippy::type_complexity)]
+    fn check_fork(
+        ancestors: &HashMap<u64, HashSet<u64>>,
+        tower: &Tower,
+        best_bank: Option<&(u128, Arc<Bank>, HashMap<u64, StakeLockout>, u64)>,
+    ) -> Option<(Arc<Bank>, u64)> {
+        let (_, bank, stake_lockouts, total_staked) = best_bank?;
+        let vote_threshold =
+            tower.check_vote_stake_threshold(bank.slot(), &stake_lockouts, *total_staked);
```
Comment (carllin) [inline core/src/replay_stage.rs]: is this check already made earlier in `select_fork`

File: core/src/replay_stage.rs [hunk 6]
```diff
@@ -644,72 +666,145 @@ impl ReplayStage {
...
+            .filter(|(_, stats)| stats.is_recent && !stats.has_voted && stats.vote_threshold)
+            .collect();
 
-        votable.sort_by_key(|b| b.0);
-        let ms = timing::duration_as_ms(&tower_start.elapsed());
+        //highest weight, lowest slot first
+        votable.sort_by_key(|b| (b.1.weight, 0i64 - b.1.slot as i64));
 
+        votable.iter().for_each(|(_, stats)| {
+            let mut parents: Vec<_> = if let Some(set) = ancestors.get(&stats.slot) {
```
Comment (carllin) [inline core/src/replay_stage.rs]: Is this just for logging purposes?

File: core/src/replay_stage.rs [hunk 7]
```diff
@@ -644,72 +666,145 @@ impl ReplayStage {
...
+        }
+        let mut rv = None;
+        let (best_bank, best_stats) = best_banks.last().unwrap();
+        debug!("best bank: {:?}", best_stats);
+        let mut by_slot: Vec<_> = best_banks.iter().collect();
+        by_slot.sort_by_key(|x| x.1.slot);
+        //look for the oldest ancestors of the best bank
+        if let Some(best_ancestors) = ancestors.get(&best_stats.slot) {
+            for (parent, parent_stats) in by_slot.iter() {
+                if parent_stats.is_locked_out {
```
Comment (carllin) [inline core/src/replay_stage.rs]: You want to set the "heaviest" (second item in the tuple) even if the bank is locked out so we can reset PoH recorder right?

File: core/src/replay_stage.rs [hunk 8]
```diff
@@ -644,72 +666,145 @@ impl ReplayStage {
...
+                debug!("best bank found ancestor: {}", parent_stats.slot);
+                inc_new_counter_info!("replay_stage-pick_best_fork-ancestor", 1);
+                rv = Some(((*parent).clone(), parent_stats.total_staked));
+            }
+        }
+        //look for the oldest child of the best bank
+        if rv.is_none() {
+            for (child, child_stats) in by_slot.iter().rev() {
+                if child_stats.is_locked_out {
+                    continue;
```
Comment (carllin) [inline core/src/replay_stage.rs]: Do you want to set the "heaviest" (second item in the tuple) to the latest child on this fork, even if the bank is locked out so we can later reset PoH recorder right to the oldest child?

File: core/src/replay_stage.rs [hunk 9]
```diff
@@ -212,51 +228,57 @@ impl ReplayStage {
...
-                        if let Some(votable_leader) =
-                            leader_schedule_cache.slot_leader_at(bank.slot(), Some(&bank))
-                        {
-                            Self::log_leader_change(
-                                &my_pubkey,
-                                bank.slot(),
-                                &mut current_leader,
-                                &votable_leader,
-                            );
+                    loop {
```
Comment (carllin) [inline core/src/replay_stage.rs]: Is this a loop so that you will vote on all the ancestors, the heaviest bank, and then the children?

If there are children, `vote_bank` will skip directly to the child and skip voting for the ancestors +the heaviest bank

File: core/src/replay_stage.rs (hunk 8 above)
Comment (aeyakovenko) [reply core/src/replay_stage.rs]: @carllin i think the right thing to do is to set poh to last vote or heaviest if no vote. Heaviest is always ahead of last vote when we can’t vote on it.

File: core/src/replay_stage.rs (hunk 9 above)
Comment (aeyakovenko) [reply core/src/replay_stage.rs]: @carllin If we switch forks post lockup this will let the validator catch up.

File: core/src/replay_stage.rs (hunk 6 above)
Comment (aeyakovenko) [reply core/src/replay_stage.rs]: Yea. I was dumping the whole tree.

File: core/src/replay_stage.rs (hunk 8 above)
Comment (aeyakovenko) [reply core/src/replay_stage.rs]: It doesn't make sense to rest the Poh to something that doesn't attach to the last vote.

Comment (carllin) [reply core/src/replay_stage.rs]: Hmmm, what's the reasoning for:
1) If not locked out, voting for the oldest child of the best bank
2) If locked out, reset to the best bank, but don't reset to the oldest child of the best bank?

Comment (aeyakovenko) [reply core/src/replay_stage.rs]: The latter creates a fork, since that skips the best bank.

File: core/src/replay_stage.rs [hunk 10]
```diff
@@ -211,51 +230,68 @@ impl ReplayStage {
...
+                                    &bank,
+                                    &poh_recorder,
+                                    &leader_schedule_cache,
+                                );
+                                last_reset = bank.last_blockhash();
+                                tpu_has_bank = false;
+                                info!("vote bank: {} reset bank: {}", vote_bank_slot, bank.slot());
+                                if !partition && vote_bank_slot != bank.slot() {
+                                    warn!("PARTITION DETECTED waiting to join fork: {} last vote: {:?}", bank.slot(), tower.last_vote());
+                                    inc_new_counter_info!("replay_stage-partition_detected", 1);
```
Comment (aeyakovenko) [inline core/src/replay_stage.rs]: @pgarg66 counters

File: core/src/replay_stage.rs [hunk 11]
```diff
@@ -211,51 +230,68 @@ impl ReplayStage {
...
+                                    partition = true;
+                                } else if partition && vote_bank_slot == bank.slot() {
+                                    warn!("PARTITION resolved fork: {} last vote: {:?}", bank.slot(), tower.last_vote());
+                                    partition = false;
+                                    inc_new_counter_info!("replay_stage-partition_resolved", 1);
```
Comment (aeyakovenko) [inline core/src/replay_stage.rs]: @pgarg66 resolved counter

File: local-cluster/tests/local_cluster.rs [hunk 12]
```diff
@@ -256,19 +256,16 @@ fn run_network_partition(partitions: &[usize]) {
 }
 
 #[test]
-#[serial]
```
Comment (sagar-solana) [inline local-cluster/tests/local_cluster.rs]: This can have really weird behavior with local cluster tests. I wouldn't recommend unless you're confident it's stable like this. It's going to run multiple validators on the same system. It'll crush it.
