### PR TITLE
Register SendTransactionService exit

### LINKED ISSUE #31079: Fatal error didn't kill the validator process
#### Problem

When `accounts_hash_verifier` throw a Fatal error, the validator process is not killed. It seems that ` send_transaction_service` wasn't shutdown when the Fatal error was thrown. 

```
[2023-04-06T00:12:37.026785091Z ERROR solana_core::accounts_hash_verifier] Fatal! Exiting! Known validator 31fxZovs3gBKVVTtC2VJUuKeVoq6mQkLjWnicWhErQ4f produced conflicting hashes for slot: 1140483 (EEfMshSC1sy2qRVFxxnbQXtHYc74uVBaVk2cv1DEegnC != 9yGSXjUusH1xyr74gCr3xEqKiqUhLmbJDdFQMcy7aWSD)
[2023-04-06T00:12:37.041620839Z INFO  solana_core::accounts_hash_verifier] AccountsHashVerifier has stopped
[2023-04-06T00:12:37.041625438Z INFO  solana_metrics::metrics] datapoint: accounts_hash_verifier num-outstanding-accounts-packages=1i num-re-enqueued-accounts-packages=0i enqueued-time-us=209204i handling-time-us=3515432i
[2023-04-06T00:12:37.087225896Z INFO  solana_core::snapshot_packager_service] SnapshotPackagerService has stopped
[2023-04-06T00:12:37.117866188Z WARN  solana_rpc::rpc_subscriptions] RPC Notification thread - already shut down.
[2023-04-06T00:12:37.159094701Z INFO  solana_metrics::metrics] datapoint: Tpu refresh_ip_to_stake_time_us=0i apply_sender_stakes_time_us=0i send_batches_time_us=0i receive_batches_time_ns=0i total_batches=0i total_packets=0i total_discard_random=0i total_discard_random_time_us=0i
[2023-04-06T00:12:37.184166140Z INFO  solana_metrics::metrics] datapoint: tpu_receiver packets_count=0i packet_batches_count=0i full_packet_batches_count=0i channel_len=0i
[2023-04-06T00:12:37.184171791Z INFO  solana_metrics::metrics] datapoint: tpu_vote_receiver packets_count=0i packet_batches_count=0i full_packet_batches_count=0i channel_len=0i
[2023-04-06T00:12:37.184174095Z INFO  solana_metrics::metrics] datapoint: tpu_forwards_receiver packets_count=0i packet_batches_count=0i full_packet_batches_count=0i channel_len=0i
[2023-04-06T00:12:37.243945756Z INFO  solana_metrics::metrics] datapoint: rpc_pubsub_total_subscriptions count=0i
[2023-04-06T00:12:37.326266633Z INFO  solana_runtime::accounts_background_service] AccountsBackgroundService has stopped
[2023-04-06T00:12:37.952695584Z INFO  solana_metrics::metrics] datapoint: send_transaction_service recv-tx=0i recv-duplicate=0i sent-tx=0i retry-queue-overflow=0i retry-queue-size=0i send-us=0i send-attempt-count=0i send-failure-count=0i nonced-tx=0i rooted-tx=0i expired-tx=0i max-retries-exceeded-tx=0i retries=0i failed-tx=0i
...
[2023-04-06T00:12:47.954152185Z INFO  solana_metrics::metrics] datapoint: send_transaction_service recv-tx=0i recv-duplicate=0i sent-tx=0i retry-queue-overflow=0i retry-queue-size=0i send-us=0i send-attempt-count=0i send-failure-count=0i nonced-tx=0i rooted-tx=0i expired-tx=0i max-retries-exceeded-tx=0i retries=0i failed-tx=0i
[2023-04-06T00:12:52.955799446Z INFO  solana_metrics::metrics] datapoint: send_transaction_service recv-tx=0i recv-duplicate=0i sent-tx=0i retry-queue-overflow=0i retry-queue-size=0i send-us=0i send-attempt-count=0i send-failure-count=0i nonced-tx=0i rooted-tx=0i expired-tx=0i max-retries-exceeded-tx=0i retries=0i failed-tx=0i
...
```

#### Proposed Solution
Debug and fix.

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
The SendTransactionService doesn't receive exit signals from the validator, allowing the threads to continue in zombie mode when the validator has otherwise halted.

#### Summary of Changes
Extend the JsonRpcService exit block to signal SendTransactionService when the validator exits, by passing in an AtomicBool instead of creating on inside SendTransactionService

Fixes #31079

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Follow-up work will examine exit and join behavior in JsonRpcService

File: send-transaction-service/src/send_transaction_service.rs [hunk 1]
```diff
@@ -804,12 +806,36 @@ mod test {
...
+            &bank_forks,
+            None,
+            receiver,
+            &connection_cache,
+            1000,
+            1,
+            exit.clone(),
+        );
+
+        exit.store(true, Ordering::Relaxed);
```
Comment (t-nelson) [inline send-transaction-service/src/send_transaction_service.rs:836]: i think exit is going to race the thread spawn here, should probably wait on... something.

similarly need to sit on `join()` after setting exit to ensure the thread stops as intended.

**Review by t-nelson — COMMENTED** [review]
strategy looks good!  i think the test could use a little tightening up though

File: send-transaction-service/src/send_transaction_service.rs (hunk 1 above)
Comment (t-nelson) [reply send-transaction-service/src/send_transaction_service.rs:836]: > should probably wait on... something.

i guess easiest would be to switch to a zero-capacity bounded channel and do a blocking write to it. once thread is up, that message will be consumed and waiter will unblock. at that point it's safe to signal exit

Comment (CriesofCarrots) [reply send-transaction-service/src/send_transaction_service.rs]: Yep, great idea. Done.

File: send-transaction-service/src/send_transaction_service.rs [hunk 2]
```diff
@@ -804,12 +806,55 @@ mod test {
...
+        sender.send(dummy_tx_info()).unwrap();
+
+        thread::spawn(move || {
+            exit.store(true, Ordering::Relaxed);
+        });
+
+        let mut option = Ok(());
+        while option.is_ok() {
+            option = sender.send(dummy_tx_info());
+        }
```
Comment (t-nelson) [inline send-transaction-service/src/send_transaction_service.rs:855]: i'm guessing we do this 'cause `SendTransactionService::join()` looks busted and that will be addressed in the alluded to followup?

**Review by t-nelson — APPROVED** [review]
thanks for the test improvements!

File: send-transaction-service/src/send_transaction_service.rs (hunk 2 above)
Comment (CriesofCarrots) [reply send-transaction-service/src/send_transaction_service.rs:855]: Naw, `join()` looks fine, actually. Ensuring the receiver was dropped was the best thing I thought of to show that updating `exit` outside of the service actually causes stuff to stop. `join()` already sets exit directly. Open to better ideas, though!

Comment (CriesofCarrots) [reply send-transaction-service/src/send_transaction_service.rs:855]: ...post-merge ;)

Comment (CriesofCarrots) [reply send-transaction-service/src/send_transaction_service.rs:855]: Turns out this was wrong. `join()` also needs to ensure the rpc Server is closed.
