### PR TITLE
Hack to skip cleanup_dead_slots upon snapshot load

### LINKED ISSUE #8560: TdS snapshots fail to verify
After TdS restarted, nodes started generating bad snapshots.

STR:
1. Run `solana-validator -l ledger -n 35.203.170.30:8001 --expected-shred-version 5437 --trusted-validator 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8o`

Example failure output:
```
[2020-03-02T05:11:24.363024211Z INFO  solana_validator]   Downloaded http://175.113.78.40:8899/snapshot-2216292-CcAbAUEz9B37pANfVDfXXx84XKwa8BZz7z6enUnD1i3R.tar.bz2 (90315267 bytes) in 5.223901195s
[2020-03-02T05:11:24.404712301Z WARN  solana_core::validator] identity pubkey: 63MGLbDbPnFrBAmhb7HstjPiF6gnvhhj8qeLB3gCfErM
[2020-03-02T05:11:24.404730801Z WARN  solana_core::validator] vote pubkey: 9QLgBAgjzDkf3Y7rP15zywMBgxVJc2HC87yG4ubRq7SL
[2020-03-02T05:11:24.404734801Z WARN  solana_core::validator] CUDA is disabled
[2020-03-02T05:11:24.404736601Z INFO  solana_core::validator] AVX detected
[2020-03-02T05:11:24.404737901Z INFO  solana_core::validator] entrypoint: Some(ContactInfo { id: 11111111111111111111111111111111, gossip: V4(35.203.170.30:8001), tvu: V4(0.0.0.0:0), tvu_forwards: V4(0.0.0.0:0), repair: V4(0.0.0.0:0), tpu: V4(0.0.0.0:0), tpu_forwards: V4(0.0.0.0:0), storage_addr: V4(0.0.0.0:0), rpc: V4(0.0.0.0:0), rpc_pubsub: V4(0.0.0.0:0), serve_repair: V4(0.0.0.0:0), wallclock: 1583125871245, shred_version: 0 })
[2020-03-02T05:11:24.404748901Z INFO  solana_core::validator] Initializing sigverify, this could take a while...
[2020-03-02T05:11:24.404750401Z INFO  solana_core::validator] Done.
[2020-03-02T05:11:24.404751601Z INFO  solana_core::validator] creating bank...
[2020-03-02T05:11:24.406324700Z INFO  solana_core::validator] genesis hash: 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY
[2020-03-02T05:11:24.406352700Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 65000
[2020-03-02T05:11:24.640746842Z INFO  solana_ledger::blockstore] "/ws/mvines/ledger/rocksdb" open took 234ms
[2020-03-02T05:11:24.641732041Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "/ws/mvines/ledger/snapshot"
[2020-03-02T05:11:24.642197241Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "/ws/mvines/ledger/snapshot-2216292-CcAbAUEz9B37pANfVDfXXx84XKwa8BZz7z6enUnD1i3R.tar.bz2"
[2020-03-02T05:19:50.800598475Z INFO  solana_ledger::snapshot_utils] snapshot untar took 506.2s
[2020-03-02T05:19:50.800633275Z INFO  solana_ledger::snapshot_utils] snapshot version: 1.0.0
[2020-03-02T05:19:50.800659075Z INFO  solana_ledger::snapshot_utils] Loading bank from "/ws/mvines/ledger/snapshot/.tmpbYWB3X/snapshots/2216292/2216292"
[2020-03-02T05:19:50.804684486Z INFO  solana_ledger::snapshot_utils] Rebuilding accounts...
[2020-03-02T05:29:14.829520614Z INFO  solana_ledger::snapshot_utils] Rebuilding status cache...
[2020-03-02T05:29:14.838537823Z INFO  solana_ledger::snapshot_utils] Loaded bank for slot: 2216292
[2020-03-02T05:29:14.838634424Z INFO  solana_runtime::accounts_db] total_stores: 8386, newest_slot: 2216292, oldest_slot: 0, max_slot: 2146936 (num=9), min_slot: 2171751 (num=1)
[2020-03-02T05:29:14.838693924Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=8386i
[2020-03-02T05:29:14.860167947Z WARN  solana_runtime::accounts_db] mismatched bank hash for slot 2216292: HnoDAJopjHyKQsp2rohY4SYRhkZeVdAw7wxcHkyHqCUC (calculated) != CcAbAUEz9B37pANfVDfXXx84XKwa8BZz7z6enUnD1i3R (expected)
[2020-03-02T05:29:14.860186447Z WARN  solana_runtime::accounts] verify_bank_hash failed: MismatchedBankHash
thread 'main' panicked at 'Snapshot bank for slot 2216292 failed to verify', ledger/src/snapshot_utils.rs:458:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2020-03-02T05:29:14.860235447Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Snapshot bank for slot 2216292 failed to verify', ledger/src/snapshot_utils.rs:458:9" location="ledger/src/snapshot_utils.rs:458:9"
```

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

A validator started from snapshot may create bad snapshots, which cause bank hash mismatch error when consumed by other validators. This is because the validator internally removes too much AccountsStorage and bad snapshots don't include some necessary ones anymore.

#### Detail of problem

`generate_index` has been broken for long time about maintaining the correct count of storage's counts, which confuses `purge_zero_lamport_accounts()` (demonstrating assertion are currently disabled in this pr, real fix #8337 is pending).
This causes too many slots to be incorrectly marked as dead.
However, it hadn't caused problems because `cleanup_dead_slots()` had been broken too when called immediately after snapshot restoration. That function didn't remove `dead_slots` at all in that case.
In short, the caller wrongly requested too many `slot`s to remove and the callee wrongly didn't  anything. So, there had been a peace...

But it changed since #8148. This PR is needed as one of fixes for the enlarged snapshot issue #8168. And that PR was thought rather harmless..

After #8148, the callee started to remove actually. But things don't break immediately. Snapshots load successfully. And validator just works.
Its rather subtle ramification of unbalanced fix is at the future snapshot creation: Because `purge_zero_lamport_accounts()` incorrectly removes too many slots as dead in some corner case, newly-created snapshots silently start to omit to include that removed `storage`s backing that slots, causing the deadly `BankHashMismatch` error because of obvious incorrect view into the accounts set.

#### Summary of Changes

Until #8337 lands, just disable erroneous too eager removing behavior as an ugly hack...
This PR should have the same effect as reverting #8148, with better merge-conflict-free characteristics. #8337 should revert most of changes in this PR.

Fixes #8560  

Backport only to v1.0 because v0.23 was branched before #8148.

### CODE REVIEW

**Comment by mvines** [comment]
> Fixes #8157
Do you mean #8560 :)

**Comment by ryoqun** [comment]
> > Fixes #8157
> > Do you mean #8560 :)

Err, fixed!

**Comment by ryoqun** [comment]
This PR is first worked on the `v0.23` branch. And it worked for the TdS cluster:


Good:
```
$ SOLANA_DISABLE_SNAPSHOT_COMPRESSION=1 LD_LIBRARY_PATH=. ../solana-ledger-tool --ledger newnew verify
4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY
[2020-03-02T15:33:25.021043796Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 65000
[2020-03-02T15:33:25.171329871Z INFO  solana_ledger::blockstore] "/mnt/solana-data/tds-with-1.0/try5/newnew/rocksdb" open took 150ms
[2020-03-02T15:33:25.171369731Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "/mnt/solana-data/tds-with-1.0/try5/newnew/snapshot"
[2020-03-02T15:33:25.172079797Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "/mnt/solana-data/tds-with-1.0/try5/newnew/snapshot-2197060-5qTAFmWaeyxmG6qXCeZS1ojH4rXmZVKA5VD5FGh6JpeF.tar.bz2"
[2020-03-02T15:35:52.747607712Z INFO  solana_ledger::snapshot_utils] snapshot untar took 147.6s
[2020-03-02T15:35:52.748096905Z INFO  solana_ledger::snapshot_utils] snapshot version: 1.0.0
[2020-03-02T15:35:52.748388028Z INFO  solana_ledger::snapshot_utils] Loading bank from "/mnt/solana-data/tds-with-1.0/try5/newnew/snapshot/.tmpLsCCXO/snapshots/2197060/2197060"
[2020-03-02T15:35:52.759477979Z INFO  solana_ledger::snapshot_utils] Rebuilding accounts...
[2020-03-02T15:36:21.534868800Z INFO  solana_ledger::snapshot_utils] Rebuilding status cache...
[2020-03-02T15:36:21.544955475Z INFO  solana_ledger::snapshot_utils] Loaded bank for slot: 2197060
[2020-03-02T15:36:21.545063955Z INFO  solana_runtime::accounts_db] total_stores: 8243, newest_slot: 2197060, oldest_slot: 0, max_slot: 2051388 (num=9), min_slot: 2171643 (num=1)
[2020-03-02T15:36:21.545102206Z INFO  solana_metrics::metrics] metrics disabled: SOLANA_METRICS_CONFIG: environment variable not found
[2020-03-02T15:36:21.545280127Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=8243i
[2020-03-02T15:36:21.549511832Z WARN  solana_runtime::accounts_db] mismatched bank hash for slot 2197060: 9brAU4C5d5gq5QABjHmLex2L3nCgHyfN8yvjdwpfxhbs (calculated) != 5qTAFmWaeyxmG6qXCeZS1ojH4rXmZVKA5VD5FGh6JpeF (expected)
[2020-03-02T15:36:21.549549442Z WARN  solana_runtime::accounts] verify_bank_hash failed: MismatchedBankHash
thread 'main' panicked at 'Snapshot bank for slot 2197060 failed to verify', ledger/src/snapshot_utils.rs:459:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Bad:
```
$ SOLANA_DISABLE_SNAPSHOT_COMPRESSION=1 LD_LIBRARY_PATH=. ../solana-ledger-tool --ledger newne2w verify
Unable to access ledger path: Os { code: 2, kind: NotFound, message: "No such file or directory" }
ubuntu@ip-10-163-204-165:/mnt/solana-data/tds-with-1.0/try5$ SOLANA_DISABLE_SNAPSHOT_COMPRESSION=1 LD_LIBRARY_PATH=. ../solana-ledger-tool --ledger newnew2 verify
4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY
[2020-03-02T15:37:55.980479001Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 65000
[2020-03-02T15:37:56.131472895Z INFO  solana_ledger::blockstore] "/mnt/solana-data/tds-with-1.0/try5/newnew2/rocksdb" open took 150ms
[2020-03-02T15:37:56.131511955Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "/mnt/solana-data/tds-with-1.0/try5/newnew2/snapshot"
[2020-03-02T15:37:56.132156101Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "/mnt/solana-data/tds-with-1.0/try5/newnew2/snapshot-2197060-5qTAFmWaeyxmG6qXCeZS1ojH4rXmZVKA5VD5FGh6JpeF.tar.bz2"
[2020-03-02T15:40:24.581907876Z INFO  solana_ledger::snapshot_utils] snapshot untar took 148.4s
[2020-03-02T15:40:24.582213748Z INFO  solana_ledger::snapshot_utils] snapshot version: 1.0.0
[2020-03-02T15:40:24.582263369Z INFO  solana_ledger::snapshot_utils] Loading bank from "/mnt/solana-data/tds-with-1.0/try5/newnew2/snapshot/.tmplEzmay/snapshots/2197060/2197060"
[2020-03-02T15:40:24.588455472Z INFO  solana_ledger::snapshot_utils] Rebuilding accounts...
[2020-03-02T15:40:54.062114769Z INFO  solana_ledger::snapshot_utils] Rebuilding status cache...
[2020-03-02T15:40:54.072846722Z INFO  solana_ledger::snapshot_utils] Loaded bank for slot: 2197060
[2020-03-02T15:40:54.072954272Z INFO  solana_runtime::accounts_db] total_stores: 8305, newest_slot: 2197060, oldest_slot: 0, max_slot: 351916 (num=9), min_slot: 2176477 (num=1)
[2020-03-02T15:40:54.072991783Z INFO  solana_metrics::metrics] metrics disabled: SOLANA_METRICS_CONFIG: environment variable not found
[2020-03-02T15:40:54.073156774Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=8305i
[2020-03-02T15:40:54.077952076Z INFO  solana_runtime::accounts_db] scan took 98us merge took 41us accumulate took 96us
[2020-03-02T15:40:54.077974226Z INFO  solana_runtime::bank] bank frozen: 2197060 hash: BDwmWnqkWeh4TcQwQUWmB9QZta9s73pQ9RgAkPbvAk6p accounts_delta: 8FLMLAJgMvpembgKg1PeGSJqK7rjUozxPLFyE5N5tkmC signature_count: 214 last_blockhash: 4xpY2b9aNytXX1o14drKg69bghYA3ivdGmdJd7JDviBE
[2020-03-02T15:40:54.078007006Z INFO  solana_runtime::bank] accounts hash slot: 2197060 stats: BankHashStats { num_removed_accounts: 214, num_added_accounts: 0, num_lamports_stored: 10398257827013, total_data_len: 545806, num_executable_accounts: 0 }
[2020-03-02T15:40:54.078039867Z INFO  solana_ledger::snapshot_utils] bank rebuild from snapshot took 29.5s
[2020-03-02T15:40:54.096521526Z INFO  solana_ledger::blockstore_processor] processing ledger from root slot 2197060...
[2020-03-02T15:40:54.161023055Z INFO  solana_ledger::blockstore_processor] ledger processed in 64ms. 83 MB allocated. 1 fork at 2197060, with 1 frozen bank
Ok

```

File: runtime/src/accounts_db.rs [hunk 1]
```diff
@@ -2332,15 +2339,42 @@ pub mod tests {
         accounts.store(current_slot, &[(&dummy_pubkey, &dummy_account)]);
         accounts.add_root(current_slot);
 
-        purge_zero_lamport_accounts(&accounts, current_slot);
-        let accounts = reconstruct_accounts_db_via_serialization(&accounts, current_slot);
+        let (accounts, skip_account_assertion) = f(accounts, current_slot);
+
+        assert_eq!(4, accounts.accounts_index.read().unwrap().roots.len());
+        if skip_account_assertion {
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs]: The following assertion causes failure currently for test_accounts_purge_chained_purge_after_snapshot_restore.

This should be fixed by #8337

**Comment by mvines** [comment]
Bench failure is unrelated, :shipit:

**Comment by ryoqun** [comment]
This got needed in the v0.23 branch for #8436

**Comment by ryoqun** [comment]
@Mergifyio refresh
