### PR TITLE
Calculate account refs fix

### LINKED ISSUE #9431: Bad snapshot created on warehouse mainnet-beta nodes running v1.0.14
#### Problem

```
[2020-04-10T10:17:54.252736523Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 65536
[2020-04-10T10:17:54.253330868Z INFO  solana_ledger::blockstore] Opening database at "/home/sol/snapshot-check/rocksdb"
[2020-04-10T10:17:54.458421763Z INFO  solana_ledger::blockstore] "/home/sol/snapshot-check/rocksdb" open took 205ms
[2020-04-10T10:17:54.458503174Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "/home/sol/snapshot-check/snapshot"
[2020-04-10T10:17:54.459968072Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "/home/sol/snapshot-check/snapshot-4770249-4
[2020-04-10T10:18:05.021372721Z INFO  solana_ledger::snapshot_utils] snapshot untar took 10.6s
[2020-04-10T10:18:05.022530605Z INFO  solana_ledger::snapshot_utils] snapshot version: 1.1.0
[2020-04-10T10:18:05.022846772Z INFO  solana_ledger::snapshot_utils] Loading bank from "/home/sol/snapshot-check/snapshot/.tmpArAsi3/snapshot
[2020-04-10T10:18:05.032469937Z INFO  solana_ledger::snapshot_utils] Rebuilding accounts...
[2020-04-10T10:18:07.419037126Z INFO  solana_ledger::snapshot_utils] Rebuilding status cache...
[2020-04-10T10:18:07.447397802Z INFO  solana_ledger::snapshot_utils] Loaded bank for slot: 4770249
[2020-04-10T10:18:07.447625073Z INFO  solana_runtime::accounts_db] total_stores: 1133, newest_slot: 4770249, oldest_slot: 0, max_slot: 477024
[2020-04-10T10:18:07.447772246Z INFO  solana_metrics::metrics] metrics configuration: host=https://metrics.solana.com:8086 db=mainnet-beta us
[2020-04-10T10:18:07.447994191Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=1133i
[2020-04-10T10:18:07.476960141Z WARN  solana_runtime::accounts_db] mismatched bank hash for slot 4770249: 687b6oxzAben8tmZvGVxZ6LmnPiB3tqcYRW
[2020-04-10T10:18:07.477002898Z WARN  solana_runtime::accounts] verify_bank_hash failed: MismatchedBankHash
thread 'main' panicked at 'Snapshot bank for slot 4770249 failed to verify', ledger/src/snapshot_utils.rs:461:9
```

#### Proposed Solution

Debug and fix.

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

cleanup function does not handle cascading deletes

#### Summary of Changes

Use recursive dependency calculation to prevent premature deletes.

Fixes #9431

### CODE REVIEW

File: runtime/src/accounts_db.rs [hunk 1]
```diff
@@ -701,6 +701,74 @@ impl AccountsDB {
...
+                        if *store_counts.get(&account_info.store_id).unwrap() != 0 {
+                            no_delete = true;
+                            break;
+                        }
+                    }
+                    no_delete
+                };
+            if no_delete {
+                for (_slot_id, account_info) in account_infos {
+                    *store_counts.get_mut(&account_info.store_id).unwrap() += 1;
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:760]: nits: I think this increment is redundant because we always [increment for `account_info.store_id`](https://github.com/solana-labs/solana/pull/9447/files#diff-2099c5256db4eb5975c8834af38f6456R713) unless `already_counted`, which is always `true` for the first time.

File: runtime/src/accounts_db.rs [hunk 2]
```diff
@@ -701,6 +701,74 @@ impl AccountsDB {
...
+    ) {
+        if already_counted.contains(&id) {
+            return;
+        }
+        *store_counts.get_mut(&id).unwrap() += 1;
+        let mut keys = HashSet::new();
+        for (key, account_infos) in purges {
+            for (_slot, account_info) in account_infos {
+                if account_info.store_id == id {
+                    keys.insert(key);
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:718]: can add `break` here?

File: runtime/src/accounts_db.rs [hunk 3]
```diff
@@ -701,6 +701,74 @@ impl AccountsDB {
...
+        id: AppendVecId,
+        purges: &HashMap<Pubkey, Vec<(Slot, AccountInfo)>>,
+        store_counts: &mut HashMap<AppendVecId, usize>,
+        already_counted: &mut HashSet<AppendVecId>,
+    ) {
+        if already_counted.contains(&id) {
+            return;
+        }
+        *store_counts.get_mut(&id).unwrap() += 1;
+        let mut keys = HashSet::new();
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:714]: nits: rename to `{affected/cacading}_pubkeys` or at least `pubkeys`?

File: runtime/src/accounts_db.rs [hunk 4]
```diff
@@ -701,6 +701,74 @@ impl AccountsDB {
...
+        for (key, account_infos) in purges {
+            for (_slot, account_info) in account_infos {
+                if account_info.store_id == id {
+                    keys.insert(key);
+                }
+            }
+        }
+        already_counted.insert(id);
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:722]: nits: This could be moved to [its related code here](https://github.com/solana-labs/solana/pull/9447/files#diff-2099c5256db4eb5975c8834af38f6456R7) immediately after the `if` or create `else`.

File: runtime/src/accounts_db.rs [hunk 5]
```diff
@@ -701,6 +701,74 @@ impl AccountsDB {
         accounts_index.uncleaned_roots.clear();
     }
 
+    fn inc_store_counts(
+        id: AppendVecId,
```
Comment (ryoqun) [inline runtime/src/accounts_db.rs:705]: nits: rename to `undeletable_id` or `no_delete_id`?

File: runtime/src/accounts_db.rs (hunk 2 above)
Comment (sakridge) [reply runtime/src/accounts_db.rs:718]: Don't think so. it needs to find all affected keys by this storage id.

Comment (sakridge) [reply runtime/src/accounts_db.rs]: ah, you're right, from the inner loop it can break.
