### PR TITLE
Enforce a minimum of 1 on full and incremental snapshot retention

### LINKED ISSUE #30794: Validator will panic when `--maximum-snapshots-to-retain 0` is specified
#### Problem

Someone on Discord reported hitting a panic when specifying `--maximum-snapshots-to-retain 0`; this was presumably with v1.13.6 (not sure yet) but I was able to reproduce the problem with the tip of master.

Panic:
```
   0: rust_begin_unwind
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
[2023-03-20T07:51:37.436181995Z INFO  solana_metrics::metrics] datapoint: poh-service ticks=181i hashes=2303680i elapsed_us=355121i total_sleep_us=784971i total_tick_time_us=395i total_lock_time_us=1975i total_hash_time_us=189870i total_record_time_us=0i total_send_record_result_us=0i
   3: core::option::Option<T>::unwrap
             at ./rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:778:21
   4: solana_core::snapshot_packager_service::SnapshotGossipManager::push_snapshot_hash
             at ./home/sol/src/solana/core/src/snapshot_packager_service.rs:250:50
[2023-03-20T07:51:37.443438653Z INFO  solana_metrics::metrics] datapoint: shrink_stats num_slots_shrunk=7i storage_read_elapsed=2115i index_read_elapsed=24720i create_and_insert_store_elapsed=437i store_accounts_elapsed=3488i update_index_elapsed=16258i handle_reclaims_elapsed=0i remove_old_stores_shrink_us=50i rewrite_elapsed=20201i drop_storage_entries_elapsed=0i recycle_stores_write_time=0i accounts_removed=419i bytes_removed=524288i bytes_written=2039808i skipped_shrink=0i alive_accounts=5337i dead_accounts=419i accounts_loaded=5756i
[2023-03-20T07:51:37.443572347Z INFO  solana_metrics::metrics] datapoint: accounts_db_active shrink=0i
   5: solana_core::snapshot_packager_service::SnapshotPackagerService::new::{{closure}}
             at ./home/sol/src/solana/core/src/snapshot_packager_service.rs:102:29
```
I see the following log:
```
[2023-03-20T07:51:36.454866749Z INFO  solana_runtime::snapshot_utils] Purging old full snapshot archives in /home/sol/ledger, retaining up to 0 full snapshots
```
This log corresponds to the below function:
https://github.com/solana-labs/solana/blob/cd7fe7674495e667e6c9168363dd66e31730bc52/runtime/src/snapshot_utils.rs#L2045-L2050
where we explicitly have some logic to keep at least one snapshot (even if user specified 0):
https://github.com/solana-labs/solana/blob/cd7fe7674495e667e6c9168363dd66e31730bc52/runtime/src/snapshot_utils.rs#L2061-L2064

However, we don't have similar logic to retain at least one element in:
https://github.com/solana-labs/solana/blob/cd7fe7674495e667e6c9168363dd66e31730bc52/runtime/src/snapshot_package.rs#L341-L347

which is called here by `SnapshotGossipManager::push_full_snapshot_hash()`:
https://github.com/solana-labs/solana/blob/cd7fe7674495e667e6c9168363dd66e31730bc52/core/src/snapshot_packager_service.rs#L271-L274

As a result, `SnapshotGossipManager::push_full_snapshot_hash()` with `self.max_full_snapshot_hashes == 0` will empty `self.full_snapshot_hashes.hashes`. This happens at least once at startup via `SnapshotGossipManager::push_starting_snapshot_hashes()`:
https://github.com/solana-labs/solana/blob/cd7fe7674495e667e6c9168363dd66e31730bc52/core/src/snapshot_packager_service.rs#L222-L234

so when the first incremental snapshot is created and we go push that update via:
https://github.com/solana-labs/solana/blob/cd7fe7674495e667e6c9168363dd66e31730bc52/core/src/snapshot_packager_service.rs#L238-L242 

this `.last()` will be a `None`, and the following `unwrap()` will panic as above:
https://github.com/solana-labs/solana/blob/cd7fe7674495e667e6c9168363dd66e31730bc52/core/src/snapshot_packager_service.rs#L250

#### Proposed Solution
Two possibilities come to mind, possibly we want both:
1) Enforce minimum snapshot retention to be at least 1 at command line level in `validator.rs`
2) Confirm 1-snapshot-minimum-retention is valid and enforce that everywhere, or make code more tolerant to 0-snapshot-minimum-retention

### PR DESCRIPTION
**Pull request by steviez**
#### Problem
Retaining 0 full or incremental snapshots doesn't make a lot of sense, since that would mean immediately purging any created snapshots. Moreso, we have some code in place that already assumed that these values would be > 0.

#### Summary of Changes
This changes the snapshots_to_retain config parameters from usize to NonZeroUsize to enforce that values must be nonzero.

Fixes #30794

### CODE REVIEW

File: runtime/src/snapshot_utils.rs [hunk 1]
```diff
@@ -3868,15 +3874,7 @@ mod tests {
         let expected_snapshots = vec![&snap3_name];
         common_test_purge_old_snapshot_archives(
             &snapshot_names,
-            1,
-            DEFAULT_MAX_INCREMENTAL_SNAPSHOT_ARCHIVES_TO_RETAIN,
-            &expected_snapshots,
-        );
-
-        // retaining 0, but minimum to retain is 1
```
Comment (steviez) [inline runtime/src/snapshot_utils.rs:3876]: This test case no longer valid as the type now specifically prevent this

File: validator/src/main.rs [hunk 2]
```diff
@@ -1394,9 +1395,12 @@ pub fn main() {
 
     let maximum_local_snapshot_age = value_t_or_exit!(matches, "maximum_local_snapshot_age", u64);
     let maximum_full_snapshot_archives_to_retain =
-        value_t_or_exit!(matches, "maximum_full_snapshots_to_retain", usize);
-    let maximum_incremental_snapshot_archives_to_retain =
-        value_t_or_exit!(matches, "maximum_incremental_snapshots_to_retain", usize);
+        value_t_or_exit!(matches, "maximum_full_snapshots_to_retain", NonZeroUsize);
```
Comment (steviez) [inline validator/src/main.rs:1398]: As-is, the error emitted here will be:
```
error: Invalid value: The argument '0' isn't a valid value
```
I could see this being kind of confusing, and I could do `value_t!()`, map the result and spit out a more specific error message (ie naming the argument); thoughts?

Comment (steviez) [reply validator/src/main.rs:1398]: Yeah, that works for me. I was initially looking/thinking of using `.validator()` when we discussed this issue last week; not sure why I went away from it but I like that it gets the boilerplate logic out of the main function
