### PR TITLE
Fix RpcClient MemCmp filter version mapping

### LINKED ISSUE #28265: MemcmpEncodedBytes Base58 Variant Deprecated on Devnet?
When running gPA calls on devnet nodes using the Base58 variant of [MemcmpEncodedBytes](https://docs.rs/solana-client/1.14.5/solana_client/rpc_filter/enum.MemcmpEncodedBytes.html) I get the following error:

```
Error: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`.
```

This happens across multiple RPC nodes and providers, but so far only on devnet: 

* QuickNode
* Triton/RPC Pool
* https:/api.devnet.solana.com

Example code for rpc filter config:

```rust
  let filter = RpcFilterType::Memcmp(Memcmp {
        offset: 326,
        bytes: MemcmpEncodedBytes::Base58(creator.to_string()),
        encoding: None,
    });
```

If I change the variant to `Binary` the calls no longer return the error. 

The docs say the `Binary` variant is deprecated, not `Base58`. 

Screen Shot 2022-10-06 at 8 41 37 AM

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
As per #28413, using the latest master version, the command `program show --programs` presents the following error when using `--url devnet`
```
Error: RPC response error -32602: Invalid params: unknown variant `base58`, expected `binary`. 
```

This is because there was a rpc-client version check for nodes below v1.11.2 which didn't get updated when v1.10 got tied to v1.13 and v1.11 got warped to v1.14.

#### Summary of Changes
Add VersionReq struct to provide tooling to handle cases when we need to match on multiple, non-contiguous versions.
Update mapping in MemCmp filters to check for versions before `v1.11.2` and any `v1.13` patch.

Replaces #28413 as fix, but I also want to consider that change for efficiency reasons
Fixes #28265

### CODE REVIEW

File: rpc-client-api/src/filter.rs [hunk 1]
```diff
@@ -263,7 +264,8 @@ pub fn maybe_map_filters(
     node_version: Option<semver::Version>,
     filters: &mut [RpcFilterType],
 ) -> Result<(), String> {
-    if node_version.is_none() || node_version.unwrap() < semver::Version::new(1, 11, 2) {
+    let version_reqs = VersionReq::from_strs(&["<1.11.2", "~1.13"])?;
+    if node_version.is_none() || version_reqs.matches(&node_version.unwrap()) {
```
Comment (t-nelson) [inline rpc-client-api/src/filter.rs:268]: nit: can we switch this to a `.map().unwrap_or()`.  the double-option-eval makes my eye twitch

File: rpc-client-api/src/version_req.rs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+        let mut version_reqs = vec![];
+        for version in versions {
+            let version_req = semver::VersionReq::parse(version.as_ref())
+                .map_err(|err| format!("Could not parse version {:?}: {:?}", version, err))?;
+            version_reqs.push(version_req);
+        }
+        Ok(Self(version_reqs))
+    }
+
+    pub(crate) fn matches(&self, version: &semver::Version) -> bool {
```
Comment (t-nelson) [inline rpc-client-api/src/version_req.rs:17]: maybe rename to `matches_any` to allude to inner behavior?

**Review by t-nelson — DISMISSED** [review]
lgtm, just nits.  thanks!
