### PR TITLE
Purges all bank snapshots after fastboot

### LINKED ISSUE #35190: sudo reboot mb validator recovery fails
#### Problem

1.17.20, 10-12 Feb 2024.

I was curious about a mb validator’s recovery ability. And so I used a spare non-voting mb validator to see if it could recover from an abrupt ```sudo reboot``` 

I ran default validator settings, so incremental snapshots happen every minute and full-snapshots every 3 hours. 

I tried 2 different validator startup scripts:
Setup A: included ```—use-snapshot-archives-at-startup when newest```
Setup B: it was removed

```sudo reboot``` when incremental snapshots are available and less than 1 minute old:

Setup A: 3 reboots, 3 successful recoveries in approx 13 mins
Setup B: 3 reboots, 3 successful recoveries in approx 15 mins

So far so good!

However, approximately 10 mins before the 3-hour full snapshot is due, the validator stops creating minute-by-minute incrementals and starts only creating the next full snapshot. This means the incremental gets up to ~15 mins old. [At least, this is my interpretation of what it looks like its doing!]. 

```sudo reboot``` at various times with old incremental during full snapshot creation:

Setup A:
Incremental 8 mins old:    Failed
Incremental 6 mins old:     Failed
Incremental 5 mins old:    Failed

Setup B:
Incremental 7 mins old:    Success, took 19 mins 
Incremental 9 mins old:     Success, took 20 mins
Incremental 13 mins old:     Success, took 23 mins

For Setup A, each time it failed for ```ERROR solana_ledger::bank_forks_utils] Failed to load bank: AccountsFile error: AppendVecError: incorrect layout/length/data in the appendvec at path /mnt/solana-accounts/run/247471897.30603``` 

#### Proposed Solution
On the advice of Brooks in the discord this issue is opened to address Setup A failing

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Given the following scenario:

* a (bank) snapshot interval of 100
* a node starts up and loads from a bank snapshot at slot 200 (i.e. fastboot)
* the node crashes shortly after load; before the next bank snapshot is taken (before slot 300)
* and `shrink` *has* run (e.g. shrink proceeds up to slot 275)
* the node restarts, still with fastboot enabled

Then the result is:

* due to `shrink`, the account storage files on disk will (may) have changed, and reflect the account state as of slot 275
* the bank snapshot at 200 has hard links to the account storage files, and those account storage files may have been shrunk
* the bank snapshot contains information about the accounts as of slot 200, but the actual storages reflect the accounts as of slot 275
* at startup, the bank snapshot at slot 200 will be selected for fastboot again, and the node will crash, saying that the/an account storage file does not hold the correct number of accounts

If the node has a script to auto-restart, it will enter a boot-crash loop indefinitely.

#### Summary of Changes

To break out of the boot-crash loop, purge all bank snapshots after loading from one. In the above scenario, this would cause the node to load from a snapshot archive instead, which is safe. If the node crashes *after* creating another bank snapshot, then fastboot will work properly again in that situation.

Fixes #35190

#### More Info

This problem has been hit on v1.17, so I want a solution that can be backported to v1.17. The implemented solution is the least invasive—and safest—one I am aware of. A different solution to allow successfully reusing the bank snapshot from slot 200 will land in `master` and *not* be backported.

### CODE REVIEW

**Comment by jeffwashington** [comment]
> > @brooksprumo can you please link the pr that adds `purge_all_bank_snapshots` that I think also must be backported?
> 
> I wasn't originally intending to backport #35291. Instead I was planning on using the previous way to purge all bank snapshots:
> 
> ```rust
> snapshot_utils::purge_old_bank_snapshots(&snapshot_config.bank_snapshots_dir, 0, None);
> ```
> 
> Would backporting #35291 be preferred?
> 
> My though process was the backport the least amount of code possible.

so the backport pr from this pr into 1.18 would be manually adjusted so it compiles in 1.18?

**Comment by jeffwashington** [comment]
> > > @brooksprumo can you please link the pr that adds `purge_all_bank_snapshots` that I think also must be backported?
> > 
> > 
> > I wasn't originally intending to backport #35291. Instead I was planning on using the previous way to purge all bank snapshots:
> > ```rust
> > snapshot_utils::purge_old_bank_snapshots(&snapshot_config.bank_snapshots_dir, 0, None);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would backporting #35291 be preferred?
> > My though process was the backport the least amount of code possible.
> 
> so the backport pr from this pr into 1.18 would be manually adjusted so it compiles in 1.18?

ugh. another approach is to submit what will compile in 1.18 in THIS pr and then backport that, then in a follow on master pr, change this code to use `purge_old_bank_snapshots` That leaves the commit in 1.18 matching a commit in master exactly.

Another alternative is don't backport anything, at least not to 1.17.

any other opinions? Am I being too pedantic?

File: ledger/src/bank_forks_utils.rs [hunk 1]
```diff
@@ -337,6 +337,15 @@ fn bank_forks_from_snapshot(
             source: err,
             path: bank_snapshot.snapshot_path(),
         })?;
+
+        // If the node crashes before taking the next bank snapshot, the next startup will attempt
+        // to load from the same bank snapshot again. And if `shrink` has run, the account storage
+        // files that are hard linked in bank snapshot will be *different* than what the bank
+        // snapshot exists.  This would cause the node to crash again.  To prevent that, purge all
```
Comment (apfitzge) [inline ledger/src/bank_forks_utils.rs:344]: Is this a typo?
"exists" -> "expects"

**Review by jeffwashington — APPROVED** [review]
lgtm. ty.

**Review by apfitzge — APPROVED** [review]
lgtm - easy backport.
