### PR TITLE
Push perf test results to slack app

### LINKED ISSUE #6389: Push automated regression test results to Slack for visibility
#### Problem

If test results only live in buildkite, we will never see them.

#### Proposed Solution

Push any new test results to Slack where they will have visibility.  Use the incoming Webhooks setup to post data to an app.

### PR DESCRIPTION
**Pull request by danpaul000**
#### Problem

We need to have any automated/scheduled performance test results pushed to Slack or we'll never see/debug them.

#### Summary of Changes

Created a Slack App that will push to #performance-results and a quick script here to `curl` together some relevant information to display.

#### Fixes

#6389

### CODE REVIEW

File: system-test/testnet-performance/upload_results_to_slack.sh [hunk 1]
```diff
@@ -0,0 +1,38 @@
+#!/usr/bin/env bash
```
Comment (mvines) [inline system-test/testnet-performance/upload_results_to_slack.sh]: nit: remove shebang because this file should only be `source`ed

File: system-test/testnet-performance/upload_results_to_slack.sh [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+upload_results() {
```
Comment (mvines) [inline system-test/testnet-performance/upload_results_to_slack.sh]: please use a more descriptive name as this function will be inserted into the namespace of the called.  "upload_results" to where?  `upload_results_to_slack` perhaps

File: system-test/testnet-performance/upload_results_to_slack.sh [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+				"text": "Result Details:
+$RESULT_DETAILS"
+			},
+		}
+	]
+}
+EOF
+)"
+
+curl -X POST \
```
Comment (mvines) [inline system-test/testnet-performance/upload_results_to_slack.sh]: nit: indent.   I wish shellcheck complained about this :)

File: system-test/testnet-performance/upload_results_to_slack.sh [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+-H 'Content-type: application/json' \
+--data "$payLoad" \
+"$SLACK_WEBHOOK_URL"
```
Comment (mvines) [inline system-test/testnet-performance/upload_results_to_slack.sh]: Looks like SLACK_WEBHOOK_URL and all the other global variables that this function assumes are not checked for, which will make debugging hard

File: multinode-demo/clear-config.sh [hunk 5]
```diff
@@ -11,9 +11,7 @@ set -e
 
 (
   set -x
-  rm -rf "${SOLANA_CONFIG_DIR:?}/" # <-- $i might be a symlink, rm the other side of it first
-  rm -rf "$SOLANA_CONFIG_DIR"
-  mkdir -p "$SOLANA_CONFIG_DIR"
+  setup_secondary_mount
+  echo "Removing config dir"
+  rm -rf ${SOLANA_CONFIG_DIR}/*
```
Comment (t-nelson) [inline multinode-demo/clear-config.sh]: Probably want to make this `rm -rf "${SOLANA_CONFIG_DIR:?}"/*`.  Otherwise BadThings(TM) might happen if `SOLANA_CONFIG_DIR` isn't set

File: net/common.sh [hunk 6]
```diff
@@ -99,14 +99,15 @@ SOLANA_CONFIG_DIR=$SOLANA_ROOT/config
 # Clear the current cluster configuration
 clear_config_dir() {
   declare config_dir="$1"
+
+  setup_secondary_mount
```
Comment (danpaul000) [inline net/common.sh]: @t-nelson FYI here, we need to make sure the secondary is linked before clearing, otherwise we might not actually delete the real contents in the unlinked config dir.

**Comment by danpaul000** [comment]
@mvines @t-nelson any other nits before I land this?  Can add whatever features as needed, but this PR is getting unwieldy.

**Comment by mvines** [comment]
lgtm, I'll let @t-nelson r+

**Comment by t-nelson** [comment]
LGTM!
