### PR TITLE
Fix repair slowness when most peers are unable to serve requests

### LINKED ISSUE #7100: Validator with snapshots disabled can't catch up to the tds cluster
STR:
1. Boot the tds cluster
2. From one shell run `solana-validator -l ledger -n tds.solana.com:8001 -o - --no-snapshot-fetch --rpc-port 8899`
3. Once your validator starts, run `solana catchup <identity-pubkey>` from another shell to monitor the catchup
Note that catchup shows negative and therefore node will never catch the cluster

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

- Repair and Repairman both think they live in a world where everyone has the entire ledger
- The Repair Client randomly asks a peer for shreds even though that peer may never have that data because they booted with a snapshot newer than the requested repair slot
- Repairman protocol attempts to divvy up catchup responsibilities among peers that report new enough root slots. This doesn't however ensure that the peers actually have that data (see above)

These problems result in Repair being slow(more misses if fewer nodes have the requested slot) and Repairman not sending all the required data(assuming peers will take over some of that responsibility). 

#### Summary of Changes

- Add lowest available slot to the gossiped repair information
- Filter out peers that simply cannot serve repairs from both repair and repairman protocols

This fixes repair's ability to bring nodes that are really far behind back up to the cluster

Fixes #7100

### CODE REVIEW

File: ledger/src/blocktree.rs [hunk 1]
```diff
@@ -1452,9 +1452,23 @@ impl Blocktree {
...
         *self.last_root.read().unwrap()
     }
+
+    // find the first available slot in blocktree that has some data in it
+    pub fn lowest_slot(&self) -> Slot {
+        for (slot, meta) in self
+            .slot_meta_iterator(0)
+            .expect("unable to iterate over meta")
+        {
+            if slot > 0 && meta.received > 0 {
```
Comment (ryoqun) [inline ledger/src/blocktree.rs]: It seems we could make the logic of "bounds" sub command of `ledger-tool` to use this for less duplicate code? Also, the `ledger-tool` doesn't have `meta.received > 0` the condition. I dunno which is correct.

From `ledger-tool/src/main.rs`:
>            SubCommand::with_name("bounds")
>            .about("Print lowest and highest non-empty slots. Note: This ignores gaps in slots")

Comment (sagar-solana) [reply ledger/src/blocktree.rs]: I think I want something more than what bounds from ledger tool gives us. Bounds just tells us "this is all lowest and highest slot for which we have some Meta data". In this case, I'm looking for the first non empty slot. Technically they're both similar since we don't update the Mets without Inserting something but that could change. Also I don't need to iterate over the whole ledger. Just need the first item and then exit.

File: core/src/repair_service.rs [hunk 2]
```diff
@@ -362,12 +377,13 @@ impl RepairService {
...
                 id,
                 latest_known_root,
+                lowest_slot,
                 slots_in_gossip.clone(),
             );
         }
     }
 
-    fn retain_slots_greater_than_root(slot_set: &mut BTreeSet<u64>, root: u64) {
+    fn retain_slots_greater_than_root(slot_set: &mut BTreeSet<u64>, root: Slot) {
```
Comment (ryoqun) [inline core/src/repair_service.rs]: [nits] Greedy me wishes more `Slot`s instead of `u64` in `BTreeSet<u64>`... Yeah, that helps readability a lot!

Comment (sagar-solana) [reply core/src/repair_service.rs]: Oohh this one slipped through. I'll fix it. Thanks!

File: core/src/repair_service.rs [hunk 3]
```diff
@@ -290,7 +302,7 @@ impl RepairService {
     fn get_completed_slots_past_root(
         blocktree: &Blocktree,
         slots_in_gossip: &mut BTreeSet<u64>,
```
Comment (ryoqun) [inline core/src/repair_service.rs]: [nits: :eyes:](https://github.com/solana-labs/solana/pull/7287/files#r354139106)

File: core/src/cluster_info.rs [hunk 4]
```diff
@@ -317,10 +317,10 @@ impl ClusterInfo {
         )
     }
 
-    pub fn push_epoch_slots(&mut self, id: Pubkey, root: u64, slots: BTreeSet<u64>) {
+    pub fn push_epoch_slots(&mut self, id: Pubkey, root: Slot, min: Slot, slots: BTreeSet<u64>) {
```
Comment (ryoqun) [inline core/src/cluster_info.rs]: [nits: :eyes:](https://github.com/solana-labs/solana/pull/7287/files#r354139106)

File: ledger/src/blocktree.rs (hunk 1 above)
Comment (ryoqun) [reply ledger/src/blocktree.rs]: Oh, I see. Then, leave the ledger tool logic as it is! Thanks for explaining.

So bounds check description should be changed like this for accuracy?
```patch
-       .about("Print lowest and highest non-empty slots. Note: This ignores gaps in slots")
+       .about("Print lowest and highest slots of metadata in ledger. Note: This ignores gaps in slots")
```

Comment (sagar-solana) [reply ledger/src/blocktree.rs]: Technically true but also not really possible right now. I think we should leave it the way it is.

Also I need to give this lowest_slot logic some more thought. Need to figure out how to avoid the repair bug if someone turns off their node for a few hours and then reboots from a snapshot. The lowest slot will still report the lowest one from the previous run. I might need to persist the boot slot and ignore lowest slots below that.

Comment (ryoqun) [reply ledger/src/blocktree.rs]: Yeah, that'd be desirable. But just naively doing so will lead just restarting for very a short downtime cuts the lowser slot needlessly. So I think we need some allowance for the exact gap maybe using `snapshot_interval_slots` and the recorded root_slot for the snapshot.

Comment (sagar-solana) [reply ledger/src/blocktree.rs]: Yeah I'm going to give it mood thought tomorrow. Bed time now :)

**Comment by carllin** [comment]
Maybe we should keep track of the lowest slot ini a field in blocktree instead off using the iterator to cover cases where we start from a snapshot after a long period of being offlne

**Comment by sagar-solana** [comment]
@carllin yeah what would that look like? We need to define the threshold. Like if we have a gap larger than N and our root has moved past the gap, then we bump the min slot?
