### PR TITLE
Fix duplicate account translation in CPI

### LINKED ISSUE #23682: Consensus (bank hash) mismatch between v1.9 and v1.10/master (mainnet)
#### Problem

#22102 seems to have introduced something that causes a consensus divergence in slot [124685989](https://explorer.solana.com/block/124685989).

Of the three commits that were squashed and merged in that PR, https://github.com/solana-labs/solana/pull/22102/commits/fa8167a8c702442ece41bbda96708e0a383fddad is the relevant one.

### Hashes and Difference

good (mnb):
> 214b561a286936b025deb27f00b9a942d352a3c3 [2022-03-15T19:57:36.357790216Z INFO  solana_runtime::bank] bank frozen: 124685989 hash: 7BauLWcimTJ5VA59pR4nhCTCWCi22qfrb8kVFLWVPhL6 accounts_delta: Arxx1yY8Wze4xMH7eQFC4i7aHdR2vRfHK5niW8Lhyw3G signature_count: 1524 last_blockhash: 9g1Aj69xp8iYBz9pM6Lxcx8BA1PcXC34ZiHfPg4kTxJ7 capitalization: 517210598907563320

> Program EWWy8ipWs2Lf4dA6CunwB2uYpevPTQUHHyiHewbwCfMp consumed **199987** of 200000 compute units

bad (master):
> 2ab4f34c029db5e5747dd2325379482e11a97f0a [2022-03-15T20:06:01.708041659Z INFO  solana_runtime::bank] bank frozen: 124685989 hash: 7jvWuXUUwwsfbBXUA96dWrxTRg9HMqHaDYtF7DQxLiJj accounts_delta: 9KXWuzac7a4DZMUjJ3r7FH5jWFm1Wws27Ess8VAUazmS signature_count: 1524 last_blockhash: 9g1Aj69xp8iYBz9pM6Lxcx8BA1PcXC34ZiHfPg4kTxJ7 capitalization: 517210598907563320

> Program EWWy8ipWs2Lf4dA6CunwB2uYpevPTQUHHyiHewbwCfMp consumed **200000** of 200000 compute units

### Log
This `Err(InstructionError(0, ProgramFailedToComplete))` only happens on master.

> [solana_program_runtime::stable_log] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 invoke [2]
> [solana_program_runtime::stable_log] Program log: Mango: CancelAllPerpOrders | limit=20
> [solana_program_runtime::stable_log] Program log: mango-log
> [solana_program_runtime::stable_log] Program log: cp1to4/ecqZ43ogDQe0xql0u2Ff66cc9XSGzkyyZdqoGDHUXDByC3VJfUNAqjqlytZh9HlwoZhJX50u7vRmUYrm6pKPh0lh5AwAAAAAAAAACAAAA1Fmr+/////+9HwAAAAAAACymVAQAAAAAzx8AAAAAAAACAAAA1Fmr+/////+9HwAAAAAAACymVAQAAAAAzx8AAAAAAAA=
> [solana_program_runtime::stable_log] Program log: mango-log
> [solana_program_runtime::stable_log] Program log: 9qpXciJ+y8R43ogDQe0xql0u2Ff66cc9XSGzkyyZdqoGDHUXDByC3VJfUNAqjqlytZh9HlwoZhJX50u7vRmUYrm6pKPh0lh5AwAAAAAAAAAAAAAAAAAAAA==
> [solana_bpf_loader_program] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 consumed 29586 of 134416 compute units
> [solana_program_runtime::stable_log] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 success
> [solana_program_runtime::stable_log] Program 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin invoke [1]
> [solana_program_runtime::stable_log] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 invoke [2]
> [solana_program_runtime::stable_log] Program log: Mango: PlacePerpOrder2 client_order_id=0
> [solana_bpf_loader_program] Program 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin consumed 9631 of 200000 compute units
> [solana_program_runtime::stable_log] Program log: bid on book order_id=149916689087037453326794 quantity=6354 price=8126
> [solana_bpf_loader_program] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 consumed 47818 of 100480 compute units
> [solana_program_runtime::stable_log] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 success
> [solana_program_runtime::stable_log] Program 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin success
> [solana_program_runtime::stable_log] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 invoke [2]
> [solana_runtime::bank] check: 1us load: 50us execute: 743us txs_len=1
> [solana_program_runtime::stable_log] Program log: Mango: PlacePerpOrder2 client_order_id=0
> [solana_program_runtime::stable_log] Program log: ask on book order_id=150211836992216951465526 quantity=6354 price=8143
> [solana_bpf_loader_program] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 consumed 47121 of 48211 compute units
> [solana_program_runtime::stable_log] Program mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68 success
> [solana_bpf_loader_program] Program EWWy8ipWs2Lf4dA6CunwB2uYpevPTQUHHyiHewbwCfMp consumed 200000 of 200000 compute units
> [solana_bpf_loader_program] Program failed to complete: exceeded maximum number of instructions allowed (200000) at instruction #12281
> [solana_program_runtime::stable_log] Program EWWy8ipWs2Lf4dA6CunwB2uYpevPTQUHHyiHewbwCfMp failed: Program failed to complete
> [solana_runtime::bank] check: 2us load: 49us execute: 853us txs_len=1
> [solana_program_runtime::stable_log] Program Vote111111111111111111111111111111111111111 invoke [1]
> [solana_metrics::metrics] CounterPoint { name: "vote-native", count: 1, timestamp: SystemTime { tv_sec: 1647381654, tv_nsec: 405320963 } }
> [solana_runtime::bank] tx error: Err(InstructionError(0, ProgramFailedToComplete)) SanitizedTransaction { message: Legacy(Message { header: MessageHeader { num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 5 }, account_keys: [Evcu8h19TmrxEnAiUBnAjQQQi7uKS7XZUzWPzHXvK9Pp, 2TgaaVoHgnSeEtXvWTx13zQeTf4hYWAMEiMQdcG6EwHi, 31cKs646dt1YkA3zPyxZ7rUAkxTBz279w4XEobFXcAKP, 6YYjGxyW7ScLJ7AbmKyAofdxuzQ3MfxnMKRNqhzvNNrt, 9qUxMSWBGAeNmXusQHuLfgSuYJqADyYoNLwZ63JJSi6V, Aqy2Pcw2SNhM4rMQbYaXE2XYsRXFejEcQfxUhUjrJDrV, Fu8q5EiFunGwSRrjFKjRUoMABj5yCoMEPccMbUiAT6PD, 98pjRuQjK3qA6gXts96PqZT4Ze5QmnCmt3QYjhbUSPue, EBDRoayCDDUvDgCimta45ajQeXbexv7aKqJubruqpyvu, EWWy8ipWs2Lf4dA6CunwB2uYpevPTQUHHyiHewbwCfMp, H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG, mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68], recent_blockhash: BmeYZnoLyJpVZKUHweL3KKWKj8Y6qdmdR2bXDotk4hSC, instructions: [CompiledInstruction { program_id_index: 9, accounts: [11, 7, 8, 2, 3, 0, 1, 6, 4, 5, 10], data: [219, 200, 88, 176, 158, 63, 253, 127, 246, 40, 92, 143, 194, 85, 84, 64, 113, 61, 10, 215, 163, 88, 84, 64, 200, 51, 104, 232, 202, 65, 229, 192, 5, 79, 236, 128, 127, 1, 0, 0] }] }), message_hash: 6pjoTazFi7k8zqsMVWv9bwRZeNzYpatgui1UB6J8iKf1, is_simple_vote_tx: false, signatures: [2F4xtcPQiQsULNia1iRQDJaFqfVBekLfLFAkcxp6vms4468CqLEzVw7pAGqRjSALr2BYdvyEhmBSGKtDjPUDjoyu] }
> [solana_runtime::bank] 1 errors of 1 txs
> [solana_runtime::bank] store: 0us txs_len=1

### Cause
As duplicate accounts were translated twice in the CPI, they were also charged for twice.
And this program execution which was close to the compute meter limit got pushed over the edge.

#### Proposed Solution

Debug and fix.

### PR DESCRIPTION
**Pull request by Lichtso**
#### Problem
#22102 changed the CPI account translation to translate every instruction account, including duplicate accounts.
This is not only inefficient as duplicate accounts only need to be translated once, but also causes a consensus issue:
Because duplicate accounts are also charged twice, this increases the compute meter consumption and can push programs with a usage close to the limit over the edge.

#### Summary of Changes
Replaces `for instruction_account in instruction_accounts.iter() {`
by:
```
visit_each_account_once::<EbpfError<BpfError>>(
        instruction_accounts,
        &mut |_index: usize, instruction_account: &InstructionAccount| {
```

Everything else is just formating, exposing the `visit_each_account_once()` function and adding a generic error result.

Fixes #23682

### CODE REVIEW

File: program-runtime/src/invoke_context.rs [hunk 1]
```diff
@@ -1154,18 +1154,14 @@ pub fn mock_process_instruction(
...
+) -> Result<(), E> {
     'root: for (index, instruction_account) in instruction_accounts.iter().enumerate() {
         // Note: This is an O(n^2) algorithm,
         // but performed on a very small slice and requires no heap allocations
-        for before in instruction_accounts
-            .get(..index)
-            .ok_or(InstructionError::NotEnoughAccountKeys)?
-            .iter()
-        {
+        for before in instruction_accounts.get(..index).unwrap().iter() {
```
Comment (Lichtso) [inline program-runtime/src/invoke_context.rs:1164]: Can't do `.ok_or(InstructionError::NotEnoughAccountKeys)` here anymore because of the generic result type. But this can never fail as `index` which is used in `instruction_accounts.get()` was acquired from `instruction_accounts.iter().enumerate()`.

Comment (jackcmay) [reply program-runtime/src/invoke_context.rs]: How about this: https://github.com/solana-labs/solana/pull/23701/commits/aac309b283e0463e683077d722646f6566632d9d

**Review by jackcmay — APPROVED** [review]
