### PR TITLE
CLI: Make `pay` subcommand a proper alias of `transfer`

### LINKED ISSUE #16706: `solana pay` is partly broken with lack of `--allow-unfunded-recipient`
#### Problem

```
$ head -c 32 /dev/urandom | base58 && echo
44SwRrxKtFgPVvKqmSRfhktDrX3qHEK4RTZz2gChe4wh
$ ./target/release/solana -ul pay 44SwRrxKtFgPVvKqmSRfhktDrX3qHEK4RTZz2gChe4wh 1
Error: The recipient address (44SwRrxKtFgPVvKqmSRfhktDrX3qHEK4RTZz2gChe4wh) is not funded. Add `--allow-unfunded-recipient` to complete the transfer
$ ./target/release/solana -ul pay --allow-unfunded-recipient 44SwRrxKtFgPVvKqmSRfhktDrX3qHEK4RTZz2gChe4wh 1
error: Found argument '--allow-unfunded-recipient' which wasn't expected, or isn't valid in this context
$ ./target/release/solana -ul transfer --allow-unfunded-recipient 44SwRrxKtFgPVvKqmSRfhktDrX3qHEK4RTZz2gChe4wh 1
Signature: 5kcsS1iDF4J1G8EwHW6B8DXNbayG7gG94rViuc9LNBFeQTbqhsG95jEtFN39YLEeozndrXaLrZRnae3fSBart8LT
```

#### Proposed Solution

```
$ ./target/release/solana -ul pay --allow-unfunded-recipient 44SwRrxKtFgPVvKqmSRfhktDrX3qHEK4RTZz2gChe4wh 1
Signature: 5kcsS1iDF4J1G8EwHW6B8DXNbayG7gG94rViuc9LNBFeQTbqhsG95jEtFN39YLEeozndrXaLrZRnae3fSBart8LT
```

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

CLI's `pay` subcommand purports to be an alias of `transfer`, yet lacks feature parity

#### Summary of Changes

Make `pay` subcommand a proper alias of `transfer`

Fixes #16706

```
$ solana -ud pay 5G1W4yDDVbVGKdKGWZKtvuuizsXUDGBfbrfEaKA6ZMhY 1
Error: The recipient address (5G1W4yDDVbVGKdKGWZKtvuuizsXUDGBfbrfEaKA6ZMhY) is not funded. Add `--allow-unfunded-recipient` to complete the transfer
```
```
$ solana -ud pay 5G1W4yDDVbVGKdKGWZKtvuuizsXUDGBfbrfEaKA6ZMhY 1 --allow-unfunded-recipient

Signature: 5MTFj5EDDVLKxdKLfdcxX8JE7Z2h5e3u9sQBCDe6sK9y4qoCGfo29weC4qzszGRAhhDC5xQdH1UWcS1EKKHkZbTn
```
```
$ solana --help | grep -A2 -B2 pay
    transaction-count              Get current transaction count
    transaction-history            Show historical transactions affecting the given address from newest to oldest
    transfer                       Transfer funds between system accounts [aliases: pay]
    validator-info                 Publish/get Validator info on Solana
    validators                     Show summary information about the current validators
```

### CODE REVIEW

File: cli/src/cli.rs [hunk 1]
```diff
@@ -2187,6 +2165,7 @@ pub fn app<'ab, 'v>(name: &str, about: &'ab str, version: &'v str) -> App<'ab, '
         .subcommand(
             SubCommand::with_name("transfer")
                 .about("Transfer funds between system accounts")
+                .visible_alias("pay")
```
Comment (mvines) [inline cli/src/cli.rs:2168]: Let's hide the alias.  We want to get people off this `pay`

Comment (CriesofCarrots) [reply cli/src/cli.rs:2168]: Yes, I prefer just `.alias()` as well

**Comment by CriesofCarrots** [comment]
Haha, I have this same changeset in my own branch right now. You win!

File: cli/src/cli.rs (hunk 1 above)
Comment (t-nelson) [reply cli/src/cli.rs]: Done!

**Comment by t-nelson** [comment]
> Haha, I have this same changeset in my own branch right now. You win!

:rabbit2:

**Review by CriesofCarrots — APPROVED** [review]
