### PR TITLE
Fix get_first_available_block for genesis; also make get_blocks(_with_limit) consistent

### LINKED ISSUE #23853: Blocks zero and one become inaccessible after the first root is set
#### Problem

Starting with https://github.com/solana-labs/solana/commit/db9826c the first two blocks become inaccessible after we set the first root. 32 confirmations after starting the test validator, `solana first-available-block` returns `2`.

@t-nelson confirmed this by querying for blocks 0 and 1 in a loop after starting up the test validator ([logs](https://gist.github.com/steveluscher/5349f77e3be9f574738745b7075a7096)).

After ~13s, those blocks become inaccessible.

```
Error: RPC response error -32001: Block 1 cleaned up, does not exist on node. First available block: 2
Error: RPC response error -32001: Block 0 cleaned up, does not exist on node. First available block: 2
```

#### Proposed Solution

@t-nelson suggested that genesis should be implicitly rooted ([discord](https://discord.com/channels/428295358100013066/439194979856809985/955880240998150285)); that this code needs to consider querying genesis ([link](https://github.com/solana-labs/solana/blob/359e2de090607ded83c1d329ffcf65d2e797ffde/ledger/src/blockstore.rs#L2351)).

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
After #23403, the first two blocks of a fresh validator become inaccessible to RPC after the first root is set. This is because of some assumptions that are true for a ledger that has had at least one prune or was booted from a snapshot, but not true for a ledger fresh from genesis.
For one, `Blockstore::lowest_slot()` (which `Blockstore::get_first_available_block()` uses to seed its root iterator) explicitly skips slot 0, even though it is populated and has SlotMeta. Secondly, the genesis block doesn't need a populated parent block to calculate parent blockhash, because it is *genesis*.

#### Summary of Changes
- Add `Blockstore::lowest_slot_with_genesis()` with the same logic as `Blockstore::lowest_slot()`, except the return slot may be zero
- Rework logic in `Blockstore::get_first_available_block()` to return 0 when that is the first root
- Also, I noticed (recollected?) that the Rpc endpoints getBlocks and getBlocksWithLimit aren't consistent with other endpoints in their starting block because they use `lowest_slot()` instead of `get_first_available_block()`. So I fixed the glitch.
- Added unit test to demonstrate how the relevant Blockstore methods work

Fixes  #23853

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Fresh boot:
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getSlot","params":[{"commitment":"confirmed"]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":1,"id":1}

// Master

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getFirstAvailableBlock","params":[]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":0,"id":1}

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getBlocksWithLimit","params":[0,5,{"commitment":"confirmed"}]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":[1,2,3,4,5],"id":1}

// This PR
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getFirstAvailableBlock","params":[]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":0,"id":1}

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getBlocksWithLimit","params":[0,5,{"commitment":"confirmed"}]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":[0,1,2,3,4],"id":1}
```

After first root:
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getSlot","params":["commitment":"confirmed"]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":50,"id":1}

// Master

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getFirstAvailableBlock","params":[]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":2,"id":1}

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getBlocksWithLimit","params":[0,5,{"commitment":"confirmed"}]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":[1,2,3,4,5],"id":1}

// This PR:

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getFirstAvailableBlock","params":[]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":0,"id":1}

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getBlocksWithLimit","params":[0,5,{"commitment":"confirmed"}]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":[0,1,2,3,4],"id":1}
```

After first prune:
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getSlot","params":["commitment":"confirmed"]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":503,"id":1}

// Master

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getFirstAvailableBlock","params":[]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":363,"id":1}

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getBlocksWithLimit","params":[0,5,{"commitment":"confirmed"}]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":[362,363,364,365,366],"id":1}

// This PR

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getFirstAvailableBlock","params":[]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":363,"id":1}

$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getBlocksWithLimit","params":[0,5,{"commitment":"confirmed"}]}' 127.0.0.1:8899
{"jsonrpc":"2.0","result":[363,364,365,366,367],"id":1}
```

File: ledger/src/blockstore.rs [hunk 1]
```diff
@@ -1930,11 +1930,17 @@ impl Blockstore {
...
-        let mut root_iterator = self.rooted_slot_iterator(self.lowest_slot())?;
-        // The block at root-index 0 cannot be complete, because it is missing its parent
-        // blockhash. A parent blockhash must be calculated from the entries of the previous block.
-        // Therefore, the first available complete block is that at root-index 1.
-        Ok(root_iterator.nth(1).unwrap_or_default())
+        let mut root_iterator = self.rooted_slot_iterator(self.lowest_slot_with_genesis())?;
+        let first_root = root_iterator.next().unwrap_or_default();
+        // If the first root is slot 0, it is genesis. Genesis is always complete, so it is correct
+        // to return it as first-available.
+        if first_root == 0 {
```
Comment (t-nelson) [inline ledger/src/blockstore.rs:1937]: will we hit this when restarting a node from snapshot and empty rocksdb dir? @joeaba had reported BT upload breakage when restarting warehouse nodes in this configuration as first available was reporting zero (and last the snapshot slot IIRC).  I figured it was the original `unwrap_or_default()` which makes it impossible to discern between starting from genesis and simply having no ledger

Comment (CriesofCarrots) [reply ledger/src/blockstore.rs:1937]: In my testing on a node booting from snapshot and empty ledger, once the RPC service was available the first_root was set to the snapshot slot. This was true both before and after this PR.

If there were no other roots, first-available would report 0, though, because we are looking at the index-1 item in the iterator. I'm guessing this was what happened in the case you're referring to?
As you say, this was and is due to the `unwrap_or_default()`. Should we return an error instead?

Comment (CriesofCarrots) [reply ledger/src/blockstore.rs:1937]: Something like "node still booting"...?

Comment (t-nelson) [reply ledger/src/blockstore.rs:1937]: I've been trying to decide what the least wrong thing to do is here.  Error seems right, but I'm not sure what the downstream effects might be.  We can punt to another PR though I think

**Review by t-nelson — APPROVED** [review]
lgtm

File: ledger/src/blockstore.rs (hunk 1 above)
Comment (CriesofCarrots) [reply ledger/src/blockstore.rs:1937]: > We can punt to another PR though I think

Sg. Possibly we also need to look at error-handling in the bigtable uploader as well
