### PR TITLE
Remove WithSigner

### LINKED ISSUE #8335: WithSigner now unnecessarily painful
#### Problem

Now that the runtime supports duplicate accounts, `solana_sdk::instruction::WithSigner` trait is obsolete, using it is error prone, and obfuscates the constructor code. Passing the wrong key into the signer parameter will create an invalid transaction instead of reporting an error when the transaction is signed [by the correct key].

#### Proposed Solution

Remove `WithSigner` and instead burn a byte with each additional index to the same pubkey.

cc: @rob-solana

### PR DESCRIPTION
**Pull request by garious**
#### Problem

We added the `WithSigner` to workaround the old limitation where an instruction couldn't reference the same account twice. Using it, the instruction processor can't know whether `next_keyed_account` will fail without first checking if a previous keyed account had been "promoted" to a signer. Then, if it failed anyway, it could be because the key is the same as a previous signer, or the instruction is invalid.  Too many edge cases!

Also, without `with_signer()` calls, we can generate most of the instruction modules from their struct definitions.

#### Summary of Changes

Remove `WithSigner` and its untested edge cases.

Fixes #8335

### CODE REVIEW

File: programs/vote/src/vote_instruction.rs [hunk 1]
```diff
@@ -199,8 +199,8 @@ pub fn vote(vote_pubkey: &Pubkey, authorized_voter_pubkey: &Pubkey, vote: Vote)
         AccountMeta::new(*vote_pubkey, false),
         AccountMeta::new_readonly(sysvar::slot_hashes::id(), false),
         AccountMeta::new_readonly(sysvar::clock::id(), false),
-    ]
-    .with_signer(authorized_voter_pubkey);
+        AccountMeta::new_readonly(*authorized_voter_pubkey, true),
```
Comment (garious) [inline programs/vote/src/vote_instruction.rs:202]: This exposed a bug in the message compiler. If `vote_pubkey` and `authorized_voter_pubkey` are the same, then the key should be promoted to writable.

Comment (garious) [reply programs/vote/src/vote_instruction.rs:202]: Fixed in 9753d242174f1e6396c8f681c72b344d1811c46e

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure
