### PR TITLE
disable qos adjustment logic when feature apply_cost_tracker_during_replay is activated

### LINKED ISSUE #31340: kin cluster stalled after seeing WouldExceedMaxAccountCostLimit error
#### Problem

Recently, we run into a network stall on kin-clusters.

After seeing the following errors, the cluster stalled. 

```
[2023-04-21T14:21:18.360233163Z ERROR solana_metrics::metrics] datapoint: replay-stage-mark_dead_slot error="error: InvalidTransaction(WouldExceedMaxAccountCostLimit)" slot=249053i
```

```
[2023-04-21T14:21:34.745678677Z INFO  solana_core::progress_map] Propagated stats:
                    total staked: 3999990868480,
                    observed staked: 999997717120,
                    vote pubkeys: {2TLD7hwoUvxS3ufmUNMsBvfaL8Q3XjhYmbvHJCoEuBke},
                    node_pubkeys: {31fxZovs3gBKVVTtC2VJUuKeVoq6mQkLjWnicWhErQ4f},
                    slot: 249067,
                    epoch: Some(12)
```

#### Proposed Solution

Debug and fix

### PR DESCRIPTION
**Pull request by taozhu-chicago**
#### Problem
Enabling the mentioned feature without first removing the QoS Adjustment Logic (https://github.com/solana-labs/solana/issues/29595#issuecomment-1524087480) breaks cluster test runs off head of Master, where all features are enabled by default. 

#### Summary of Changes
- disables the QoS Adjustment Logic when feature is activated (Will still remove the logic eventually #31379)

Fixes #31340

### CODE REVIEW

**Comment by taozhu-chicago** [comment]
tag @KirillLykov @jeffwashington 
This should fix kin-sim and other cluster test _without_ needing to specifically disable the feature

**Comment by apfitzge** [comment]
Made a comment on the feature-gate issue: https://github.com/solana-labs/solana/issues/29595#issuecomment-1550130455

**Comment by KirillLykov** [comment]
Cluster didn't panic any longer with this fix

File: core/src/banking_stage/consumer.rs [hunk 1]
```diff
@@ -1074,7 +1082,9 @@ mod tests {
             mint_keypair,
             ..
         } = create_slow_genesis_config(10_000);
-        let bank = Arc::new(Bank::new_no_wallclock_throttle_for_tests(&genesis_config));
+        let mut bank = Bank::new_no_wallclock_throttle_for_tests(&genesis_config);
+        bank.deactivate_feature(&feature_set::apply_cost_tracker_during_replay::id());
```
Comment (apfitzge) [inline core/src/banking_stage/consumer.rs:1086]: Any reason to explicitly **disable** the feature for this test? I don't see anything in it that stands out as failing immediately.
If that's the case, imo it's better to have this test run the scenario twice with the feature enabled and disabled.

But obviously let me know if I'm missing something!

File: core/src/banking_stage/consumer.rs [hunk 2]
```diff
@@ -429,11 +429,19 @@ impl Consumer {
...
         } = execute_and_commit_transactions_output;
 
-        QosService::update_or_remove_transaction_costs(
-            transaction_qos_cost_results.iter(),
-            commit_transactions_result.as_ref().ok(),
-            bank,
-        );
+        // once feature `apply_cost_tracker_during_replay` is activated, leader shall no longer
+        // adjust block with executed cost (a behavior more inline with bankless leader), instead
+        // will be exclusively using requested `compute_unit_limit` in cost tracking.
```
Comment (apfitzge) [inline core/src/banking_stage/consumer.rs:434]: 🤔 
> exclusively using requested `compute_unit_limit` in cost tracking

Sorry to nit-pick this comment, but I want to be really clear about the expectations and behaviors, since this kind of implies that we will require the request to be set (to me at least), and I don't beleive that is the case.

1. We still have a default CU-limit which is used if not specified.
2. If we have pure builtin txs, even if the request is set, we don't use that limit in the cost tracking, only fee calculations.

Are these 2 points still going to be true moving forward?

Might be better to just be a bit more vague in the comments, w/ details being in the cost model itself. Something along the lines of "instead calculated, requested, or default costs will be used in cost tracking".

**Review by apfitzge — COMMENTED** [review]
ah, merged while I was reviewing 🐢

File: core/src/banking_stage/consumer.rs (hunk 1 above)
Comment (taozhu-chicago) [reply core/src/banking_stage/consumer.rs:1086]: per the intention of the pr, with the feature enabled, the adjustment will be bypassed, which breaks this test.

But a good point to test it with out both feature on/off. Will PR with added test.

File: core/src/banking_stage/consumer.rs (hunk 2 above)
Comment (taozhu-chicago) [reply core/src/banking_stage/consumer.rs:434]: yes for point 1, default will be used if `compute_unit_limit` is not explicitly set. I implicitly included default when mentioning requested cu. But good point, #31700 clarifies it. 

Point 2 is also correct, but it probably should change. Since all builtins now (in 1.16+) also consume requested CUs, probably no need to distinguish builtin and bpf programs in cost model.

File: core/src/banking_stage/consumer.rs (hunk 1 above)
Comment (apfitzge) [reply core/src/banking_stage/consumer.rs:1086]: But what part of the test breaks without this? All the asserts check, afaict, is that there is *some* non-zero cost, and the tx was committed.

File: core/src/banking_stage/consumer.rs (hunk 2 above)
Comment (apfitzge) [reply core/src/banking_stage/consumer.rs:434]: > Since all builtins now (in 1.16+) also consume requested CUs, probably no need to distinguish builtin and bpf programs in cost model.

I suppose the difference is we know the static builtin costs up-front, compared to bpf. So we can accurately determine those costs, which are (if tx will succeed) strictly <= requested.

Actually, taking it a slight step further - if we found it to be a problem we could immediately reject (try taking fees only) if a builtin-only tx requested too few CUs.

File: core/src/banking_stage/consumer.rs (hunk 1 above)
Comment (taozhu-chicago) [reply core/src/banking_stage/consumer.rs:1086]: It breaks here:
```
-            assert_eq!(get_block_cost(), 2 * single_transfer_cost);
-            assert_eq!(get_tx_count(), 2);
+            assert_eq!(get_block_cost(), expected_block_cost);
+            assert_eq!(get_tx_count(), expected_tracked_tx_count);
```
the adjustment logic removes failed tx (the one fail due to AccountInUse) from cost tracker. #31708 for it.
