### PR TITLE
Fixed issue #22124 -- missing historical data if slot updated later.

### LINKED ISSUE #22124: Postgres AccountsDB plugin does not capture all historical account writes
#### Problem

The plugin wants to allow capturing historic account writes in the `account_audit` table and uses a `AFTER UPDATE OR DELETE` trigger on the `account` table to accomplish that.

However, the individual writes to `account` have the form:
```
INSERT INTO account ... ON CONFLICT (pubkey) DO UPDATE SET ... 
    WHERE acct.slot < excluded.slot 
        OR (acct.slot = excluded.slot AND acct.write_version < excluded.write_version)
```
which means that older conflicting writes where the `WHERE` condition is false will not update the `account` table at all and not end up in `account_audit`.

Out-of-order writes will always be seen, even when using only one thread to write to postgres, because the account writes don't necessarily arrive at the accountsdb plugin in order.

(Here's a log that shows this out of order arrival. Note that the write_version is monotonic, but the slot isn't - even when looking at a single account.
```
<pubkey>                                     <slot>    <write version>
6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E 113550443 180070299602
6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E 113550447 180070324306
6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E 113550447 180070325347
6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E 113550452 180070352904
6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E 113550453 180070358229
6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E 113550456 180070362308
6WGoQr5mJAEpYCdX6qjju2vEnJuD7e8ZeYes7X7Shi7E 113550454 180070363471
```

#### Proposed Solution

Possibly writes need to be inserted into `account_audit` explicitly?

@lijunwangs

### PR DESCRIPTION
**Pull request by lijunwangs**
#### Problem
In the account notification via plugin -- some account update with older slots may come after the updates of those with newer slot. It is found the account_audit table misses such updates.

#### Summary of Changes
In case updates are rejected in the account table because they are "old", directly insert into the account_audit table for keeping historical data.

Fixes #22124

### CODE REVIEW

File: accountsdb-plugin-postgres/src/postgres_client.rs [hunk 1]
```diff
@@ -324,6 +326,28 @@ impl SimplePostgresClient {
...
+        let stmt = "INSERT INTO account_audit (pubkey, slot, owner, lamports, executable, rent_epoch, data, write_version, updated_on) \
+        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)";
+
+        let stmt = client.prepare(stmt);
+
+        match stmt {
+            Err(err) => {
+                return Err(AccountsDbPluginError::Custom(Box::new(AccountsDbPluginPostgresError::DataSchemaError {
+                    msg: format!(
+                        "Error in preparing for the accounts update PostgreSQL database: {} host: {:?} user: {:?} config: {:?}",
```
Comment (lijunwangs) [inline accountsdb-plugin-postgres/src/postgres_client.rs:342]: account audit update

File: accountsdb-plugin-postgres/src/postgres_client.rs [hunk 2]
```diff
@@ -370,16 +394,52 @@ impl SimplePostgresClient {
         }
     }
 
+    /// Internal function for updating or inserting a single account
```
Comment (lijunwangs) [inline accountsdb-plugin-postgres/src/postgres_client.rs:397]: inserting into account_audit table

**Review by carllin — APPROVED** [review]

**Comment by carllin** [comment]
Lijun and I also discussed some possibilities for integration tests to catch future regressions like this.
