### PR TITLE
fix: the one where we fix client subscriptions

### LINKED ISSUE #24472: Subscribing/unsubscribing from the same subscription multiple times yields incorrect behavior
#### Problem

1. If you make multiple subscriptions with the same method/params, only the first one will receive publishes.
2. If you unsubscribe from a subscription for which there are multiple client subscriptions with the same method/params, the subscription gets killed for all of them.

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

Props to @lwus for bringing to my attention that:

1. If you make two RPC subscriptions for fundamentally the same subscription (ie. same method, same params) only the first subscription's callback will ever fire.
2. If you start with more than one client subscription for fundamentally the same RPC subscription, and then dispose of _one_ of them, the client will unsubscribe _all_ of them.
3. If you make two RPC subscriptions for fundamentally the same subscription, we needlessly make two RPC subscription requests to the server, when only one is needed. 

#### Summary of Changes

This PR represents a pretty massive rewrite of the client subscriptions tracker. Let me lay out the goal of every commit:

* As preparation, we create a type called `ClientSubscriptionId` to disambiguate it from _server_ subscription ids. This makes it more clear when you're unsubscribing a client handle for a given method/params (which there can be many of) and when you're unsubscribing a server handle for a given method/params (which there can only ever be one of)
* Then we install `fast-stable-stringify`. We'll use this to identify a given method/params pair by its hash, so that we can pool a multitude of _client_ subscriptions behind a single _server_ subscription. There will be a 1:1 relationship between the hash of a subscription and the `ServerSubscriptionId` assigned to it. This library comes in hot at ~700 bytes gzipped, so I feel pretty good about that.
* Next, is a giant, unreviewable overhaul of the subscription tracker. How to review it: first, take a look at the TypeScript types. I've created a tagged union of all of the possible subscriptions you can make, by method, and another tagged union of all of the states that a subscription can be in (`pending`, `subscribing`, `subscribed`, `unsubscribing`, and `unsubscribed`). The `updateSubscriptions` method is now solely responsible for managing the transitions from one state to the next.
* The next commit is just a cleanup of the websocket tests and mocks to handle the special case that . Feel free to ignore it.
* In the next commit we add a library to be able to spy on function calls and make expectations about them in test plans.
* Read more about the next commit in the ‘test plan’ section below.
* In the final commit, we augment the state machine to implement handling for ‘auto-disposing’ subscriptions like `signatureSubscribe`. Read the tests to remind yourself of what makes signature subscriptions special in this regard.

#### Test plan

What the mega refactor commit lacks in reviewability, I hope I've made up for in spades through test coverage. The tests in this commit cover everything from ‘what happens if you attach a subscription while you're in the middle of unsubscribing from an existing one’ and ‘what happens if the websocket goes down’ and ‘what happens if the unsubscribe request fatals.’ And all of this, without the need for a live validator. Check out a clean run and read through the test titles: https://gist.github.com/steveluscher/79f0c06c5c4d6648466668d47babf0f6

#### Let's bake this!

If you're reading this, and you rely on subscriptions in your dApp, please help me beta test this! Install the prerelease version of web3.js by using `yarn add @solana/web3.js@next` or `npm i --save @solana/web3.js@next`.

Fixes #24472, #24176

### CODE REVIEW

**Comment by steveluscher** [comment]
What I wouldn't give for a good 'ol fashioned @altano review on this diff, for old time's sake.

File: web3.js/src/connection.ts [hunk 1]
```diff
@@ -2120,6 +2120,18 @@ export type ConnectionConfig = {
...
+  label: string,
+) {
+  console.warn(
+    `You removed a(n) ${label} subscription with id \`${id}\` ` +
+      'where no active subscription having that id could be . ' +
+      'found. Verify that your code does not try to ' +
+      'unsubscribe the same listener more than once.',
+  );
+}
+
```
Comment (steveluscher) [inline web3.js/src/connection.ts:2195]: This commit is from #24607. It shows up here because GitHub doesn't support stacked PRs properly.

File: web3.js/src/connection.ts [hunk 2]
```diff
@@ -64,6 +66,133 @@ const BufferFromRawAccountData = coerce(
...
+type Subscription = BaseSubscription &
+  StatefulSubscription &
+  DistributiveOmit<SubscriptionConfig, 'callback'>;
+
+/**
+ * @internal
+ */
+function hashSubscriptionConfig({
+  method,
+  params,
```
Comment (jstarry) [inline web3.js/src/connection.ts:192]: Can this operate over the "args" (what we pass to `this._rpcWebSocket.call(...)`) instead? That will more closely match the rpc server's behavior

File: web3.js/src/connection.ts [hunk 3]
```diff
@@ -4263,75 +4207,273 @@ export class Connection {
...
         return;
       }
-    }
+      unsubscribed = true;
+      delete this._subscriptionDisposeFunctionsByClientSubscriptionId[
+        clientSubscriptionId
+      ];
+      const subscription = this._subscriptionsByHash[hash];
+      assert(
+        subscription,
```
Comment (jstarry) [inline web3.js/src/connection.ts:4501]: nit: `subscription !== undefined` might be clearer here

File: web3.js/src/connection.ts [hunk 4]
```diff
@@ -4592,15 +4686,30 @@ export class Connection {
...
+
+  async _unsubscribeClientSubscription(
+    clientSubscriptionId: ClientSubscriptionId,
+    subscriptionName: string,
+  ) {
+    const dispose =
+      this._subscriptionDisposeFunctionsByClientSubscriptionId[
+        clientSubscriptionId
+      ];
+    if (dispose) {
```
Comment (jstarry) [inline web3.js/src/connection.ts:4739]: How about deleting the dispose function from `_subscriptionDisposeFunctionsByClientSubscriptionId` within this `if` block? Then the dispose function doesn't have to worry about whether it has been called before. The responsibility for that check will belong to this `_unsubscribeClientSubscription` function.

File: web3.js/src/connection.ts [hunk 5]
```diff
@@ -4723,14 +4825,25 @@ export class Connection {
...
-      callback,
-      options,
-      subscriptionId: null,
-    };
-    this._updateSubscriptions();
+    const clientSubscriptionId = this._makeSubscription({
+      callback: (notification, context) => {
+        callback(notification, context);
+        // Signatures subscriptions are auto-removed by the RPC service
+        // so no need to explicitly send an unsubscribe message.
```
Comment (jstarry) [inline web3.js/src/connection.ts:4880]: this comment implies that we won't send the unsubscribe message, but it looks like we *are* doing that now

File: web3.js/src/connection.ts [hunk 6]
```diff
@@ -4263,75 +4207,273 @@ export class Connection {
...
+               * Being that nobody is interested in this
+               * subscription any longer, delete it.
+               */
+              delete this._subscriptionsByHash[hash];
+              if (subscription.state === 'unsubscribed') {
+                delete this._subscriptionCallbacksByServerSubscriptionId[
+                  subscription.serverSubscriptionId
+                ];
+              }
+              await this._updateSubscriptions();
```
Comment (jstarry) [inline web3.js/src/connection.ts:4255]: It worries me that one invocation of `_updateSubscriptions` could trigger many other recursive updates. The top level invocation and the lower level invocations would all be running at the same time and could cause all sorts of race conditions.

File: web3.js/src/connection.ts [hunk 7]
```diff
@@ -4263,75 +4207,273 @@ export class Connection {
...
+              return;
+            }
+            await (async () => {
```
Comment (jstarry) [inline web3.js/src/connection.ts:4258]: The subscription state could have changed away from `'pending'` or `'unsubscribed'` before this async function is scheduled. This also applies to how we handle unsubscribes.

File: web3.js/src/connection.ts [hunk 8]
```diff
@@ -4117,122 +4161,22 @@ export class Connection {
...
-    if (
-      accountClientSubscriptionIds.length === 0 &&
-      programClientSubscriptionIds.length === 0 &&
-      slotClientSubscriptionIds.length === 0 &&
-      slotUpdateClientSubscriptionIds.length === 0 &&
-      signatureClientSubscriptionIds.length === 0 &&
-      rootClientSubscriptionIds.length === 0 &&
-      logsClientSubscriptionIds.length === 0
-    ) {
+  async _updateSubscriptions() {
```
Comment (jstarry) [inline web3.js/src/connection.ts:4193]: I'm finding this method very difficult to review because of the potential for race conditions in state transitions. I think it would be easier to follow if this method was synchronous and was refactored to synchronously transitions subscriptions to "subscribing", "unsubscribing", and deleted states. Then, the async methods for subscribing and unsubscribing can check if a given subscription still needs to be subscribed/unsubscribed before and after making the rpc request.

File: web3.js/src/connection.ts [hunk 9]
```diff
@@ -4263,75 +4207,273 @@ export class Connection {
...
-    for (let clientSubscriptionId of logsClientSubscriptionIds) {
-      const sub = this._logsSubscriptions[clientSubscriptionId];
-      let filter;
-      if (typeof sub.filter === 'object') {
-        filter = {mentions: [sub.filter.toString()]};
-      } else {
-        filter = sub.filter;
+    callbacks.forEach(cb => {
+      try {
+        cb(...(publishArgs as [any, any]));
```
Comment (jstarry) [inline web3.js/src/connection.ts:4408]: Should this be `any[]`? Some callbacks only have one argument, and future callbacks could have more than 2

**Review by jstarry — COMMENTED** [review]
Thanks for taking this on! Looks really good so far.

File: web3.js/src/connection.ts [hunk 10]
```diff
@@ -4263,75 +4207,273 @@ export class Connection {
...
+    switch (rawConfig.method) {
+      case 'accountSubscribe':
+      case 'logsSubscribe':
+      case 'programSubscribe':
+        if (rawConfig.params.commitment === undefined) {
+          subscriptionConfig = {
+            ...rawConfig,
+            params: {
+              ...rawConfig.params,
+              commitment: 'finalized',
```
[the remark this answers is not in the document]
Comment (steveluscher) [reply web3.js/src/connection.ts:4448]: Oh, interesting.

I think that in all cases, no matter what the `Connection's` default commitment is, if you make a subscription _without_ supplying a commitment, then the server defaults to `Finalized` (see `unwrap_or_default()` here):

https://github.com/solana-labs/solana/blob/3114c199bde434b47f255bb6fdd6492836fd9a45/rpc/src/rpc_pubsub.rs#L410-L423

https://github.com/solana-labs/solana/blob/b8837c04ec3976c9c16d028fbee86f87823fb97f/sdk/src/commitment_config.rs#L197-L201

The aim of this code here is to apply the _same_ default that the server would apply in the absence of a `commitment`, so that these client configs hash to the same ‘subscription topic’:

```
// Config A
{
  /* ... */
  "params": [
    "83astBRguLMdt2h5U1Tpdq5tjFoJ6noeGwaY3mDLVcri",
    {"commitment": "finalized"}
  ]
}
// Config B
{
  /* ... */
  "params": [
    "83astBRguLMdt2h5U1Tpdq5tjFoJ6noeGwaY3mDLVcri",
    {}
  ]
}
```

I will extra super double check this though.

File: web3.js/src/connection.ts [hunk 11]
```diff
@@ -4263,75 +4207,273 @@ export class Connection {
...
+  /**
+   * @private
+   */
+  _makeSubscription(
+    // The subscription config, before applying defaults
+    rawConfig: SubscriptionConfig,
+  ): ClientSubscriptionId {
+    const clientSubscriptionId = this._nextClientSubscriptionId++;
+    let subscriptionConfig: SubscriptionConfig;
+    // Apply defaults.
```
[the remark this answers is not in the document]
Comment (steveluscher) [reply web3.js/src/connection.ts:4438]: Sure. I can't remember why I did it this way. I suppose on the off-chance that someone else adds a call to `this._makeSubscription` without applying defaults, then we could get into trouble, but that Shouldn't Come About™.

File: web3.js/src/connection.ts [hunk 12]
```diff
@@ -4263,75 +4207,273 @@ export class Connection {
...
+        } else {
+          subscriptionConfig = rawConfig;
+        }
+        break;
+      default:
+        subscriptionConfig = rawConfig;
+    }
+    const hash = hashSubscriptionConfig(subscriptionConfig);
+    const existingSubscription = this._subscriptionsByHash[hash];
+    if (existingSubscription == null) {
```
[the remark this answers is not in the document]
Comment (steveluscher) [reply web3.js/src/connection.ts:4479]: Yeah, this is one of those funny things. It's quite common among folks to check for `null | undefined` using the coercive `== null`. Here, you have a type that TypeScript damn well knows to be `Subscription | undefined`, but despite that it doesn't complain about the use of a coercive `null` check, because a coercive `null` check is valid here.

I'll change it, though.

File: web3.js/src/connection.ts (hunk 2 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:192]: Nice catch. These all result in different server subscriptions, so best to push the hash function down, as you've said.

```
> await client.call('accountSubscribe',['CM78CPUeXjn8o3yroDHxUtKsZZgoy4GPkPPXfouKNH13', {encoding:'base64'}])
3
> await client.call('accountSubscribe',['CM78CPUeXjn8o3yroDHxUtKsZZgoy4GPkPPXfouKNH13', {encoding:'base64+zstd'}])
4
> await client.call('accountSubscribe',['CM78CPUeXjn8o3yroDHxUtKsZZgoy4GPkPPXfouKNH13', {encoding:'jsonParsed'}])
5
> await client.call('accountSubscribe',['CM78CPUeXjn8o3yroDHxUtKsZZgoy4GPkPPXfouKNH13', {encoding:'base58'}])
6
```

File: web3.js/src/connection.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (steveluscher) [reply web3.js/src/connection.ts:4448]: Mmm. Now looking closer at `_buildArgs` I see what you mean.

File: web3.js/src/connection.ts (hunk 4 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4739]: Yeah, sorry, this is just muscle memory from years of damage. Because functions can be passed around like values, it becomes inevitable that _someday_ someone will find a way to get a reference to the actual dispose function itself. Once that's done, they can call it over and over and over, no matter that we've removed it from the map.

In this particular case, we don't leak the dispose handles to callers, so what you've suggested will work. Will change!

Comment (steveluscher) [reply web3.js/src/connection.ts:4739]: * I still want to leave the responsibility for deleting the dispose handle up to the dispose handle itself. A little self-destruct.

File: web3.js/src/connection.ts (hunk 5 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4880]: We don't, actually! Check out the special case driven by `_subscriptionsAutoDisposedByRpc`, and check out the ‘auto-disposing subscriptions’ section of the tests.

File: web3.js/src/connection.ts (hunk 7 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4258]: It can't, actually! Invoking an async function inline doesn't schedule it – it executes synchronously and eagerly.

```
async function sleep(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}

console.log('A');
(async () => {
  console.log('synchronous state transition before B');
  await sleep(10);
  console.log('deferred code after continuation');
})();
console.log('B');
```

The same is true of Promises; the implementation executes eagerly and synchronously.

```
async function sleep(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}

console.log('A');
new Promise(resolve => {
  console.log('synchronous state transition before B');
  sleep(10).then(() => {
    console.log('deferred code after continuation');
    resolve();
  });
});
console.log('B');
```

File: web3.js/src/connection.ts (hunk 8 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4193]: It's a bit of a bird's nest, I know. Hopefully though, my comments and reduced test cases above have convinced you that this update method does _exactly_ what you've asked for! It causes every state transition, synchronously through eager evaluation, then yields in exactly two places by awaiting `this._rpcWebSocket.call(...)` depending on whether we need to subscribe or unsubscribe.

File: web3.js/src/connection.ts (hunk 9 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4408]: I had that initially, but TypeScript squaked: 

```
A spread argument must either have a tuple type or be passed to a rest parameter. ts(2556)
```

**Comment by steveluscher** [comment]
This was a great review, @jstarry. I addressed each one of your comments in a commit on top of ‘[fix: special case auto-disposing subscriptions like signatureSubscribe](https://github.com/solana-labs/solana/pull/24473/commits/dc1076e6cb0471ef684111573f0a99c70e87f923)’ so that you can walk through the new stuff one by one.

File: web3.js/src/connection.ts (hunk 6 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4265]: OMG. I wrote a gigantic explainer here. Now, it's gone. Damnit GitHub.

Comment (steveluscher) [reply web3.js/src/connection.ts:4265]: > The top level invocation and the lower level invocations would all be running at the same time…

But not _actually_ at the same time, right? The way this state machine is written, every state transition is executed synchronously and eagerly. Every time a subscription enters the state machine it either transitions or skips. So long as every pass through the machine causes a transition, there's no risk of infinite recursion, and because every subscription operates independently of the others, there are no races.

When you encounter a recursion, those also get processed synchronously and eagerly. Imagine that you had 4 subscriptions in the `pending` state, and the first one happened to have zero callbacks. The stack would look something like this.

```
1A (no callbacks; gets deleted then recurses)
 L 2B (transitions to subscribing)
 L 3B (transitions to subscribing)
 L 4B (transitions to subscribing) 
2A (subscribing, so skips)
3A (subscribing, so skips)
4A (subscribing, so skips)
```

One nice thing about going through the entire update function recursively is that, as the state whittles itself down to a stable state, you get all of the socket timeout connection/disconnection logic for free.

File: web3.js/src/connection.ts (hunk 7 above)
Comment (jstarry) [reply web3.js/src/connection.ts:4268]: Ah you're right, thanks

File: web3.js/src/connection.ts [hunk 13]
```diff
@@ -1958,33 +2041,15 @@ export type SignatureSubscriptionCallback = (
  * Signature subscription options
  */
 export type SignatureSubscriptionOptions = {
-  commitment?: Commitment;
+  commitment?: Commitment; // Must default to `Connection._commitment` or 'finalized' otherwise
```
Comment (jstarry) [inline web3.js/src/connection.ts:2044]: Is this comment directed at maintainers? If so, I think we should move this comment (and the others you've copied around) to the `args: IWSRequestParams` param on `_makeSubscription`. I don't think that the current comment makes it very clear why it must default to some commitment, but that explanation should be read by contributor who calls `_makeSubscription` in a new function. In fact, it could generally describe that the client should set explicit defaults for parameters to ensure that subscriptions are hashed correctly.

File: web3.js/src/connection.ts [hunk 14]
```diff
@@ -4281,75 +4232,209 @@ export class Connection {
...
+               *
+               * Being that nobody is interested in this
+               * subscription any longer, delete it.
+               */
+              delete this._subscriptionsByHash[hash];
+              if (subscription.state === 'unsubscribed') {
+                delete this._subscriptionCallbacksByServerSubscriptionId[
+                  subscription.serverSubscriptionId
+                ];
+              }
```
Comment (jstarry) [inline web3.js/src/connection.ts:4264]: Can you document that this block needs to be idempotent? While we are iterating through the subscriptions, we could recurse and delete subscriptions that would be iterated over later.

File: web3.js/src/connection.ts (hunk 6 above)
Comment (jstarry) [reply web3.js/src/connection.ts:4265]: Ok, this flow makes sense and is well thought out, thanks for the explanation!

File: web3.js/src/connection.ts [hunk 15]
```diff
@@ -4281,75 +4232,209 @@ export class Connection {
...
+              await this._updateSubscriptions();
+              return;
+            }
+            await (async () => {
+              const {args, method} = subscription;
+              try {
+                this._subscriptionsByHash[hash] = {
+                  ...subscription,
+                  state: 'subscribing',
+                };
```
Comment (jstarry) [inline web3.js/src/connection.ts:4274]: By creating a new object here, I believe we could resubscribe multiple times to the same subscription:
```
1A (no callbacks; gets deleted then recurses)
 L 2B (pending, creates new object with subscribing state)
2A (old object is still pending, transitions to subscribing again)
```
I would have expected you to set the state directly on the existing object so that it serves as a lock to prevent multiple subscribes / unsubscribes.

File: web3.js/src/connection.ts (hunk 8 above)
Comment (jstarry) [reply web3.js/src/connection.ts:4203]: Cool, this makes sense now. I think there's still potential for race conditions but I'm more happy now with how you've structured this. Thanks for pushing back thoughtfully. I also wrote up this gist to clarify to myself the yielding behavior of async code: https://gist.github.com/jstarry/9b86287eec9468696d5dd28aa7a6c50a

File: web3.js/src/connection.ts (hunk 4 above)
Comment (jstarry) [reply web3.js/src/connection.ts:4683]: Haha yeah good to be defensive I suppose, your change works for me.

File: web3.js/src/connection.ts (hunk 15 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4274]: OK. `Object.entries`… not the right choice here. Switching now to a strategy where what we iterate over are the hashes, then do the lookup as late as possible.

**Comment by steveluscher** [comment]
Alright @jstarry, the review can continue from ‘fix: write documentation explaining how and why to apply a default commitment’ onward, now that I've squashed the _heinous_ bugs that you caught.

File: web3.js/src/connection.ts [hunk 16]
```diff
@@ -4281,75 +4232,237 @@ export class Connection {
...
+                const serverSubscriptionId: ServerSubscriptionId =
+                  (await this._rpcWebSocket.call(method, args)) as number;
```
Comment (jstarry) [inline web3.js/src/connection.ts:4280]: While calling this method, the websocket could be closed and all subscriptions are set to `'pending'`, I think we should check for that before setting to `'subscribed'` here (this applies to unsubscribe as well).

Comment (jstarry) [inline web3.js/src/connection.ts:4280]: While calling this method, the websocket could be closed and all subscriptions are set to `'pending'`, I think we should check for that before setting to `'subscribed'` here (this applies to unsubscribe as well).

Comment (steveluscher) [reply web3.js/src/connection.ts:4280]: Woo, that sent me down a debugging rabbit hole. OK, I got to the bottom of this. Wow. From MDN.

> The browser will throw an exception if you call send() when the connection is in the CONNECTING state. If you call send() when the connection is in the CLOSING or CLOSED states, the browser will silently discard the data.

I just presumed that if you invoke `call()` when the socket is down, it would _throw an exception_ and process the catch block below that sets the subscription back to `pending`.

The ‘bare metal’ socket doesn't throw. It just drops the data, and never calls the callback.

```
ws = new WebSocket('wss://demo.piesocket.com/v3/channel_1?api_key=VCXCEuvhGcBDP7XhiJJUDvR1e1D3eiVjgZ9VRiaV&notify_self')
ws.onopen = () => {
    ws.close();
    console.log('is `CLOSING`', ws.readyState === ws.CLOSING);
    try {
        ws.send(JSON.stringify('hello'));
        console.log('sent, when I expected an error to be thrown');
    } catch(e) {
        console.error('legit caught an error', e);
    }
};
```

**But**, the rpc-websockets client _always_ throws if it doesn't receive a reply within a timeout.

https://github.com/elpheria/rpc-websockets/blob/trunk/src/lib/client.ts#L157-L172

That's the bug here. The `try` block will only ever continue past `await this._rpcWebSocket.call()` if a reply was received, in which case we're all good. The `catch` block however _might_ get called because of a disconnection-caused timeout. It's _there_ where I need to make sure that we're still in the `subscribing` state before I just hard shunt the subscription back to `pending`. And _that_ I can write a test for.

**Comment by steveluscher** [comment]
Alright @jstarry, one more commit on top: ‘fix: bail on async…’

File: web3.js/src/connection.ts (hunk 16 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4293]: Alright @jstarry, one more commit on top: ‘fix: bail on async…’ should fix this.

File: web3.js/src/connection.ts [hunk 17]
```diff
@@ -4281,75 +4240,248 @@ export class Connection {
...
-    for (let id of logsKeys) {
-      const sub = this._logsSubscriptions[id];
-      let filter;
-      if (typeof sub.filter === 'object') {
-        filter = {mentions: [sub.filter.toString()]};
-      } else {
-        filter = sub.filter;
+    callbacks.forEach(cb => {
+      try {
+        cb(...(callbackArgs as [any, any]));
```
Comment (jstarry) [inline web3.js/src/connection.ts:4401]: Can you add a comment explaining that `callbackArgs` might not actually match this tuple but we just do this to avoid a typescript issue?

File: web3.js/src/connection.ts [hunk 18]
```diff
@@ -4281,75 +4240,248 @@ export class Connection {
...
+      } catch (e) {
```
Comment (jstarry) [inline web3.js/src/connection.ts:4402]: This is a behavior change but probably a good one. I'm guessing you're trying to help out app developers here in case their callback throws an error?

File: web3.js/src/connection.ts [hunk 19]
```diff
@@ -4281,75 +4240,248 @@ export class Connection {
...
+    subscriptionConfig: SubscriptionConfig,
+    /**
+     * When preparing `args` for a call to `_makeSubscription`, be sure
+     * to carefully apply a default `commitment` property, if necessary.
+     *
+     * - If the user supplied a `commitment` use that.
+     * - Otherwise, if the `Connection::commitment` is set, use that.
+     * - Otherwise, set it to the RPC server default: `finalized`.
+     *
+     * This is extrememly important to ensure that these two fundamentally
```
Comment (jstarry) [inline web3.js/src/connection.ts:4435]:
```suggestion
     * This is extremely important to ensure that these two fundamentally
```

**Review by jstarry — COMMENTED** [review]
Almost there, just did a full pass so should be good to go after this round

File: web3.js/src/connection.ts [hunk 20]
```diff
@@ -2146,6 +2194,13 @@ export class Connection {
   /** @internal */ _rpcWebSocketIdleTimeout: ReturnType<
     typeof setTimeout
   > | null = null;
+  /** @internal
+   * A number that we increment every time an active connection closes.
+   * Used to determine whether the same socket connection that was open
+   * when an async operation started is the same one that's active when
+   * its continuation fires.
+   *
+   */ private _rpcWebSocketGeneration: number = 0;
```
[the remark this answers is not in the document]
Comment (steveluscher) [reply web3.js/src/connection.ts:2203]: Maybe! I've used this pattern many times before, and I never know what to call it other than ‘generation,’ as in ‘the next generation’ or ‘generations past.’ Renaming it to ‘counter’ will make it more clear what this _is_ at this callsite, but maybe at the cost of making this implementation more confusing:

```
const isCurrentConnectionStillActive = () => {
  return currentConnectionClosedCount === this._rpcWebSocketConnectionClosedCounter;
};
```

File: web3.js/src/connection.ts (hunk 18 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4402]: Yeah. I was _shocked_ that we've gotten away this long without wrapping user-supplied callbacks in guards. Right now, one bad callback can bring down the whole publish queue.

File: web3.js/src/connection.ts (hunk 17 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4401]: Yeah. What a mess: https://github.com/microsoft/TypeScript/issues/47615

File: web3.js/src/connection.ts [hunk 21]
```diff
@@ -2161,40 +2216,35 @@ export class Connection {
...
+   * subscriptions have been disposed in such a way, so that we know
+   * whether the client is dealing with a not-yet-processed signature
+   * (in which case we must tear down the server subscription) or an
+   * already-processed signature (in which case the client can simply
+   * clear out the subscription locally without telling the server).
+   *
+   * NOTE: There is a proposal to eliminate this special case, here:
+   * https://github.com/solana-labs/solana/issues/18892
+   */
+  /** @internal */ _subscriptionsAutoDisposedByRpc: Set<ServerSubscriptionId> =
```
[the remark this answers is not in the document]
Comment (steveluscher) [reply web3.js/src/connection.ts:2246]: Welllll… before I do that, we need to adjudicate this: https://github.com/solana-labs/solana/issues/18892

I bolted this special case on deliberately so, as to make it easy to rip it out later, once we decide to go ahead addressing that issue.

[the remark this answers is not in the document]
Comment (steveluscher) [reply web3.js/src/connection.ts:2246]: As for the flow, it's all crafted so that unsubscribes _do_ get sent, if:

* You call `remove` before getting any notification.
* You call `remove` when the only thing you've received so far is a `signatureReceived` notification

…but they _do not_ get sent, if:

* You call `remove` after having received a `signatureProcessed` or regular status notification.

This is all exercised in the tests. Look for ‘after an auto-disposing subscription has published a non-final notification.’

File: web3.js/src/connection.ts (hunk 16 above)
Comment (steveluscher) [reply web3.js/src/connection.ts:4293]: A socket could disconnect while we're literally in the middle of processing the reply, 100%. The thing is that the disconnect _happens_ in a thread outside the JS engine (ie. in the browser's networking stack) so there's no possible way for it to show up on the single JavaScript thread until the next runloop.

The async `_rpcWebSocket.call()` can only resume in one of two ways:

* throw (reject) when the reply timeout gets hit.
* resume execution (resolve) because it received a reply.

Presume, now, that `_rpcWebSocket.call()` has yielded to the scheduler and is waiting for one of those two things to happen.

* If a close event happens before we get a reply, the only possible thing that could happen next is for the reply timeout to be hit†, which would trigger our `catch` which handles this properly now.
* If a reply comes in, then we're definitely not closed, and every statement after the `await` will run synchronously until there are no more statements to evaluate.

Now, imagine that a close happened, in a _real world_ sense, while that code after the `await` was running (eg. I yanked out the network cable). The _browser_ will learn of the close, for sure, but there's literally no way for the browser to schedule the close event on the JS thread until _after_ the reply is done being processed. The browser can fire the `close` event into the JS thread all it wants, but it's not going to be able to preempt the code after the `await`.

```
this._subscriptionsByHash[hash] = {
  ...subscription,
  serverSubscriptionId,
  state: 'subscribed',
};
this._subscriptionCallbacksByServerSubscriptionId[
  serverSubscriptionId
] = subscription.callbacks;
await this._updateSubscriptions();
```

…by sneaking a call to `_wsOnClose` in between those three lines.

JavaScript being single threaded is one of the worst things about JavaScript, but also definitely one of the best things about JavaScript.

---
† If it's literally possible to _receive_ and _process_ a data frame (reply) _after_ having received a `close` event on the JS thread, then everything I said above doesn't matter, I will eat my hat, and websockets are terrible.

File: web3.js/src/connection.ts (hunk 21 above)
[the remark this answers is not in the document]
Comment (jstarry) [reply web3.js/src/connection.ts:2246]: Ah ok, I'm just happy to hear that it's setup to rip out later :) I'm fine with it is for now

File: web3.js/src/connection.ts (hunk 20 above)
[the remark this answers is not in the document]
Comment (jstarry) [reply web3.js/src/connection.ts:2203]: Yeah I guess it just comes down to what we're used to. Always feel free to ignore anything follows "nit: " from me, it's usually pretty subjective haha

File: web3.js/src/connection.ts (hunk 16 above)
Comment (jstarry) [reply web3.js/src/connection.ts:4293]: My understanding from [this gist](https://gist.github.com/jstarry/9b86287eec9468696d5dd28aa7a6c50a) is that even if an async rpc call receives and processes a reply, we might not pick up where we left off until after processing other events in the work queue

Comment (steveluscher) [reply web3.js/src/connection.ts:4293]: Oh totally, but other events will mostly touch _other_ subscriptions, and the ones that do touch this subscription will perform no actions because it's in the `'subscribing'` state:

```
case 'subscribing':
case 'unsubscribing':
  break;
```

Receiving a reply corresponds to [this event firing](https://github.com/elpheria/rpc-websockets/blob/trunk/src/lib/client.ts#L306) in the `rpc-websockets` library:

```
this.socket.addEventListener("message", ({data: message}) => { ... }
```

All of the code of that event handler fires sync, including [this bit at the end](https://github.com/elpheria/rpc-websockets/blob/trunk/src/lib/client.ts#L360-L363):

```
if (message.error)
  this.queue[message.id].promise[1](message.error)
else
  this.queue[message.id].promise[0](message.result)
```

`promise[0]` there corresponds to the `resolve` of `this._rpcWebSockets.call(...)`. When it's called with `message.result` (the reply) then all of the code after _our_ `await` will run synchronously:

```
this._subscriptionsByHash[hash] = {
  ...subscription,
  serverSubscriptionId,
  state: 'subscribed',
};
this._subscriptionCallbacksByServerSubscriptionId[
  serverSubscriptionId
] = subscription.callbacks;
await this._updateSubscriptions();
```

So essentially you can draw a straight line between the `'message'` event firing and all of that code running before yielding back to the browser. This means that the act of receiving a reply implies two things:

* you were definitely not `CLOSED` or `CLOSING` at that moment (otherwise you wouldn't have been able to receive `'message'`), and
* no `'close'` event can sneak into the JS thread while you're running the reply processing code.

Take a look at these branches of `connection-subscriptions.test.ts`:

```
Subscriptions
  The `accountSubscribe` RPC method
    attaching the first notification listener
      ✓ results in a subscription request being made to the RPC
      then unsubscribing that listener before the subscription has been acknowledged by the server
        once the subscription has been acknowledged by the server
          ✓ results in the subscription being torn down immediately
      then having the socket connection drop unexpectedly
        then unsubscribing that listener
          upon the socket connection reopening
            ✓ does not result in a new subscription request being made to the RPC
        upon the socket connection reopening
          ✓ results in a new subscription request being made to the RPC
          then upon the prior subscription fataling (eg. because its timeout triggers)
            ✓ does not result in a new subscription request being made to the RPC
```

Those exercise what happens when you have an in-flight `'subscribing'` state and one of two things happens:

* the user decides they don't care anymore and call `remove*`
* the connection drops

Thoughts? :)

Comment (jstarry) [reply web3.js/src/connection.ts:4293]: > So essentially you can draw a straight line between the 'message' event firing and all of that code running before yielding back to the browser. This means that the act of receiving a reply implies two things:

Ah, this makes a lot of sense. Looks good then, thanks :)

**Review by jstarry — DISMISSED** [review]
at long last 😉

**Comment by steveluscher** [comment]
> at long last 😉

O no. Famous last words.
